return
{
  entities =
  {
    {"stone-wall", {x = -14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -14.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = -14.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -1.5, y = -14.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 1.5, y = -14.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 0.5, y = -14.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -13.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = -13}, {dir = "west", force = "enemy", }},
    {"laser-turret", {x = -10, y = -13}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -13.5}, {force = "enemy", }},
    {"laser-turret", {x = -7, y = -13}, {force = "enemy", }},
    {"laser-turret", {x = -4, y = -13}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -12.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = -12.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -1.5, y = -12.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 1.5, y = -12.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 0.5, y = -12.5}, {dir = "east", force = "enemy", }},
    {"laser-turret", {x = 4, y = -13}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -13.5}, {force = "enemy", }},
    {"laser-turret", {x = 7, y = -13}, {force = "enemy", }},
    {"laser-turret", {x = 10, y = -13}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -13.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -13}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -11.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = -10}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -11.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -10}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -7.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = -7}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -6.5}, {force = "enemy", }},
    {"lab", {x = -7.5, y = -6.5}, {}},
    {"roboport", {x = 0, y = -6}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"steel-chest", {x = 6.5, y = -6.5}, {items = {["battery-equipment"] = 10}, }},
    {"steel-chest", {x = 8.5, y = -6.5}, {items = {["uranium-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 11.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -7.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -7}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = -4}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -4.5}, {force = "enemy", }},
    {"substation", {x = -5, y = -5}, {}},
    {"logistic-chest-passive-provider", {x = -2.5, y = -4.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"aliencon-robot", {x = -0.21, y = -5.11}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.67, y = -5.11}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.11, y = -5.13}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.34, y = -5.13}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.52, y = -5.18}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.54, y = -5.18}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.97, y = -5.08}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.94, y = -5.08}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.81, y = -5.08}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.69, y = -5.08}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.53, y = -5.08}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.4, y = -5.11}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.38, y = -5.11}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.35, y = -5.11}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.2, y = -5.11}, {force = "enemy", }},
    {"substation", {x = 5, y = -5}, {}},
    {"steel-chest", {x = 6.5, y = -4.5}, {items = {["processing-unit"] = 100}, }},
    {"steel-chest", {x = 8.5, y = -4.5}, {items = {["nuclear-fuel"] = 5}, }},
    {"stone-wall", {x = 11.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -4}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -3.5}, {force = "enemy", }},
    {"aliengenerator", {x = 0.5, y = -2}, {force = "enemy", }},
    {"steel-chest", {x = 6.5, y = -2.5}, {items = {["uranium-fuel-cell"] = 50}, }},
    {"steel-chest", {x = 8.5, y = -2.5}, {items = {["uranium-235"] = 5}, }},
    {"stone-wall", {x = 11.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -2.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = -12.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = -12.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = 12.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = 12.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = -12.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = -12.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = 12.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = 12.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 2.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = 4}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 3.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -2.5, y = 2.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"aliencon-robot", {x = -0.08, y = 2.87}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.57, y = 2.87}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.8, y = 2.87}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.93, y = 2.87}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.08, y = 2.87}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.24, y = 2.84}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.42, y = 2.79}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.62, y = 2.74}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.7, y = 2.71}, {force = "enemy", }},
    {"roboport", {x = 0, y = 4}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"aliencon-robot", {x = 1.38, y = 2.99}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.33, y = 2.99}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.02, y = 2.94}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.48, y = 2.89}, {force = "enemy", }},
    {"steel-chest", {x = 6.5, y = 2.5}, {items = {["assembling-machine-2"] = 25}, }},
    {"steel-chest", {x = 8.5, y = 2.5}, {items = {["raw-fish"] = 100}, }},
    {"stone-wall", {x = 11.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 3.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = 4}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 5.5}, {force = "enemy", }},
    {"substation", {x = -5, y = 5}, {}},
    {"substation", {x = 5, y = 5}, {}},
    {"steel-chest", {x = 6.5, y = 4.5}, {items = {["flying-robot-frame"] = 25}, }},
    {"steel-chest", {x = 8.5, y = 4.5}, {items = {["low-density-structure"] = 20}, }},
    {"stone-wall", {x = 11.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = 7}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 7.5}, {force = "enemy", }},
    {"assembling-machine-2", {x = -7.5, y = 7.5}, {recipe = "production-science-pack", }},
    {"assembling-machine-2", {x = -3.5, y = 7.5}, {recipe = "chemical-science-pack", }},
    {"steel-chest", {x = 6.5, y = 6.5}, {items = {["advanced-circuit"] = 200}, }},
    {"steel-chest", {x = 8.5, y = 6.5}, {items = {["electronic-circuit"] = 400}, }},
    {"stone-wall", {x = 11.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = 7}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = 10}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 8.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = 10}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = 13}, {dir = "west", force = "enemy", }},
    {"laser-turret", {x = -10, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 13.5}, {force = "enemy", }},
    {"laser-turret", {x = -7, y = 13}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = -4, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 12.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = 12.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -1.5, y = 12.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 1.5, y = 12.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 0.5, y = 12.5}, {dir = "east", force = "enemy", }},
    {"laser-turret", {x = 4, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 7, y = 13}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = 10, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 14.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = 14.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -1.5, y = 14.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 1.5, y = 14.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 0.5, y = 14.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 14.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-2", {x = -16, y = -16}},
    {"grass-2", {x = -16, y = -15}},
    {"grass-2", {x = -16, y = -14}},
    {"red-desert-0", {x = -16, y = -13}},
    {"red-desert-0", {x = -16, y = -12}},
    {"red-desert-0", {x = -16, y = -11}},
    {"red-desert-0", {x = -16, y = -10}},
    {"red-desert-0", {x = -16, y = -9}},
    {"red-desert-0", {x = -16, y = -8}},
    {"dirt-6", {x = -16, y = -7}},
    {"dirt-6", {x = -16, y = -6}},
    {"grass-2", {x = -16, y = -5}},
    {"grass-2", {x = -16, y = -4}},
    {"grass-2", {x = -16, y = -3}},
    {"refined-concrete", {x = -16, y = -2}},
    {"refined-concrete", {x = -16, y = -1}},
    {"refined-concrete", {x = -16, y = 0}},
    {"refined-concrete", {x = -16, y = 1}},
    {"grass-2", {x = -16, y = 2}},
    {"grass-2", {x = -16, y = 3}},
    {"grass-2", {x = -16, y = 4}},
    {"grass-2", {x = -16, y = 5}},
    {"dirt-5", {x = -16, y = 6}},
    {"dirt-5", {x = -16, y = 7}},
    {"dirt-6", {x = -16, y = 8}},
    {"dirt-6", {x = -16, y = 9}},
    {"dirt-6", {x = -16, y = 10}},
    {"dirt-5", {x = -16, y = 11}},
    {"dirt-5", {x = -16, y = 12}},
    {"dirt-5", {x = -16, y = 13}},
    {"dirt-5", {x = -16, y = 14}},
    {"dirt-5", {x = -16, y = 15}},
    {"grass-2", {x = -15, y = -16}},
    {"grass-2", {x = -15, y = -15}},
    {"grass-2", {x = -15, y = -14}},
    {"grass-2", {x = -15, y = -13}},
    {"red-desert-0", {x = -15, y = -12}},
    {"red-desert-0", {x = -15, y = -11}},
    {"red-desert-0", {x = -15, y = -10}},
    {"red-desert-0", {x = -15, y = -9}},
    {"grass-2", {x = -15, y = -8}},
    {"grass-2", {x = -15, y = -7}},
    {"grass-2", {x = -15, y = -6}},
    {"grass-2", {x = -15, y = -5}},
    {"grass-2", {x = -15, y = -4}},
    {"grass-2", {x = -15, y = -3}},
    {"refined-concrete", {x = -15, y = -2}},
    {"refined-concrete", {x = -15, y = -1}},
    {"refined-concrete", {x = -15, y = 0}},
    {"refined-concrete", {x = -15, y = 1}},
    {"grass-2", {x = -15, y = 2}},
    {"grass-2", {x = -15, y = 3}},
    {"grass-2", {x = -15, y = 4}},
    {"grass-2", {x = -15, y = 5}},
    {"grass-2", {x = -15, y = 6}},
    {"dirt-6", {x = -15, y = 7}},
    {"dirt-6", {x = -15, y = 8}},
    {"dirt-6", {x = -15, y = 9}},
    {"dirt-6", {x = -15, y = 10}},
    {"dirt-5", {x = -15, y = 11}},
    {"dirt-5", {x = -15, y = 12}},
    {"dirt-5", {x = -15, y = 13}},
    {"dirt-5", {x = -15, y = 14}},
    {"dirt-5", {x = -15, y = 15}},
    {"grass-2", {x = -14, y = -16}},
    {"grass-2", {x = -14, y = -15}},
    {"grass-2", {x = -14, y = -14}},
    {"grass-2", {x = -14, y = -13}},
    {"grass-2", {x = -14, y = -12}},
    {"grass-2", {x = -14, y = -11}},
    {"grass-2", {x = -14, y = -10}},
    {"grass-2", {x = -14, y = -9}},
    {"grass-2", {x = -14, y = -8}},
    {"grass-2", {x = -14, y = -7}},
    {"grass-2", {x = -14, y = -6}},
    {"grass-2", {x = -14, y = -5}},
    {"grass-2", {x = -14, y = -4}},
    {"grass-2", {x = -14, y = -3}},
    {"refined-concrete", {x = -14, y = -2}},
    {"refined-concrete", {x = -14, y = -1}},
    {"refined-concrete", {x = -14, y = 0}},
    {"refined-concrete", {x = -14, y = 1}},
    {"grass-2", {x = -14, y = 2}},
    {"grass-2", {x = -14, y = 3}},
    {"grass-2", {x = -14, y = 4}},
    {"grass-2", {x = -14, y = 5}},
    {"grass-2", {x = -14, y = 6}},
    {"grass-2", {x = -14, y = 7}},
    {"dirt-6", {x = -14, y = 8}},
    {"dirt-5", {x = -14, y = 9}},
    {"dirt-5", {x = -14, y = 10}},
    {"dirt-5", {x = -14, y = 11}},
    {"dirt-5", {x = -14, y = 12}},
    {"dirt-5", {x = -14, y = 13}},
    {"dirt-5", {x = -14, y = 14}},
    {"dirt-5", {x = -14, y = 15}},
    {"grass-2", {x = -13, y = -16}},
    {"grass-2", {x = -13, y = -15}},
    {"grass-2", {x = -13, y = -14}},
    {"grass-2", {x = -13, y = -13}},
    {"grass-2", {x = -13, y = -12}},
    {"grass-2", {x = -13, y = -11}},
    {"grass-2", {x = -13, y = -10}},
    {"grass-2", {x = -13, y = -9}},
    {"grass-2", {x = -13, y = -8}},
    {"grass-2", {x = -13, y = -7}},
    {"grass-2", {x = -13, y = -6}},
    {"grass-2", {x = -13, y = -5}},
    {"grass-2", {x = -13, y = -4}},
    {"grass-2", {x = -13, y = -3}},
    {"refined-concrete", {x = -13, y = -2}},
    {"refined-concrete", {x = -13, y = -1}},
    {"refined-concrete", {x = -13, y = 0}},
    {"refined-concrete", {x = -13, y = 1}},
    {"grass-2", {x = -13, y = 2}},
    {"grass-2", {x = -13, y = 3}},
    {"grass-2", {x = -13, y = 4}},
    {"grass-2", {x = -13, y = 5}},
    {"grass-2", {x = -13, y = 6}},
    {"grass-2", {x = -13, y = 7}},
    {"dirt-5", {x = -13, y = 8}},
    {"dirt-5", {x = -13, y = 9}},
    {"dirt-5", {x = -13, y = 10}},
    {"dirt-5", {x = -13, y = 11}},
    {"dirt-5", {x = -13, y = 12}},
    {"dirt-5", {x = -13, y = 13}},
    {"dirt-5", {x = -13, y = 14}},
    {"dirt-5", {x = -13, y = 15}},
    {"grass-2", {x = -12, y = -16}},
    {"grass-2", {x = -12, y = -15}},
    {"grass-2", {x = -12, y = -14}},
    {"grass-2", {x = -12, y = -13}},
    {"grass-2", {x = -12, y = -12}},
    {"grass-2", {x = -12, y = -11}},
    {"grass-2", {x = -12, y = -10}},
    {"grass-2", {x = -12, y = -9}},
    {"grass-2", {x = -12, y = -8}},
    {"grass-2", {x = -12, y = -7}},
    {"grass-2", {x = -12, y = -6}},
    {"grass-2", {x = -12, y = -5}},
    {"grass-2", {x = -12, y = -4}},
    {"grass-2", {x = -12, y = -3}},
    {"refined-concrete", {x = -12, y = -2}},
    {"refined-concrete", {x = -12, y = -1}},
    {"refined-concrete", {x = -12, y = 0}},
    {"refined-concrete", {x = -12, y = 1}},
    {"grass-2", {x = -12, y = 2}},
    {"grass-2", {x = -12, y = 3}},
    {"grass-2", {x = -12, y = 4}},
    {"grass-2", {x = -12, y = 5}},
    {"grass-2", {x = -12, y = 6}},
    {"grass-2", {x = -12, y = 7}},
    {"dirt-5", {x = -12, y = 8}},
    {"dirt-5", {x = -12, y = 9}},
    {"dirt-5", {x = -12, y = 10}},
    {"dirt-5", {x = -12, y = 11}},
    {"dirt-5", {x = -12, y = 12}},
    {"dirt-5", {x = -12, y = 13}},
    {"dirt-5", {x = -12, y = 14}},
    {"dirt-5", {x = -12, y = 15}},
    {"grass-2", {x = -11, y = -16}},
    {"grass-2", {x = -11, y = -15}},
    {"grass-2", {x = -11, y = -14}},
    {"grass-2", {x = -11, y = -13}},
    {"grass-2", {x = -11, y = -12}},
    {"grass-2", {x = -11, y = -11}},
    {"grass-2", {x = -11, y = -10}},
    {"grass-2", {x = -11, y = -9}},
    {"grass-2", {x = -11, y = -8}},
    {"grass-2", {x = -11, y = -7}},
    {"grass-2", {x = -11, y = -6}},
    {"grass-2", {x = -11, y = -5}},
    {"grass-2", {x = -11, y = -4}},
    {"grass-2", {x = -11, y = -3}},
    {"refined-concrete", {x = -11, y = -2}},
    {"refined-concrete", {x = -11, y = -1}},
    {"refined-concrete", {x = -11, y = 0}},
    {"refined-concrete", {x = -11, y = 1}},
    {"grass-2", {x = -11, y = 2}},
    {"grass-2", {x = -11, y = 3}},
    {"grass-2", {x = -11, y = 4}},
    {"grass-2", {x = -11, y = 5}},
    {"grass-2", {x = -11, y = 6}},
    {"dirt-5", {x = -11, y = 7}},
    {"dirt-5", {x = -11, y = 8}},
    {"dirt-5", {x = -11, y = 9}},
    {"dirt-5", {x = -11, y = 10}},
    {"dirt-5", {x = -11, y = 11}},
    {"dirt-5", {x = -11, y = 12}},
    {"dirt-5", {x = -11, y = 13}},
    {"dirt-5", {x = -11, y = 14}},
    {"dirt-5", {x = -11, y = 15}},
    {"grass-2", {x = -10, y = -16}},
    {"grass-2", {x = -10, y = -15}},
    {"grass-2", {x = -10, y = -14}},
    {"grass-2", {x = -10, y = -13}},
    {"grass-2", {x = -10, y = -12}},
    {"grass-2", {x = -10, y = -11}},
    {"grass-2", {x = -10, y = -10}},
    {"grass-2", {x = -10, y = -9}},
    {"grass-2", {x = -10, y = -8}},
    {"grass-2", {x = -10, y = -7}},
    {"grass-2", {x = -10, y = -6}},
    {"grass-2", {x = -10, y = -5}},
    {"grass-2", {x = -10, y = -4}},
    {"grass-2", {x = -10, y = -3}},
    {"refined-concrete", {x = -10, y = -2}},
    {"refined-concrete", {x = -10, y = -1}},
    {"refined-concrete", {x = -10, y = 0}},
    {"refined-concrete", {x = -10, y = 1}},
    {"grass-2", {x = -10, y = 2}},
    {"grass-2", {x = -10, y = 3}},
    {"grass-2", {x = -10, y = 4}},
    {"grass-2", {x = -10, y = 5}},
    {"grass-2", {x = -10, y = 6}},
    {"dirt-5", {x = -10, y = 7}},
    {"dirt-5", {x = -10, y = 8}},
    {"dirt-5", {x = -10, y = 9}},
    {"dirt-5", {x = -10, y = 10}},
    {"dirt-5", {x = -10, y = 11}},
    {"dirt-5", {x = -10, y = 12}},
    {"dirt-5", {x = -10, y = 13}},
    {"dirt-5", {x = -10, y = 14}},
    {"dirt-5", {x = -10, y = 15}},
    {"grass-2", {x = -9, y = -16}},
    {"grass-2", {x = -9, y = -15}},
    {"grass-2", {x = -9, y = -14}},
    {"grass-2", {x = -9, y = -13}},
    {"grass-2", {x = -9, y = -12}},
    {"grass-2", {x = -9, y = -11}},
    {"grass-2", {x = -9, y = -10}},
    {"grass-2", {x = -9, y = -9}},
    {"grass-2", {x = -9, y = -8}},
    {"grass-2", {x = -9, y = -7}},
    {"grass-2", {x = -9, y = -6}},
    {"grass-2", {x = -9, y = -5}},
    {"grass-2", {x = -9, y = -4}},
    {"grass-2", {x = -9, y = -3}},
    {"refined-concrete", {x = -9, y = -2}},
    {"refined-concrete", {x = -9, y = -1}},
    {"refined-concrete", {x = -9, y = 0}},
    {"refined-concrete", {x = -9, y = 1}},
    {"grass-2", {x = -9, y = 2}},
    {"grass-2", {x = -9, y = 3}},
    {"grass-2", {x = -9, y = 4}},
    {"grass-2", {x = -9, y = 5}},
    {"dirt-5", {x = -9, y = 6}},
    {"dirt-5", {x = -9, y = 7}},
    {"dirt-5", {x = -9, y = 8}},
    {"dirt-5", {x = -9, y = 9}},
    {"dirt-5", {x = -9, y = 10}},
    {"dirt-5", {x = -9, y = 11}},
    {"dirt-5", {x = -9, y = 12}},
    {"dirt-5", {x = -9, y = 13}},
    {"dirt-5", {x = -9, y = 14}},
    {"dirt-5", {x = -9, y = 15}},
    {"grass-2", {x = -8, y = -16}},
    {"grass-2", {x = -8, y = -15}},
    {"grass-2", {x = -8, y = -14}},
    {"grass-2", {x = -8, y = -13}},
    {"grass-2", {x = -8, y = -12}},
    {"grass-2", {x = -8, y = -11}},
    {"refined-concrete", {x = -8, y = -10}},
    {"refined-concrete", {x = -8, y = -9}},
    {"refined-concrete", {x = -8, y = -8}},
    {"refined-concrete", {x = -8, y = -7}},
    {"refined-concrete", {x = -8, y = -6}},
    {"refined-concrete", {x = -8, y = -5}},
    {"refined-concrete", {x = -8, y = -4}},
    {"refined-concrete", {x = -8, y = -3}},
    {"refined-concrete", {x = -8, y = -2}},
    {"refined-concrete", {x = -8, y = -1}},
    {"refined-concrete", {x = -8, y = 0}},
    {"refined-concrete", {x = -8, y = 1}},
    {"refined-concrete", {x = -8, y = 2}},
    {"refined-concrete", {x = -8, y = 3}},
    {"refined-concrete", {x = -8, y = 4}},
    {"refined-concrete", {x = -8, y = 5}},
    {"refined-concrete", {x = -8, y = 6}},
    {"refined-concrete", {x = -8, y = 7}},
    {"refined-concrete", {x = -8, y = 8}},
    {"refined-concrete", {x = -8, y = 9}},
    {"dirt-5", {x = -8, y = 10}},
    {"dirt-5", {x = -8, y = 11}},
    {"dirt-5", {x = -8, y = 12}},
    {"dirt-5", {x = -8, y = 13}},
    {"dirt-5", {x = -8, y = 14}},
    {"dirt-5", {x = -8, y = 15}},
    {"grass-2", {x = -7, y = -16}},
    {"grass-2", {x = -7, y = -15}},
    {"grass-2", {x = -7, y = -14}},
    {"grass-2", {x = -7, y = -13}},
    {"grass-2", {x = -7, y = -12}},
    {"grass-2", {x = -7, y = -11}},
    {"refined-concrete", {x = -7, y = -10}},
    {"refined-concrete", {x = -7, y = -9}},
    {"refined-concrete", {x = -7, y = -8}},
    {"refined-concrete", {x = -7, y = -7}},
    {"refined-concrete", {x = -7, y = -6}},
    {"refined-concrete", {x = -7, y = -5}},
    {"refined-concrete", {x = -7, y = -4}},
    {"refined-concrete", {x = -7, y = -3}},
    {"refined-concrete", {x = -7, y = -2}},
    {"refined-concrete", {x = -7, y = -1}},
    {"refined-concrete", {x = -7, y = 0}},
    {"refined-concrete", {x = -7, y = 1}},
    {"refined-concrete", {x = -7, y = 2}},
    {"refined-concrete", {x = -7, y = 3}},
    {"refined-concrete", {x = -7, y = 4}},
    {"refined-concrete", {x = -7, y = 5}},
    {"refined-concrete", {x = -7, y = 6}},
    {"refined-concrete", {x = -7, y = 7}},
    {"refined-concrete", {x = -7, y = 8}},
    {"refined-concrete", {x = -7, y = 9}},
    {"dirt-5", {x = -7, y = 10}},
    {"dirt-5", {x = -7, y = 11}},
    {"dirt-5", {x = -7, y = 12}},
    {"dirt-5", {x = -7, y = 13}},
    {"dirt-5", {x = -7, y = 14}},
    {"dirt-5", {x = -7, y = 15}},
    {"grass-2", {x = -6, y = -16}},
    {"grass-2", {x = -6, y = -15}},
    {"grass-2", {x = -6, y = -14}},
    {"grass-2", {x = -6, y = -13}},
    {"grass-2", {x = -6, y = -12}},
    {"grass-2", {x = -6, y = -11}},
    {"refined-concrete", {x = -6, y = -10}},
    {"refined-concrete", {x = -6, y = -9}},
    {"refined-concrete", {x = -6, y = -8}},
    {"refined-concrete", {x = -6, y = -7}},
    {"refined-concrete", {x = -6, y = -6}},
    {"refined-concrete", {x = -6, y = -5}},
    {"refined-concrete", {x = -6, y = -4}},
    {"refined-concrete", {x = -6, y = -3}},
    {"refined-concrete", {x = -6, y = -2}},
    {"refined-concrete", {x = -6, y = -1}},
    {"refined-concrete", {x = -6, y = 0}},
    {"refined-concrete", {x = -6, y = 1}},
    {"refined-concrete", {x = -6, y = 2}},
    {"refined-concrete", {x = -6, y = 3}},
    {"refined-concrete", {x = -6, y = 4}},
    {"refined-concrete", {x = -6, y = 5}},
    {"refined-concrete", {x = -6, y = 6}},
    {"refined-concrete", {x = -6, y = 7}},
    {"refined-concrete", {x = -6, y = 8}},
    {"refined-concrete", {x = -6, y = 9}},
    {"dirt-5", {x = -6, y = 10}},
    {"dirt-5", {x = -6, y = 11}},
    {"dirt-5", {x = -6, y = 12}},
    {"dirt-5", {x = -6, y = 13}},
    {"dirt-5", {x = -6, y = 14}},
    {"dirt-5", {x = -6, y = 15}},
    {"grass-2", {x = -5, y = -16}},
    {"grass-2", {x = -5, y = -15}},
    {"grass-2", {x = -5, y = -14}},
    {"grass-2", {x = -5, y = -13}},
    {"grass-2", {x = -5, y = -12}},
    {"grass-2", {x = -5, y = -11}},
    {"refined-concrete", {x = -5, y = -10}},
    {"refined-concrete", {x = -5, y = -9}},
    {"refined-concrete", {x = -5, y = -8}},
    {"refined-concrete", {x = -5, y = -7}},
    {"refined-concrete", {x = -5, y = -6}},
    {"refined-concrete", {x = -5, y = -5}},
    {"refined-concrete", {x = -5, y = -4}},
    {"refined-concrete", {x = -5, y = -3}},
    {"refined-concrete", {x = -5, y = -2}},
    {"refined-concrete", {x = -5, y = -1}},
    {"refined-concrete", {x = -5, y = 0}},
    {"refined-concrete", {x = -5, y = 1}},
    {"refined-concrete", {x = -5, y = 2}},
    {"refined-concrete", {x = -5, y = 3}},
    {"refined-concrete", {x = -5, y = 4}},
    {"refined-concrete", {x = -5, y = 5}},
    {"refined-concrete", {x = -5, y = 6}},
    {"refined-concrete", {x = -5, y = 7}},
    {"refined-concrete", {x = -5, y = 8}},
    {"refined-concrete", {x = -5, y = 9}},
    {"dirt-5", {x = -5, y = 10}},
    {"dirt-5", {x = -5, y = 11}},
    {"dirt-5", {x = -5, y = 12}},
    {"dirt-5", {x = -5, y = 13}},
    {"dirt-5", {x = -5, y = 14}},
    {"dirt-5", {x = -5, y = 15}},
    {"grass-2", {x = -4, y = -16}},
    {"grass-2", {x = -4, y = -15}},
    {"grass-2", {x = -4, y = -14}},
    {"grass-2", {x = -4, y = -13}},
    {"grass-2", {x = -4, y = -12}},
    {"dirt-6", {x = -4, y = -11}},
    {"refined-concrete", {x = -4, y = -10}},
    {"refined-concrete", {x = -4, y = -9}},
    {"refined-concrete", {x = -4, y = -8}},
    {"refined-concrete", {x = -4, y = -7}},
    {"grass-2", {x = -4, y = -6}},
    {"grass-2", {x = -4, y = -5}},
    {"grass-2", {x = -4, y = -4}},
    {"grass-2", {x = -4, y = -3}},
    {"grass-2", {x = -4, y = -2}},
    {"grass-2", {x = -4, y = -1}},
    {"grass-2", {x = -4, y = 0}},
    {"grass-2", {x = -4, y = 1}},
    {"grass-2", {x = -4, y = 2}},
    {"grass-2", {x = -4, y = 3}},
    {"grass-2", {x = -4, y = 4}},
    {"grass-2", {x = -4, y = 5}},
    {"refined-concrete", {x = -4, y = 6}},
    {"refined-concrete", {x = -4, y = 7}},
    {"refined-concrete", {x = -4, y = 8}},
    {"refined-concrete", {x = -4, y = 9}},
    {"dirt-5", {x = -4, y = 10}},
    {"dirt-5", {x = -4, y = 11}},
    {"dirt-5", {x = -4, y = 12}},
    {"dirt-5", {x = -4, y = 13}},
    {"dirt-5", {x = -4, y = 14}},
    {"dirt-5", {x = -4, y = 15}},
    {"grass-2", {x = -3, y = -16}},
    {"grass-2", {x = -3, y = -15}},
    {"grass-2", {x = -3, y = -14}},
    {"grass-2", {x = -3, y = -13}},
    {"dirt-6", {x = -3, y = -12}},
    {"dirt-6", {x = -3, y = -11}},
    {"refined-concrete", {x = -3, y = -10}},
    {"refined-concrete", {x = -3, y = -9}},
    {"refined-concrete", {x = -3, y = -8}},
    {"refined-concrete", {x = -3, y = -7}},
    {"grass-2", {x = -3, y = -6}},
    {"grass-2", {x = -3, y = -5}},
    {"grass-2", {x = -3, y = -4}},
    {"grass-2", {x = -3, y = -3}},
    {"grass-2", {x = -3, y = -2}},
    {"grass-2", {x = -3, y = -1}},
    {"grass-2", {x = -3, y = 0}},
    {"grass-2", {x = -3, y = 1}},
    {"grass-2", {x = -3, y = 2}},
    {"grass-2", {x = -3, y = 3}},
    {"grass-2", {x = -3, y = 4}},
    {"grass-2", {x = -3, y = 5}},
    {"refined-concrete", {x = -3, y = 6}},
    {"refined-concrete", {x = -3, y = 7}},
    {"refined-concrete", {x = -3, y = 8}},
    {"refined-concrete", {x = -3, y = 9}},
    {"dirt-5", {x = -3, y = 10}},
    {"dirt-5", {x = -3, y = 11}},
    {"dirt-5", {x = -3, y = 12}},
    {"dirt-5", {x = -3, y = 13}},
    {"dirt-5", {x = -3, y = 14}},
    {"dirt-5", {x = -3, y = 15}},
    {"refined-concrete", {x = -2, y = -16}},
    {"refined-concrete", {x = -2, y = -15}},
    {"refined-concrete", {x = -2, y = -14}},
    {"refined-concrete", {x = -2, y = -13}},
    {"refined-concrete", {x = -2, y = -12}},
    {"refined-concrete", {x = -2, y = -11}},
    {"refined-concrete", {x = -2, y = -10}},
    {"refined-concrete", {x = -2, y = -9}},
    {"refined-concrete", {x = -2, y = -8}},
    {"refined-concrete", {x = -2, y = -7}},
    {"grass-2", {x = -2, y = -6}},
    {"grass-2", {x = -2, y = -5}},
    {"grass-2", {x = -2, y = -4}},
    {"grass-2", {x = -2, y = -3}},
    {"grass-2", {x = -2, y = -2}},
    {"grass-2", {x = -2, y = -1}},
    {"grass-2", {x = -2, y = 0}},
    {"grass-2", {x = -2, y = 1}},
    {"grass-2", {x = -2, y = 2}},
    {"grass-2", {x = -2, y = 3}},
    {"grass-2", {x = -2, y = 4}},
    {"grass-2", {x = -2, y = 5}},
    {"refined-concrete", {x = -2, y = 6}},
    {"refined-concrete", {x = -2, y = 7}},
    {"refined-concrete", {x = -2, y = 8}},
    {"refined-concrete", {x = -2, y = 9}},
    {"refined-concrete", {x = -2, y = 10}},
    {"refined-concrete", {x = -2, y = 11}},
    {"refined-concrete", {x = -2, y = 12}},
    {"refined-concrete", {x = -2, y = 13}},
    {"refined-concrete", {x = -2, y = 14}},
    {"refined-concrete", {x = -2, y = 15}},
    {"refined-concrete", {x = -1, y = -16}},
    {"refined-concrete", {x = -1, y = -15}},
    {"refined-concrete", {x = -1, y = -14}},
    {"refined-concrete", {x = -1, y = -13}},
    {"refined-concrete", {x = -1, y = -12}},
    {"refined-concrete", {x = -1, y = -11}},
    {"refined-concrete", {x = -1, y = -10}},
    {"refined-concrete", {x = -1, y = -9}},
    {"refined-concrete", {x = -1, y = -8}},
    {"refined-concrete", {x = -1, y = -7}},
    {"grass-2", {x = -1, y = -6}},
    {"grass-2", {x = -1, y = -5}},
    {"grass-2", {x = -1, y = -4}},
    {"grass-2", {x = -1, y = -3}},
    {"grass-2", {x = -1, y = -2}},
    {"grass-2", {x = -1, y = -1}},
    {"grass-2", {x = -1, y = 0}},
    {"grass-2", {x = -1, y = 1}},
    {"grass-2", {x = -1, y = 2}},
    {"grass-2", {x = -1, y = 3}},
    {"grass-2", {x = -1, y = 4}},
    {"grass-2", {x = -1, y = 5}},
    {"refined-concrete", {x = -1, y = 6}},
    {"refined-concrete", {x = -1, y = 7}},
    {"refined-concrete", {x = -1, y = 8}},
    {"refined-concrete", {x = -1, y = 9}},
    {"refined-concrete", {x = -1, y = 10}},
    {"refined-concrete", {x = -1, y = 11}},
    {"refined-concrete", {x = -1, y = 12}},
    {"refined-concrete", {x = -1, y = 13}},
    {"refined-concrete", {x = -1, y = 14}},
    {"refined-concrete", {x = -1, y = 15}},
    {"refined-concrete", {x = 0, y = -16}},
    {"refined-concrete", {x = 0, y = -15}},
    {"refined-concrete", {x = 0, y = -14}},
    {"refined-concrete", {x = 0, y = -13}},
    {"refined-concrete", {x = 0, y = -12}},
    {"refined-concrete", {x = 0, y = -11}},
    {"refined-concrete", {x = 0, y = -10}},
    {"refined-concrete", {x = 0, y = -9}},
    {"refined-concrete", {x = 0, y = -8}},
    {"refined-concrete", {x = 0, y = -7}},
    {"grass-2", {x = 0, y = -6}},
    {"grass-2", {x = 0, y = -5}},
    {"grass-2", {x = 0, y = -4}},
    {"grass-2", {x = 0, y = -3}},
    {"grass-2", {x = 0, y = -2}},
    {"grass-2", {x = 0, y = -1}},
    {"grass-2", {x = 0, y = 0}},
    {"grass-2", {x = 0, y = 1}},
    {"grass-2", {x = 0, y = 2}},
    {"grass-2", {x = 0, y = 3}},
    {"grass-2", {x = 0, y = 4}},
    {"grass-2", {x = 0, y = 5}},
    {"refined-concrete", {x = 0, y = 6}},
    {"refined-concrete", {x = 0, y = 7}},
    {"refined-concrete", {x = 0, y = 8}},
    {"refined-concrete", {x = 0, y = 9}},
    {"refined-concrete", {x = 0, y = 10}},
    {"refined-concrete", {x = 0, y = 11}},
    {"refined-concrete", {x = 0, y = 12}},
    {"refined-concrete", {x = 0, y = 13}},
    {"refined-concrete", {x = 0, y = 14}},
    {"refined-concrete", {x = 0, y = 15}},
    {"refined-concrete", {x = 1, y = -16}},
    {"refined-concrete", {x = 1, y = -15}},
    {"refined-concrete", {x = 1, y = -14}},
    {"refined-concrete", {x = 1, y = -13}},
    {"refined-concrete", {x = 1, y = -12}},
    {"refined-concrete", {x = 1, y = -11}},
    {"refined-concrete", {x = 1, y = -10}},
    {"refined-concrete", {x = 1, y = -9}},
    {"refined-concrete", {x = 1, y = -8}},
    {"refined-concrete", {x = 1, y = -7}},
    {"grass-2", {x = 1, y = -6}},
    {"grass-2", {x = 1, y = -5}},
    {"grass-2", {x = 1, y = -4}},
    {"grass-2", {x = 1, y = -3}},
    {"grass-2", {x = 1, y = -2}},
    {"grass-2", {x = 1, y = -1}},
    {"grass-2", {x = 1, y = 0}},
    {"grass-2", {x = 1, y = 1}},
    {"grass-2", {x = 1, y = 2}},
    {"grass-2", {x = 1, y = 3}},
    {"grass-2", {x = 1, y = 4}},
    {"grass-2", {x = 1, y = 5}},
    {"refined-concrete", {x = 1, y = 6}},
    {"refined-concrete", {x = 1, y = 7}},
    {"refined-concrete", {x = 1, y = 8}},
    {"refined-concrete", {x = 1, y = 9}},
    {"refined-concrete", {x = 1, y = 10}},
    {"refined-concrete", {x = 1, y = 11}},
    {"refined-concrete", {x = 1, y = 12}},
    {"refined-concrete", {x = 1, y = 13}},
    {"refined-concrete", {x = 1, y = 14}},
    {"refined-concrete", {x = 1, y = 15}},
    {"grass-2", {x = 2, y = -16}},
    {"grass-2", {x = 2, y = -15}},
    {"grass-2", {x = 2, y = -14}},
    {"grass-2", {x = 2, y = -13}},
    {"dirt-6", {x = 2, y = -12}},
    {"dirt-6", {x = 2, y = -11}},
    {"refined-concrete", {x = 2, y = -10}},
    {"refined-concrete", {x = 2, y = -9}},
    {"refined-concrete", {x = 2, y = -8}},
    {"refined-concrete", {x = 2, y = -7}},
    {"grass-2", {x = 2, y = -6}},
    {"grass-2", {x = 2, y = -5}},
    {"grass-2", {x = 2, y = -4}},
    {"grass-2", {x = 2, y = -3}},
    {"grass-2", {x = 2, y = -2}},
    {"grass-2", {x = 2, y = -1}},
    {"grass-2", {x = 2, y = 0}},
    {"grass-2", {x = 2, y = 1}},
    {"grass-2", {x = 2, y = 2}},
    {"grass-2", {x = 2, y = 3}},
    {"grass-2", {x = 2, y = 4}},
    {"grass-2", {x = 2, y = 5}},
    {"refined-concrete", {x = 2, y = 6}},
    {"refined-concrete", {x = 2, y = 7}},
    {"refined-concrete", {x = 2, y = 8}},
    {"refined-concrete", {x = 2, y = 9}},
    {"grass-2", {x = 2, y = 10}},
    {"grass-2", {x = 2, y = 11}},
    {"grass-2", {x = 2, y = 12}},
    {"dirt-5", {x = 2, y = 13}},
    {"dirt-5", {x = 2, y = 14}},
    {"dirt-5", {x = 2, y = 15}},
    {"grass-2", {x = 3, y = -16}},
    {"grass-2", {x = 3, y = -15}},
    {"grass-2", {x = 3, y = -14}},
    {"grass-2", {x = 3, y = -13}},
    {"grass-2", {x = 3, y = -12}},
    {"grass-2", {x = 3, y = -11}},
    {"refined-concrete", {x = 3, y = -10}},
    {"refined-concrete", {x = 3, y = -9}},
    {"refined-concrete", {x = 3, y = -8}},
    {"refined-concrete", {x = 3, y = -7}},
    {"grass-2", {x = 3, y = -6}},
    {"grass-2", {x = 3, y = -5}},
    {"grass-2", {x = 3, y = -4}},
    {"grass-2", {x = 3, y = -3}},
    {"grass-2", {x = 3, y = -2}},
    {"grass-2", {x = 3, y = -1}},
    {"grass-2", {x = 3, y = 0}},
    {"grass-2", {x = 3, y = 1}},
    {"grass-2", {x = 3, y = 2}},
    {"grass-2", {x = 3, y = 3}},
    {"grass-2", {x = 3, y = 4}},
    {"grass-2", {x = 3, y = 5}},
    {"refined-concrete", {x = 3, y = 6}},
    {"refined-concrete", {x = 3, y = 7}},
    {"refined-concrete", {x = 3, y = 8}},
    {"refined-concrete", {x = 3, y = 9}},
    {"grass-2", {x = 3, y = 10}},
    {"grass-2", {x = 3, y = 11}},
    {"grass-2", {x = 3, y = 12}},
    {"dirt-5", {x = 3, y = 13}},
    {"dirt-5", {x = 3, y = 14}},
    {"dirt-5", {x = 3, y = 15}},
    {"grass-2", {x = 4, y = -16}},
    {"grass-2", {x = 4, y = -15}},
    {"grass-2", {x = 4, y = -14}},
    {"grass-2", {x = 4, y = -13}},
    {"grass-2", {x = 4, y = -12}},
    {"grass-2", {x = 4, y = -11}},
    {"refined-concrete", {x = 4, y = -10}},
    {"refined-concrete", {x = 4, y = -9}},
    {"refined-concrete", {x = 4, y = -8}},
    {"refined-concrete", {x = 4, y = -7}},
    {"grass-2", {x = 4, y = -6}},
    {"grass-2", {x = 4, y = -5}},
    {"grass-2", {x = 4, y = -4}},
    {"grass-2", {x = 4, y = -3}},
    {"grass-2", {x = 4, y = -2}},
    {"grass-2", {x = 4, y = -1}},
    {"grass-2", {x = 4, y = 0}},
    {"grass-2", {x = 4, y = 1}},
    {"grass-2", {x = 4, y = 2}},
    {"grass-2", {x = 4, y = 3}},
    {"grass-2", {x = 4, y = 4}},
    {"grass-2", {x = 4, y = 5}},
    {"refined-concrete", {x = 4, y = 6}},
    {"refined-concrete", {x = 4, y = 7}},
    {"refined-concrete", {x = 4, y = 8}},
    {"refined-concrete", {x = 4, y = 9}},
    {"grass-2", {x = 4, y = 10}},
    {"grass-2", {x = 4, y = 11}},
    {"grass-2", {x = 4, y = 12}},
    {"dirt-5", {x = 4, y = 13}},
    {"dirt-5", {x = 4, y = 14}},
    {"dirt-5", {x = 4, y = 15}},
    {"grass-2", {x = 5, y = -16}},
    {"grass-2", {x = 5, y = -15}},
    {"grass-2", {x = 5, y = -14}},
    {"grass-2", {x = 5, y = -13}},
    {"grass-2", {x = 5, y = -12}},
    {"grass-2", {x = 5, y = -11}},
    {"refined-concrete", {x = 5, y = -10}},
    {"refined-concrete", {x = 5, y = -9}},
    {"refined-concrete", {x = 5, y = -8}},
    {"refined-concrete", {x = 5, y = -7}},
    {"refined-concrete", {x = 5, y = -6}},
    {"refined-concrete", {x = 5, y = -5}},
    {"refined-concrete", {x = 5, y = -4}},
    {"refined-concrete", {x = 5, y = -3}},
    {"refined-concrete", {x = 5, y = -2}},
    {"refined-concrete", {x = 5, y = -1}},
    {"refined-concrete", {x = 5, y = 0}},
    {"refined-concrete", {x = 5, y = 1}},
    {"refined-concrete", {x = 5, y = 2}},
    {"refined-concrete", {x = 5, y = 3}},
    {"refined-concrete", {x = 5, y = 4}},
    {"refined-concrete", {x = 5, y = 5}},
    {"refined-concrete", {x = 5, y = 6}},
    {"refined-concrete", {x = 5, y = 7}},
    {"refined-concrete", {x = 5, y = 8}},
    {"refined-concrete", {x = 5, y = 9}},
    {"grass-2", {x = 5, y = 10}},
    {"grass-2", {x = 5, y = 11}},
    {"grass-2", {x = 5, y = 12}},
    {"grass-2", {x = 5, y = 13}},
    {"grass-2", {x = 5, y = 14}},
    {"grass-2", {x = 5, y = 15}},
    {"grass-2", {x = 6, y = -16}},
    {"grass-2", {x = 6, y = -15}},
    {"grass-2", {x = 6, y = -14}},
    {"grass-2", {x = 6, y = -13}},
    {"grass-2", {x = 6, y = -12}},
    {"grass-2", {x = 6, y = -11}},
    {"refined-concrete", {x = 6, y = -10}},
    {"refined-concrete", {x = 6, y = -9}},
    {"refined-concrete", {x = 6, y = -8}},
    {"refined-concrete", {x = 6, y = -7}},
    {"refined-concrete", {x = 6, y = -6}},
    {"refined-concrete", {x = 6, y = -5}},
    {"refined-concrete", {x = 6, y = -4}},
    {"refined-concrete", {x = 6, y = -3}},
    {"refined-concrete", {x = 6, y = -2}},
    {"refined-concrete", {x = 6, y = -1}},
    {"refined-concrete", {x = 6, y = 0}},
    {"refined-concrete", {x = 6, y = 1}},
    {"refined-concrete", {x = 6, y = 2}},
    {"refined-concrete", {x = 6, y = 3}},
    {"refined-concrete", {x = 6, y = 4}},
    {"refined-concrete", {x = 6, y = 5}},
    {"refined-concrete", {x = 6, y = 6}},
    {"refined-concrete", {x = 6, y = 7}},
    {"refined-concrete", {x = 6, y = 8}},
    {"refined-concrete", {x = 6, y = 9}},
    {"grass-2", {x = 6, y = 10}},
    {"grass-2", {x = 6, y = 11}},
    {"grass-2", {x = 6, y = 12}},
    {"grass-2", {x = 6, y = 13}},
    {"grass-2", {x = 6, y = 14}},
    {"grass-2", {x = 6, y = 15}},
    {"grass-2", {x = 7, y = -16}},
    {"grass-2", {x = 7, y = -15}},
    {"grass-2", {x = 7, y = -14}},
    {"grass-2", {x = 7, y = -13}},
    {"grass-2", {x = 7, y = -12}},
    {"grass-2", {x = 7, y = -11}},
    {"refined-concrete", {x = 7, y = -10}},
    {"refined-concrete", {x = 7, y = -9}},
    {"refined-concrete", {x = 7, y = -8}},
    {"refined-concrete", {x = 7, y = -7}},
    {"refined-concrete", {x = 7, y = -6}},
    {"refined-concrete", {x = 7, y = -5}},
    {"refined-concrete", {x = 7, y = -4}},
    {"refined-concrete", {x = 7, y = -3}},
    {"refined-concrete", {x = 7, y = -2}},
    {"refined-concrete", {x = 7, y = -1}},
    {"refined-concrete", {x = 7, y = 0}},
    {"refined-concrete", {x = 7, y = 1}},
    {"refined-concrete", {x = 7, y = 2}},
    {"refined-concrete", {x = 7, y = 3}},
    {"refined-concrete", {x = 7, y = 4}},
    {"refined-concrete", {x = 7, y = 5}},
    {"refined-concrete", {x = 7, y = 6}},
    {"refined-concrete", {x = 7, y = 7}},
    {"refined-concrete", {x = 7, y = 8}},
    {"refined-concrete", {x = 7, y = 9}},
    {"grass-2", {x = 7, y = 10}},
    {"grass-2", {x = 7, y = 11}},
    {"grass-2", {x = 7, y = 12}},
    {"grass-2", {x = 7, y = 13}},
    {"grass-2", {x = 7, y = 14}},
    {"grass-2", {x = 7, y = 15}},
    {"grass-2", {x = 8, y = -16}},
    {"grass-2", {x = 8, y = -15}},
    {"grass-2", {x = 8, y = -14}},
    {"grass-2", {x = 8, y = -13}},
    {"grass-2", {x = 8, y = -12}},
    {"grass-2", {x = 8, y = -11}},
    {"refined-concrete", {x = 8, y = -10}},
    {"refined-concrete", {x = 8, y = -9}},
    {"refined-concrete", {x = 8, y = -8}},
    {"refined-concrete", {x = 8, y = -7}},
    {"refined-concrete", {x = 8, y = -6}},
    {"refined-concrete", {x = 8, y = -5}},
    {"refined-concrete", {x = 8, y = -4}},
    {"refined-concrete", {x = 8, y = -3}},
    {"refined-concrete", {x = 8, y = -2}},
    {"refined-concrete", {x = 8, y = -1}},
    {"refined-concrete", {x = 8, y = 0}},
    {"refined-concrete", {x = 8, y = 1}},
    {"refined-concrete", {x = 8, y = 2}},
    {"refined-concrete", {x = 8, y = 3}},
    {"refined-concrete", {x = 8, y = 4}},
    {"refined-concrete", {x = 8, y = 5}},
    {"refined-concrete", {x = 8, y = 6}},
    {"refined-concrete", {x = 8, y = 7}},
    {"refined-concrete", {x = 8, y = 8}},
    {"refined-concrete", {x = 8, y = 9}},
    {"grass-2", {x = 8, y = 10}},
    {"grass-2", {x = 8, y = 11}},
    {"grass-2", {x = 8, y = 12}},
    {"grass-2", {x = 8, y = 13}},
    {"grass-2", {x = 8, y = 14}},
    {"grass-2", {x = 8, y = 15}},
    {"grass-2", {x = 9, y = -16}},
    {"grass-2", {x = 9, y = -15}},
    {"grass-2", {x = 9, y = -14}},
    {"grass-2", {x = 9, y = -13}},
    {"grass-2", {x = 9, y = -12}},
    {"dirt-5", {x = 9, y = -11}},
    {"dirt-5", {x = 9, y = -10}},
    {"grass-2", {x = 9, y = -9}},
    {"grass-2", {x = 9, y = -8}},
    {"grass-2", {x = 9, y = -7}},
    {"grass-2", {x = 9, y = -6}},
    {"grass-2", {x = 9, y = -5}},
    {"grass-2", {x = 9, y = -4}},
    {"grass-2", {x = 9, y = -3}},
    {"refined-concrete", {x = 9, y = -2}},
    {"refined-concrete", {x = 9, y = -1}},
    {"refined-concrete", {x = 9, y = 0}},
    {"refined-concrete", {x = 9, y = 1}},
    {"grass-2", {x = 9, y = 2}},
    {"grass-2", {x = 9, y = 3}},
    {"grass-2", {x = 9, y = 4}},
    {"grass-2", {x = 9, y = 5}},
    {"grass-2", {x = 9, y = 6}},
    {"grass-2", {x = 9, y = 7}},
    {"grass-2", {x = 9, y = 8}},
    {"grass-2", {x = 9, y = 9}},
    {"grass-2", {x = 9, y = 10}},
    {"grass-2", {x = 9, y = 11}},
    {"grass-2", {x = 9, y = 12}},
    {"grass-2", {x = 9, y = 13}},
    {"grass-2", {x = 9, y = 14}},
    {"grass-2", {x = 9, y = 15}},
    {"grass-2", {x = 10, y = -16}},
    {"grass-2", {x = 10, y = -15}},
    {"grass-2", {x = 10, y = -14}},
    {"grass-2", {x = 10, y = -13}},
    {"dirt-5", {x = 10, y = -12}},
    {"dirt-5", {x = 10, y = -11}},
    {"dirt-5", {x = 10, y = -10}},
    {"grass-2", {x = 10, y = -9}},
    {"grass-2", {x = 10, y = -8}},
    {"grass-2", {x = 10, y = -7}},
    {"grass-2", {x = 10, y = -6}},
    {"grass-2", {x = 10, y = -5}},
    {"grass-2", {x = 10, y = -4}},
    {"grass-2", {x = 10, y = -3}},
    {"refined-concrete", {x = 10, y = -2}},
    {"refined-concrete", {x = 10, y = -1}},
    {"refined-concrete", {x = 10, y = 0}},
    {"refined-concrete", {x = 10, y = 1}},
    {"grass-2", {x = 10, y = 2}},
    {"grass-2", {x = 10, y = 3}},
    {"grass-2", {x = 10, y = 4}},
    {"grass-2", {x = 10, y = 5}},
    {"grass-2", {x = 10, y = 6}},
    {"grass-2", {x = 10, y = 7}},
    {"grass-2", {x = 10, y = 8}},
    {"grass-2", {x = 10, y = 9}},
    {"grass-2", {x = 10, y = 10}},
    {"grass-2", {x = 10, y = 11}},
    {"grass-2", {x = 10, y = 12}},
    {"grass-2", {x = 10, y = 13}},
    {"grass-2", {x = 10, y = 14}},
    {"grass-2", {x = 10, y = 15}},
    {"grass-2", {x = 11, y = -16}},
    {"grass-2", {x = 11, y = -15}},
    {"dirt-5", {x = 11, y = -14}},
    {"dirt-5", {x = 11, y = -13}},
    {"dirt-5", {x = 11, y = -12}},
    {"dirt-5", {x = 11, y = -11}},
    {"dirt-5", {x = 11, y = -10}},
    {"grass-2", {x = 11, y = -9}},
    {"grass-2", {x = 11, y = -8}},
    {"grass-2", {x = 11, y = -7}},
    {"grass-2", {x = 11, y = -6}},
    {"grass-2", {x = 11, y = -5}},
    {"grass-2", {x = 11, y = -4}},
    {"grass-2", {x = 11, y = -3}},
    {"refined-concrete", {x = 11, y = -2}},
    {"refined-concrete", {x = 11, y = -1}},
    {"refined-concrete", {x = 11, y = 0}},
    {"refined-concrete", {x = 11, y = 1}},
    {"grass-2", {x = 11, y = 2}},
    {"grass-2", {x = 11, y = 3}},
    {"grass-2", {x = 11, y = 4}},
    {"grass-2", {x = 11, y = 5}},
    {"grass-2", {x = 11, y = 6}},
    {"grass-2", {x = 11, y = 7}},
    {"grass-2", {x = 11, y = 8}},
    {"grass-2", {x = 11, y = 9}},
    {"grass-2", {x = 11, y = 10}},
    {"grass-2", {x = 11, y = 11}},
    {"grass-2", {x = 11, y = 12}},
    {"grass-2", {x = 11, y = 13}},
    {"grass-2", {x = 11, y = 14}},
    {"grass-2", {x = 11, y = 15}},
    {"grass-2", {x = 12, y = -16}},
    {"dirt-5", {x = 12, y = -15}},
    {"dirt-5", {x = 12, y = -14}},
    {"dirt-5", {x = 12, y = -13}},
    {"dirt-5", {x = 12, y = -12}},
    {"dirt-5", {x = 12, y = -11}},
    {"dirt-5", {x = 12, y = -10}},
    {"dirt-5", {x = 12, y = -9}},
    {"grass-2", {x = 12, y = -8}},
    {"grass-2", {x = 12, y = -7}},
    {"grass-2", {x = 12, y = -6}},
    {"grass-2", {x = 12, y = -5}},
    {"grass-2", {x = 12, y = -4}},
    {"grass-2", {x = 12, y = -3}},
    {"refined-concrete", {x = 12, y = -2}},
    {"refined-concrete", {x = 12, y = -1}},
    {"refined-concrete", {x = 12, y = 0}},
    {"refined-concrete", {x = 12, y = 1}},
    {"grass-2", {x = 12, y = 2}},
    {"grass-2", {x = 12, y = 3}},
    {"grass-2", {x = 12, y = 4}},
    {"grass-2", {x = 12, y = 5}},
    {"grass-2", {x = 12, y = 6}},
    {"grass-2", {x = 12, y = 7}},
    {"grass-2", {x = 12, y = 8}},
    {"grass-2", {x = 12, y = 9}},
    {"grass-2", {x = 12, y = 10}},
    {"grass-2", {x = 12, y = 11}},
    {"grass-2", {x = 12, y = 12}},
    {"grass-2", {x = 12, y = 13}},
    {"grass-2", {x = 12, y = 14}},
    {"grass-2", {x = 12, y = 15}},
    {"dirt-5", {x = 13, y = -16}},
    {"dirt-5", {x = 13, y = -15}},
    {"dirt-5", {x = 13, y = -14}},
    {"dirt-5", {x = 13, y = -13}},
    {"dirt-5", {x = 13, y = -12}},
    {"dirt-5", {x = 13, y = -11}},
    {"dirt-5", {x = 13, y = -10}},
    {"dirt-5", {x = 13, y = -9}},
    {"grass-2", {x = 13, y = -8}},
    {"grass-2", {x = 13, y = -7}},
    {"grass-2", {x = 13, y = -6}},
    {"grass-2", {x = 13, y = -5}},
    {"grass-2", {x = 13, y = -4}},
    {"grass-2", {x = 13, y = -3}},
    {"refined-concrete", {x = 13, y = -2}},
    {"refined-concrete", {x = 13, y = -1}},
    {"refined-concrete", {x = 13, y = 0}},
    {"refined-concrete", {x = 13, y = 1}},
    {"grass-2", {x = 13, y = 2}},
    {"grass-2", {x = 13, y = 3}},
    {"grass-2", {x = 13, y = 4}},
    {"grass-2", {x = 13, y = 5}},
    {"grass-2", {x = 13, y = 6}},
    {"grass-2", {x = 13, y = 7}},
    {"grass-2", {x = 13, y = 8}},
    {"grass-2", {x = 13, y = 9}},
    {"grass-2", {x = 13, y = 10}},
    {"grass-2", {x = 13, y = 11}},
    {"grass-2", {x = 13, y = 12}},
    {"grass-2", {x = 13, y = 13}},
    {"grass-2", {x = 13, y = 14}},
    {"grass-2", {x = 13, y = 15}},
    {"dirt-5", {x = 14, y = -16}},
    {"dirt-5", {x = 14, y = -15}},
    {"dirt-5", {x = 14, y = -14}},
    {"dirt-5", {x = 14, y = -13}},
    {"dirt-5", {x = 14, y = -12}},
    {"dirt-5", {x = 14, y = -11}},
    {"dirt-5", {x = 14, y = -10}},
    {"dirt-5", {x = 14, y = -9}},
    {"dirt-5", {x = 14, y = -8}},
    {"grass-2", {x = 14, y = -7}},
    {"grass-2", {x = 14, y = -6}},
    {"grass-2", {x = 14, y = -5}},
    {"grass-2", {x = 14, y = -4}},
    {"grass-2", {x = 14, y = -3}},
    {"refined-concrete", {x = 14, y = -2}},
    {"refined-concrete", {x = 14, y = -1}},
    {"refined-concrete", {x = 14, y = 0}},
    {"refined-concrete", {x = 14, y = 1}},
    {"grass-2", {x = 14, y = 2}},
    {"grass-2", {x = 14, y = 3}},
    {"grass-2", {x = 14, y = 4}},
    {"dirt-5", {x = 14, y = 5}},
    {"dirt-5", {x = 14, y = 6}},
    {"dirt-5", {x = 14, y = 7}},
    {"dirt-5", {x = 14, y = 8}},
    {"dirt-5", {x = 14, y = 9}},
    {"dirt-5", {x = 14, y = 10}},
    {"grass-2", {x = 14, y = 11}},
    {"grass-2", {x = 14, y = 12}},
    {"dry-dirt", {x = 14, y = 13}},
    {"dry-dirt", {x = 14, y = 14}},
    {"grass-2", {x = 14, y = 15}},
    {"dirt-5", {x = 15, y = -16}},
    {"dirt-5", {x = 15, y = -15}},
    {"dirt-5", {x = 15, y = -14}},
    {"dirt-5", {x = 15, y = -13}},
    {"dirt-5", {x = 15, y = -12}},
    {"dirt-5", {x = 15, y = -11}},
    {"dirt-5", {x = 15, y = -10}},
    {"dirt-5", {x = 15, y = -9}},
    {"dirt-5", {x = 15, y = -8}},
    {"dirt-5", {x = 15, y = -7}},
    {"grass-2", {x = 15, y = -6}},
    {"grass-2", {x = 15, y = -5}},
    {"grass-2", {x = 15, y = -4}},
    {"grass-2", {x = 15, y = -3}},
    {"refined-concrete", {x = 15, y = -2}},
    {"refined-concrete", {x = 15, y = -1}},
    {"refined-concrete", {x = 15, y = 0}},
    {"refined-concrete", {x = 15, y = 1}},
    {"grass-2", {x = 15, y = 2}},
    {"dirt-3", {x = 15, y = 3}},
    {"dirt-3", {x = 15, y = 4}},
    {"dirt-5", {x = 15, y = 5}},
    {"dirt-5", {x = 15, y = 6}},
    {"dirt-5", {x = 15, y = 7}},
    {"dirt-5", {x = 15, y = 8}},
    {"dirt-5", {x = 15, y = 9}},
    {"dirt-5", {x = 15, y = 10}},
    {"dirt-5", {x = 15, y = 11}},
    {"dirt-5", {x = 15, y = 12}},
    {"dry-dirt", {x = 15, y = 13}},
    {"dry-dirt", {x = 15, y = 14}},
    {"dirt-5", {x = 15, y = 15}},
  }
}
