return
{
  entities =
  {
    {"laser-turret", {x = -14, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"artillery-turret", {x = -10.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"fast-inserter", {x = -8.5, y = -14.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"steel-chest", {x = -7.5, y = -14.5}, {force = "enemy", items = {["artillery-shell"] = 48}, }},
    {"stone-wall", {x = -6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -1, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -14}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -12.5}, {force = "enemy", }},
    {"steel-chest", {x = 2.5, y = -13.5}, {items = {["repair-pack"] = 100}, }},
    {"steel-chest", {x = 4.5, y = -13.5}, {items = {["express-underground-belt"] = 50}, }},
    {"steel-chest", {x = 6.5, y = -13.5}, {items = {["express-splitter"] = 50}, }},
    {"steel-chest", {x = 8.5, y = -13.5}, {items = {["utility-science-pack"] = 56}, }},
    {"stone-wall", {x = 13.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"substation", {x = -7, y = -10}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -10.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -8.5}, {force = "enemy", }},
    {"steel-chest", {x = -5.5, y = -9.5}, {items = {["express-transport-belt"] = 100}, }},
    {"stone-wall", {x = -4.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -8.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -8.5}, {force = "enemy", }},
    {"substation", {x = 5, y = -8}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = -7}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -6.5}, {force = "enemy", }},
    {"green-crystal-gen", {x = -1.5, y = -8}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -6.5}, {force = "enemy", }},
    {"steel-chest", {x = 11.5, y = -6.5}, {items = {["energy-shield-equipment"] = 1, ["night-vision-equipment"] = 1}, }},
    {"laser-turret", {x = 14, y = -6}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = 2, y = -5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -5.5}, {force = "enemy", }},
    {"steel-chest", {x = 11.5, y = -5.5}, {items = {["repair-pack"] = 100}, }},
    {"stone-wall", {x = 13.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = 5.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 4.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 7.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 6.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 8.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = 15.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = 15.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = 15.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = 15.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 3.5}, {force = "enemy", }},
    {"gate", {x = 5.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 4.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 7.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 6.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 8.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 5.5}, {force = "enemy", }},
    {"laser-turret", {x = 2, y = 5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 4.5}, {force = "enemy", }},
    {"steel-chest", {x = 11.5, y = 5.5}, {items = {["cryexplosive-rounds-magazine"] = 1, ["exoskeleton-equipment"] = 1}, }},
    {"laser-turret", {x = 14, y = 6}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 4.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = 7}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 6.5}, {force = "enemy", }},
    {"purple-crystal-gen", {x = -1.5, y = 6}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 6.5}, {force = "enemy", }},
    {"substation", {x = 5, y = 8}, {force = "enemy", }},
    {"roboport", {x = 9, y = 9}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"steel-chest", {x = 11.5, y = 6.5}, {items = {["production-science-pack"] = 56, ["raw-fish"] = 100}, }},
    {"stone-wall", {x = 12.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 8.5}, {force = "enemy", }},
    {"substation", {x = -7, y = 10}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 8.5}, {force = "enemy", }},
    {"steel-chest", {x = -5.5, y = 9.5}, {items = {["automation-science-pack"] = 50, ["logistic-science-pack"] = 50}, }},
    {"stone-wall", {x = -4.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 8.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 8.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.16, y = 9.73}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.16, y = 9.84}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 9.87}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 9.94}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 9.97}, {force = "enemy", }},
    {"logistic-chest-storage", {x = 11.5, y = 9.5}, {force = "enemy", items = {["repair-pack"] = 4700}, }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 11.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 10.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 11.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.16, y = 10.01}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.16, y = 10.11}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.16, y = 10.21}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.16, y = 10.39}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.26, y = 10.59}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.3, y = 10.77}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.37, y = 11.01}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.43, y = 11.29}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.47, y = 11.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.47, y = 11.66}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.47, y = 11.84}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.47, y = 11.97}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 10.01}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.13, y = 10.11}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.09, y = 10.21}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.09, y = 10.42}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.13, y = 10.7}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 10.97}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 11.11}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 11.21}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 11.35}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 11.52}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.16, y = 11.66}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.2, y = 11.77}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.23, y = 11.84}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.26, y = 11.87}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.26, y = 11.91}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 10.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 12.5}, {force = "enemy", }},
    {"artillery-turret", {x = -10.5, y = 13.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -1, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 12.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.47, y = 12.08}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.47, y = 12.21}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.47, y = 12.25}, {force = "enemy", }},
    {"aliencon-robot", {x = 5.47, y = 12.29}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 15.5}, {force = "enemy", }},
    {"fast-inserter", {x = -8.5, y = 14.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 15.5}, {force = "enemy", }},
    {"steel-chest", {x = -7.5, y = 14.5}, {force = "enemy", items = {["artillery-shell"] = 48}, }},
    {"stone-wall", {x = -7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 14.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -16, y = -16}},
    {"grass-1", {x = -16, y = -15}},
    {"grass-1", {x = -16, y = -14}},
    {"grass-1", {x = -16, y = -13}},
    {"grass-1", {x = -16, y = -12}},
    {"grass-1", {x = -16, y = -11}},
    {"grass-1", {x = -16, y = -10}},
    {"grass-1", {x = -16, y = -9}},
    {"grass-1", {x = -16, y = -8}},
    {"grass-1", {x = -16, y = -7}},
    {"grass-1", {x = -16, y = -6}},
    {"grass-1", {x = -16, y = -5}},
    {"grass-1", {x = -16, y = -4}},
    {"grass-1", {x = -16, y = -3}},
    {"refined-concrete", {x = -16, y = -2}},
    {"refined-concrete", {x = -16, y = -1}},
    {"refined-concrete", {x = -16, y = 0}},
    {"refined-concrete", {x = -16, y = 1}},
    {"grass-1", {x = -16, y = 2}},
    {"grass-1", {x = -16, y = 3}},
    {"grass-1", {x = -16, y = 4}},
    {"grass-1", {x = -16, y = 5}},
    {"grass-1", {x = -16, y = 6}},
    {"grass-1", {x = -16, y = 7}},
    {"grass-1", {x = -16, y = 8}},
    {"grass-1", {x = -16, y = 9}},
    {"grass-1", {x = -16, y = 10}},
    {"grass-1", {x = -16, y = 11}},
    {"grass-1", {x = -16, y = 12}},
    {"grass-1", {x = -16, y = 13}},
    {"grass-1", {x = -16, y = 14}},
    {"grass-1", {x = -16, y = 15}},
    {"grass-1", {x = -15, y = -16}},
    {"grass-1", {x = -15, y = -15}},
    {"grass-1", {x = -15, y = -14}},
    {"grass-1", {x = -15, y = -13}},
    {"refined-concrete", {x = -15, y = -12}},
    {"refined-concrete", {x = -15, y = -11}},
    {"grass-1", {x = -15, y = -10}},
    {"grass-1", {x = -15, y = -9}},
    {"grass-1", {x = -15, y = -8}},
    {"grass-1", {x = -15, y = -7}},
    {"grass-1", {x = -15, y = -6}},
    {"grass-1", {x = -15, y = -5}},
    {"grass-1", {x = -15, y = -4}},
    {"grass-1", {x = -15, y = -3}},
    {"refined-concrete", {x = -15, y = -2}},
    {"refined-concrete", {x = -15, y = -1}},
    {"refined-concrete", {x = -15, y = 0}},
    {"refined-concrete", {x = -15, y = 1}},
    {"grass-1", {x = -15, y = 2}},
    {"grass-1", {x = -15, y = 3}},
    {"grass-1", {x = -15, y = 4}},
    {"grass-1", {x = -15, y = 5}},
    {"grass-1", {x = -15, y = 6}},
    {"grass-1", {x = -15, y = 7}},
    {"grass-1", {x = -15, y = 8}},
    {"grass-1", {x = -15, y = 9}},
    {"refined-concrete", {x = -15, y = 10}},
    {"refined-concrete", {x = -15, y = 11}},
    {"grass-1", {x = -15, y = 12}},
    {"grass-1", {x = -15, y = 13}},
    {"grass-1", {x = -15, y = 14}},
    {"grass-1", {x = -15, y = 15}},
    {"grass-1", {x = -14, y = -16}},
    {"grass-1", {x = -14, y = -15}},
    {"grass-1", {x = -14, y = -14}},
    {"grass-1", {x = -14, y = -13}},
    {"refined-concrete", {x = -14, y = -12}},
    {"refined-concrete", {x = -14, y = -11}},
    {"grass-1", {x = -14, y = -10}},
    {"grass-1", {x = -14, y = -9}},
    {"grass-1", {x = -14, y = -8}},
    {"grass-1", {x = -14, y = -7}},
    {"grass-1", {x = -14, y = -6}},
    {"grass-1", {x = -14, y = -5}},
    {"grass-1", {x = -14, y = -4}},
    {"grass-1", {x = -14, y = -3}},
    {"refined-concrete", {x = -14, y = -2}},
    {"refined-concrete", {x = -14, y = -1}},
    {"refined-concrete", {x = -14, y = 0}},
    {"refined-concrete", {x = -14, y = 1}},
    {"grass-1", {x = -14, y = 2}},
    {"grass-1", {x = -14, y = 3}},
    {"grass-1", {x = -14, y = 4}},
    {"grass-1", {x = -14, y = 5}},
    {"grass-1", {x = -14, y = 6}},
    {"grass-1", {x = -14, y = 7}},
    {"grass-1", {x = -14, y = 8}},
    {"grass-1", {x = -14, y = 9}},
    {"refined-concrete", {x = -14, y = 10}},
    {"refined-concrete", {x = -14, y = 11}},
    {"grass-1", {x = -14, y = 12}},
    {"grass-1", {x = -14, y = 13}},
    {"grass-1", {x = -14, y = 14}},
    {"grass-1", {x = -14, y = 15}},
    {"grass-1", {x = -13, y = -16}},
    {"grass-1", {x = -13, y = -15}},
    {"grass-1", {x = -13, y = -14}},
    {"grass-1", {x = -13, y = -13}},
    {"refined-concrete", {x = -13, y = -12}},
    {"refined-concrete", {x = -13, y = -11}},
    {"grass-1", {x = -13, y = -10}},
    {"grass-1", {x = -13, y = -9}},
    {"grass-1", {x = -13, y = -8}},
    {"grass-1", {x = -13, y = -7}},
    {"grass-1", {x = -13, y = -6}},
    {"grass-1", {x = -13, y = -5}},
    {"grass-1", {x = -13, y = -4}},
    {"grass-1", {x = -13, y = -3}},
    {"refined-concrete", {x = -13, y = -2}},
    {"refined-concrete", {x = -13, y = -1}},
    {"refined-concrete", {x = -13, y = 0}},
    {"refined-concrete", {x = -13, y = 1}},
    {"grass-1", {x = -13, y = 2}},
    {"grass-1", {x = -13, y = 3}},
    {"grass-1", {x = -13, y = 4}},
    {"grass-1", {x = -13, y = 5}},
    {"grass-1", {x = -13, y = 6}},
    {"grass-1", {x = -13, y = 7}},
    {"grass-1", {x = -13, y = 8}},
    {"grass-1", {x = -13, y = 9}},
    {"refined-concrete", {x = -13, y = 10}},
    {"refined-concrete", {x = -13, y = 11}},
    {"grass-1", {x = -13, y = 12}},
    {"grass-1", {x = -13, y = 13}},
    {"grass-1", {x = -13, y = 14}},
    {"grass-1", {x = -13, y = 15}},
    {"grass-1", {x = -12, y = -16}},
    {"grass-1", {x = -12, y = -15}},
    {"grass-1", {x = -12, y = -14}},
    {"grass-1", {x = -12, y = -13}},
    {"refined-concrete", {x = -12, y = -12}},
    {"refined-concrete", {x = -12, y = -11}},
    {"grass-1", {x = -12, y = -10}},
    {"grass-1", {x = -12, y = -9}},
    {"grass-1", {x = -12, y = -8}},
    {"grass-1", {x = -12, y = -7}},
    {"grass-1", {x = -12, y = -6}},
    {"grass-1", {x = -12, y = -5}},
    {"grass-1", {x = -12, y = -4}},
    {"grass-1", {x = -12, y = -3}},
    {"refined-concrete", {x = -12, y = -2}},
    {"refined-concrete", {x = -12, y = -1}},
    {"refined-concrete", {x = -12, y = 0}},
    {"refined-concrete", {x = -12, y = 1}},
    {"grass-1", {x = -12, y = 2}},
    {"grass-1", {x = -12, y = 3}},
    {"grass-1", {x = -12, y = 4}},
    {"grass-1", {x = -12, y = 5}},
    {"grass-1", {x = -12, y = 6}},
    {"grass-1", {x = -12, y = 7}},
    {"grass-1", {x = -12, y = 8}},
    {"grass-1", {x = -12, y = 9}},
    {"refined-concrete", {x = -12, y = 10}},
    {"refined-concrete", {x = -12, y = 11}},
    {"grass-1", {x = -12, y = 12}},
    {"grass-1", {x = -12, y = 13}},
    {"grass-1", {x = -12, y = 14}},
    {"grass-1", {x = -12, y = 15}},
    {"grass-1", {x = -11, y = -16}},
    {"grass-1", {x = -11, y = -15}},
    {"refined-concrete", {x = -11, y = -14}},
    {"refined-concrete", {x = -11, y = -13}},
    {"refined-concrete", {x = -11, y = -12}},
    {"refined-concrete", {x = -11, y = -11}},
    {"grass-1", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-1", {x = -11, y = -5}},
    {"grass-1", {x = -11, y = -4}},
    {"grass-1", {x = -11, y = -3}},
    {"refined-concrete", {x = -11, y = -2}},
    {"refined-concrete", {x = -11, y = -1}},
    {"refined-concrete", {x = -11, y = 0}},
    {"refined-concrete", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-1", {x = -11, y = 4}},
    {"grass-1", {x = -11, y = 5}},
    {"grass-1", {x = -11, y = 6}},
    {"grass-1", {x = -11, y = 7}},
    {"grass-1", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"refined-concrete", {x = -11, y = 10}},
    {"refined-concrete", {x = -11, y = 11}},
    {"refined-concrete", {x = -11, y = 12}},
    {"refined-concrete", {x = -11, y = 13}},
    {"grass-1", {x = -11, y = 14}},
    {"grass-1", {x = -11, y = 15}},
    {"grass-1", {x = -10, y = -16}},
    {"grass-1", {x = -10, y = -15}},
    {"refined-concrete", {x = -10, y = -14}},
    {"refined-concrete", {x = -10, y = -13}},
    {"refined-concrete", {x = -10, y = -12}},
    {"refined-concrete", {x = -10, y = -11}},
    {"grass-1", {x = -10, y = -10}},
    {"grass-1", {x = -10, y = -9}},
    {"grass-1", {x = -10, y = -8}},
    {"grass-1", {x = -10, y = -7}},
    {"grass-1", {x = -10, y = -6}},
    {"grass-1", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-1", {x = -10, y = -3}},
    {"refined-concrete", {x = -10, y = -2}},
    {"refined-concrete", {x = -10, y = -1}},
    {"refined-concrete", {x = -10, y = 0}},
    {"refined-concrete", {x = -10, y = 1}},
    {"grass-1", {x = -10, y = 2}},
    {"grass-1", {x = -10, y = 3}},
    {"grass-1", {x = -10, y = 4}},
    {"grass-1", {x = -10, y = 5}},
    {"grass-1", {x = -10, y = 6}},
    {"grass-1", {x = -10, y = 7}},
    {"grass-1", {x = -10, y = 8}},
    {"grass-1", {x = -10, y = 9}},
    {"refined-concrete", {x = -10, y = 10}},
    {"refined-concrete", {x = -10, y = 11}},
    {"refined-concrete", {x = -10, y = 12}},
    {"refined-concrete", {x = -10, y = 13}},
    {"grass-1", {x = -10, y = 14}},
    {"grass-1", {x = -10, y = 15}},
    {"grass-1", {x = -9, y = -16}},
    {"grass-1", {x = -9, y = -15}},
    {"refined-concrete", {x = -9, y = -14}},
    {"refined-concrete", {x = -9, y = -13}},
    {"refined-concrete", {x = -9, y = -12}},
    {"refined-concrete", {x = -9, y = -11}},
    {"grass-1", {x = -9, y = -10}},
    {"grass-1", {x = -9, y = -9}},
    {"grass-1", {x = -9, y = -8}},
    {"grass-1", {x = -9, y = -7}},
    {"grass-1", {x = -9, y = -6}},
    {"grass-1", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"refined-concrete", {x = -9, y = -2}},
    {"refined-concrete", {x = -9, y = -1}},
    {"refined-concrete", {x = -9, y = 0}},
    {"refined-concrete", {x = -9, y = 1}},
    {"grass-1", {x = -9, y = 2}},
    {"grass-1", {x = -9, y = 3}},
    {"grass-1", {x = -9, y = 4}},
    {"grass-1", {x = -9, y = 5}},
    {"grass-1", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-1", {x = -9, y = 9}},
    {"refined-concrete", {x = -9, y = 10}},
    {"refined-concrete", {x = -9, y = 11}},
    {"refined-concrete", {x = -9, y = 12}},
    {"refined-concrete", {x = -9, y = 13}},
    {"grass-1", {x = -9, y = 14}},
    {"grass-1", {x = -9, y = 15}},
    {"grass-1", {x = -8, y = -16}},
    {"grass-1", {x = -8, y = -15}},
    {"refined-concrete", {x = -8, y = -14}},
    {"refined-concrete", {x = -8, y = -13}},
    {"refined-concrete", {x = -8, y = -12}},
    {"refined-concrete", {x = -8, y = -11}},
    {"grass-1", {x = -8, y = -10}},
    {"grass-1", {x = -8, y = -9}},
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"refined-concrete", {x = -8, y = -2}},
    {"refined-concrete", {x = -8, y = -1}},
    {"refined-concrete", {x = -8, y = 0}},
    {"refined-concrete", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-1", {x = -8, y = 9}},
    {"refined-concrete", {x = -8, y = 10}},
    {"refined-concrete", {x = -8, y = 11}},
    {"refined-concrete", {x = -8, y = 12}},
    {"refined-concrete", {x = -8, y = 13}},
    {"grass-1", {x = -8, y = 14}},
    {"grass-1", {x = -8, y = 15}},
    {"grass-1", {x = -7, y = -16}},
    {"grass-1", {x = -7, y = -15}},
    {"refined-concrete", {x = -7, y = -14}},
    {"refined-concrete", {x = -7, y = -13}},
    {"refined-concrete", {x = -7, y = -12}},
    {"refined-concrete", {x = -7, y = -11}},
    {"grass-1", {x = -7, y = -10}},
    {"grass-1", {x = -7, y = -9}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"refined-concrete", {x = -7, y = -2}},
    {"refined-concrete", {x = -7, y = -1}},
    {"refined-concrete", {x = -7, y = 0}},
    {"refined-concrete", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -7, y = 8}},
    {"grass-1", {x = -7, y = 9}},
    {"refined-concrete", {x = -7, y = 10}},
    {"refined-concrete", {x = -7, y = 11}},
    {"refined-concrete", {x = -7, y = 12}},
    {"refined-concrete", {x = -7, y = 13}},
    {"grass-1", {x = -7, y = 14}},
    {"grass-1", {x = -7, y = 15}},
    {"grass-1", {x = -6, y = -16}},
    {"grass-1", {x = -6, y = -15}},
    {"refined-concrete", {x = -6, y = -14}},
    {"refined-concrete", {x = -6, y = -13}},
    {"refined-concrete", {x = -6, y = -12}},
    {"refined-concrete", {x = -6, y = -11}},
    {"grass-1", {x = -6, y = -10}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"refined-concrete", {x = -6, y = -2}},
    {"refined-concrete", {x = -6, y = -1}},
    {"refined-concrete", {x = -6, y = 0}},
    {"refined-concrete", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"grass-1", {x = -6, y = 9}},
    {"refined-concrete", {x = -6, y = 10}},
    {"refined-concrete", {x = -6, y = 11}},
    {"refined-concrete", {x = -6, y = 12}},
    {"refined-concrete", {x = -6, y = 13}},
    {"grass-1", {x = -6, y = 14}},
    {"grass-1", {x = -6, y = 15}},
    {"grass-1", {x = -5, y = -16}},
    {"grass-1", {x = -5, y = -15}},
    {"refined-concrete", {x = -5, y = -14}},
    {"refined-concrete", {x = -5, y = -13}},
    {"refined-concrete", {x = -5, y = -12}},
    {"refined-concrete", {x = -5, y = -11}},
    {"grass-1", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"refined-concrete", {x = -5, y = -2}},
    {"refined-concrete", {x = -5, y = -1}},
    {"refined-concrete", {x = -5, y = 0}},
    {"refined-concrete", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -5, y = 8}},
    {"grass-1", {x = -5, y = 9}},
    {"refined-concrete", {x = -5, y = 10}},
    {"refined-concrete", {x = -5, y = 11}},
    {"refined-concrete", {x = -5, y = 12}},
    {"refined-concrete", {x = -5, y = 13}},
    {"grass-1", {x = -5, y = 14}},
    {"grass-1", {x = -5, y = 15}},
    {"grass-1", {x = -4, y = -16}},
    {"grass-1", {x = -4, y = -15}},
    {"grass-1", {x = -4, y = -14}},
    {"grass-1", {x = -4, y = -13}},
    {"refined-concrete", {x = -4, y = -12}},
    {"refined-concrete", {x = -4, y = -11}},
    {"grass-1", {x = -4, y = -10}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"refined-concrete", {x = -4, y = -2}},
    {"refined-concrete", {x = -4, y = -1}},
    {"refined-concrete", {x = -4, y = 0}},
    {"refined-concrete", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -4, y = 8}},
    {"grass-1", {x = -4, y = 9}},
    {"refined-concrete", {x = -4, y = 10}},
    {"refined-concrete", {x = -4, y = 11}},
    {"grass-1", {x = -4, y = 12}},
    {"grass-1", {x = -4, y = 13}},
    {"grass-1", {x = -4, y = 14}},
    {"grass-1", {x = -4, y = 15}},
    {"grass-1", {x = -3, y = -16}},
    {"grass-1", {x = -3, y = -15}},
    {"grass-1", {x = -3, y = -14}},
    {"grass-1", {x = -3, y = -13}},
    {"refined-concrete", {x = -3, y = -12}},
    {"refined-concrete", {x = -3, y = -11}},
    {"grass-1", {x = -3, y = -10}},
    {"grass-1", {x = -3, y = -9}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"refined-concrete", {x = -3, y = -2}},
    {"refined-concrete", {x = -3, y = -1}},
    {"refined-concrete", {x = -3, y = 0}},
    {"refined-concrete", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -3, y = 8}},
    {"grass-1", {x = -3, y = 9}},
    {"refined-concrete", {x = -3, y = 10}},
    {"refined-concrete", {x = -3, y = 11}},
    {"grass-1", {x = -3, y = 12}},
    {"grass-1", {x = -3, y = 13}},
    {"grass-1", {x = -3, y = 14}},
    {"grass-1", {x = -3, y = 15}},
    {"grass-1", {x = -2, y = -16}},
    {"grass-1", {x = -2, y = -15}},
    {"grass-1", {x = -2, y = -14}},
    {"grass-1", {x = -2, y = -13}},
    {"refined-concrete", {x = -2, y = -12}},
    {"refined-concrete", {x = -2, y = -11}},
    {"grass-1", {x = -2, y = -10}},
    {"grass-1", {x = -2, y = -9}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-1", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"refined-concrete", {x = -2, y = -2}},
    {"refined-concrete", {x = -2, y = -1}},
    {"refined-concrete", {x = -2, y = 0}},
    {"refined-concrete", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -2, y = 8}},
    {"grass-1", {x = -2, y = 9}},
    {"refined-concrete", {x = -2, y = 10}},
    {"refined-concrete", {x = -2, y = 11}},
    {"grass-1", {x = -2, y = 12}},
    {"grass-1", {x = -2, y = 13}},
    {"grass-1", {x = -2, y = 14}},
    {"grass-1", {x = -2, y = 15}},
    {"grass-1", {x = -1, y = -16}},
    {"grass-1", {x = -1, y = -15}},
    {"grass-1", {x = -1, y = -14}},
    {"grass-1", {x = -1, y = -13}},
    {"refined-concrete", {x = -1, y = -12}},
    {"refined-concrete", {x = -1, y = -11}},
    {"grass-1", {x = -1, y = -10}},
    {"grass-1", {x = -1, y = -9}},
    {"grass-1", {x = -1, y = -8}},
    {"grass-1", {x = -1, y = -7}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"refined-concrete", {x = -1, y = -2}},
    {"refined-concrete", {x = -1, y = -1}},
    {"refined-concrete", {x = -1, y = 0}},
    {"refined-concrete", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = -1, y = 8}},
    {"grass-1", {x = -1, y = 9}},
    {"refined-concrete", {x = -1, y = 10}},
    {"refined-concrete", {x = -1, y = 11}},
    {"grass-1", {x = -1, y = 12}},
    {"grass-1", {x = -1, y = 13}},
    {"grass-1", {x = -1, y = 14}},
    {"grass-1", {x = -1, y = 15}},
    {"grass-1", {x = 0, y = -16}},
    {"grass-1", {x = 0, y = -15}},
    {"grass-1", {x = 0, y = -14}},
    {"grass-1", {x = 0, y = -13}},
    {"refined-concrete", {x = 0, y = -12}},
    {"refined-concrete", {x = 0, y = -11}},
    {"grass-1", {x = 0, y = -10}},
    {"grass-1", {x = 0, y = -9}},
    {"grass-1", {x = 0, y = -8}},
    {"grass-1", {x = 0, y = -7}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"refined-concrete", {x = 0, y = -2}},
    {"refined-concrete", {x = 0, y = -1}},
    {"refined-concrete", {x = 0, y = 0}},
    {"refined-concrete", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-1", {x = 0, y = 9}},
    {"refined-concrete", {x = 0, y = 10}},
    {"refined-concrete", {x = 0, y = 11}},
    {"grass-1", {x = 0, y = 12}},
    {"grass-1", {x = 0, y = 13}},
    {"grass-1", {x = 0, y = 14}},
    {"grass-1", {x = 0, y = 15}},
    {"grass-1", {x = 1, y = -16}},
    {"grass-1", {x = 1, y = -15}},
    {"grass-1", {x = 1, y = -14}},
    {"grass-1", {x = 1, y = -13}},
    {"refined-concrete", {x = 1, y = -12}},
    {"refined-concrete", {x = 1, y = -11}},
    {"grass-1", {x = 1, y = -10}},
    {"grass-1", {x = 1, y = -9}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"refined-concrete", {x = 1, y = -2}},
    {"refined-concrete", {x = 1, y = -1}},
    {"refined-concrete", {x = 1, y = 0}},
    {"refined-concrete", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-1", {x = 1, y = 9}},
    {"refined-concrete", {x = 1, y = 10}},
    {"refined-concrete", {x = 1, y = 11}},
    {"grass-1", {x = 1, y = 12}},
    {"grass-1", {x = 1, y = 13}},
    {"grass-1", {x = 1, y = 14}},
    {"grass-1", {x = 1, y = 15}},
    {"grass-1", {x = 2, y = -16}},
    {"grass-1", {x = 2, y = -15}},
    {"refined-concrete", {x = 2, y = -14}},
    {"refined-concrete", {x = 2, y = -13}},
    {"refined-concrete", {x = 2, y = -12}},
    {"refined-concrete", {x = 2, y = -11}},
    {"grass-1", {x = 2, y = -10}},
    {"grass-1", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"refined-concrete", {x = 2, y = -2}},
    {"refined-concrete", {x = 2, y = -1}},
    {"refined-concrete", {x = 2, y = 0}},
    {"refined-concrete", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 2, y = 9}},
    {"refined-concrete", {x = 2, y = 10}},
    {"refined-concrete", {x = 2, y = 11}},
    {"refined-concrete", {x = 2, y = 12}},
    {"refined-concrete", {x = 2, y = 13}},
    {"grass-1", {x = 2, y = 14}},
    {"grass-1", {x = 2, y = 15}},
    {"grass-1", {x = 3, y = -16}},
    {"grass-1", {x = 3, y = -15}},
    {"refined-concrete", {x = 3, y = -14}},
    {"refined-concrete", {x = 3, y = -13}},
    {"refined-concrete", {x = 3, y = -12}},
    {"refined-concrete", {x = 3, y = -11}},
    {"grass-1", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"refined-concrete", {x = 3, y = -2}},
    {"refined-concrete", {x = 3, y = -1}},
    {"refined-concrete", {x = 3, y = 0}},
    {"refined-concrete", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 3, y = 9}},
    {"refined-concrete", {x = 3, y = 10}},
    {"refined-concrete", {x = 3, y = 11}},
    {"refined-concrete", {x = 3, y = 12}},
    {"refined-concrete", {x = 3, y = 13}},
    {"grass-1", {x = 3, y = 14}},
    {"grass-1", {x = 3, y = 15}},
    {"grass-1", {x = 4, y = -16}},
    {"grass-1", {x = 4, y = -15}},
    {"refined-concrete", {x = 4, y = -14}},
    {"refined-concrete", {x = 4, y = -13}},
    {"refined-concrete", {x = 4, y = -12}},
    {"refined-concrete", {x = 4, y = -11}},
    {"refined-concrete", {x = 4, y = -10}},
    {"refined-concrete", {x = 4, y = -9}},
    {"refined-concrete", {x = 4, y = -8}},
    {"refined-concrete", {x = 4, y = -7}},
    {"refined-concrete", {x = 4, y = -6}},
    {"refined-concrete", {x = 4, y = -5}},
    {"refined-concrete", {x = 4, y = -4}},
    {"refined-concrete", {x = 4, y = -3}},
    {"refined-concrete", {x = 4, y = -2}},
    {"refined-concrete", {x = 4, y = -1}},
    {"refined-concrete", {x = 4, y = 0}},
    {"refined-concrete", {x = 4, y = 1}},
    {"refined-concrete", {x = 4, y = 2}},
    {"refined-concrete", {x = 4, y = 3}},
    {"refined-concrete", {x = 4, y = 4}},
    {"refined-concrete", {x = 4, y = 5}},
    {"refined-concrete", {x = 4, y = 6}},
    {"refined-concrete", {x = 4, y = 7}},
    {"refined-concrete", {x = 4, y = 8}},
    {"refined-concrete", {x = 4, y = 9}},
    {"refined-concrete", {x = 4, y = 10}},
    {"refined-concrete", {x = 4, y = 11}},
    {"refined-concrete", {x = 4, y = 12}},
    {"refined-concrete", {x = 4, y = 13}},
    {"grass-1", {x = 4, y = 14}},
    {"grass-1", {x = 4, y = 15}},
    {"grass-1", {x = 5, y = -16}},
    {"grass-1", {x = 5, y = -15}},
    {"refined-concrete", {x = 5, y = -14}},
    {"refined-concrete", {x = 5, y = -13}},
    {"refined-concrete", {x = 5, y = -12}},
    {"refined-concrete", {x = 5, y = -11}},
    {"refined-concrete", {x = 5, y = -10}},
    {"refined-concrete", {x = 5, y = -9}},
    {"refined-concrete", {x = 5, y = -8}},
    {"refined-concrete", {x = 5, y = -7}},
    {"refined-concrete", {x = 5, y = -6}},
    {"refined-concrete", {x = 5, y = -5}},
    {"refined-concrete", {x = 5, y = -4}},
    {"refined-concrete", {x = 5, y = -3}},
    {"refined-concrete", {x = 5, y = -2}},
    {"refined-concrete", {x = 5, y = -1}},
    {"refined-concrete", {x = 5, y = 0}},
    {"refined-concrete", {x = 5, y = 1}},
    {"refined-concrete", {x = 5, y = 2}},
    {"refined-concrete", {x = 5, y = 3}},
    {"refined-concrete", {x = 5, y = 4}},
    {"refined-concrete", {x = 5, y = 5}},
    {"refined-concrete", {x = 5, y = 6}},
    {"refined-concrete", {x = 5, y = 7}},
    {"refined-concrete", {x = 5, y = 8}},
    {"refined-concrete", {x = 5, y = 9}},
    {"refined-concrete", {x = 5, y = 10}},
    {"refined-concrete", {x = 5, y = 11}},
    {"refined-concrete", {x = 5, y = 12}},
    {"refined-concrete", {x = 5, y = 13}},
    {"grass-1", {x = 5, y = 14}},
    {"grass-1", {x = 5, y = 15}},
    {"grass-1", {x = 6, y = -16}},
    {"grass-1", {x = 6, y = -15}},
    {"refined-concrete", {x = 6, y = -14}},
    {"refined-concrete", {x = 6, y = -13}},
    {"refined-concrete", {x = 6, y = -12}},
    {"refined-concrete", {x = 6, y = -11}},
    {"refined-concrete", {x = 6, y = -10}},
    {"refined-concrete", {x = 6, y = -9}},
    {"refined-concrete", {x = 6, y = -8}},
    {"refined-concrete", {x = 6, y = -7}},
    {"refined-concrete", {x = 6, y = -6}},
    {"refined-concrete", {x = 6, y = -5}},
    {"refined-concrete", {x = 6, y = -4}},
    {"refined-concrete", {x = 6, y = -3}},
    {"refined-concrete", {x = 6, y = -2}},
    {"refined-concrete", {x = 6, y = -1}},
    {"refined-concrete", {x = 6, y = 0}},
    {"refined-concrete", {x = 6, y = 1}},
    {"refined-concrete", {x = 6, y = 2}},
    {"refined-concrete", {x = 6, y = 3}},
    {"refined-concrete", {x = 6, y = 4}},
    {"refined-concrete", {x = 6, y = 5}},
    {"refined-concrete", {x = 6, y = 6}},
    {"refined-concrete", {x = 6, y = 7}},
    {"refined-concrete", {x = 6, y = 8}},
    {"refined-concrete", {x = 6, y = 9}},
    {"refined-concrete", {x = 6, y = 10}},
    {"refined-concrete", {x = 6, y = 11}},
    {"refined-concrete", {x = 6, y = 12}},
    {"refined-concrete", {x = 6, y = 13}},
    {"grass-1", {x = 6, y = 14}},
    {"grass-1", {x = 6, y = 15}},
    {"grass-1", {x = 7, y = -16}},
    {"grass-1", {x = 7, y = -15}},
    {"refined-concrete", {x = 7, y = -14}},
    {"refined-concrete", {x = 7, y = -13}},
    {"refined-concrete", {x = 7, y = -12}},
    {"refined-concrete", {x = 7, y = -11}},
    {"refined-concrete", {x = 7, y = -10}},
    {"refined-concrete", {x = 7, y = -9}},
    {"refined-concrete", {x = 7, y = -8}},
    {"refined-concrete", {x = 7, y = -7}},
    {"refined-concrete", {x = 7, y = -6}},
    {"refined-concrete", {x = 7, y = -5}},
    {"refined-concrete", {x = 7, y = -4}},
    {"refined-concrete", {x = 7, y = -3}},
    {"refined-concrete", {x = 7, y = -2}},
    {"refined-concrete", {x = 7, y = -1}},
    {"refined-concrete", {x = 7, y = 0}},
    {"refined-concrete", {x = 7, y = 1}},
    {"refined-concrete", {x = 7, y = 2}},
    {"refined-concrete", {x = 7, y = 3}},
    {"refined-concrete", {x = 7, y = 4}},
    {"refined-concrete", {x = 7, y = 5}},
    {"refined-concrete", {x = 7, y = 6}},
    {"refined-concrete", {x = 7, y = 7}},
    {"refined-concrete", {x = 7, y = 8}},
    {"refined-concrete", {x = 7, y = 9}},
    {"refined-concrete", {x = 7, y = 10}},
    {"refined-concrete", {x = 7, y = 11}},
    {"refined-concrete", {x = 7, y = 12}},
    {"refined-concrete", {x = 7, y = 13}},
    {"grass-1", {x = 7, y = 14}},
    {"grass-1", {x = 7, y = 15}},
    {"grass-1", {x = 8, y = -16}},
    {"grass-1", {x = 8, y = -15}},
    {"refined-concrete", {x = 8, y = -14}},
    {"refined-concrete", {x = 8, y = -13}},
    {"refined-concrete", {x = 8, y = -12}},
    {"refined-concrete", {x = 8, y = -11}},
    {"refined-concrete", {x = 8, y = -10}},
    {"refined-concrete", {x = 8, y = -9}},
    {"refined-concrete", {x = 8, y = -8}},
    {"refined-concrete", {x = 8, y = -7}},
    {"refined-concrete", {x = 8, y = -6}},
    {"refined-concrete", {x = 8, y = -5}},
    {"refined-concrete", {x = 8, y = -4}},
    {"refined-concrete", {x = 8, y = -3}},
    {"refined-concrete", {x = 8, y = -2}},
    {"refined-concrete", {x = 8, y = -1}},
    {"refined-concrete", {x = 8, y = 0}},
    {"refined-concrete", {x = 8, y = 1}},
    {"refined-concrete", {x = 8, y = 2}},
    {"refined-concrete", {x = 8, y = 3}},
    {"refined-concrete", {x = 8, y = 4}},
    {"refined-concrete", {x = 8, y = 5}},
    {"refined-concrete", {x = 8, y = 6}},
    {"refined-concrete", {x = 8, y = 7}},
    {"refined-concrete", {x = 8, y = 8}},
    {"refined-concrete", {x = 8, y = 9}},
    {"refined-concrete", {x = 8, y = 10}},
    {"refined-concrete", {x = 8, y = 11}},
    {"refined-concrete", {x = 8, y = 12}},
    {"refined-concrete", {x = 8, y = 13}},
    {"grass-1", {x = 8, y = 14}},
    {"grass-1", {x = 8, y = 15}},
    {"grass-1", {x = 9, y = -16}},
    {"grass-1", {x = 9, y = -15}},
    {"grass-1", {x = 9, y = -14}},
    {"grass-1", {x = 9, y = -13}},
    {"grass-1", {x = 9, y = -12}},
    {"refined-concrete", {x = 9, y = -11}},
    {"refined-concrete", {x = 9, y = -10}},
    {"grass-1", {x = 9, y = -9}},
    {"grass-1", {x = 9, y = -8}},
    {"refined-concrete", {x = 9, y = -7}},
    {"refined-concrete", {x = 9, y = -6}},
    {"grass-1", {x = 9, y = -5}},
    {"grass-1", {x = 9, y = -4}},
    {"grass-1", {x = 9, y = -3}},
    {"refined-concrete", {x = 9, y = -2}},
    {"refined-concrete", {x = 9, y = -1}},
    {"refined-concrete", {x = 9, y = 0}},
    {"refined-concrete", {x = 9, y = 1}},
    {"grass-1", {x = 9, y = 2}},
    {"grass-1", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"refined-concrete", {x = 9, y = 5}},
    {"refined-concrete", {x = 9, y = 6}},
    {"grass-1", {x = 9, y = 7}},
    {"grass-1", {x = 9, y = 8}},
    {"refined-concrete", {x = 9, y = 9}},
    {"refined-concrete", {x = 9, y = 10}},
    {"grass-1", {x = 9, y = 11}},
    {"grass-1", {x = 9, y = 12}},
    {"grass-1", {x = 9, y = 13}},
    {"grass-1", {x = 9, y = 14}},
    {"grass-1", {x = 9, y = 15}},
    {"grass-1", {x = 10, y = -16}},
    {"grass-1", {x = 10, y = -15}},
    {"grass-1", {x = 10, y = -14}},
    {"grass-1", {x = 10, y = -13}},
    {"grass-1", {x = 10, y = -12}},
    {"refined-concrete", {x = 10, y = -11}},
    {"refined-concrete", {x = 10, y = -10}},
    {"grass-1", {x = 10, y = -9}},
    {"grass-1", {x = 10, y = -8}},
    {"refined-concrete", {x = 10, y = -7}},
    {"refined-concrete", {x = 10, y = -6}},
    {"grass-1", {x = 10, y = -5}},
    {"grass-1", {x = 10, y = -4}},
    {"grass-1", {x = 10, y = -3}},
    {"refined-concrete", {x = 10, y = -2}},
    {"refined-concrete", {x = 10, y = -1}},
    {"refined-concrete", {x = 10, y = 0}},
    {"refined-concrete", {x = 10, y = 1}},
    {"grass-1", {x = 10, y = 2}},
    {"grass-1", {x = 10, y = 3}},
    {"grass-1", {x = 10, y = 4}},
    {"refined-concrete", {x = 10, y = 5}},
    {"refined-concrete", {x = 10, y = 6}},
    {"grass-1", {x = 10, y = 7}},
    {"grass-1", {x = 10, y = 8}},
    {"refined-concrete", {x = 10, y = 9}},
    {"refined-concrete", {x = 10, y = 10}},
    {"grass-3", {x = 10, y = 11}},
    {"grass-3", {x = 10, y = 12}},
    {"grass-1", {x = 10, y = 13}},
    {"grass-1", {x = 10, y = 14}},
    {"grass-1", {x = 10, y = 15}},
    {"grass-1", {x = 11, y = -16}},
    {"grass-1", {x = 11, y = -15}},
    {"grass-1", {x = 11, y = -14}},
    {"grass-1", {x = 11, y = -13}},
    {"grass-1", {x = 11, y = -12}},
    {"refined-concrete", {x = 11, y = -11}},
    {"refined-concrete", {x = 11, y = -10}},
    {"grass-1", {x = 11, y = -9}},
    {"grass-1", {x = 11, y = -8}},
    {"refined-concrete", {x = 11, y = -7}},
    {"refined-concrete", {x = 11, y = -6}},
    {"grass-1", {x = 11, y = -5}},
    {"grass-1", {x = 11, y = -4}},
    {"grass-1", {x = 11, y = -3}},
    {"refined-concrete", {x = 11, y = -2}},
    {"refined-concrete", {x = 11, y = -1}},
    {"refined-concrete", {x = 11, y = 0}},
    {"refined-concrete", {x = 11, y = 1}},
    {"grass-1", {x = 11, y = 2}},
    {"grass-1", {x = 11, y = 3}},
    {"grass-1", {x = 11, y = 4}},
    {"refined-concrete", {x = 11, y = 5}},
    {"refined-concrete", {x = 11, y = 6}},
    {"grass-1", {x = 11, y = 7}},
    {"grass-3", {x = 11, y = 8}},
    {"refined-concrete", {x = 11, y = 9}},
    {"refined-concrete", {x = 11, y = 10}},
    {"grass-3", {x = 11, y = 11}},
    {"grass-3", {x = 11, y = 12}},
    {"grass-3", {x = 11, y = 13}},
    {"grass-3", {x = 11, y = 14}},
    {"grass-1", {x = 11, y = 15}},
    {"grass-1", {x = 12, y = -16}},
    {"grass-1", {x = 12, y = -15}},
    {"grass-1", {x = 12, y = -14}},
    {"grass-1", {x = 12, y = -13}},
    {"grass-1", {x = 12, y = -12}},
    {"refined-concrete", {x = 12, y = -11}},
    {"refined-concrete", {x = 12, y = -10}},
    {"grass-1", {x = 12, y = -9}},
    {"grass-1", {x = 12, y = -8}},
    {"grass-1", {x = 12, y = -7}},
    {"grass-1", {x = 12, y = -6}},
    {"grass-1", {x = 12, y = -5}},
    {"grass-1", {x = 12, y = -4}},
    {"grass-1", {x = 12, y = -3}},
    {"refined-concrete", {x = 12, y = -2}},
    {"refined-concrete", {x = 12, y = -1}},
    {"refined-concrete", {x = 12, y = 0}},
    {"refined-concrete", {x = 12, y = 1}},
    {"grass-1", {x = 12, y = 2}},
    {"grass-1", {x = 12, y = 3}},
    {"grass-1", {x = 12, y = 4}},
    {"grass-1", {x = 12, y = 5}},
    {"grass-1", {x = 12, y = 6}},
    {"grass-3", {x = 12, y = 7}},
    {"grass-3", {x = 12, y = 8}},
    {"refined-concrete", {x = 12, y = 9}},
    {"refined-concrete", {x = 12, y = 10}},
    {"grass-3", {x = 12, y = 11}},
    {"grass-3", {x = 12, y = 12}},
    {"grass-3", {x = 12, y = 13}},
    {"grass-3", {x = 12, y = 14}},
    {"grass-3", {x = 12, y = 15}},
    {"grass-1", {x = 13, y = -16}},
    {"grass-1", {x = 13, y = -15}},
    {"grass-1", {x = 13, y = -14}},
    {"grass-1", {x = 13, y = -13}},
    {"grass-1", {x = 13, y = -12}},
    {"refined-concrete", {x = 13, y = -11}},
    {"refined-concrete", {x = 13, y = -10}},
    {"grass-1", {x = 13, y = -9}},
    {"grass-1", {x = 13, y = -8}},
    {"grass-1", {x = 13, y = -7}},
    {"grass-1", {x = 13, y = -6}},
    {"grass-1", {x = 13, y = -5}},
    {"grass-1", {x = 13, y = -4}},
    {"grass-1", {x = 13, y = -3}},
    {"refined-concrete", {x = 13, y = -2}},
    {"refined-concrete", {x = 13, y = -1}},
    {"refined-concrete", {x = 13, y = 0}},
    {"refined-concrete", {x = 13, y = 1}},
    {"grass-1", {x = 13, y = 2}},
    {"grass-1", {x = 13, y = 3}},
    {"grass-1", {x = 13, y = 4}},
    {"grass-1", {x = 13, y = 5}},
    {"grass-3", {x = 13, y = 6}},
    {"grass-3", {x = 13, y = 7}},
    {"grass-3", {x = 13, y = 8}},
    {"refined-concrete", {x = 13, y = 9}},
    {"refined-concrete", {x = 13, y = 10}},
    {"grass-3", {x = 13, y = 11}},
    {"grass-3", {x = 13, y = 12}},
    {"grass-3", {x = 13, y = 13}},
    {"grass-3", {x = 13, y = 14}},
    {"grass-3", {x = 13, y = 15}},
    {"grass-1", {x = 14, y = -16}},
    {"grass-1", {x = 14, y = -15}},
    {"grass-1", {x = 14, y = -14}},
    {"grass-1", {x = 14, y = -13}},
    {"grass-1", {x = 14, y = -12}},
    {"grass-1", {x = 14, y = -11}},
    {"grass-1", {x = 14, y = -10}},
    {"grass-1", {x = 14, y = -9}},
    {"grass-1", {x = 14, y = -8}},
    {"grass-1", {x = 14, y = -7}},
    {"grass-1", {x = 14, y = -6}},
    {"grass-1", {x = 14, y = -5}},
    {"grass-1", {x = 14, y = -4}},
    {"grass-1", {x = 14, y = -3}},
    {"refined-concrete", {x = 14, y = -2}},
    {"refined-concrete", {x = 14, y = -1}},
    {"refined-concrete", {x = 14, y = 0}},
    {"refined-concrete", {x = 14, y = 1}},
    {"grass-1", {x = 14, y = 2}},
    {"grass-1", {x = 14, y = 3}},
    {"grass-3", {x = 14, y = 4}},
    {"grass-3", {x = 14, y = 5}},
    {"grass-3", {x = 14, y = 6}},
    {"grass-3", {x = 14, y = 7}},
    {"grass-3", {x = 14, y = 8}},
    {"grass-3", {x = 14, y = 9}},
    {"grass-3", {x = 14, y = 10}},
    {"grass-3", {x = 14, y = 11}},
    {"grass-3", {x = 14, y = 12}},
    {"grass-3", {x = 14, y = 13}},
    {"grass-3", {x = 14, y = 14}},
    {"grass-3", {x = 14, y = 15}},
    {"grass-1", {x = 15, y = -16}},
    {"grass-1", {x = 15, y = -15}},
    {"grass-1", {x = 15, y = -14}},
    {"grass-1", {x = 15, y = -13}},
    {"grass-1", {x = 15, y = -12}},
    {"grass-1", {x = 15, y = -11}},
    {"grass-1", {x = 15, y = -10}},
    {"grass-1", {x = 15, y = -9}},
    {"grass-1", {x = 15, y = -8}},
    {"grass-1", {x = 15, y = -7}},
    {"grass-1", {x = 15, y = -6}},
    {"grass-1", {x = 15, y = -5}},
    {"grass-1", {x = 15, y = -4}},
    {"grass-1", {x = 15, y = -3}},
    {"refined-concrete", {x = 15, y = -2}},
    {"refined-concrete", {x = 15, y = -1}},
    {"refined-concrete", {x = 15, y = 0}},
    {"refined-concrete", {x = 15, y = 1}},
    {"grass-1", {x = 15, y = 2}},
    {"grass-1", {x = 15, y = 3}},
    {"grass-3", {x = 15, y = 4}},
    {"grass-3", {x = 15, y = 5}},
    {"grass-3", {x = 15, y = 6}},
    {"grass-3", {x = 15, y = 7}},
    {"grass-3", {x = 15, y = 8}},
    {"grass-3", {x = 15, y = 9}},
    {"grass-3", {x = 15, y = 10}},
    {"grass-3", {x = 15, y = 11}},
    {"grass-3", {x = 15, y = 12}},
    {"grass-3", {x = 15, y = 13}},
    {"grass-3", {x = 15, y = 14}},
    {"grass-3", {x = 15, y = 15}},
  }
}
