return
{
  entities =
  {
    {"laser-turret", {x = -14, y = -14}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -4, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -15.5}, {force = "enemy", }},
    {"gate", {x = 1.5, y = -15.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 0.5, y = -15.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 2.5, y = -15.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 5, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -14}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -13.5}, {force = "enemy", }},
    {"steel-chest", {x = -0.5, y = -12.5}, {force = "enemy", items = {["copper-ore"] = 2400}, }},
    {"steel-chest", {x = 1.5, y = -12.5}, {force = "enemy", items = {["copper-ore"] = 2400}, }},
    {"steel-chest", {x = 0.5, y = -12.5}, {force = "enemy", items = {["copper-ore"] = 2400}, }},
    {"stone-wall", {x = 3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -12.5}, {force = "enemy", }},
    {"steel-chest", {x = 7.5, y = -13.5}, {items = {["battery-mk2-equipment"] = 1, ["personal-roboport-equipment"] = 1}, }},
    {"stone-wall", {x = 7.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -10.5}, {force = "enemy", }},
    {"substation", {x = -9, y = -10}, {}},
    {"green-crystal-gen", {x = -3.5, y = -11}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -10.5}, {force = "enemy", }},
    {"fast-inserter", {x = -0.5, y = -11.5}, {force = "enemy", }},
    {"steel-chest", {x = -0.5, y = -10.5}, {force = "enemy", items = {["copper-ore"] = 2400}, }},
    {"fast-inserter", {x = 1.5, y = -11.5}, {force = "enemy", }},
    {"fast-inserter", {x = 0.5, y = -11.5}, {force = "enemy", }},
    {"steel-chest", {x = 1.5, y = -10.5}, {force = "enemy", items = {["copper-ore"] = 2400}, }},
    {"steel-chest", {x = 0.5, y = -10.5}, {force = "enemy", items = {["copper-ore"] = 2400}, }},
    {"stone-wall", {x = 3.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -11.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 6.5, y = -10.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"stone-wall", {x = 6.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -10.5}, {force = "enemy", }},
    {"substation", {x = 9, y = -10}, {}},
    {"stone-wall", {x = 14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -8.5}, {force = "enemy", }},
    {"steel-chest", {x = -7.5, y = -9.5}, {items = {["construction-robot"] = 10, ["laser-turret"] = 28, ["repair-pack"] = 100}, }},
    {"stone-wall", {x = -7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -8.5}, {force = "enemy", }},
    {"fast-inserter", {x = -0.5, y = -9.5}, {force = "enemy", }},
    {"steel-chest", {x = -0.5, y = -8.5}, {force = "enemy", items = {["copper-ore"] = 2400}, }},
    {"fast-inserter", {x = 1.5, y = -9.5}, {force = "enemy", }},
    {"fast-inserter", {x = 0.5, y = -9.5}, {force = "enemy", }},
    {"steel-chest", {x = 1.5, y = -8.5}, {force = "enemy", items = {["copper-ore"] = 2351}, }},
    {"steel-chest", {x = 0.5, y = -8.5}, {force = "enemy", items = {["copper-ore"] = 2400}, }},
    {"roboport", {x = 4, y = -7}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"stone-wall", {x = 7.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -9.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -8}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -6.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = -6.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = -7.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = -6.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = -7.5}, {force = "enemy", }},
    {"fast-inserter", {x = -0.5, y = -7.5}, {force = "enemy", }},
    {"electric-furnace", {x = 0.5, y = -5.5}, {force = "enemy", }},
    {"fast-inserter", {x = 1.5, y = -7.5}, {force = "enemy", }},
    {"fast-inserter", {x = 0.5, y = -7.5}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -6.2}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -6.38}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -6.51}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -6.64}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -6.72}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -6.78}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -6.8}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.38, y = -6.16}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.38, y = -6.48}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.38, y = -6.75}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.38, y = -6.9}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.38, y = -6.98}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.38, y = -7.02}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.36, y = -7.02}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.45, y = -6.02}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.43, y = -6.22}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.43, y = -6.39}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.39, y = -6.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.37, y = -6.56}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.37, y = -6.58}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.37, y = -6.62}, {force = "enemy", }},
    {"gate", {x = 7.5, y = -6.5}, {force = "enemy", }},
    {"gate", {x = 7.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = -4}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -5.5}, {force = "enemy", }},
    {"steel-chest", {x = -11.5, y = -5.5}, {items = {["logistic-robot"] = 10, ["utility-science-pack"] = 100}, }},
    {"stone-wall", {x = -10.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -5.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = -4.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = -5.5}, {force = "enemy", }},
    {"logistic-robot", {x = 0.7, y = -5.23}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -5.04}, {force = "enemy", }},
    {"logistic-robot", {x = 0.78, y = -4.83}, {force = "enemy", }},
    {"logistic-robot", {x = 0.78, y = -4.77}, {force = "enemy", }},
    {"logistic-robot", {x = 0.78, y = -4.83}, {force = "enemy", }},
    {"logistic-robot", {x = 0.76, y = -5}, {force = "enemy", }},
    {"logistic-robot", {x = 0.74, y = -5.18}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -5.44}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -5.73}, {force = "enemy", }},
    {"logistic-robot", {x = 0.72, y = -5.96}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.81, y = -5.48}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.77, y = -5.48}, {force = "enemy", }},
    {"fast-inserter", {x = 2.5, y = -4.5}, {dir = "west", force = "enemy", }},
    {"logistic-chest-active-provider", {x = 3.5, y = -4.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.21, y = -5.3}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.25, y = -5.21}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.25, y = -5.23}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.27, y = -5.3}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.31, y = -5.47}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.31, y = -5.7}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.38, y = -5.93}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.39, y = -5.05}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.39, y = -5.11}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.41, y = -5.2}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.43, y = -5.26}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.45, y = -5.36}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.45, y = -5.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.45, y = -5.66}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.45, y = -5.82}, {force = "enemy", }},
    {"gate", {x = 7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -2.5}, {force = "enemy", }},
    {"gate", {x = -5.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -4.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -3.5}, {force = "enemy", }},
    {"aliengenerator", {x = 2.5, y = -2}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -3.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 9.5, y = -2.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 8.5, y = -2.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 10.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -0.5}, {force = "enemy", }},
    {"assembling-machine-2", {x = -5.5, y = -0.5}, {force = "enemy", recipe = "iron-gear-wheel", }},
    {"stone-wall", {x = -7.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -1.5}, {force = "enemy", }},
    {"fast-inserter", {x = 9.5, y = -1.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 8.5, y = -1.5}, {dir = "south", force = "enemy", }},
    {"assembling-machine-2", {x = 9.5, y = 0.5}, {force = "enemy", recipe = "repair-pack", }},
    {"fast-inserter", {x = 10.5, y = -1.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = -15.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = -15.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 1.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -8.5, y = 0.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -8.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 0.5}, {force = "enemy", }},
    {"fast-inserter", {x = -7.5, y = 0.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = -5.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 0.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = 4}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 2.5}, {force = "enemy", }},
    {"assembling-machine-2", {x = -10.5, y = 4.5}, {force = "enemy", recipe = "copper-cable", }},
    {"stone-wall", {x = -11.5, y = 2.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -8.5, y = 2.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -8.5, y = 3.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -6.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"fast-inserter", {x = -5.5, y = 3.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -5.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 3.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 3.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -1.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 1.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 0.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 5.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 5.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 4.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 7.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 6.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 2.5}, {force = "enemy", }},
    {"steel-chest", {x = 6.5, y = 2.5}, {items = {["artillery-wagon"] = 1, ["atomic-bomb"] = 10, ["utility-science-pack"] = 100}, }},
    {"fast-inserter", {x = 8.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 9.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 9.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 8.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 10.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 5.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -8.5, y = 4.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -8.5, y = 5.5}, {force = "enemy", }},
    {"fast-inserter", {x = -7.5, y = 5.5}, {dir = "west", force = "enemy", }},
    {"long-handed-inserter", {x = -7.5, y = 4.5}, {dir = "west", force = "enemy", }},
    {"assembling-machine-2", {x = -5.5, y = 5.5}, {force = "enemy", recipe = "electronic-circuit", }},
    {"stone-wall", {x = -3.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 5.5}, {force = "enemy", }},
    {"laser-turret", {x = -2, y = 5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 4.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = 5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 7.5}, {force = "enemy", }},
    {"fast-inserter", {x = -10.5, y = 6.5}, {dir = "south", force = "enemy", }},
    {"logistic-chest-storage", {x = -10.5, y = 7.5}, {force = "enemy", items = {["copper-plate"] = 3800}, }},
    {"express-transport-belt", {x = -8.5, y = 6.5}, {force = "enemy", }},
    {"fast-inserter", {x = -8.5, y = 7.5}, {dir = "south", force = "enemy", }},
    {"substation", {x = -5, y = 8}, {}},
    {"stone-wall", {x = -2.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 6.5}, {force = "enemy", }},
    {"substation", {x = 9, y = 8}, {}},
    {"stone-wall", {x = 11.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = 8}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {force = "enemy", }},
    {"steel-chest", {x = -12.5, y = 9.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = -12.5, y = 8.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"fast-inserter", {x = -11.5, y = 9.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = 8.5}, {dir = "west", force = "enemy", }},
    {"electric-furnace", {x = -9.5, y = 9.5}, {force = "enemy", }},
    {"fast-inserter", {x = -7.5, y = 9.5}, {dir = "east", force = "enemy", }},
    {"fast-inserter", {x = -7.5, y = 8.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = -6.5, y = 9.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = -6.5, y = 8.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"fast-inserter", {x = -5.5, y = 9.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = -4.5, y = 9.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -2.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 11.5}, {force = "enemy", }},
    {"steel-chest", {x = -12.5, y = 10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"fast-inserter", {x = -10.5, y = 11.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = 10.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = -8.5, y = 11.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = -9.5, y = 11.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = -7.5, y = 10.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = -6.5, y = 10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -6.5, y = 11.5}, {force = "enemy", }},
    {"fast-inserter", {x = -5.5, y = 10.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = -4.5, y = 10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -4.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 10.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = 14}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 12.5}, {force = "enemy", }},
    {"steel-chest", {x = -10.5, y = 12.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = -8.5, y = 12.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = -9.5, y = 12.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -6.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 13.5}, {force = "enemy", }},
    {"laser-turret", {x = -5, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 9, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 13.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 14}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 14.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -16, y = -16}},
    {"grass-1", {x = -16, y = -15}},
    {"grass-1", {x = -16, y = -14}},
    {"grass-1", {x = -16, y = -13}},
    {"grass-1", {x = -16, y = -12}},
    {"grass-1", {x = -16, y = -11}},
    {"grass-1", {x = -16, y = -10}},
    {"grass-1", {x = -16, y = -9}},
    {"grass-1", {x = -16, y = -8}},
    {"grass-1", {x = -16, y = -7}},
    {"grass-1", {x = -16, y = -6}},
    {"grass-1", {x = -16, y = -5}},
    {"grass-1", {x = -16, y = -4}},
    {"grass-1", {x = -16, y = -3}},
    {"grass-1", {x = -16, y = -2}},
    {"grass-1", {x = -16, y = -1}},
    {"grass-1", {x = -16, y = 0}},
    {"grass-1", {x = -16, y = 1}},
    {"grass-1", {x = -16, y = 2}},
    {"grass-1", {x = -16, y = 3}},
    {"grass-1", {x = -16, y = 4}},
    {"grass-1", {x = -16, y = 5}},
    {"grass-1", {x = -16, y = 6}},
    {"grass-1", {x = -16, y = 7}},
    {"grass-1", {x = -16, y = 8}},
    {"grass-1", {x = -16, y = 9}},
    {"grass-1", {x = -16, y = 10}},
    {"grass-1", {x = -16, y = 11}},
    {"grass-1", {x = -16, y = 12}},
    {"grass-1", {x = -16, y = 13}},
    {"grass-1", {x = -16, y = 14}},
    {"grass-1", {x = -16, y = 15}},
    {"grass-1", {x = -15, y = -16}},
    {"grass-1", {x = -15, y = -15}},
    {"grass-1", {x = -15, y = -14}},
    {"grass-1", {x = -15, y = -13}},
    {"grass-1", {x = -15, y = -12}},
    {"grass-1", {x = -15, y = -11}},
    {"grass-1", {x = -15, y = -10}},
    {"grass-1", {x = -15, y = -9}},
    {"grass-1", {x = -15, y = -8}},
    {"grass-1", {x = -15, y = -7}},
    {"grass-1", {x = -15, y = -6}},
    {"grass-1", {x = -15, y = -5}},
    {"grass-1", {x = -15, y = -4}},
    {"grass-1", {x = -15, y = -3}},
    {"grass-1", {x = -15, y = -2}},
    {"grass-1", {x = -15, y = -1}},
    {"grass-1", {x = -15, y = 0}},
    {"grass-1", {x = -15, y = 1}},
    {"grass-1", {x = -15, y = 2}},
    {"grass-1", {x = -15, y = 3}},
    {"grass-1", {x = -15, y = 4}},
    {"grass-1", {x = -15, y = 5}},
    {"grass-1", {x = -15, y = 6}},
    {"grass-1", {x = -15, y = 7}},
    {"grass-1", {x = -15, y = 8}},
    {"grass-1", {x = -15, y = 9}},
    {"grass-1", {x = -15, y = 10}},
    {"grass-1", {x = -15, y = 11}},
    {"grass-1", {x = -15, y = 12}},
    {"grass-1", {x = -15, y = 13}},
    {"grass-1", {x = -15, y = 14}},
    {"grass-1", {x = -15, y = 15}},
    {"grass-1", {x = -14, y = -16}},
    {"grass-1", {x = -14, y = -15}},
    {"grass-1", {x = -14, y = -14}},
    {"grass-1", {x = -14, y = -13}},
    {"grass-1", {x = -14, y = -12}},
    {"grass-1", {x = -14, y = -11}},
    {"grass-1", {x = -14, y = -10}},
    {"grass-1", {x = -14, y = -9}},
    {"grass-1", {x = -14, y = -8}},
    {"grass-1", {x = -14, y = -7}},
    {"grass-1", {x = -14, y = -6}},
    {"grass-1", {x = -14, y = -5}},
    {"grass-1", {x = -14, y = -4}},
    {"grass-1", {x = -14, y = -3}},
    {"grass-1", {x = -14, y = -2}},
    {"grass-1", {x = -14, y = -1}},
    {"grass-1", {x = -14, y = 0}},
    {"grass-1", {x = -14, y = 1}},
    {"grass-1", {x = -14, y = 2}},
    {"grass-1", {x = -14, y = 3}},
    {"grass-1", {x = -14, y = 4}},
    {"grass-1", {x = -14, y = 5}},
    {"grass-1", {x = -14, y = 6}},
    {"grass-1", {x = -14, y = 7}},
    {"grass-1", {x = -14, y = 8}},
    {"grass-1", {x = -14, y = 9}},
    {"grass-1", {x = -14, y = 10}},
    {"grass-1", {x = -14, y = 11}},
    {"grass-1", {x = -14, y = 12}},
    {"grass-1", {x = -14, y = 13}},
    {"grass-1", {x = -14, y = 14}},
    {"grass-1", {x = -14, y = 15}},
    {"grass-1", {x = -13, y = -16}},
    {"grass-1", {x = -13, y = -15}},
    {"grass-1", {x = -13, y = -14}},
    {"grass-1", {x = -13, y = -13}},
    {"grass-1", {x = -13, y = -12}},
    {"grass-1", {x = -13, y = -11}},
    {"grass-1", {x = -13, y = -10}},
    {"grass-1", {x = -13, y = -9}},
    {"grass-1", {x = -13, y = -8}},
    {"grass-1", {x = -13, y = -7}},
    {"grass-1", {x = -13, y = -6}},
    {"grass-1", {x = -13, y = -5}},
    {"grass-1", {x = -13, y = -4}},
    {"grass-1", {x = -13, y = -3}},
    {"grass-1", {x = -13, y = -2}},
    {"grass-1", {x = -13, y = -1}},
    {"grass-1", {x = -13, y = 0}},
    {"grass-1", {x = -13, y = 1}},
    {"grass-1", {x = -13, y = 2}},
    {"grass-1", {x = -13, y = 3}},
    {"grass-1", {x = -13, y = 4}},
    {"grass-1", {x = -13, y = 5}},
    {"grass-1", {x = -13, y = 6}},
    {"grass-1", {x = -13, y = 7}},
    {"grass-1", {x = -13, y = 8}},
    {"grass-1", {x = -13, y = 9}},
    {"grass-1", {x = -13, y = 10}},
    {"grass-1", {x = -13, y = 11}},
    {"grass-1", {x = -13, y = 12}},
    {"grass-1", {x = -13, y = 13}},
    {"grass-1", {x = -13, y = 14}},
    {"grass-1", {x = -13, y = 15}},
    {"grass-1", {x = -12, y = -16}},
    {"grass-1", {x = -12, y = -15}},
    {"grass-1", {x = -12, y = -14}},
    {"grass-1", {x = -12, y = -13}},
    {"grass-1", {x = -12, y = -12}},
    {"grass-1", {x = -12, y = -11}},
    {"grass-1", {x = -12, y = -10}},
    {"grass-1", {x = -12, y = -9}},
    {"grass-1", {x = -12, y = -8}},
    {"grass-1", {x = -12, y = -7}},
    {"grass-1", {x = -12, y = -6}},
    {"grass-1", {x = -12, y = -5}},
    {"grass-1", {x = -12, y = -4}},
    {"grass-1", {x = -12, y = -3}},
    {"grass-1", {x = -12, y = -2}},
    {"grass-1", {x = -12, y = -1}},
    {"grass-1", {x = -12, y = 0}},
    {"grass-1", {x = -12, y = 1}},
    {"grass-1", {x = -12, y = 2}},
    {"grass-1", {x = -12, y = 3}},
    {"grass-1", {x = -12, y = 4}},
    {"grass-1", {x = -12, y = 5}},
    {"grass-1", {x = -12, y = 6}},
    {"grass-1", {x = -12, y = 7}},
    {"grass-1", {x = -12, y = 8}},
    {"grass-1", {x = -12, y = 9}},
    {"grass-1", {x = -12, y = 10}},
    {"grass-1", {x = -12, y = 11}},
    {"grass-1", {x = -12, y = 12}},
    {"grass-1", {x = -12, y = 13}},
    {"grass-1", {x = -12, y = 14}},
    {"grass-1", {x = -12, y = 15}},
    {"grass-1", {x = -11, y = -16}},
    {"grass-1", {x = -11, y = -15}},
    {"grass-1", {x = -11, y = -14}},
    {"grass-1", {x = -11, y = -13}},
    {"grass-1", {x = -11, y = -12}},
    {"grass-1", {x = -11, y = -11}},
    {"grass-1", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-1", {x = -11, y = -5}},
    {"grass-1", {x = -11, y = -4}},
    {"grass-1", {x = -11, y = -3}},
    {"grass-1", {x = -11, y = -2}},
    {"grass-1", {x = -11, y = -1}},
    {"grass-1", {x = -11, y = 0}},
    {"grass-1", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-1", {x = -11, y = 4}},
    {"grass-1", {x = -11, y = 5}},
    {"grass-1", {x = -11, y = 6}},
    {"grass-1", {x = -11, y = 7}},
    {"grass-1", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"grass-1", {x = -11, y = 10}},
    {"grass-1", {x = -11, y = 11}},
    {"grass-1", {x = -11, y = 12}},
    {"grass-1", {x = -11, y = 13}},
    {"grass-1", {x = -11, y = 14}},
    {"grass-1", {x = -11, y = 15}},
    {"grass-1", {x = -10, y = -16}},
    {"grass-1", {x = -10, y = -15}},
    {"grass-1", {x = -10, y = -14}},
    {"grass-1", {x = -10, y = -13}},
    {"grass-1", {x = -10, y = -12}},
    {"grass-1", {x = -10, y = -11}},
    {"grass-1", {x = -10, y = -10}},
    {"grass-1", {x = -10, y = -9}},
    {"grass-1", {x = -10, y = -8}},
    {"grass-1", {x = -10, y = -7}},
    {"grass-1", {x = -10, y = -6}},
    {"grass-1", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-1", {x = -10, y = -3}},
    {"grass-1", {x = -10, y = -2}},
    {"grass-1", {x = -10, y = -1}},
    {"grass-1", {x = -10, y = 0}},
    {"grass-1", {x = -10, y = 1}},
    {"grass-1", {x = -10, y = 2}},
    {"grass-1", {x = -10, y = 3}},
    {"grass-1", {x = -10, y = 4}},
    {"grass-1", {x = -10, y = 5}},
    {"grass-1", {x = -10, y = 6}},
    {"grass-1", {x = -10, y = 7}},
    {"grass-1", {x = -10, y = 8}},
    {"grass-1", {x = -10, y = 9}},
    {"grass-1", {x = -10, y = 10}},
    {"grass-1", {x = -10, y = 11}},
    {"grass-1", {x = -10, y = 12}},
    {"grass-1", {x = -10, y = 13}},
    {"grass-1", {x = -10, y = 14}},
    {"grass-1", {x = -10, y = 15}},
    {"grass-1", {x = -9, y = -16}},
    {"grass-1", {x = -9, y = -15}},
    {"grass-1", {x = -9, y = -14}},
    {"grass-1", {x = -9, y = -13}},
    {"grass-1", {x = -9, y = -12}},
    {"grass-1", {x = -9, y = -11}},
    {"grass-1", {x = -9, y = -10}},
    {"grass-1", {x = -9, y = -9}},
    {"grass-1", {x = -9, y = -8}},
    {"grass-1", {x = -9, y = -7}},
    {"grass-1", {x = -9, y = -6}},
    {"grass-1", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"grass-1", {x = -9, y = -2}},
    {"grass-1", {x = -9, y = -1}},
    {"grass-1", {x = -9, y = 0}},
    {"grass-1", {x = -9, y = 1}},
    {"grass-1", {x = -9, y = 2}},
    {"grass-1", {x = -9, y = 3}},
    {"grass-1", {x = -9, y = 4}},
    {"grass-1", {x = -9, y = 5}},
    {"grass-1", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-1", {x = -9, y = 9}},
    {"grass-1", {x = -9, y = 10}},
    {"grass-1", {x = -9, y = 11}},
    {"grass-1", {x = -9, y = 12}},
    {"grass-1", {x = -9, y = 13}},
    {"grass-1", {x = -9, y = 14}},
    {"grass-1", {x = -9, y = 15}},
    {"grass-1", {x = -8, y = -16}},
    {"grass-1", {x = -8, y = -15}},
    {"grass-1", {x = -8, y = -14}},
    {"grass-1", {x = -8, y = -13}},
    {"grass-1", {x = -8, y = -12}},
    {"grass-1", {x = -8, y = -11}},
    {"grass-1", {x = -8, y = -10}},
    {"grass-1", {x = -8, y = -9}},
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-1", {x = -8, y = -2}},
    {"grass-1", {x = -8, y = -1}},
    {"grass-1", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-1", {x = -8, y = 9}},
    {"grass-1", {x = -8, y = 10}},
    {"grass-1", {x = -8, y = 11}},
    {"grass-1", {x = -8, y = 12}},
    {"grass-1", {x = -8, y = 13}},
    {"grass-1", {x = -8, y = 14}},
    {"grass-1", {x = -8, y = 15}},
    {"grass-1", {x = -7, y = -16}},
    {"grass-1", {x = -7, y = -15}},
    {"grass-1", {x = -7, y = -14}},
    {"grass-1", {x = -7, y = -13}},
    {"grass-1", {x = -7, y = -12}},
    {"grass-1", {x = -7, y = -11}},
    {"grass-1", {x = -7, y = -10}},
    {"grass-1", {x = -7, y = -9}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-1", {x = -7, y = -2}},
    {"grass-1", {x = -7, y = -1}},
    {"grass-1", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -7, y = 8}},
    {"grass-1", {x = -7, y = 9}},
    {"grass-1", {x = -7, y = 10}},
    {"grass-1", {x = -7, y = 11}},
    {"grass-1", {x = -7, y = 12}},
    {"grass-1", {x = -7, y = 13}},
    {"grass-1", {x = -7, y = 14}},
    {"grass-1", {x = -7, y = 15}},
    {"grass-1", {x = -6, y = -16}},
    {"grass-1", {x = -6, y = -15}},
    {"grass-1", {x = -6, y = -14}},
    {"grass-1", {x = -6, y = -13}},
    {"grass-1", {x = -6, y = -12}},
    {"grass-1", {x = -6, y = -11}},
    {"grass-1", {x = -6, y = -10}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-1", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"grass-1", {x = -6, y = 9}},
    {"grass-1", {x = -6, y = 10}},
    {"grass-1", {x = -6, y = 11}},
    {"grass-1", {x = -6, y = 12}},
    {"grass-1", {x = -6, y = 13}},
    {"grass-1", {x = -6, y = 14}},
    {"grass-1", {x = -6, y = 15}},
    {"grass-1", {x = -5, y = -16}},
    {"grass-1", {x = -5, y = -15}},
    {"grass-1", {x = -5, y = -14}},
    {"grass-1", {x = -5, y = -13}},
    {"grass-1", {x = -5, y = -12}},
    {"grass-1", {x = -5, y = -11}},
    {"grass-1", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -5, y = 8}},
    {"grass-1", {x = -5, y = 9}},
    {"grass-1", {x = -5, y = 10}},
    {"grass-1", {x = -5, y = 11}},
    {"grass-1", {x = -5, y = 12}},
    {"grass-1", {x = -5, y = 13}},
    {"grass-1", {x = -5, y = 14}},
    {"grass-1", {x = -5, y = 15}},
    {"grass-1", {x = -4, y = -16}},
    {"grass-1", {x = -4, y = -15}},
    {"grass-1", {x = -4, y = -14}},
    {"grass-1", {x = -4, y = -13}},
    {"grass-1", {x = -4, y = -12}},
    {"grass-1", {x = -4, y = -11}},
    {"grass-1", {x = -4, y = -10}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"grass-1", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -4, y = 8}},
    {"grass-1", {x = -4, y = 9}},
    {"grass-1", {x = -4, y = 10}},
    {"grass-1", {x = -4, y = 11}},
    {"grass-1", {x = -4, y = 12}},
    {"grass-1", {x = -4, y = 13}},
    {"grass-1", {x = -4, y = 14}},
    {"grass-1", {x = -4, y = 15}},
    {"grass-1", {x = -3, y = -16}},
    {"grass-1", {x = -3, y = -15}},
    {"grass-1", {x = -3, y = -14}},
    {"grass-1", {x = -3, y = -13}},
    {"grass-1", {x = -3, y = -12}},
    {"grass-1", {x = -3, y = -11}},
    {"grass-1", {x = -3, y = -10}},
    {"grass-1", {x = -3, y = -9}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -3, y = 8}},
    {"grass-1", {x = -3, y = 9}},
    {"grass-1", {x = -3, y = 10}},
    {"grass-1", {x = -3, y = 11}},
    {"grass-1", {x = -3, y = 12}},
    {"grass-1", {x = -3, y = 13}},
    {"grass-1", {x = -3, y = 14}},
    {"grass-1", {x = -3, y = 15}},
    {"grass-1", {x = -2, y = -16}},
    {"grass-1", {x = -2, y = -15}},
    {"grass-1", {x = -2, y = -14}},
    {"grass-1", {x = -2, y = -13}},
    {"grass-1", {x = -2, y = -12}},
    {"grass-1", {x = -2, y = -11}},
    {"grass-1", {x = -2, y = -10}},
    {"grass-1", {x = -2, y = -9}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-1", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -2, y = 8}},
    {"grass-1", {x = -2, y = 9}},
    {"grass-1", {x = -2, y = 10}},
    {"grass-1", {x = -2, y = 11}},
    {"grass-1", {x = -2, y = 12}},
    {"grass-1", {x = -2, y = 13}},
    {"grass-1", {x = -2, y = 14}},
    {"grass-1", {x = -2, y = 15}},
    {"grass-1", {x = -1, y = -16}},
    {"grass-1", {x = -1, y = -15}},
    {"grass-1", {x = -1, y = -14}},
    {"grass-1", {x = -1, y = -13}},
    {"grass-1", {x = -1, y = -12}},
    {"grass-1", {x = -1, y = -11}},
    {"grass-1", {x = -1, y = -10}},
    {"grass-1", {x = -1, y = -9}},
    {"grass-1", {x = -1, y = -8}},
    {"grass-1", {x = -1, y = -7}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = -1, y = 8}},
    {"grass-1", {x = -1, y = 9}},
    {"grass-1", {x = -1, y = 10}},
    {"grass-1", {x = -1, y = 11}},
    {"grass-1", {x = -1, y = 12}},
    {"grass-1", {x = -1, y = 13}},
    {"grass-1", {x = -1, y = 14}},
    {"grass-1", {x = -1, y = 15}},
    {"grass-1", {x = 0, y = -16}},
    {"grass-1", {x = 0, y = -15}},
    {"grass-1", {x = 0, y = -14}},
    {"grass-1", {x = 0, y = -13}},
    {"grass-1", {x = 0, y = -12}},
    {"grass-1", {x = 0, y = -11}},
    {"grass-1", {x = 0, y = -10}},
    {"grass-1", {x = 0, y = -9}},
    {"grass-1", {x = 0, y = -8}},
    {"grass-1", {x = 0, y = -7}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-1", {x = 0, y = 9}},
    {"grass-1", {x = 0, y = 10}},
    {"grass-1", {x = 0, y = 11}},
    {"grass-1", {x = 0, y = 12}},
    {"grass-1", {x = 0, y = 13}},
    {"grass-1", {x = 0, y = 14}},
    {"grass-1", {x = 0, y = 15}},
    {"grass-1", {x = 1, y = -16}},
    {"grass-1", {x = 1, y = -15}},
    {"grass-1", {x = 1, y = -14}},
    {"grass-1", {x = 1, y = -13}},
    {"grass-1", {x = 1, y = -12}},
    {"grass-1", {x = 1, y = -11}},
    {"grass-1", {x = 1, y = -10}},
    {"grass-1", {x = 1, y = -9}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-3", {x = 1, y = -1}},
    {"grass-3", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-1", {x = 1, y = 9}},
    {"grass-1", {x = 1, y = 10}},
    {"grass-1", {x = 1, y = 11}},
    {"grass-1", {x = 1, y = 12}},
    {"grass-1", {x = 1, y = 13}},
    {"grass-1", {x = 1, y = 14}},
    {"grass-1", {x = 1, y = 15}},
    {"grass-1", {x = 2, y = -16}},
    {"grass-1", {x = 2, y = -15}},
    {"grass-1", {x = 2, y = -14}},
    {"grass-1", {x = 2, y = -13}},
    {"grass-1", {x = 2, y = -12}},
    {"grass-1", {x = 2, y = -11}},
    {"grass-1", {x = 2, y = -10}},
    {"grass-1", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 2, y = 9}},
    {"grass-1", {x = 2, y = 10}},
    {"grass-1", {x = 2, y = 11}},
    {"grass-1", {x = 2, y = 12}},
    {"grass-1", {x = 2, y = 13}},
    {"grass-1", {x = 2, y = 14}},
    {"grass-1", {x = 2, y = 15}},
    {"grass-1", {x = 3, y = -16}},
    {"grass-1", {x = 3, y = -15}},
    {"grass-1", {x = 3, y = -14}},
    {"grass-1", {x = 3, y = -13}},
    {"grass-1", {x = 3, y = -12}},
    {"grass-1", {x = 3, y = -11}},
    {"grass-1", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 3, y = 9}},
    {"grass-1", {x = 3, y = 10}},
    {"grass-1", {x = 3, y = 11}},
    {"grass-1", {x = 3, y = 12}},
    {"grass-1", {x = 3, y = 13}},
    {"grass-1", {x = 3, y = 14}},
    {"grass-1", {x = 3, y = 15}},
    {"grass-1", {x = 4, y = -16}},
    {"grass-1", {x = 4, y = -15}},
    {"grass-1", {x = 4, y = -14}},
    {"grass-1", {x = 4, y = -13}},
    {"grass-1", {x = 4, y = -12}},
    {"grass-1", {x = 4, y = -11}},
    {"grass-1", {x = 4, y = -10}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 4, y = 8}},
    {"grass-1", {x = 4, y = 9}},
    {"grass-1", {x = 4, y = 10}},
    {"grass-1", {x = 4, y = 11}},
    {"grass-1", {x = 4, y = 12}},
    {"grass-1", {x = 4, y = 13}},
    {"grass-1", {x = 4, y = 14}},
    {"grass-1", {x = 4, y = 15}},
    {"grass-1", {x = 5, y = -16}},
    {"grass-1", {x = 5, y = -15}},
    {"grass-1", {x = 5, y = -14}},
    {"grass-1", {x = 5, y = -13}},
    {"grass-1", {x = 5, y = -12}},
    {"grass-1", {x = 5, y = -11}},
    {"grass-1", {x = 5, y = -10}},
    {"grass-1", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 5, y = 8}},
    {"grass-1", {x = 5, y = 9}},
    {"grass-1", {x = 5, y = 10}},
    {"grass-1", {x = 5, y = 11}},
    {"grass-1", {x = 5, y = 12}},
    {"grass-1", {x = 5, y = 13}},
    {"grass-1", {x = 5, y = 14}},
    {"grass-1", {x = 5, y = 15}},
    {"grass-1", {x = 6, y = -16}},
    {"grass-1", {x = 6, y = -15}},
    {"grass-1", {x = 6, y = -14}},
    {"grass-1", {x = 6, y = -13}},
    {"grass-1", {x = 6, y = -12}},
    {"grass-1", {x = 6, y = -11}},
    {"grass-1", {x = 6, y = -10}},
    {"grass-1", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-1", {x = 6, y = 7}},
    {"grass-1", {x = 6, y = 8}},
    {"grass-1", {x = 6, y = 9}},
    {"grass-1", {x = 6, y = 10}},
    {"grass-1", {x = 6, y = 11}},
    {"grass-1", {x = 6, y = 12}},
    {"grass-1", {x = 6, y = 13}},
    {"grass-1", {x = 6, y = 14}},
    {"grass-1", {x = 6, y = 15}},
    {"grass-1", {x = 7, y = -16}},
    {"grass-1", {x = 7, y = -15}},
    {"grass-1", {x = 7, y = -14}},
    {"grass-1", {x = 7, y = -13}},
    {"grass-1", {x = 7, y = -12}},
    {"grass-1", {x = 7, y = -11}},
    {"grass-1", {x = 7, y = -10}},
    {"grass-1", {x = 7, y = -9}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-1", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
    {"grass-1", {x = 7, y = 8}},
    {"grass-1", {x = 7, y = 9}},
    {"grass-1", {x = 7, y = 10}},
    {"grass-1", {x = 7, y = 11}},
    {"grass-1", {x = 7, y = 12}},
    {"grass-1", {x = 7, y = 13}},
    {"grass-1", {x = 7, y = 14}},
    {"grass-1", {x = 7, y = 15}},
    {"grass-1", {x = 8, y = -16}},
    {"grass-1", {x = 8, y = -15}},
    {"grass-1", {x = 8, y = -14}},
    {"grass-1", {x = 8, y = -13}},
    {"grass-1", {x = 8, y = -12}},
    {"grass-1", {x = 8, y = -11}},
    {"grass-1", {x = 8, y = -10}},
    {"grass-1", {x = 8, y = -9}},
    {"grass-1", {x = 8, y = -8}},
    {"grass-1", {x = 8, y = -7}},
    {"grass-1", {x = 8, y = -6}},
    {"grass-1", {x = 8, y = -5}},
    {"grass-1", {x = 8, y = -4}},
    {"grass-1", {x = 8, y = -3}},
    {"grass-1", {x = 8, y = -2}},
    {"grass-1", {x = 8, y = -1}},
    {"grass-1", {x = 8, y = 0}},
    {"grass-1", {x = 8, y = 1}},
    {"grass-1", {x = 8, y = 2}},
    {"grass-1", {x = 8, y = 3}},
    {"grass-1", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-1", {x = 8, y = 6}},
    {"grass-1", {x = 8, y = 7}},
    {"grass-1", {x = 8, y = 8}},
    {"grass-1", {x = 8, y = 9}},
    {"grass-1", {x = 8, y = 10}},
    {"grass-1", {x = 8, y = 11}},
    {"grass-1", {x = 8, y = 12}},
    {"grass-1", {x = 8, y = 13}},
    {"grass-1", {x = 8, y = 14}},
    {"grass-1", {x = 8, y = 15}},
    {"grass-1", {x = 9, y = -16}},
    {"grass-1", {x = 9, y = -15}},
    {"grass-1", {x = 9, y = -14}},
    {"grass-1", {x = 9, y = -13}},
    {"grass-1", {x = 9, y = -12}},
    {"grass-1", {x = 9, y = -11}},
    {"grass-1", {x = 9, y = -10}},
    {"grass-1", {x = 9, y = -9}},
    {"grass-1", {x = 9, y = -8}},
    {"grass-1", {x = 9, y = -7}},
    {"grass-1", {x = 9, y = -6}},
    {"grass-1", {x = 9, y = -5}},
    {"grass-1", {x = 9, y = -4}},
    {"grass-1", {x = 9, y = -3}},
    {"grass-1", {x = 9, y = -2}},
    {"grass-1", {x = 9, y = -1}},
    {"grass-1", {x = 9, y = 0}},
    {"grass-1", {x = 9, y = 1}},
    {"grass-1", {x = 9, y = 2}},
    {"grass-1", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"grass-1", {x = 9, y = 5}},
    {"grass-1", {x = 9, y = 6}},
    {"grass-1", {x = 9, y = 7}},
    {"grass-1", {x = 9, y = 8}},
    {"grass-1", {x = 9, y = 9}},
    {"grass-1", {x = 9, y = 10}},
    {"grass-1", {x = 9, y = 11}},
    {"grass-1", {x = 9, y = 12}},
    {"grass-1", {x = 9, y = 13}},
    {"grass-1", {x = 9, y = 14}},
    {"grass-1", {x = 9, y = 15}},
    {"grass-1", {x = 10, y = -16}},
    {"grass-1", {x = 10, y = -15}},
    {"grass-1", {x = 10, y = -14}},
    {"grass-1", {x = 10, y = -13}},
    {"grass-1", {x = 10, y = -12}},
    {"grass-1", {x = 10, y = -11}},
    {"grass-1", {x = 10, y = -10}},
    {"grass-1", {x = 10, y = -9}},
    {"grass-1", {x = 10, y = -8}},
    {"grass-1", {x = 10, y = -7}},
    {"grass-1", {x = 10, y = -6}},
    {"grass-1", {x = 10, y = -5}},
    {"grass-1", {x = 10, y = -4}},
    {"grass-1", {x = 10, y = -3}},
    {"grass-1", {x = 10, y = -2}},
    {"grass-1", {x = 10, y = -1}},
    {"grass-1", {x = 10, y = 0}},
    {"grass-1", {x = 10, y = 1}},
    {"grass-1", {x = 10, y = 2}},
    {"grass-1", {x = 10, y = 3}},
    {"grass-1", {x = 10, y = 4}},
    {"grass-1", {x = 10, y = 5}},
    {"grass-1", {x = 10, y = 6}},
    {"grass-1", {x = 10, y = 7}},
    {"grass-1", {x = 10, y = 8}},
    {"grass-1", {x = 10, y = 9}},
    {"grass-1", {x = 10, y = 10}},
    {"grass-1", {x = 10, y = 11}},
    {"grass-1", {x = 10, y = 12}},
    {"grass-1", {x = 10, y = 13}},
    {"grass-1", {x = 10, y = 14}},
    {"grass-1", {x = 10, y = 15}},
    {"grass-1", {x = 11, y = -16}},
    {"grass-1", {x = 11, y = -15}},
    {"grass-1", {x = 11, y = -14}},
    {"grass-1", {x = 11, y = -13}},
    {"grass-1", {x = 11, y = -12}},
    {"grass-1", {x = 11, y = -11}},
    {"grass-1", {x = 11, y = -10}},
    {"grass-1", {x = 11, y = -9}},
    {"grass-1", {x = 11, y = -8}},
    {"grass-1", {x = 11, y = -7}},
    {"grass-1", {x = 11, y = -6}},
    {"grass-1", {x = 11, y = -5}},
    {"grass-1", {x = 11, y = -4}},
    {"grass-1", {x = 11, y = -3}},
    {"grass-1", {x = 11, y = -2}},
    {"grass-1", {x = 11, y = -1}},
    {"grass-1", {x = 11, y = 0}},
    {"grass-1", {x = 11, y = 1}},
    {"grass-1", {x = 11, y = 2}},
    {"grass-1", {x = 11, y = 3}},
    {"grass-1", {x = 11, y = 4}},
    {"grass-1", {x = 11, y = 5}},
    {"grass-1", {x = 11, y = 6}},
    {"grass-1", {x = 11, y = 7}},
    {"grass-1", {x = 11, y = 8}},
    {"grass-1", {x = 11, y = 9}},
    {"grass-1", {x = 11, y = 10}},
    {"grass-1", {x = 11, y = 11}},
    {"grass-1", {x = 11, y = 12}},
    {"grass-1", {x = 11, y = 13}},
    {"grass-1", {x = 11, y = 14}},
    {"grass-1", {x = 11, y = 15}},
    {"grass-1", {x = 12, y = -16}},
    {"grass-1", {x = 12, y = -15}},
    {"grass-1", {x = 12, y = -14}},
    {"grass-1", {x = 12, y = -13}},
    {"grass-1", {x = 12, y = -12}},
    {"grass-1", {x = 12, y = -11}},
    {"grass-1", {x = 12, y = -10}},
    {"grass-1", {x = 12, y = -9}},
    {"grass-1", {x = 12, y = -8}},
    {"grass-1", {x = 12, y = -7}},
    {"grass-1", {x = 12, y = -6}},
    {"grass-1", {x = 12, y = -5}},
    {"grass-1", {x = 12, y = -4}},
    {"grass-1", {x = 12, y = -3}},
    {"grass-1", {x = 12, y = -2}},
    {"grass-1", {x = 12, y = -1}},
    {"grass-1", {x = 12, y = 0}},
    {"grass-1", {x = 12, y = 1}},
    {"grass-1", {x = 12, y = 2}},
    {"grass-1", {x = 12, y = 3}},
    {"grass-1", {x = 12, y = 4}},
    {"grass-1", {x = 12, y = 5}},
    {"grass-1", {x = 12, y = 6}},
    {"grass-1", {x = 12, y = 7}},
    {"grass-1", {x = 12, y = 8}},
    {"grass-1", {x = 12, y = 9}},
    {"grass-1", {x = 12, y = 10}},
    {"grass-1", {x = 12, y = 11}},
    {"grass-1", {x = 12, y = 12}},
    {"grass-1", {x = 12, y = 13}},
    {"grass-1", {x = 12, y = 14}},
    {"grass-1", {x = 12, y = 15}},
    {"grass-1", {x = 13, y = -16}},
    {"grass-1", {x = 13, y = -15}},
    {"grass-1", {x = 13, y = -14}},
    {"grass-1", {x = 13, y = -13}},
    {"grass-1", {x = 13, y = -12}},
    {"grass-1", {x = 13, y = -11}},
    {"grass-1", {x = 13, y = -10}},
    {"grass-1", {x = 13, y = -9}},
    {"grass-1", {x = 13, y = -8}},
    {"grass-1", {x = 13, y = -7}},
    {"grass-1", {x = 13, y = -6}},
    {"grass-1", {x = 13, y = -5}},
    {"grass-1", {x = 13, y = -4}},
    {"grass-1", {x = 13, y = -3}},
    {"grass-1", {x = 13, y = -2}},
    {"grass-1", {x = 13, y = -1}},
    {"grass-1", {x = 13, y = 0}},
    {"grass-1", {x = 13, y = 1}},
    {"grass-1", {x = 13, y = 2}},
    {"grass-1", {x = 13, y = 3}},
    {"grass-1", {x = 13, y = 4}},
    {"grass-1", {x = 13, y = 5}},
    {"grass-1", {x = 13, y = 6}},
    {"grass-1", {x = 13, y = 7}},
    {"grass-1", {x = 13, y = 8}},
    {"grass-1", {x = 13, y = 9}},
    {"grass-1", {x = 13, y = 10}},
    {"grass-1", {x = 13, y = 11}},
    {"grass-1", {x = 13, y = 12}},
    {"grass-1", {x = 13, y = 13}},
    {"grass-1", {x = 13, y = 14}},
    {"grass-1", {x = 13, y = 15}},
    {"grass-1", {x = 14, y = -16}},
    {"grass-1", {x = 14, y = -15}},
    {"grass-1", {x = 14, y = -14}},
    {"grass-1", {x = 14, y = -13}},
    {"grass-1", {x = 14, y = -12}},
    {"grass-1", {x = 14, y = -11}},
    {"grass-1", {x = 14, y = -10}},
    {"grass-1", {x = 14, y = -9}},
    {"grass-1", {x = 14, y = -8}},
    {"grass-1", {x = 14, y = -7}},
    {"grass-1", {x = 14, y = -6}},
    {"grass-1", {x = 14, y = -5}},
    {"grass-1", {x = 14, y = -4}},
    {"grass-1", {x = 14, y = -3}},
    {"grass-1", {x = 14, y = -2}},
    {"grass-1", {x = 14, y = -1}},
    {"grass-1", {x = 14, y = 0}},
    {"grass-1", {x = 14, y = 1}},
    {"grass-1", {x = 14, y = 2}},
    {"grass-1", {x = 14, y = 3}},
    {"grass-1", {x = 14, y = 4}},
    {"grass-1", {x = 14, y = 5}},
    {"grass-1", {x = 14, y = 6}},
    {"grass-1", {x = 14, y = 7}},
    {"grass-1", {x = 14, y = 8}},
    {"grass-1", {x = 14, y = 9}},
    {"grass-1", {x = 14, y = 10}},
    {"grass-1", {x = 14, y = 11}},
    {"grass-1", {x = 14, y = 12}},
    {"grass-1", {x = 14, y = 13}},
    {"grass-1", {x = 14, y = 14}},
    {"grass-1", {x = 14, y = 15}},
    {"grass-1", {x = 15, y = -16}},
    {"grass-1", {x = 15, y = -15}},
    {"grass-1", {x = 15, y = -14}},
    {"grass-1", {x = 15, y = -13}},
    {"grass-1", {x = 15, y = -12}},
    {"grass-1", {x = 15, y = -11}},
    {"grass-1", {x = 15, y = -10}},
    {"grass-1", {x = 15, y = -9}},
    {"grass-1", {x = 15, y = -8}},
    {"grass-1", {x = 15, y = -7}},
    {"grass-1", {x = 15, y = -6}},
    {"grass-1", {x = 15, y = -5}},
    {"grass-1", {x = 15, y = -4}},
    {"grass-1", {x = 15, y = -3}},
    {"grass-1", {x = 15, y = -2}},
    {"grass-1", {x = 15, y = -1}},
    {"grass-1", {x = 15, y = 0}},
    {"grass-1", {x = 15, y = 1}},
    {"grass-1", {x = 15, y = 2}},
    {"grass-1", {x = 15, y = 3}},
    {"grass-1", {x = 15, y = 4}},
    {"grass-1", {x = 15, y = 5}},
    {"grass-1", {x = 15, y = 6}},
    {"grass-1", {x = 15, y = 7}},
    {"grass-1", {x = 15, y = 8}},
    {"grass-1", {x = 15, y = 9}},
    {"grass-1", {x = 15, y = 10}},
    {"grass-1", {x = 15, y = 11}},
    {"grass-1", {x = 15, y = 12}},
    {"grass-1", {x = 15, y = 13}},
    {"grass-1", {x = 15, y = 14}},
    {"grass-1", {x = 15, y = 15}},
  }
}
