return
{
  entities =
  {
    {"stone-wall", {x = -10.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -11.5}, {force = "enemy", }},
    {"laser-turret", {x = -9, y = -11}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -12.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = -11}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -12.5}, {force = "enemy", }},
    {"laser-turret", {x = -3, y = -11}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -12.5}, {force = "enemy", }},
    {"laser-turret", {x = 0, y = -11}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -12.5}, {force = "enemy", }},
    {"laser-turret", {x = 3, y = -11}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -12.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = -11}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -12.5}, {force = "enemy", }},
    {"gate", {x = 12.5, y = -12.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -12.5}, {force = "enemy", }},
    {"gate", {x = 13.5, y = -12.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -9.5}, {force = "enemy", }},
    {"laser-turret", {x = -11, y = -9}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -10.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -7.5}, {force = "enemy", }},
    {"tree-01", {x = -2.39, y = -7.77}, {}},
    {"laser-turret", {x = 12, y = -7}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = -11, y = -6}, {dir = "west", force = "enemy", }},
    {"laser-turret", {x = 9, y = -6}, {dir = "east", force = "enemy", }},
    {"laser-turret", {x = 12, y = -5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -3.5}, {force = "enemy", }},
    {"laser-turret", {x = -11, y = -3}, {dir = "west", force = "enemy", }},
    {"steel-chest", {x = -4.5, y = -4.5}, {items = {beacon = 1, ["effectivity-module-3"] = 1}, }},
    {"substation", {x = -4, y = -3}, {force = "enemy", }},
    {"steel-chest", {x = 5.5, y = -3.5}, {items = {["speed-module-3"] = 1}, }},
    {"tree-05", {x = 10.07, y = -3.72}, {}},
    {"laser-turret", {x = 12, y = -3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -1.5}, {force = "enemy", }},
    {"roboport", {x = -4, y = 0}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"aliencon-robot", {x = -1.95, y = -1.17}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.99, y = -1.44}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.07, y = -1.66}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -2.5, y = -2.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"substation", {x = 5, y = -2}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 0.5}, {force = "enemy", }},
    {"laser-turret", {x = -11, y = 0}, {dir = "west", force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 0.85}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 0.73}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 0.58}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 0.47}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 0.28}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 0.13}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 0.01}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = -0.14}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = -0.26}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = -0.48}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.91, y = -0.79}, {force = "enemy", }},
    {"purple-crystal-gen", {x = -0.5, y = -1}, {force = "enemy", }},
    {"laser-turret", {x = 10, y = 1}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 2.5}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.91, y = 1.61}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.91, y = 1.57}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.91, y = 1.54}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 1.5}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 1.38}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 1.19}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.87, y = 1}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -2.5, y = 2.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"gate", {x = 14.5, y = 2.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 3.5}, {force = "enemy", }},
    {"gate", {x = -13.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 3.5}, {force = "enemy", }},
    {"tree-08-red", {x = -8.69, y = 5.35}, {}},
    {"tree-08-red", {x = -6.82, y = 4.46}, {}},
    {"tree-08-red", {x = -7.76, y = 3.46}, {}},
    {"rock-huge", {x = 5.14, y = 4.28}, {}},
    {"gate", {x = 14.5, y = 4.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = 3.5}, {force = "enemy", }},
    {"gate", {x = -13.5, y = 6.5}, {force = "enemy", }},
    {"gate", {x = -13.5, y = 5.5}, {force = "enemy", }},
    {"steel-chest", {x = -3.5, y = 6.5}, {items = {["productivity-module-3"] = 1, ["repair-pack"] = 100}, }},
    {"substation", {x = -2, y = 6}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 7.5}, {force = "enemy", }},
    {"laser-turret", {x = -10, y = 9}, {dir = "west", force = "enemy", }},
    {"tree-07", {x = -7.59, y = 8.75}, {}},
    {"laser-turret", {x = -1, y = 9}, {dir = "east", force = "enemy", }},
    {"gate", {x = 8.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 7.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 9.5}, {force = "enemy", }},
    {"tree-07", {x = -8.87, y = 10.51}, {}},
    {"tree-07", {x = -7.71, y = 11.21}, {}},
    {"gate", {x = 8.5, y = 10.5}, {force = "enemy", }},
    {"gate", {x = 8.5, y = 9.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = 12.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = 11.5}, {force = "enemy", }},
    {"laser-turret", {x = -11, y = 13}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = -8, y = 13}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = -5, y = 13}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = -2, y = 13}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = 1, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 14.5}, {force = "enemy", }},
    {"gate", {x = 4.5, y = 14.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 14.5}, {force = "enemy", }},
    {"gate", {x = 5.5, y = 14.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 6.5, y = 14.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 14.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -15, y = -15}},
    {"grass-1", {x = -15, y = -14}},
    {"grass-1", {x = -15, y = -13}},
    {"grass-1", {x = -15, y = -12}},
    {"grass-1", {x = -15, y = -11}},
    {"grass-1", {x = -15, y = -10}},
    {"grass-1", {x = -15, y = -9}},
    {"grass-1", {x = -15, y = -8}},
    {"grass-1", {x = -15, y = -7}},
    {"grass-1", {x = -15, y = -6}},
    {"grass-1", {x = -15, y = -5}},
    {"grass-1", {x = -15, y = -4}},
    {"grass-1", {x = -15, y = -3}},
    {"grass-1", {x = -15, y = -2}},
    {"grass-1", {x = -15, y = -1}},
    {"grass-1", {x = -15, y = 0}},
    {"grass-1", {x = -15, y = 1}},
    {"grass-1", {x = -15, y = 2}},
    {"grass-1", {x = -15, y = 3}},
    {"grass-1", {x = -15, y = 4}},
    {"grass-1", {x = -15, y = 5}},
    {"grass-3", {x = -15, y = 6}},
    {"grass-3", {x = -15, y = 7}},
    {"grass-3", {x = -15, y = 8}},
    {"grass-1", {x = -15, y = 9}},
    {"grass-1", {x = -15, y = 10}},
    {"grass-1", {x = -15, y = 11}},
    {"grass-1", {x = -15, y = 12}},
    {"grass-1", {x = -15, y = 13}},
    {"grass-1", {x = -15, y = 14}},
    {"grass-1", {x = -14, y = -15}},
    {"grass-1", {x = -14, y = -14}},
    {"grass-1", {x = -14, y = -13}},
    {"grass-1", {x = -14, y = -12}},
    {"grass-1", {x = -14, y = -11}},
    {"grass-1", {x = -14, y = -10}},
    {"grass-1", {x = -14, y = -9}},
    {"grass-1", {x = -14, y = -8}},
    {"grass-1", {x = -14, y = -7}},
    {"grass-1", {x = -14, y = -6}},
    {"grass-1", {x = -14, y = -5}},
    {"grass-1", {x = -14, y = -4}},
    {"grass-1", {x = -14, y = -3}},
    {"grass-1", {x = -14, y = -2}},
    {"grass-1", {x = -14, y = -1}},
    {"grass-1", {x = -14, y = 0}},
    {"grass-1", {x = -14, y = 1}},
    {"grass-1", {x = -14, y = 2}},
    {"grass-1", {x = -14, y = 3}},
    {"grass-1", {x = -14, y = 4}},
    {"grass-1", {x = -14, y = 5}},
    {"grass-3", {x = -14, y = 6}},
    {"grass-3", {x = -14, y = 7}},
    {"grass-1", {x = -14, y = 8}},
    {"grass-1", {x = -14, y = 9}},
    {"red-desert-0", {x = -14, y = 10}},
    {"red-desert-0", {x = -14, y = 11}},
    {"red-desert-0", {x = -14, y = 12}},
    {"grass-1", {x = -14, y = 13}},
    {"grass-1", {x = -14, y = 14}},
    {"grass-1", {x = -13, y = -15}},
    {"grass-1", {x = -13, y = -14}},
    {"grass-1", {x = -13, y = -13}},
    {"grass-1", {x = -13, y = -12}},
    {"grass-1", {x = -13, y = -11}},
    {"grass-1", {x = -13, y = -10}},
    {"grass-1", {x = -13, y = -9}},
    {"grass-1", {x = -13, y = -8}},
    {"grass-1", {x = -13, y = -7}},
    {"grass-1", {x = -13, y = -6}},
    {"grass-1", {x = -13, y = -5}},
    {"grass-1", {x = -13, y = -4}},
    {"grass-1", {x = -13, y = -3}},
    {"grass-1", {x = -13, y = -2}},
    {"grass-1", {x = -13, y = -1}},
    {"grass-1", {x = -13, y = 0}},
    {"grass-1", {x = -13, y = 1}},
    {"grass-1", {x = -13, y = 2}},
    {"grass-1", {x = -13, y = 3}},
    {"red-desert-0", {x = -13, y = 4}},
    {"dirt-7", {x = -13, y = 5}},
    {"grass-1", {x = -13, y = 6}},
    {"grass-1", {x = -13, y = 7}},
    {"grass-1", {x = -13, y = 8}},
    {"grass-3", {x = -13, y = 9}},
    {"grass-3", {x = -13, y = 10}},
    {"red-desert-0", {x = -13, y = 11}},
    {"red-desert-0", {x = -13, y = 12}},
    {"grass-1", {x = -13, y = 13}},
    {"grass-1", {x = -13, y = 14}},
    {"grass-1", {x = -12, y = -15}},
    {"grass-1", {x = -12, y = -14}},
    {"grass-1", {x = -12, y = -13}},
    {"grass-1", {x = -12, y = -12}},
    {"grass-1", {x = -12, y = -11}},
    {"grass-1", {x = -12, y = -10}},
    {"grass-1", {x = -12, y = -9}},
    {"grass-1", {x = -12, y = -8}},
    {"grass-1", {x = -12, y = -7}},
    {"grass-1", {x = -12, y = -6}},
    {"grass-1", {x = -12, y = -5}},
    {"grass-1", {x = -12, y = -4}},
    {"grass-1", {x = -12, y = -3}},
    {"grass-1", {x = -12, y = -2}},
    {"grass-1", {x = -12, y = -1}},
    {"grass-1", {x = -12, y = 0}},
    {"grass-1", {x = -12, y = 1}},
    {"grass-1", {x = -12, y = 2}},
    {"grass-1", {x = -12, y = 3}},
    {"red-desert-0", {x = -12, y = 4}},
    {"dirt-7", {x = -12, y = 5}},
    {"red-desert-0", {x = -12, y = 6}},
    {"grass-1", {x = -12, y = 7}},
    {"grass-1", {x = -12, y = 8}},
    {"grass-3", {x = -12, y = 9}},
    {"grass-3", {x = -12, y = 10}},
    {"grass-3", {x = -12, y = 11}},
    {"grass-1", {x = -12, y = 12}},
    {"grass-1", {x = -12, y = 13}},
    {"grass-1", {x = -12, y = 14}},
    {"grass-1", {x = -11, y = -15}},
    {"grass-1", {x = -11, y = -14}},
    {"grass-1", {x = -11, y = -13}},
    {"grass-1", {x = -11, y = -12}},
    {"grass-1", {x = -11, y = -11}},
    {"grass-1", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-1", {x = -11, y = -5}},
    {"grass-1", {x = -11, y = -4}},
    {"grass-1", {x = -11, y = -3}},
    {"grass-1", {x = -11, y = -2}},
    {"grass-1", {x = -11, y = -1}},
    {"grass-1", {x = -11, y = 0}},
    {"grass-1", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-3", {x = -11, y = 4}},
    {"grass-3", {x = -11, y = 5}},
    {"grass-3", {x = -11, y = 6}},
    {"grass-1", {x = -11, y = 7}},
    {"grass-1", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"red-desert-0", {x = -11, y = 10}},
    {"grass-3", {x = -11, y = 11}},
    {"grass-1", {x = -11, y = 12}},
    {"grass-1", {x = -11, y = 13}},
    {"grass-1", {x = -11, y = 14}},
    {"grass-1", {x = -10, y = -15}},
    {"grass-1", {x = -10, y = -14}},
    {"grass-1", {x = -10, y = -13}},
    {"grass-1", {x = -10, y = -12}},
    {"grass-1", {x = -10, y = -11}},
    {"grass-1", {x = -10, y = -10}},
    {"grass-1", {x = -10, y = -9}},
    {"grass-1", {x = -10, y = -8}},
    {"grass-3", {x = -10, y = -7}},
    {"grass-1", {x = -10, y = -6}},
    {"grass-1", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-1", {x = -10, y = -3}},
    {"grass-1", {x = -10, y = -2}},
    {"grass-1", {x = -10, y = -1}},
    {"grass-1", {x = -10, y = 0}},
    {"grass-1", {x = -10, y = 1}},
    {"grass-1", {x = -10, y = 2}},
    {"grass-1", {x = -10, y = 3}},
    {"grass-3", {x = -10, y = 4}},
    {"grass-3", {x = -10, y = 5}},
    {"grass-3", {x = -10, y = 6}},
    {"grass-1", {x = -10, y = 7}},
    {"grass-1", {x = -10, y = 8}},
    {"grass-1", {x = -10, y = 9}},
    {"red-desert-0", {x = -10, y = 10}},
    {"red-desert-0", {x = -10, y = 11}},
    {"grass-1", {x = -10, y = 12}},
    {"grass-1", {x = -10, y = 13}},
    {"grass-1", {x = -10, y = 14}},
    {"grass-1", {x = -9, y = -15}},
    {"grass-1", {x = -9, y = -14}},
    {"grass-1", {x = -9, y = -13}},
    {"grass-1", {x = -9, y = -12}},
    {"grass-1", {x = -9, y = -11}},
    {"grass-1", {x = -9, y = -10}},
    {"red-desert-0", {x = -9, y = -9}},
    {"red-desert-0", {x = -9, y = -8}},
    {"grass-3", {x = -9, y = -7}},
    {"red-desert-0", {x = -9, y = -6}},
    {"grass-3", {x = -9, y = -5}},
    {"grass-3", {x = -9, y = -4}},
    {"red-desert-0", {x = -9, y = -3}},
    {"red-desert-0", {x = -9, y = -2}},
    {"red-desert-0", {x = -9, y = -1}},
    {"red-desert-0", {x = -9, y = 0}},
    {"grass-3", {x = -9, y = 1}},
    {"grass-3", {x = -9, y = 2}},
    {"red-desert-0", {x = -9, y = 3}},
    {"grass-3", {x = -9, y = 4}},
    {"grass-3", {x = -9, y = 5}},
    {"grass-3", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-1", {x = -9, y = 9}},
    {"grass-3", {x = -9, y = 10}},
    {"grass-3", {x = -9, y = 11}},
    {"grass-1", {x = -9, y = 12}},
    {"grass-1", {x = -9, y = 13}},
    {"grass-1", {x = -9, y = 14}},
    {"grass-1", {x = -8, y = -15}},
    {"grass-1", {x = -8, y = -14}},
    {"grass-1", {x = -8, y = -13}},
    {"grass-1", {x = -8, y = -12}},
    {"grass-1", {x = -8, y = -11}},
    {"grass-3", {x = -8, y = -10}},
    {"grass-3", {x = -8, y = -9}},
    {"grass-3", {x = -8, y = -8}},
    {"red-desert-0", {x = -8, y = -7}},
    {"red-desert-0", {x = -8, y = -6}},
    {"red-desert-0", {x = -8, y = -5}},
    {"red-desert-0", {x = -8, y = -4}},
    {"red-desert-0", {x = -8, y = -3}},
    {"grass-3", {x = -8, y = -2}},
    {"grass-3", {x = -8, y = -1}},
    {"grass-3", {x = -8, y = 0}},
    {"grass-3", {x = -8, y = 1}},
    {"grass-3", {x = -8, y = 2}},
    {"red-desert-0", {x = -8, y = 3}},
    {"red-desert-0", {x = -8, y = 4}},
    {"red-desert-0", {x = -8, y = 5}},
    {"red-desert-0", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-1", {x = -8, y = 9}},
    {"grass-3", {x = -8, y = 10}},
    {"grass-3", {x = -8, y = 11}},
    {"grass-1", {x = -8, y = 12}},
    {"grass-1", {x = -8, y = 13}},
    {"grass-1", {x = -8, y = 14}},
    {"grass-1", {x = -7, y = -15}},
    {"grass-1", {x = -7, y = -14}},
    {"grass-1", {x = -7, y = -13}},
    {"grass-1", {x = -7, y = -12}},
    {"grass-1", {x = -7, y = -11}},
    {"grass-3", {x = -7, y = -10}},
    {"grass-3", {x = -7, y = -9}},
    {"grass-3", {x = -7, y = -8}},
    {"red-desert-0", {x = -7, y = -7}},
    {"red-desert-0", {x = -7, y = -6}},
    {"red-desert-0", {x = -7, y = -5}},
    {"red-desert-0", {x = -7, y = -4}},
    {"red-desert-0", {x = -7, y = -3}},
    {"grass-3", {x = -7, y = -2}},
    {"grass-3", {x = -7, y = -1}},
    {"grass-3", {x = -7, y = 0}},
    {"grass-3", {x = -7, y = 1}},
    {"red-desert-0", {x = -7, y = 2}},
    {"red-desert-0", {x = -7, y = 3}},
    {"grass-3", {x = -7, y = 4}},
    {"grass-3", {x = -7, y = 5}},
    {"red-desert-0", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -7, y = 8}},
    {"grass-1", {x = -7, y = 9}},
    {"grass-3", {x = -7, y = 10}},
    {"grass-3", {x = -7, y = 11}},
    {"grass-1", {x = -7, y = 12}},
    {"grass-1", {x = -7, y = 13}},
    {"grass-1", {x = -7, y = 14}},
    {"grass-1", {x = -6, y = -15}},
    {"grass-1", {x = -6, y = -14}},
    {"grass-1", {x = -6, y = -13}},
    {"grass-1", {x = -6, y = -12}},
    {"grass-1", {x = -6, y = -11}},
    {"grass-1", {x = -6, y = -10}},
    {"red-desert-0", {x = -6, y = -9}},
    {"red-desert-0", {x = -6, y = -8}},
    {"red-desert-0", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-3", {x = -6, y = 0}},
    {"grass-3", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-3", {x = -6, y = 4}},
    {"grass-3", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"grass-1", {x = -6, y = 9}},
    {"red-desert-0", {x = -6, y = 10}},
    {"red-desert-0", {x = -6, y = 11}},
    {"grass-1", {x = -6, y = 12}},
    {"grass-1", {x = -6, y = 13}},
    {"grass-1", {x = -6, y = 14}},
    {"grass-1", {x = -5, y = -15}},
    {"grass-1", {x = -5, y = -14}},
    {"grass-1", {x = -5, y = -13}},
    {"grass-1", {x = -5, y = -12}},
    {"grass-1", {x = -5, y = -11}},
    {"grass-1", {x = -5, y = -10}},
    {"red-desert-0", {x = -5, y = -9}},
    {"red-desert-0", {x = -5, y = -8}},
    {"red-desert-0", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -5, y = 8}},
    {"grass-1", {x = -5, y = 9}},
    {"grass-1", {x = -5, y = 10}},
    {"grass-1", {x = -5, y = 11}},
    {"grass-1", {x = -5, y = 12}},
    {"grass-1", {x = -5, y = 13}},
    {"grass-1", {x = -5, y = 14}},
    {"grass-1", {x = -4, y = -15}},
    {"grass-1", {x = -4, y = -14}},
    {"grass-1", {x = -4, y = -13}},
    {"grass-1", {x = -4, y = -12}},
    {"grass-1", {x = -4, y = -11}},
    {"grass-1", {x = -4, y = -10}},
    {"red-desert-0", {x = -4, y = -9}},
    {"red-desert-0", {x = -4, y = -8}},
    {"water", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"red-desert-0", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -4, y = 8}},
    {"grass-1", {x = -4, y = 9}},
    {"red-desert-0", {x = -4, y = 10}},
    {"grass-1", {x = -4, y = 11}},
    {"grass-1", {x = -4, y = 12}},
    {"grass-1", {x = -4, y = 13}},
    {"grass-1", {x = -4, y = 14}},
    {"grass-1", {x = -3, y = -15}},
    {"grass-1", {x = -3, y = -14}},
    {"grass-1", {x = -3, y = -13}},
    {"grass-1", {x = -3, y = -12}},
    {"grass-1", {x = -3, y = -11}},
    {"grass-1", {x = -3, y = -10}},
    {"red-desert-0", {x = -3, y = -9}},
    {"red-desert-0", {x = -3, y = -8}},
    {"water", {x = -3, y = -7}},
    {"water", {x = -3, y = -6}},
    {"water", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -3, y = 8}},
    {"grass-1", {x = -3, y = 9}},
    {"red-desert-0", {x = -3, y = 10}},
    {"grass-1", {x = -3, y = 11}},
    {"grass-1", {x = -3, y = 12}},
    {"grass-1", {x = -3, y = 13}},
    {"grass-1", {x = -3, y = 14}},
    {"grass-1", {x = -2, y = -15}},
    {"grass-1", {x = -2, y = -14}},
    {"grass-1", {x = -2, y = -13}},
    {"grass-1", {x = -2, y = -12}},
    {"grass-1", {x = -2, y = -11}},
    {"grass-1", {x = -2, y = -10}},
    {"red-desert-0", {x = -2, y = -9}},
    {"red-desert-0", {x = -2, y = -8}},
    {"water", {x = -2, y = -7}},
    {"water", {x = -2, y = -6}},
    {"water", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -2, y = 8}},
    {"grass-1", {x = -2, y = 9}},
    {"grass-1", {x = -2, y = 10}},
    {"grass-1", {x = -2, y = 11}},
    {"grass-1", {x = -2, y = 12}},
    {"grass-1", {x = -2, y = 13}},
    {"grass-1", {x = -2, y = 14}},
    {"grass-1", {x = -1, y = -15}},
    {"grass-1", {x = -1, y = -14}},
    {"grass-1", {x = -1, y = -13}},
    {"grass-1", {x = -1, y = -12}},
    {"grass-1", {x = -1, y = -11}},
    {"grass-1", {x = -1, y = -10}},
    {"grass-3", {x = -1, y = -9}},
    {"grass-3", {x = -1, y = -8}},
    {"water", {x = -1, y = -7}},
    {"water", {x = -1, y = -6}},
    {"water", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = -1, y = 8}},
    {"grass-1", {x = -1, y = 9}},
    {"grass-1", {x = -1, y = 10}},
    {"grass-1", {x = -1, y = 11}},
    {"grass-1", {x = -1, y = 12}},
    {"grass-1", {x = -1, y = 13}},
    {"grass-1", {x = -1, y = 14}},
    {"grass-1", {x = 0, y = -15}},
    {"grass-1", {x = 0, y = -14}},
    {"grass-1", {x = 0, y = -13}},
    {"grass-1", {x = 0, y = -12}},
    {"grass-1", {x = 0, y = -11}},
    {"grass-1", {x = 0, y = -10}},
    {"grass-3", {x = 0, y = -9}},
    {"grass-3", {x = 0, y = -8}},
    {"grass-3", {x = 0, y = -7}},
    {"water", {x = 0, y = -6}},
    {"water", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-1", {x = 0, y = 9}},
    {"grass-1", {x = 0, y = 10}},
    {"grass-1", {x = 0, y = 11}},
    {"grass-1", {x = 0, y = 12}},
    {"grass-1", {x = 0, y = 13}},
    {"grass-1", {x = 0, y = 14}},
    {"grass-1", {x = 1, y = -15}},
    {"grass-1", {x = 1, y = -14}},
    {"grass-1", {x = 1, y = -13}},
    {"grass-1", {x = 1, y = -12}},
    {"grass-1", {x = 1, y = -11}},
    {"grass-1", {x = 1, y = -10}},
    {"red-desert-0", {x = 1, y = -9}},
    {"red-desert-0", {x = 1, y = -8}},
    {"red-desert-0", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"red-desert-0", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-1", {x = 1, y = 9}},
    {"grass-1", {x = 1, y = 10}},
    {"grass-1", {x = 1, y = 11}},
    {"grass-1", {x = 1, y = 12}},
    {"grass-1", {x = 1, y = 13}},
    {"grass-1", {x = 1, y = 14}},
    {"grass-1", {x = 2, y = -15}},
    {"grass-1", {x = 2, y = -14}},
    {"grass-1", {x = 2, y = -13}},
    {"grass-1", {x = 2, y = -12}},
    {"grass-1", {x = 2, y = -11}},
    {"grass-1", {x = 2, y = -10}},
    {"red-desert-0", {x = 2, y = -9}},
    {"red-desert-0", {x = 2, y = -8}},
    {"red-desert-0", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"red-desert-0", {x = 2, y = -4}},
    {"red-desert-0", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"red-desert-0", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 2, y = 9}},
    {"grass-1", {x = 2, y = 10}},
    {"grass-1", {x = 2, y = 11}},
    {"grass-1", {x = 2, y = 12}},
    {"grass-1", {x = 2, y = 13}},
    {"grass-1", {x = 2, y = 14}},
    {"grass-1", {x = 3, y = -15}},
    {"grass-1", {x = 3, y = -14}},
    {"grass-1", {x = 3, y = -13}},
    {"grass-1", {x = 3, y = -12}},
    {"grass-1", {x = 3, y = -11}},
    {"grass-1", {x = 3, y = -10}},
    {"red-desert-0", {x = 3, y = -9}},
    {"red-desert-0", {x = 3, y = -8}},
    {"red-desert-0", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 3, y = 9}},
    {"grass-1", {x = 3, y = 10}},
    {"grass-1", {x = 3, y = 11}},
    {"red-desert-0", {x = 3, y = 12}},
    {"red-desert-0", {x = 3, y = 13}},
    {"grass-1", {x = 3, y = 14}},
    {"grass-1", {x = 4, y = -15}},
    {"grass-1", {x = 4, y = -14}},
    {"grass-1", {x = 4, y = -13}},
    {"grass-1", {x = 4, y = -12}},
    {"grass-1", {x = 4, y = -11}},
    {"grass-1", {x = 4, y = -10}},
    {"red-desert-0", {x = 4, y = -9}},
    {"red-desert-0", {x = 4, y = -8}},
    {"red-desert-0", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 4, y = 8}},
    {"grass-1", {x = 4, y = 9}},
    {"grass-1", {x = 4, y = 10}},
    {"grass-1", {x = 4, y = 11}},
    {"red-desert-0", {x = 4, y = 12}},
    {"red-desert-0", {x = 4, y = 13}},
    {"grass-1", {x = 4, y = 14}},
    {"grass-1", {x = 5, y = -15}},
    {"grass-1", {x = 5, y = -14}},
    {"grass-1", {x = 5, y = -13}},
    {"grass-1", {x = 5, y = -12}},
    {"grass-1", {x = 5, y = -11}},
    {"grass-1", {x = 5, y = -10}},
    {"grass-1", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 5, y = 8}},
    {"grass-1", {x = 5, y = 9}},
    {"grass-1", {x = 5, y = 10}},
    {"grass-1", {x = 5, y = 11}},
    {"red-desert-0", {x = 5, y = 12}},
    {"grass-1", {x = 5, y = 13}},
    {"grass-1", {x = 5, y = 14}},
    {"grass-3", {x = 6, y = -15}},
    {"grass-1", {x = 6, y = -14}},
    {"grass-1", {x = 6, y = -13}},
    {"grass-1", {x = 6, y = -12}},
    {"grass-1", {x = 6, y = -11}},
    {"grass-1", {x = 6, y = -10}},
    {"grass-1", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-3", {x = 6, y = 7}},
    {"grass-3", {x = 6, y = 8}},
    {"red-desert-0", {x = 6, y = 9}},
    {"red-desert-0", {x = 6, y = 10}},
    {"grass-1", {x = 6, y = 11}},
    {"grass-1", {x = 6, y = 12}},
    {"grass-1", {x = 6, y = 13}},
    {"grass-1", {x = 6, y = 14}},
    {"grass-3", {x = 7, y = -15}},
    {"grass-3", {x = 7, y = -14}},
    {"grass-1", {x = 7, y = -13}},
    {"grass-1", {x = 7, y = -12}},
    {"grass-1", {x = 7, y = -11}},
    {"grass-1", {x = 7, y = -10}},
    {"grass-1", {x = 7, y = -9}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-1", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
    {"red-desert-0", {x = 7, y = 8}},
    {"red-desert-0", {x = 7, y = 9}},
    {"red-desert-0", {x = 7, y = 10}},
    {"grass-1", {x = 7, y = 11}},
    {"grass-1", {x = 7, y = 12}},
    {"grass-1", {x = 7, y = 13}},
    {"grass-1", {x = 7, y = 14}},
    {"grass-3", {x = 8, y = -15}},
    {"grass-3", {x = 8, y = -14}},
    {"grass-3", {x = 8, y = -13}},
    {"grass-1", {x = 8, y = -12}},
    {"grass-1", {x = 8, y = -11}},
    {"grass-1", {x = 8, y = -10}},
    {"grass-1", {x = 8, y = -9}},
    {"grass-1", {x = 8, y = -8}},
    {"grass-1", {x = 8, y = -7}},
    {"grass-1", {x = 8, y = -6}},
    {"grass-1", {x = 8, y = -5}},
    {"grass-1", {x = 8, y = -4}},
    {"grass-1", {x = 8, y = -3}},
    {"grass-1", {x = 8, y = -2}},
    {"grass-1", {x = 8, y = -1}},
    {"grass-1", {x = 8, y = 0}},
    {"grass-1", {x = 8, y = 1}},
    {"grass-1", {x = 8, y = 2}},
    {"grass-1", {x = 8, y = 3}},
    {"grass-1", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-1", {x = 8, y = 6}},
    {"grass-1", {x = 8, y = 7}},
    {"grass-1", {x = 8, y = 8}},
    {"grass-1", {x = 8, y = 9}},
    {"grass-1", {x = 8, y = 10}},
    {"grass-1", {x = 8, y = 11}},
    {"grass-1", {x = 8, y = 12}},
    {"grass-1", {x = 8, y = 13}},
    {"grass-1", {x = 8, y = 14}},
    {"grass-3", {x = 9, y = -15}},
    {"grass-3", {x = 9, y = -14}},
    {"grass-3", {x = 9, y = -13}},
    {"grass-1", {x = 9, y = -12}},
    {"grass-1", {x = 9, y = -11}},
    {"grass-1", {x = 9, y = -10}},
    {"grass-1", {x = 9, y = -9}},
    {"grass-1", {x = 9, y = -8}},
    {"grass-1", {x = 9, y = -7}},
    {"grass-1", {x = 9, y = -6}},
    {"grass-1", {x = 9, y = -5}},
    {"grass-1", {x = 9, y = -4}},
    {"grass-1", {x = 9, y = -3}},
    {"grass-1", {x = 9, y = -2}},
    {"grass-1", {x = 9, y = -1}},
    {"grass-1", {x = 9, y = 0}},
    {"grass-1", {x = 9, y = 1}},
    {"grass-1", {x = 9, y = 2}},
    {"grass-1", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"grass-1", {x = 9, y = 5}},
    {"grass-1", {x = 9, y = 6}},
    {"grass-1", {x = 9, y = 7}},
    {"red-desert-0", {x = 9, y = 8}},
    {"red-desert-0", {x = 9, y = 9}},
    {"red-desert-0", {x = 9, y = 10}},
    {"grass-1", {x = 9, y = 11}},
    {"grass-1", {x = 9, y = 12}},
    {"grass-1", {x = 9, y = 13}},
    {"grass-1", {x = 9, y = 14}},
    {"grass-3", {x = 10, y = -15}},
    {"grass-3", {x = 10, y = -14}},
    {"grass-1", {x = 10, y = -13}},
    {"grass-1", {x = 10, y = -12}},
    {"grass-1", {x = 10, y = -11}},
    {"grass-1", {x = 10, y = -10}},
    {"grass-1", {x = 10, y = -9}},
    {"grass-1", {x = 10, y = -8}},
    {"grass-1", {x = 10, y = -7}},
    {"grass-1", {x = 10, y = -6}},
    {"grass-1", {x = 10, y = -5}},
    {"grass-1", {x = 10, y = -4}},
    {"grass-1", {x = 10, y = -3}},
    {"grass-1", {x = 10, y = -2}},
    {"grass-1", {x = 10, y = -1}},
    {"grass-1", {x = 10, y = 0}},
    {"grass-1", {x = 10, y = 1}},
    {"grass-1", {x = 10, y = 2}},
    {"grass-1", {x = 10, y = 3}},
    {"grass-1", {x = 10, y = 4}},
    {"grass-1", {x = 10, y = 5}},
    {"grass-1", {x = 10, y = 6}},
    {"grass-1", {x = 10, y = 7}},
    {"red-desert-0", {x = 10, y = 8}},
    {"red-desert-0", {x = 10, y = 9}},
    {"red-desert-0", {x = 10, y = 10}},
    {"grass-1", {x = 10, y = 11}},
    {"grass-1", {x = 10, y = 12}},
    {"grass-1", {x = 10, y = 13}},
    {"grass-1", {x = 10, y = 14}},
    {"grass-3", {x = 11, y = -15}},
    {"grass-3", {x = 11, y = -14}},
    {"grass-1", {x = 11, y = -13}},
    {"grass-1", {x = 11, y = -12}},
    {"grass-1", {x = 11, y = -11}},
    {"grass-1", {x = 11, y = -10}},
    {"grass-1", {x = 11, y = -9}},
    {"grass-1", {x = 11, y = -8}},
    {"grass-1", {x = 11, y = -7}},
    {"grass-1", {x = 11, y = -6}},
    {"grass-1", {x = 11, y = -5}},
    {"grass-1", {x = 11, y = -4}},
    {"grass-1", {x = 11, y = -3}},
    {"grass-1", {x = 11, y = -2}},
    {"grass-1", {x = 11, y = -1}},
    {"grass-1", {x = 11, y = 0}},
    {"grass-1", {x = 11, y = 1}},
    {"grass-1", {x = 11, y = 2}},
    {"grass-1", {x = 11, y = 3}},
    {"grass-1", {x = 11, y = 4}},
    {"grass-1", {x = 11, y = 5}},
    {"grass-1", {x = 11, y = 6}},
    {"grass-1", {x = 11, y = 7}},
    {"grass-1", {x = 11, y = 8}},
    {"grass-1", {x = 11, y = 9}},
    {"grass-1", {x = 11, y = 10}},
    {"grass-1", {x = 11, y = 11}},
    {"grass-1", {x = 11, y = 12}},
    {"grass-1", {x = 11, y = 13}},
    {"grass-1", {x = 11, y = 14}},
    {"grass-3", {x = 12, y = -15}},
    {"grass-3", {x = 12, y = -14}},
    {"red-desert-0", {x = 12, y = -13}},
    {"red-desert-0", {x = 12, y = -12}},
    {"red-desert-0", {x = 12, y = -11}},
    {"grass-1", {x = 12, y = -10}},
    {"grass-1", {x = 12, y = -9}},
    {"grass-1", {x = 12, y = -8}},
    {"grass-1", {x = 12, y = -7}},
    {"grass-1", {x = 12, y = -6}},
    {"grass-1", {x = 12, y = -5}},
    {"grass-1", {x = 12, y = -4}},
    {"grass-1", {x = 12, y = -3}},
    {"grass-1", {x = 12, y = -2}},
    {"grass-1", {x = 12, y = -1}},
    {"grass-1", {x = 12, y = 0}},
    {"grass-3", {x = 12, y = 1}},
    {"grass-3", {x = 12, y = 2}},
    {"red-desert-0", {x = 12, y = 3}},
    {"grass-1", {x = 12, y = 4}},
    {"grass-1", {x = 12, y = 5}},
    {"grass-1", {x = 12, y = 6}},
    {"grass-1", {x = 12, y = 7}},
    {"grass-1", {x = 12, y = 8}},
    {"grass-1", {x = 12, y = 9}},
    {"grass-1", {x = 12, y = 10}},
    {"grass-1", {x = 12, y = 11}},
    {"grass-1", {x = 12, y = 12}},
    {"grass-1", {x = 12, y = 13}},
    {"grass-1", {x = 12, y = 14}},
    {"grass-3", {x = 13, y = -15}},
    {"grass-3", {x = 13, y = -14}},
    {"red-desert-0", {x = 13, y = -13}},
    {"grass-3", {x = 13, y = -12}},
    {"grass-3", {x = 13, y = -11}},
    {"grass-1", {x = 13, y = -10}},
    {"grass-1", {x = 13, y = -9}},
    {"grass-1", {x = 13, y = -8}},
    {"grass-1", {x = 13, y = -7}},
    {"grass-1", {x = 13, y = -6}},
    {"grass-1", {x = 13, y = -5}},
    {"grass-1", {x = 13, y = -4}},
    {"grass-1", {x = 13, y = -3}},
    {"grass-1", {x = 13, y = -2}},
    {"grass-1", {x = 13, y = -1}},
    {"grass-1", {x = 13, y = 0}},
    {"red-desert-0", {x = 13, y = 1}},
    {"red-desert-0", {x = 13, y = 2}},
    {"red-desert-0", {x = 13, y = 3}},
    {"grass-1", {x = 13, y = 4}},
    {"grass-1", {x = 13, y = 5}},
    {"grass-1", {x = 13, y = 6}},
    {"grass-1", {x = 13, y = 7}},
    {"grass-1", {x = 13, y = 8}},
    {"grass-1", {x = 13, y = 9}},
    {"grass-1", {x = 13, y = 10}},
    {"grass-1", {x = 13, y = 11}},
    {"grass-1", {x = 13, y = 12}},
    {"grass-1", {x = 13, y = 13}},
    {"grass-1", {x = 13, y = 14}},
    {"grass-3", {x = 14, y = -15}},
    {"grass-3", {x = 14, y = -14}},
    {"red-desert-0", {x = 14, y = -13}},
    {"grass-3", {x = 14, y = -12}},
    {"grass-1", {x = 14, y = -11}},
    {"grass-1", {x = 14, y = -10}},
    {"grass-1", {x = 14, y = -9}},
    {"grass-1", {x = 14, y = -8}},
    {"grass-1", {x = 14, y = -7}},
    {"grass-1", {x = 14, y = -6}},
    {"grass-1", {x = 14, y = -5}},
    {"grass-1", {x = 14, y = -4}},
    {"grass-1", {x = 14, y = -3}},
    {"grass-1", {x = 14, y = -2}},
    {"grass-1", {x = 14, y = -1}},
    {"grass-1", {x = 14, y = 0}},
    {"grass-1", {x = 14, y = 1}},
    {"grass-1", {x = 14, y = 2}},
    {"grass-1", {x = 14, y = 3}},
    {"grass-1", {x = 14, y = 4}},
    {"grass-1", {x = 14, y = 5}},
    {"grass-1", {x = 14, y = 6}},
    {"grass-1", {x = 14, y = 7}},
    {"grass-1", {x = 14, y = 8}},
    {"grass-1", {x = 14, y = 9}},
    {"grass-1", {x = 14, y = 10}},
    {"grass-1", {x = 14, y = 11}},
    {"grass-1", {x = 14, y = 12}},
    {"grass-1", {x = 14, y = 13}},
    {"grass-1", {x = 14, y = 14}},
  }
}
