return
{
  entities =
  {
    {"stone-wall", {x = -14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -12.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = -13}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -13.5}, {force = "enemy", }},
    {"laser-turret", {x = 0, y = -13}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -13.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -13}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -11.5}, {force = "enemy", }},
    {"radar", {x = -8.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -11.5}, {force = "enemy", }},
    {"purple-crystal-gen", {x = 8.5, y = -11}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -6.5}, {force = "enemy", }},
    {"substation", {x = -4, y = -6}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -7.5}, {force = "enemy", }},
    {"inserter", {x = -0.5, y = -6.5}, {dir = "west", force = "enemy", }},
    {"logistic-chest-requester", {x = -1.5, y = -6.5}, {force = "enemy", items = {["artillery-shell"] = 6}, }},
    {"logistic-chest-requester", {x = -1.5, y = -7.5}, {force = "enemy", items = {["artillery-shell"] = 4}, }},
    {"artillery-turret", {x = 1.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -7.5}, {force = "enemy", }},
    {"substation", {x = 5, y = -6}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -4.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = -5}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -4.5}, {force = "enemy", }},
    {"stack-inserter", {x = -0.5, y = -5.5}, {dir = "west", force = "enemy", }},
    {"logistic-chest-requester", {x = -1.5, y = -5.5}, {force = "enemy", items = {["artillery-shell"] = 11}, }},
    {"stone-wall", {x = -1.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -4.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -5.5}, {force = "enemy", }},
    {"gate", {x = -15.5, y = -2.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = -8.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -9.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -6.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -7.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -3.5}, {force = "enemy", }},
    {"aliengenerator", {x = 0.5, y = -2}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -2.5}, {force = "enemy", }},
    {"gate", {x = 7.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = 9.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 8.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 10.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = 15.5, y = -2.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = -15.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = -15.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = 15.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = 15.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = -15.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = -14.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = -8.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -9.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -6.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -7.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = -5.5, y = 0.5}, {items = {["battery-mk2-equipment"] = 1, ["energy-shield-equipment"] = 1, ["uranium-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -5.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 1.5}, {force = "enemy", }},
    {"steel-chest", {x = 6.5, y = 0.5}, {items = {["atomic-bomb"] = 10, ["discharge-defense-equipment"] = 1, ["solar-panel-equipment"] = 1}, }},
    {"gate", {x = 7.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = 9.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 8.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 10.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = 15.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = 14.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 3.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = 3}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 2.5}, {force = "enemy", }},
    {"substation", {x = -4, y = 4}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 2.5}, {force = "enemy", }},
    {"artillery-turret", {x = -0.5, y = 4.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 2.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 3.5}, {}},
    {"stone-wall", {x = 3.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 2.5}, {force = "enemy", }},
    {"substation", {x = 5, y = 4}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 2.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = 3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 5.5}, {force = "enemy", }},
    {"fast-inserter", {x = 1.5, y = 4.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 5.5}, {}},
    {"express-transport-belt", {x = 2.5, y = 4.5}, {}},
    {"stone-wall", {x = 3.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 7.5}, {force = "enemy", }},
    {"roboport", {x = 0, y = 9}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"aliencon-robot", {x = 0.1, y = 7.96}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.18, y = 7.96}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.21, y = 7.96}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.33, y = 7.99}, {force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 6.5}, {}},
    {"express-transport-belt", {x = 2.5, y = 7.5}, {}},
    {"radar", {x = 9.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -4.5, y = 9.5}, {force = "enemy", items = {["artillery-shell"] = 28, ["repair-pack"] = 2000}, }},
    {"steel-chest", {x = -3.5, y = 9.5}, {items = {["production-science-pack"] = 200}, }},
    {"aliencon-robot", {x = -0.58, y = 8.25}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.3, y = 8.11}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.07, y = 8.02}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.64, y = 8.08}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.06, y = 8.16}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.4, y = 8.22}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.6, y = 8.25}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.74, y = 8.28}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.83, y = 8.28}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.94, y = 8.3}, {force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 8.5}, {}},
    {"express-transport-belt", {x = 2.5, y = 9.5}, {}},
    {"aliencon-robot", {x = 2.02, y = 8.36}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.17, y = 8.45}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.31, y = 8.62}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.42, y = 8.73}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.48, y = 8.84}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.5, y = 8.93}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.62, y = 9.13}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.73, y = 9.32}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.82, y = 9.55}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.84, y = 9.89}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 5.5, y = 9.5}, {force = "enemy", items = {["artillery-shell"] = 28, ["repair-pack"] = 2000}, }},
    {"steel-chest", {x = 4.5, y = 9.5}, {items = {["utility-science-pack"] = 200}, }},
    {"logistic-chest-passive-provider", {x = 6.5, y = 9.5}, {force = "enemy", items = {["artillery-shell"] = 48}, }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 11.5}, {force = "enemy", }},
    {"green-crystal-gen", {x = -8.5, y = 10}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 11.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 10.5}, {}},
    {"express-transport-belt", {x = 2.5, y = 11.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = 11.5}, {dir = "west", force = "enemy", }},
    {"aliencon-robot", {x = 2.84, y = 10.12}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.84, y = 10.34}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.84, y = 10.63}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.82, y = 10.85}, {force = "enemy", }},
    {"express-transport-belt", {x = 4.5, y = 11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = 5.5, y = 11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = 6.5, y = 11.5}, {dir = "west", force = "enemy", }},
    {"stack-inserter", {x = 6.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 0, y = 13}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 13.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = 13}, {dir = "south", force = "enemy", dmg = {dmg = 500}, }},
    {"stone-wall", {x = 14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 14.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -16, y = -16}},
    {"grass-1", {x = -16, y = -15}},
    {"grass-1", {x = -16, y = -14}},
    {"grass-1", {x = -16, y = -13}},
    {"grass-1", {x = -16, y = -12}},
    {"grass-1", {x = -16, y = -11}},
    {"grass-1", {x = -16, y = -10}},
    {"grass-1", {x = -16, y = -9}},
    {"grass-1", {x = -16, y = -8}},
    {"grass-1", {x = -16, y = -7}},
    {"grass-1", {x = -16, y = -6}},
    {"grass-1", {x = -16, y = -5}},
    {"grass-1", {x = -16, y = -4}},
    {"grass-1", {x = -16, y = -3}},
    {"grass-1", {x = -16, y = -2}},
    {"grass-1", {x = -16, y = -1}},
    {"grass-1", {x = -16, y = 0}},
    {"grass-1", {x = -16, y = 1}},
    {"grass-1", {x = -16, y = 2}},
    {"grass-1", {x = -16, y = 3}},
    {"grass-1", {x = -16, y = 4}},
    {"grass-1", {x = -16, y = 5}},
    {"grass-1", {x = -16, y = 6}},
    {"grass-1", {x = -16, y = 7}},
    {"grass-1", {x = -16, y = 8}},
    {"grass-1", {x = -16, y = 9}},
    {"grass-1", {x = -16, y = 10}},
    {"grass-1", {x = -16, y = 11}},
    {"grass-1", {x = -16, y = 12}},
    {"grass-1", {x = -16, y = 13}},
    {"grass-1", {x = -16, y = 14}},
    {"grass-1", {x = -16, y = 15}},
    {"grass-1", {x = -15, y = -16}},
    {"grass-1", {x = -15, y = -15}},
    {"grass-1", {x = -15, y = -14}},
    {"grass-1", {x = -15, y = -13}},
    {"grass-1", {x = -15, y = -12}},
    {"grass-1", {x = -15, y = -11}},
    {"grass-1", {x = -15, y = -10}},
    {"grass-1", {x = -15, y = -9}},
    {"grass-1", {x = -15, y = -8}},
    {"grass-1", {x = -15, y = -7}},
    {"grass-1", {x = -15, y = -6}},
    {"grass-1", {x = -15, y = -5}},
    {"grass-1", {x = -15, y = -4}},
    {"grass-1", {x = -15, y = -3}},
    {"grass-1", {x = -15, y = -2}},
    {"grass-1", {x = -15, y = -1}},
    {"grass-1", {x = -15, y = 0}},
    {"grass-1", {x = -15, y = 1}},
    {"grass-1", {x = -15, y = 2}},
    {"grass-1", {x = -15, y = 3}},
    {"grass-1", {x = -15, y = 4}},
    {"grass-1", {x = -15, y = 5}},
    {"grass-1", {x = -15, y = 6}},
    {"grass-1", {x = -15, y = 7}},
    {"grass-1", {x = -15, y = 8}},
    {"grass-1", {x = -15, y = 9}},
    {"grass-1", {x = -15, y = 10}},
    {"grass-1", {x = -15, y = 11}},
    {"grass-1", {x = -15, y = 12}},
    {"grass-1", {x = -15, y = 13}},
    {"grass-1", {x = -15, y = 14}},
    {"grass-1", {x = -15, y = 15}},
    {"grass-1", {x = -14, y = -16}},
    {"grass-1", {x = -14, y = -15}},
    {"grass-1", {x = -14, y = -14}},
    {"grass-1", {x = -14, y = -13}},
    {"grass-1", {x = -14, y = -12}},
    {"grass-1", {x = -14, y = -11}},
    {"grass-1", {x = -14, y = -10}},
    {"grass-1", {x = -14, y = -9}},
    {"grass-1", {x = -14, y = -8}},
    {"grass-1", {x = -14, y = -7}},
    {"grass-1", {x = -14, y = -6}},
    {"grass-1", {x = -14, y = -5}},
    {"grass-1", {x = -14, y = -4}},
    {"refined-concrete", {x = -14, y = -3}},
    {"refined-concrete", {x = -14, y = -2}},
    {"refined-concrete", {x = -14, y = -1}},
    {"refined-concrete", {x = -14, y = 0}},
    {"grass-1", {x = -14, y = 1}},
    {"grass-1", {x = -14, y = 2}},
    {"grass-1", {x = -14, y = 3}},
    {"grass-1", {x = -14, y = 4}},
    {"grass-1", {x = -14, y = 5}},
    {"grass-1", {x = -14, y = 6}},
    {"grass-1", {x = -14, y = 7}},
    {"grass-1", {x = -14, y = 8}},
    {"grass-1", {x = -14, y = 9}},
    {"grass-1", {x = -14, y = 10}},
    {"grass-1", {x = -14, y = 11}},
    {"grass-1", {x = -14, y = 12}},
    {"grass-1", {x = -14, y = 13}},
    {"grass-1", {x = -14, y = 14}},
    {"grass-1", {x = -14, y = 15}},
    {"grass-1", {x = -13, y = -16}},
    {"grass-1", {x = -13, y = -15}},
    {"grass-1", {x = -13, y = -14}},
    {"grass-1", {x = -13, y = -13}},
    {"grass-1", {x = -13, y = -12}},
    {"grass-1", {x = -13, y = -11}},
    {"grass-1", {x = -13, y = -10}},
    {"grass-1", {x = -13, y = -9}},
    {"grass-1", {x = -13, y = -8}},
    {"grass-1", {x = -13, y = -7}},
    {"grass-1", {x = -13, y = -6}},
    {"grass-1", {x = -13, y = -5}},
    {"grass-1", {x = -13, y = -4}},
    {"refined-concrete", {x = -13, y = -3}},
    {"refined-concrete", {x = -13, y = -2}},
    {"refined-concrete", {x = -13, y = -1}},
    {"refined-concrete", {x = -13, y = 0}},
    {"grass-1", {x = -13, y = 1}},
    {"grass-1", {x = -13, y = 2}},
    {"grass-1", {x = -13, y = 3}},
    {"grass-1", {x = -13, y = 4}},
    {"grass-1", {x = -13, y = 5}},
    {"grass-1", {x = -13, y = 6}},
    {"grass-1", {x = -13, y = 7}},
    {"grass-1", {x = -13, y = 8}},
    {"grass-1", {x = -13, y = 9}},
    {"grass-1", {x = -13, y = 10}},
    {"grass-1", {x = -13, y = 11}},
    {"grass-1", {x = -13, y = 12}},
    {"grass-1", {x = -13, y = 13}},
    {"grass-1", {x = -13, y = 14}},
    {"grass-1", {x = -13, y = 15}},
    {"grass-1", {x = -12, y = -16}},
    {"grass-1", {x = -12, y = -15}},
    {"grass-1", {x = -12, y = -14}},
    {"grass-1", {x = -12, y = -13}},
    {"grass-1", {x = -12, y = -12}},
    {"grass-1", {x = -12, y = -11}},
    {"grass-1", {x = -12, y = -10}},
    {"grass-1", {x = -12, y = -9}},
    {"grass-1", {x = -12, y = -8}},
    {"grass-1", {x = -12, y = -7}},
    {"grass-1", {x = -12, y = -6}},
    {"grass-1", {x = -12, y = -5}},
    {"grass-1", {x = -12, y = -4}},
    {"refined-concrete", {x = -12, y = -3}},
    {"refined-concrete", {x = -12, y = -2}},
    {"refined-concrete", {x = -12, y = -1}},
    {"refined-concrete", {x = -12, y = 0}},
    {"grass-1", {x = -12, y = 1}},
    {"grass-1", {x = -12, y = 2}},
    {"grass-1", {x = -12, y = 3}},
    {"grass-1", {x = -12, y = 4}},
    {"grass-1", {x = -12, y = 5}},
    {"grass-1", {x = -12, y = 6}},
    {"grass-1", {x = -12, y = 7}},
    {"grass-1", {x = -12, y = 8}},
    {"grass-1", {x = -12, y = 9}},
    {"grass-1", {x = -12, y = 10}},
    {"grass-1", {x = -12, y = 11}},
    {"grass-1", {x = -12, y = 12}},
    {"grass-1", {x = -12, y = 13}},
    {"grass-1", {x = -12, y = 14}},
    {"grass-1", {x = -12, y = 15}},
    {"grass-1", {x = -11, y = -16}},
    {"grass-1", {x = -11, y = -15}},
    {"grass-1", {x = -11, y = -14}},
    {"grass-1", {x = -11, y = -13}},
    {"grass-1", {x = -11, y = -12}},
    {"grass-1", {x = -11, y = -11}},
    {"grass-1", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-1", {x = -11, y = -5}},
    {"grass-1", {x = -11, y = -4}},
    {"refined-concrete", {x = -11, y = -3}},
    {"refined-concrete", {x = -11, y = -2}},
    {"refined-concrete", {x = -11, y = -1}},
    {"refined-concrete", {x = -11, y = 0}},
    {"grass-1", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-1", {x = -11, y = 4}},
    {"grass-1", {x = -11, y = 5}},
    {"grass-1", {x = -11, y = 6}},
    {"grass-1", {x = -11, y = 7}},
    {"grass-1", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"grass-1", {x = -11, y = 10}},
    {"grass-1", {x = -11, y = 11}},
    {"grass-1", {x = -11, y = 12}},
    {"grass-1", {x = -11, y = 13}},
    {"grass-1", {x = -11, y = 14}},
    {"grass-1", {x = -11, y = 15}},
    {"grass-1", {x = -10, y = -16}},
    {"grass-1", {x = -10, y = -15}},
    {"grass-1", {x = -10, y = -14}},
    {"grass-1", {x = -10, y = -13}},
    {"grass-1", {x = -10, y = -12}},
    {"refined-concrete", {x = -10, y = -11}},
    {"refined-concrete", {x = -10, y = -10}},
    {"refined-concrete", {x = -10, y = -9}},
    {"refined-concrete", {x = -10, y = -8}},
    {"refined-concrete", {x = -10, y = -7}},
    {"refined-concrete", {x = -10, y = -6}},
    {"refined-concrete", {x = -10, y = -5}},
    {"refined-concrete", {x = -10, y = -4}},
    {"refined-concrete", {x = -10, y = -3}},
    {"refined-concrete", {x = -10, y = -2}},
    {"refined-concrete", {x = -10, y = -1}},
    {"refined-concrete", {x = -10, y = 0}},
    {"refined-concrete", {x = -10, y = 1}},
    {"refined-concrete", {x = -10, y = 2}},
    {"refined-concrete", {x = -10, y = 3}},
    {"refined-concrete", {x = -10, y = 4}},
    {"refined-concrete", {x = -10, y = 5}},
    {"refined-concrete", {x = -10, y = 6}},
    {"refined-concrete", {x = -10, y = 7}},
    {"refined-concrete", {x = -10, y = 8}},
    {"refined-concrete", {x = -10, y = 9}},
    {"grass-1", {x = -10, y = 10}},
    {"grass-1", {x = -10, y = 11}},
    {"grass-1", {x = -10, y = 12}},
    {"grass-1", {x = -10, y = 13}},
    {"grass-1", {x = -10, y = 14}},
    {"grass-1", {x = -10, y = 15}},
    {"grass-1", {x = -9, y = -16}},
    {"grass-1", {x = -9, y = -15}},
    {"grass-1", {x = -9, y = -14}},
    {"grass-1", {x = -9, y = -13}},
    {"grass-1", {x = -9, y = -12}},
    {"refined-concrete", {x = -9, y = -11}},
    {"refined-concrete", {x = -9, y = -10}},
    {"refined-concrete", {x = -9, y = -9}},
    {"refined-concrete", {x = -9, y = -8}},
    {"refined-concrete", {x = -9, y = -7}},
    {"refined-concrete", {x = -9, y = -6}},
    {"refined-concrete", {x = -9, y = -5}},
    {"refined-concrete", {x = -9, y = -4}},
    {"refined-concrete", {x = -9, y = -3}},
    {"refined-concrete", {x = -9, y = -2}},
    {"refined-concrete", {x = -9, y = -1}},
    {"refined-concrete", {x = -9, y = 0}},
    {"refined-concrete", {x = -9, y = 1}},
    {"refined-concrete", {x = -9, y = 2}},
    {"refined-concrete", {x = -9, y = 3}},
    {"refined-concrete", {x = -9, y = 4}},
    {"refined-concrete", {x = -9, y = 5}},
    {"refined-concrete", {x = -9, y = 6}},
    {"refined-concrete", {x = -9, y = 7}},
    {"refined-concrete", {x = -9, y = 8}},
    {"refined-concrete", {x = -9, y = 9}},
    {"grass-1", {x = -9, y = 10}},
    {"grass-1", {x = -9, y = 11}},
    {"grass-1", {x = -9, y = 12}},
    {"grass-1", {x = -9, y = 13}},
    {"grass-1", {x = -9, y = 14}},
    {"grass-1", {x = -9, y = 15}},
    {"grass-1", {x = -8, y = -16}},
    {"grass-1", {x = -8, y = -15}},
    {"grass-1", {x = -8, y = -14}},
    {"grass-1", {x = -8, y = -13}},
    {"grass-1", {x = -8, y = -12}},
    {"refined-concrete", {x = -8, y = -11}},
    {"refined-concrete", {x = -8, y = -10}},
    {"refined-concrete", {x = -8, y = -9}},
    {"refined-concrete", {x = -8, y = -8}},
    {"refined-concrete", {x = -8, y = -7}},
    {"refined-concrete", {x = -8, y = -6}},
    {"refined-concrete", {x = -8, y = -5}},
    {"refined-concrete", {x = -8, y = -4}},
    {"refined-concrete", {x = -8, y = -3}},
    {"refined-concrete", {x = -8, y = -2}},
    {"refined-concrete", {x = -8, y = -1}},
    {"refined-concrete", {x = -8, y = 0}},
    {"refined-concrete", {x = -8, y = 1}},
    {"refined-concrete", {x = -8, y = 2}},
    {"refined-concrete", {x = -8, y = 3}},
    {"refined-concrete", {x = -8, y = 4}},
    {"refined-concrete", {x = -8, y = 5}},
    {"refined-concrete", {x = -8, y = 6}},
    {"refined-concrete", {x = -8, y = 7}},
    {"refined-concrete", {x = -8, y = 8}},
    {"refined-concrete", {x = -8, y = 9}},
    {"grass-1", {x = -8, y = 10}},
    {"grass-1", {x = -8, y = 11}},
    {"grass-1", {x = -8, y = 12}},
    {"grass-1", {x = -8, y = 13}},
    {"grass-1", {x = -8, y = 14}},
    {"grass-1", {x = -8, y = 15}},
    {"grass-1", {x = -7, y = -16}},
    {"grass-1", {x = -7, y = -15}},
    {"grass-1", {x = -7, y = -14}},
    {"grass-1", {x = -7, y = -13}},
    {"grass-1", {x = -7, y = -12}},
    {"refined-concrete", {x = -7, y = -11}},
    {"refined-concrete", {x = -7, y = -10}},
    {"refined-concrete", {x = -7, y = -9}},
    {"refined-concrete", {x = -7, y = -8}},
    {"refined-concrete", {x = -7, y = -7}},
    {"refined-concrete", {x = -7, y = -6}},
    {"refined-concrete", {x = -7, y = -5}},
    {"refined-concrete", {x = -7, y = -4}},
    {"refined-concrete", {x = -7, y = -3}},
    {"refined-concrete", {x = -7, y = -2}},
    {"refined-concrete", {x = -7, y = -1}},
    {"refined-concrete", {x = -7, y = 0}},
    {"refined-concrete", {x = -7, y = 1}},
    {"refined-concrete", {x = -7, y = 2}},
    {"refined-concrete", {x = -7, y = 3}},
    {"refined-concrete", {x = -7, y = 4}},
    {"refined-concrete", {x = -7, y = 5}},
    {"refined-concrete", {x = -7, y = 6}},
    {"refined-concrete", {x = -7, y = 7}},
    {"refined-concrete", {x = -7, y = 8}},
    {"refined-concrete", {x = -7, y = 9}},
    {"grass-1", {x = -7, y = 10}},
    {"grass-1", {x = -7, y = 11}},
    {"grass-1", {x = -7, y = 12}},
    {"grass-1", {x = -7, y = 13}},
    {"grass-1", {x = -7, y = 14}},
    {"grass-1", {x = -7, y = 15}},
    {"grass-1", {x = -6, y = -16}},
    {"grass-1", {x = -6, y = -15}},
    {"grass-1", {x = -6, y = -14}},
    {"grass-1", {x = -6, y = -13}},
    {"grass-1", {x = -6, y = -12}},
    {"refined-concrete", {x = -6, y = -11}},
    {"refined-concrete", {x = -6, y = -10}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-1", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"refined-concrete", {x = -6, y = 7}},
    {"refined-concrete", {x = -6, y = 8}},
    {"refined-concrete", {x = -6, y = 9}},
    {"grass-1", {x = -6, y = 10}},
    {"grass-1", {x = -6, y = 11}},
    {"grass-1", {x = -6, y = 12}},
    {"grass-1", {x = -6, y = 13}},
    {"grass-1", {x = -6, y = 14}},
    {"grass-1", {x = -6, y = 15}},
    {"grass-1", {x = -5, y = -16}},
    {"grass-1", {x = -5, y = -15}},
    {"grass-1", {x = -5, y = -14}},
    {"grass-1", {x = -5, y = -13}},
    {"grass-1", {x = -5, y = -12}},
    {"refined-concrete", {x = -5, y = -11}},
    {"refined-concrete", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"refined-concrete", {x = -5, y = 7}},
    {"refined-concrete", {x = -5, y = 8}},
    {"refined-concrete", {x = -5, y = 9}},
    {"grass-1", {x = -5, y = 10}},
    {"grass-1", {x = -5, y = 11}},
    {"grass-1", {x = -5, y = 12}},
    {"grass-1", {x = -5, y = 13}},
    {"grass-1", {x = -5, y = 14}},
    {"grass-1", {x = -5, y = 15}},
    {"grass-1", {x = -4, y = -16}},
    {"grass-1", {x = -4, y = -15}},
    {"grass-1", {x = -4, y = -14}},
    {"grass-1", {x = -4, y = -13}},
    {"grass-1", {x = -4, y = -12}},
    {"refined-concrete", {x = -4, y = -11}},
    {"refined-concrete", {x = -4, y = -10}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"grass-1", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"refined-concrete", {x = -4, y = 7}},
    {"refined-concrete", {x = -4, y = 8}},
    {"refined-concrete", {x = -4, y = 9}},
    {"grass-1", {x = -4, y = 10}},
    {"grass-1", {x = -4, y = 11}},
    {"grass-1", {x = -4, y = 12}},
    {"grass-1", {x = -4, y = 13}},
    {"grass-1", {x = -4, y = 14}},
    {"grass-1", {x = -4, y = 15}},
    {"grass-1", {x = -3, y = -16}},
    {"grass-1", {x = -3, y = -15}},
    {"grass-1", {x = -3, y = -14}},
    {"grass-1", {x = -3, y = -13}},
    {"grass-1", {x = -3, y = -12}},
    {"refined-concrete", {x = -3, y = -11}},
    {"refined-concrete", {x = -3, y = -10}},
    {"grass-1", {x = -3, y = -9}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"refined-concrete", {x = -3, y = 7}},
    {"refined-concrete", {x = -3, y = 8}},
    {"refined-concrete", {x = -3, y = 9}},
    {"grass-1", {x = -3, y = 10}},
    {"grass-1", {x = -3, y = 11}},
    {"grass-1", {x = -3, y = 12}},
    {"grass-1", {x = -3, y = 13}},
    {"grass-1", {x = -3, y = 14}},
    {"grass-1", {x = -3, y = 15}},
    {"grass-1", {x = -2, y = -16}},
    {"grass-1", {x = -2, y = -15}},
    {"grass-1", {x = -2, y = -14}},
    {"grass-1", {x = -2, y = -13}},
    {"grass-1", {x = -2, y = -12}},
    {"refined-concrete", {x = -2, y = -11}},
    {"refined-concrete", {x = -2, y = -10}},
    {"refined-concrete", {x = -2, y = -9}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-1", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"refined-concrete", {x = -2, y = 7}},
    {"refined-concrete", {x = -2, y = 8}},
    {"refined-concrete", {x = -2, y = 9}},
    {"grass-1", {x = -2, y = 10}},
    {"grass-1", {x = -2, y = 11}},
    {"grass-1", {x = -2, y = 12}},
    {"grass-1", {x = -2, y = 13}},
    {"grass-1", {x = -2, y = 14}},
    {"grass-1", {x = -2, y = 15}},
    {"grass-1", {x = -1, y = -16}},
    {"grass-1", {x = -1, y = -15}},
    {"grass-1", {x = -1, y = -14}},
    {"grass-1", {x = -1, y = -13}},
    {"grass-1", {x = -1, y = -12}},
    {"refined-concrete", {x = -1, y = -11}},
    {"refined-concrete", {x = -1, y = -10}},
    {"refined-concrete", {x = -1, y = -9}},
    {"refined-concrete", {x = -1, y = -8}},
    {"grass-1", {x = -1, y = -7}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"refined-concrete", {x = -1, y = 5}},
    {"refined-concrete", {x = -1, y = 6}},
    {"refined-concrete", {x = -1, y = 7}},
    {"refined-concrete", {x = -1, y = 8}},
    {"refined-concrete", {x = -1, y = 9}},
    {"grass-1", {x = -1, y = 10}},
    {"grass-1", {x = -1, y = 11}},
    {"grass-1", {x = -1, y = 12}},
    {"grass-1", {x = -1, y = 13}},
    {"grass-1", {x = -1, y = 14}},
    {"grass-1", {x = -1, y = 15}},
    {"grass-1", {x = 0, y = -16}},
    {"grass-1", {x = 0, y = -15}},
    {"grass-1", {x = 0, y = -14}},
    {"grass-1", {x = 0, y = -13}},
    {"grass-1", {x = 0, y = -12}},
    {"refined-concrete", {x = 0, y = -11}},
    {"refined-concrete", {x = 0, y = -10}},
    {"refined-concrete", {x = 0, y = -9}},
    {"refined-concrete", {x = 0, y = -8}},
    {"grass-1", {x = 0, y = -7}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"refined-concrete", {x = 0, y = 5}},
    {"refined-concrete", {x = 0, y = 6}},
    {"refined-concrete", {x = 0, y = 7}},
    {"refined-concrete", {x = 0, y = 8}},
    {"refined-concrete", {x = 0, y = 9}},
    {"grass-1", {x = 0, y = 10}},
    {"grass-1", {x = 0, y = 11}},
    {"grass-1", {x = 0, y = 12}},
    {"grass-1", {x = 0, y = 13}},
    {"grass-1", {x = 0, y = 14}},
    {"grass-1", {x = 0, y = 15}},
    {"grass-1", {x = 1, y = -16}},
    {"grass-1", {x = 1, y = -15}},
    {"grass-1", {x = 1, y = -14}},
    {"grass-1", {x = 1, y = -13}},
    {"grass-1", {x = 1, y = -12}},
    {"refined-concrete", {x = 1, y = -11}},
    {"refined-concrete", {x = 1, y = -10}},
    {"refined-concrete", {x = 1, y = -9}},
    {"refined-concrete", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"refined-concrete", {x = 1, y = 5}},
    {"refined-concrete", {x = 1, y = 6}},
    {"refined-concrete", {x = 1, y = 7}},
    {"refined-concrete", {x = 1, y = 8}},
    {"refined-concrete", {x = 1, y = 9}},
    {"grass-1", {x = 1, y = 10}},
    {"grass-1", {x = 1, y = 11}},
    {"grass-1", {x = 1, y = 12}},
    {"grass-1", {x = 1, y = 13}},
    {"grass-1", {x = 1, y = 14}},
    {"grass-1", {x = 1, y = 15}},
    {"grass-1", {x = 2, y = -16}},
    {"grass-1", {x = 2, y = -15}},
    {"grass-1", {x = 2, y = -14}},
    {"grass-1", {x = 2, y = -13}},
    {"grass-1", {x = 2, y = -12}},
    {"refined-concrete", {x = 2, y = -11}},
    {"refined-concrete", {x = 2, y = -10}},
    {"refined-concrete", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"refined-concrete", {x = 2, y = 7}},
    {"refined-concrete", {x = 2, y = 8}},
    {"refined-concrete", {x = 2, y = 9}},
    {"grass-1", {x = 2, y = 10}},
    {"grass-1", {x = 2, y = 11}},
    {"grass-1", {x = 2, y = 12}},
    {"grass-1", {x = 2, y = 13}},
    {"grass-1", {x = 2, y = 14}},
    {"grass-1", {x = 2, y = 15}},
    {"grass-1", {x = 3, y = -16}},
    {"grass-1", {x = 3, y = -15}},
    {"grass-1", {x = 3, y = -14}},
    {"grass-1", {x = 3, y = -13}},
    {"grass-1", {x = 3, y = -12}},
    {"refined-concrete", {x = 3, y = -11}},
    {"refined-concrete", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"refined-concrete", {x = 3, y = 7}},
    {"refined-concrete", {x = 3, y = 8}},
    {"refined-concrete", {x = 3, y = 9}},
    {"grass-1", {x = 3, y = 10}},
    {"grass-1", {x = 3, y = 11}},
    {"grass-1", {x = 3, y = 12}},
    {"grass-1", {x = 3, y = 13}},
    {"grass-1", {x = 3, y = 14}},
    {"grass-1", {x = 3, y = 15}},
    {"grass-1", {x = 4, y = -16}},
    {"grass-1", {x = 4, y = -15}},
    {"grass-1", {x = 4, y = -14}},
    {"grass-1", {x = 4, y = -13}},
    {"grass-1", {x = 4, y = -12}},
    {"refined-concrete", {x = 4, y = -11}},
    {"refined-concrete", {x = 4, y = -10}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"refined-concrete", {x = 4, y = 7}},
    {"refined-concrete", {x = 4, y = 8}},
    {"refined-concrete", {x = 4, y = 9}},
    {"grass-1", {x = 4, y = 10}},
    {"grass-1", {x = 4, y = 11}},
    {"grass-1", {x = 4, y = 12}},
    {"grass-1", {x = 4, y = 13}},
    {"grass-1", {x = 4, y = 14}},
    {"grass-1", {x = 4, y = 15}},
    {"grass-1", {x = 5, y = -16}},
    {"grass-1", {x = 5, y = -15}},
    {"grass-1", {x = 5, y = -14}},
    {"grass-1", {x = 5, y = -13}},
    {"grass-1", {x = 5, y = -12}},
    {"refined-concrete", {x = 5, y = -11}},
    {"refined-concrete", {x = 5, y = -10}},
    {"grass-1", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"refined-concrete", {x = 5, y = 7}},
    {"refined-concrete", {x = 5, y = 8}},
    {"refined-concrete", {x = 5, y = 9}},
    {"grass-1", {x = 5, y = 10}},
    {"grass-1", {x = 5, y = 11}},
    {"grass-1", {x = 5, y = 12}},
    {"grass-1", {x = 5, y = 13}},
    {"grass-1", {x = 5, y = 14}},
    {"grass-1", {x = 5, y = 15}},
    {"grass-1", {x = 6, y = -16}},
    {"grass-1", {x = 6, y = -15}},
    {"grass-1", {x = 6, y = -14}},
    {"grass-1", {x = 6, y = -13}},
    {"grass-1", {x = 6, y = -12}},
    {"refined-concrete", {x = 6, y = -11}},
    {"refined-concrete", {x = 6, y = -10}},
    {"grass-1", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"refined-concrete", {x = 6, y = 7}},
    {"refined-concrete", {x = 6, y = 8}},
    {"refined-concrete", {x = 6, y = 9}},
    {"grass-1", {x = 6, y = 10}},
    {"grass-1", {x = 6, y = 11}},
    {"grass-1", {x = 6, y = 12}},
    {"grass-1", {x = 6, y = 13}},
    {"grass-1", {x = 6, y = 14}},
    {"grass-1", {x = 6, y = 15}},
    {"grass-1", {x = 7, y = -16}},
    {"grass-1", {x = 7, y = -15}},
    {"grass-1", {x = 7, y = -14}},
    {"grass-1", {x = 7, y = -13}},
    {"grass-1", {x = 7, y = -12}},
    {"refined-concrete", {x = 7, y = -11}},
    {"refined-concrete", {x = 7, y = -10}},
    {"refined-concrete", {x = 7, y = -9}},
    {"refined-concrete", {x = 7, y = -8}},
    {"refined-concrete", {x = 7, y = -7}},
    {"refined-concrete", {x = 7, y = -6}},
    {"refined-concrete", {x = 7, y = -5}},
    {"refined-concrete", {x = 7, y = -4}},
    {"refined-concrete", {x = 7, y = -3}},
    {"refined-concrete", {x = 7, y = -2}},
    {"refined-concrete", {x = 7, y = -1}},
    {"refined-concrete", {x = 7, y = 0}},
    {"refined-concrete", {x = 7, y = 1}},
    {"refined-concrete", {x = 7, y = 2}},
    {"refined-concrete", {x = 7, y = 3}},
    {"refined-concrete", {x = 7, y = 4}},
    {"refined-concrete", {x = 7, y = 5}},
    {"refined-concrete", {x = 7, y = 6}},
    {"refined-concrete", {x = 7, y = 7}},
    {"refined-concrete", {x = 7, y = 8}},
    {"refined-concrete", {x = 7, y = 9}},
    {"grass-1", {x = 7, y = 10}},
    {"grass-1", {x = 7, y = 11}},
    {"grass-1", {x = 7, y = 12}},
    {"grass-1", {x = 7, y = 13}},
    {"grass-1", {x = 7, y = 14}},
    {"grass-1", {x = 7, y = 15}},
    {"grass-1", {x = 8, y = -16}},
    {"grass-1", {x = 8, y = -15}},
    {"grass-1", {x = 8, y = -14}},
    {"grass-1", {x = 8, y = -13}},
    {"grass-1", {x = 8, y = -12}},
    {"refined-concrete", {x = 8, y = -11}},
    {"refined-concrete", {x = 8, y = -10}},
    {"refined-concrete", {x = 8, y = -9}},
    {"refined-concrete", {x = 8, y = -8}},
    {"refined-concrete", {x = 8, y = -7}},
    {"refined-concrete", {x = 8, y = -6}},
    {"refined-concrete", {x = 8, y = -5}},
    {"refined-concrete", {x = 8, y = -4}},
    {"refined-concrete", {x = 8, y = -3}},
    {"refined-concrete", {x = 8, y = -2}},
    {"refined-concrete", {x = 8, y = -1}},
    {"refined-concrete", {x = 8, y = 0}},
    {"refined-concrete", {x = 8, y = 1}},
    {"refined-concrete", {x = 8, y = 2}},
    {"refined-concrete", {x = 8, y = 3}},
    {"refined-concrete", {x = 8, y = 4}},
    {"refined-concrete", {x = 8, y = 5}},
    {"refined-concrete", {x = 8, y = 6}},
    {"refined-concrete", {x = 8, y = 7}},
    {"refined-concrete", {x = 8, y = 8}},
    {"refined-concrete", {x = 8, y = 9}},
    {"grass-1", {x = 8, y = 10}},
    {"grass-1", {x = 8, y = 11}},
    {"grass-1", {x = 8, y = 12}},
    {"grass-1", {x = 8, y = 13}},
    {"grass-1", {x = 8, y = 14}},
    {"grass-1", {x = 8, y = 15}},
    {"grass-1", {x = 9, y = -16}},
    {"grass-1", {x = 9, y = -15}},
    {"grass-1", {x = 9, y = -14}},
    {"grass-1", {x = 9, y = -13}},
    {"grass-1", {x = 9, y = -12}},
    {"refined-concrete", {x = 9, y = -11}},
    {"refined-concrete", {x = 9, y = -10}},
    {"refined-concrete", {x = 9, y = -9}},
    {"refined-concrete", {x = 9, y = -8}},
    {"refined-concrete", {x = 9, y = -7}},
    {"refined-concrete", {x = 9, y = -6}},
    {"refined-concrete", {x = 9, y = -5}},
    {"refined-concrete", {x = 9, y = -4}},
    {"refined-concrete", {x = 9, y = -3}},
    {"refined-concrete", {x = 9, y = -2}},
    {"refined-concrete", {x = 9, y = -1}},
    {"refined-concrete", {x = 9, y = 0}},
    {"refined-concrete", {x = 9, y = 1}},
    {"refined-concrete", {x = 9, y = 2}},
    {"refined-concrete", {x = 9, y = 3}},
    {"refined-concrete", {x = 9, y = 4}},
    {"refined-concrete", {x = 9, y = 5}},
    {"refined-concrete", {x = 9, y = 6}},
    {"refined-concrete", {x = 9, y = 7}},
    {"refined-concrete", {x = 9, y = 8}},
    {"refined-concrete", {x = 9, y = 9}},
    {"grass-1", {x = 9, y = 10}},
    {"grass-1", {x = 9, y = 11}},
    {"grass-1", {x = 9, y = 12}},
    {"grass-1", {x = 9, y = 13}},
    {"grass-1", {x = 9, y = 14}},
    {"grass-1", {x = 9, y = 15}},
    {"grass-1", {x = 10, y = -16}},
    {"grass-1", {x = 10, y = -15}},
    {"grass-1", {x = 10, y = -14}},
    {"grass-1", {x = 10, y = -13}},
    {"grass-1", {x = 10, y = -12}},
    {"refined-concrete", {x = 10, y = -11}},
    {"refined-concrete", {x = 10, y = -10}},
    {"refined-concrete", {x = 10, y = -9}},
    {"refined-concrete", {x = 10, y = -8}},
    {"refined-concrete", {x = 10, y = -7}},
    {"refined-concrete", {x = 10, y = -6}},
    {"refined-concrete", {x = 10, y = -5}},
    {"refined-concrete", {x = 10, y = -4}},
    {"refined-concrete", {x = 10, y = -3}},
    {"refined-concrete", {x = 10, y = -2}},
    {"refined-concrete", {x = 10, y = -1}},
    {"refined-concrete", {x = 10, y = 0}},
    {"refined-concrete", {x = 10, y = 1}},
    {"refined-concrete", {x = 10, y = 2}},
    {"refined-concrete", {x = 10, y = 3}},
    {"refined-concrete", {x = 10, y = 4}},
    {"refined-concrete", {x = 10, y = 5}},
    {"refined-concrete", {x = 10, y = 6}},
    {"refined-concrete", {x = 10, y = 7}},
    {"refined-concrete", {x = 10, y = 8}},
    {"refined-concrete", {x = 10, y = 9}},
    {"grass-1", {x = 10, y = 10}},
    {"grass-1", {x = 10, y = 11}},
    {"grass-1", {x = 10, y = 12}},
    {"grass-1", {x = 10, y = 13}},
    {"grass-1", {x = 10, y = 14}},
    {"grass-1", {x = 10, y = 15}},
    {"grass-1", {x = 11, y = -16}},
    {"grass-1", {x = 11, y = -15}},
    {"grass-1", {x = 11, y = -14}},
    {"grass-1", {x = 11, y = -13}},
    {"grass-1", {x = 11, y = -12}},
    {"grass-1", {x = 11, y = -11}},
    {"grass-1", {x = 11, y = -10}},
    {"grass-1", {x = 11, y = -9}},
    {"grass-1", {x = 11, y = -8}},
    {"grass-1", {x = 11, y = -7}},
    {"grass-1", {x = 11, y = -6}},
    {"grass-1", {x = 11, y = -5}},
    {"grass-1", {x = 11, y = -4}},
    {"grass-1", {x = 11, y = -3}},
    {"grass-1", {x = 11, y = -2}},
    {"grass-1", {x = 11, y = -1}},
    {"grass-1", {x = 11, y = 0}},
    {"grass-1", {x = 11, y = 1}},
    {"grass-1", {x = 11, y = 2}},
    {"grass-1", {x = 11, y = 3}},
    {"grass-1", {x = 11, y = 4}},
    {"grass-1", {x = 11, y = 5}},
    {"grass-1", {x = 11, y = 6}},
    {"grass-1", {x = 11, y = 7}},
    {"grass-1", {x = 11, y = 8}},
    {"grass-1", {x = 11, y = 9}},
    {"grass-1", {x = 11, y = 10}},
    {"grass-1", {x = 11, y = 11}},
    {"grass-1", {x = 11, y = 12}},
    {"grass-1", {x = 11, y = 13}},
    {"grass-1", {x = 11, y = 14}},
    {"grass-1", {x = 11, y = 15}},
    {"grass-1", {x = 12, y = -16}},
    {"grass-1", {x = 12, y = -15}},
    {"grass-1", {x = 12, y = -14}},
    {"grass-1", {x = 12, y = -13}},
    {"grass-1", {x = 12, y = -12}},
    {"grass-1", {x = 12, y = -11}},
    {"grass-1", {x = 12, y = -10}},
    {"grass-1", {x = 12, y = -9}},
    {"grass-1", {x = 12, y = -8}},
    {"grass-1", {x = 12, y = -7}},
    {"grass-1", {x = 12, y = -6}},
    {"grass-1", {x = 12, y = -5}},
    {"grass-1", {x = 12, y = -4}},
    {"grass-1", {x = 12, y = -3}},
    {"grass-1", {x = 12, y = -2}},
    {"grass-1", {x = 12, y = -1}},
    {"grass-1", {x = 12, y = 0}},
    {"grass-1", {x = 12, y = 1}},
    {"grass-1", {x = 12, y = 2}},
    {"grass-1", {x = 12, y = 3}},
    {"grass-1", {x = 12, y = 4}},
    {"grass-1", {x = 12, y = 5}},
    {"grass-1", {x = 12, y = 6}},
    {"grass-1", {x = 12, y = 7}},
    {"grass-1", {x = 12, y = 8}},
    {"grass-1", {x = 12, y = 9}},
    {"grass-1", {x = 12, y = 10}},
    {"grass-1", {x = 12, y = 11}},
    {"grass-1", {x = 12, y = 12}},
    {"grass-1", {x = 12, y = 13}},
    {"grass-1", {x = 12, y = 14}},
    {"grass-1", {x = 12, y = 15}},
    {"grass-1", {x = 13, y = -16}},
    {"grass-1", {x = 13, y = -15}},
    {"grass-1", {x = 13, y = -14}},
    {"grass-1", {x = 13, y = -13}},
    {"grass-1", {x = 13, y = -12}},
    {"grass-1", {x = 13, y = -11}},
    {"grass-1", {x = 13, y = -10}},
    {"grass-1", {x = 13, y = -9}},
    {"grass-1", {x = 13, y = -8}},
    {"grass-1", {x = 13, y = -7}},
    {"grass-1", {x = 13, y = -6}},
    {"grass-1", {x = 13, y = -5}},
    {"grass-1", {x = 13, y = -4}},
    {"grass-1", {x = 13, y = -3}},
    {"grass-1", {x = 13, y = -2}},
    {"grass-1", {x = 13, y = -1}},
    {"grass-1", {x = 13, y = 0}},
    {"grass-1", {x = 13, y = 1}},
    {"grass-1", {x = 13, y = 2}},
    {"grass-1", {x = 13, y = 3}},
    {"grass-1", {x = 13, y = 4}},
    {"grass-1", {x = 13, y = 5}},
    {"grass-1", {x = 13, y = 6}},
    {"grass-1", {x = 13, y = 7}},
    {"grass-1", {x = 13, y = 8}},
    {"grass-1", {x = 13, y = 9}},
    {"grass-1", {x = 13, y = 10}},
    {"grass-1", {x = 13, y = 11}},
    {"grass-1", {x = 13, y = 12}},
    {"grass-1", {x = 13, y = 13}},
    {"grass-1", {x = 13, y = 14}},
    {"grass-1", {x = 13, y = 15}},
    {"grass-1", {x = 14, y = -16}},
    {"grass-1", {x = 14, y = -15}},
    {"grass-1", {x = 14, y = -14}},
    {"grass-1", {x = 14, y = -13}},
    {"grass-1", {x = 14, y = -12}},
    {"grass-1", {x = 14, y = -11}},
    {"grass-1", {x = 14, y = -10}},
    {"grass-1", {x = 14, y = -9}},
    {"grass-1", {x = 14, y = -8}},
    {"grass-1", {x = 14, y = -7}},
    {"grass-1", {x = 14, y = -6}},
    {"grass-1", {x = 14, y = -5}},
    {"grass-1", {x = 14, y = -4}},
    {"grass-1", {x = 14, y = -3}},
    {"grass-1", {x = 14, y = -2}},
    {"grass-1", {x = 14, y = -1}},
    {"grass-1", {x = 14, y = 0}},
    {"grass-1", {x = 14, y = 1}},
    {"grass-1", {x = 14, y = 2}},
    {"grass-1", {x = 14, y = 3}},
    {"grass-1", {x = 14, y = 4}},
    {"grass-1", {x = 14, y = 5}},
    {"grass-1", {x = 14, y = 6}},
    {"grass-1", {x = 14, y = 7}},
    {"grass-1", {x = 14, y = 8}},
    {"grass-1", {x = 14, y = 9}},
    {"grass-1", {x = 14, y = 10}},
    {"grass-1", {x = 14, y = 11}},
    {"grass-1", {x = 14, y = 12}},
    {"grass-1", {x = 14, y = 13}},
    {"grass-1", {x = 14, y = 14}},
    {"grass-1", {x = 14, y = 15}},
    {"grass-1", {x = 15, y = -16}},
    {"grass-1", {x = 15, y = -15}},
    {"grass-1", {x = 15, y = -14}},
    {"grass-1", {x = 15, y = -13}},
    {"grass-1", {x = 15, y = -12}},
    {"grass-1", {x = 15, y = -11}},
    {"grass-1", {x = 15, y = -10}},
    {"grass-1", {x = 15, y = -9}},
    {"grass-1", {x = 15, y = -8}},
    {"grass-1", {x = 15, y = -7}},
    {"grass-1", {x = 15, y = -6}},
    {"grass-1", {x = 15, y = -5}},
    {"grass-1", {x = 15, y = -4}},
    {"grass-1", {x = 15, y = -3}},
    {"grass-1", {x = 15, y = -2}},
    {"grass-1", {x = 15, y = -1}},
    {"grass-1", {x = 15, y = 0}},
    {"grass-1", {x = 15, y = 1}},
    {"grass-1", {x = 15, y = 2}},
    {"grass-1", {x = 15, y = 3}},
    {"grass-1", {x = 15, y = 4}},
    {"grass-1", {x = 15, y = 5}},
    {"grass-1", {x = 15, y = 6}},
    {"grass-1", {x = 15, y = 7}},
    {"grass-1", {x = 15, y = 8}},
    {"grass-1", {x = 15, y = 9}},
    {"grass-1", {x = 15, y = 10}},
    {"grass-1", {x = 15, y = 11}},
    {"grass-1", {x = 15, y = 12}},
    {"grass-1", {x = 15, y = 13}},
    {"grass-1", {x = 15, y = 14}},
    {"grass-1", {x = 15, y = 15}},
  }
}
