return
{
  entities =
  {
    {"gate", {x = -15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -10, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -8, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -4, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -2, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 0, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 2, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 4, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 8, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 10, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 12, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -14}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -15.5}, {force = "enemy", }},
    {"gate", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -12.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -12}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -10.5}, {force = "enemy", }},
    {"gate", {x = -10.5, y = -10.5}, {force = "enemy", }},
    {"gate", {x = -10.5, y = -11.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = -8.5, y = -10.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = -4.5, y = -10.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = 2.5, y = -10.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = 10.5, y = -10.5}, {}},
    {"steel-chest", {x = 11.5, y = -11.5}, {items = {["cryexplosive-rounds-magazine"] = 200, ["repair-pack"] = 100}, }},
    {"laser-turret", {x = 14, y = -10}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = -8}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -8.5}, {force = "enemy", }},
    {"steel-chest", {x = -9.5, y = -8.5}, {items = {["uranium-235"] = 2, ["uranium-fuel-cell"] = 50}, }},
    {"stone-wall", {x = -8.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -9.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -8}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -7.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = -6}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -7.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -6}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = -4}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -4.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = -8.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -4.5}, {force = "enemy", }},
    {"steel-chest", {x = 5.5, y = -5.5}, {items = {["atomic-bomb"] = 10, ["spidertron-rocket-launcher-2"] = 1}, }},
    {"stone-wall", {x = 6.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -5.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = 10.5, y = -4.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -4}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -3.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = -2}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -3.5}, {force = "enemy", }},
    {"purple-crystal-gen", {x = 0.5, y = -3}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -3.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -2}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -1.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 0}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -0.5}, {force = "enemy", }},
    {"substation", {x = -2, y = 0}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -1.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 0}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 0.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 2}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 1.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = -8.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 1.5}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.15, y = 1.54}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.44, y = 1.54}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.69, y = 1.51}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.82, y = 1.51}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.95, y = 1.51}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.18, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.59, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = -2.85, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.05, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.15, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.51, y = 1.64}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.15, y = 1.59}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.72, y = 1.57}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.05, y = 0.87}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.13, y = 0.85}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.21, y = 0.85}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.31, y = 0.85}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.51, y = 0.87}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.8, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.26, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.69, y = 0.9}, {force = "enemy", }},
    {"green-crystal-gen", {x = 0.5, y = 0}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.82, y = 1.77}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.84, y = 1.77}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.64, y = 1.77}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.15, y = 1.77}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.36, y = 1.69}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.95, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.92, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.87, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.64, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.41, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.18, y = 0.9}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.02, y = 0.87}, {force = "enemy", }},
    {"aliencon-robot", {x = 0, y = 0.87}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 0.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 2}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 2.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 4}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 3.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -3.5, y = 3.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"logistic-chest-passive-provider", {x = -3.5, y = 2.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"roboport", {x = -1, y = 4}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"logistic-chest-passive-provider", {x = 1.5, y = 3.5}, {force = "enemy", items = {["repair-pack"] = 4700}, }},
    {"logistic-chest-passive-provider", {x = 1.5, y = 2.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"stone-wall", {x = 3.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 2.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = 10.5, y = 2.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 4}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 4.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 6}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 5.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -3.5, y = 5.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"logistic-chest-passive-provider", {x = -3.5, y = 4.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"logistic-chest-passive-provider", {x = 1.5, y = 5.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"logistic-chest-passive-provider", {x = 1.5, y = 4.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"gate", {x = 3.5, y = 5.5}, {force = "enemy", }},
    {"gate", {x = 3.5, y = 4.5}, {force = "enemy", }},
    {"steel-chest", {x = 5.5, y = 5.5}, {items = {["battery-mk2-equipment"] = 1, ["solar-panel-equipment"] = 20}, }},
    {"stone-wall", {x = 6.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 4.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 6}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 8}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 8}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 8.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 10}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 9.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = -8.5, y = 8.5}, {force = "enemy", }},
    {"steel-chest", {x = -6.5, y = 8.5}, {items = {accumulator = 50, ["solar-panel"] = 50}, }},
    {"stone-wall", {x = -7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 8.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 10}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 10.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 12}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 11.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = -8.5, y = 10.5}, {}},
    {"medium-electric-pole", {x = -1.5, y = 10.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = 5.5, y = 10.5}, {force = "enemy", }},
    {"medium-electric-pole", {x = 10.5, y = 10.5}, {}},
    {"laser-turret", {x = 14, y = 12}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 14}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -10, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -8, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -4, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -2, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 0, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 2, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 4, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 8, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 10, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 12, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 14.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"dirt-6", {x = -16, y = -16}},
    {"dirt-6", {x = -16, y = -15}},
    {"dirt-7", {x = -16, y = -14}},
    {"dirt-7", {x = -16, y = -13}},
    {"dirt-7", {x = -16, y = -12}},
    {"dirt-7", {x = -16, y = -11}},
    {"dirt-7", {x = -16, y = -10}},
    {"dirt-7", {x = -16, y = -9}},
    {"dirt-7", {x = -16, y = -8}},
    {"dirt-7", {x = -16, y = -7}},
    {"dirt-7", {x = -16, y = -6}},
    {"dirt-7", {x = -16, y = -5}},
    {"dirt-7", {x = -16, y = -4}},
    {"dirt-7", {x = -16, y = -3}},
    {"dirt-7", {x = -16, y = -2}},
    {"dirt-7", {x = -16, y = -1}},
    {"dirt-7", {x = -16, y = 0}},
    {"dirt-7", {x = -16, y = 1}},
    {"dirt-7", {x = -16, y = 2}},
    {"dirt-7", {x = -16, y = 3}},
    {"dirt-7", {x = -16, y = 4}},
    {"dirt-7", {x = -16, y = 5}},
    {"dirt-7", {x = -16, y = 6}},
    {"dirt-6", {x = -16, y = 7}},
    {"dirt-6", {x = -16, y = 8}},
    {"dirt-6", {x = -16, y = 9}},
    {"dirt-6", {x = -16, y = 10}},
    {"dirt-6", {x = -16, y = 11}},
    {"dirt-6", {x = -16, y = 12}},
    {"dirt-6", {x = -16, y = 13}},
    {"dirt-5", {x = -16, y = 14}},
    {"dirt-5", {x = -16, y = 15}},
    {"dirt-6", {x = -15, y = -16}},
    {"dirt-6", {x = -15, y = -15}},
    {"dirt-6", {x = -15, y = -14}},
    {"dirt-7", {x = -15, y = -13}},
    {"dirt-7", {x = -15, y = -12}},
    {"dirt-7", {x = -15, y = -11}},
    {"dirt-7", {x = -15, y = -10}},
    {"dirt-7", {x = -15, y = -9}},
    {"dirt-7", {x = -15, y = -8}},
    {"dirt-7", {x = -15, y = -7}},
    {"dirt-7", {x = -15, y = -6}},
    {"dirt-7", {x = -15, y = -5}},
    {"dirt-7", {x = -15, y = -4}},
    {"dirt-7", {x = -15, y = -3}},
    {"dirt-6", {x = -15, y = -2}},
    {"dirt-6", {x = -15, y = -1}},
    {"dirt-6", {x = -15, y = 0}},
    {"dirt-6", {x = -15, y = 1}},
    {"dirt-6", {x = -15, y = 2}},
    {"dirt-6", {x = -15, y = 3}},
    {"dirt-6", {x = -15, y = 4}},
    {"dirt-6", {x = -15, y = 5}},
    {"dirt-6", {x = -15, y = 6}},
    {"dirt-6", {x = -15, y = 7}},
    {"dirt-6", {x = -15, y = 8}},
    {"dirt-6", {x = -15, y = 9}},
    {"dirt-6", {x = -15, y = 10}},
    {"dirt-6", {x = -15, y = 11}},
    {"dirt-6", {x = -15, y = 12}},
    {"dirt-5", {x = -15, y = 13}},
    {"dirt-5", {x = -15, y = 14}},
    {"dirt-5", {x = -15, y = 15}},
    {"dirt-6", {x = -14, y = -16}},
    {"dirt-6", {x = -14, y = -15}},
    {"dirt-6", {x = -14, y = -14}},
    {"dirt-6", {x = -14, y = -13}},
    {"dirt-7", {x = -14, y = -12}},
    {"dirt-7", {x = -14, y = -11}},
    {"dirt-7", {x = -14, y = -10}},
    {"dirt-6", {x = -14, y = -9}},
    {"dirt-6", {x = -14, y = -8}},
    {"dirt-7", {x = -14, y = -7}},
    {"dirt-7", {x = -14, y = -6}},
    {"dirt-7", {x = -14, y = -5}},
    {"dirt-6", {x = -14, y = -4}},
    {"dirt-6", {x = -14, y = -3}},
    {"dirt-6", {x = -14, y = -2}},
    {"dirt-6", {x = -14, y = -1}},
    {"dirt-6", {x = -14, y = 0}},
    {"dirt-6", {x = -14, y = 1}},
    {"dirt-6", {x = -14, y = 2}},
    {"dirt-6", {x = -14, y = 3}},
    {"dirt-6", {x = -14, y = 4}},
    {"dirt-6", {x = -14, y = 5}},
    {"dirt-6", {x = -14, y = 6}},
    {"dirt-6", {x = -14, y = 7}},
    {"dirt-6", {x = -14, y = 8}},
    {"dirt-6", {x = -14, y = 9}},
    {"dirt-6", {x = -14, y = 10}},
    {"dirt-6", {x = -14, y = 11}},
    {"dirt-6", {x = -14, y = 12}},
    {"dirt-5", {x = -14, y = 13}},
    {"dirt-5", {x = -14, y = 14}},
    {"dirt-5", {x = -14, y = 15}},
    {"dirt-6", {x = -13, y = -16}},
    {"dirt-6", {x = -13, y = -15}},
    {"dirt-6", {x = -13, y = -14}},
    {"dirt-6", {x = -13, y = -13}},
    {"dirt-7", {x = -13, y = -12}},
    {"dirt-7", {x = -13, y = -11}},
    {"dirt-6", {x = -13, y = -10}},
    {"dirt-6", {x = -13, y = -9}},
    {"dirt-6", {x = -13, y = -8}},
    {"dirt-6", {x = -13, y = -7}},
    {"dirt-6", {x = -13, y = -6}},
    {"dirt-6", {x = -13, y = -5}},
    {"dirt-6", {x = -13, y = -4}},
    {"dirt-6", {x = -13, y = -3}},
    {"dirt-6", {x = -13, y = -2}},
    {"dirt-6", {x = -13, y = -1}},
    {"dirt-6", {x = -13, y = 0}},
    {"dirt-6", {x = -13, y = 1}},
    {"dirt-6", {x = -13, y = 2}},
    {"dirt-6", {x = -13, y = 3}},
    {"dirt-6", {x = -13, y = 4}},
    {"dirt-6", {x = -13, y = 5}},
    {"dirt-6", {x = -13, y = 6}},
    {"dirt-6", {x = -13, y = 7}},
    {"dirt-6", {x = -13, y = 8}},
    {"dirt-6", {x = -13, y = 9}},
    {"dirt-6", {x = -13, y = 10}},
    {"dirt-6", {x = -13, y = 11}},
    {"dirt-6", {x = -13, y = 12}},
    {"dirt-6", {x = -13, y = 13}},
    {"dirt-6", {x = -13, y = 14}},
    {"dirt-6", {x = -13, y = 15}},
    {"dirt-6", {x = -12, y = -16}},
    {"dirt-6", {x = -12, y = -15}},
    {"dirt-6", {x = -12, y = -14}},
    {"dirt-7", {x = -12, y = -13}},
    {"dirt-7", {x = -12, y = -12}},
    {"dirt-7", {x = -12, y = -11}},
    {"dirt-6", {x = -12, y = -10}},
    {"dirt-6", {x = -12, y = -9}},
    {"dirt-6", {x = -12, y = -8}},
    {"dirt-6", {x = -12, y = -7}},
    {"dirt-6", {x = -12, y = -6}},
    {"dirt-6", {x = -12, y = -5}},
    {"dirt-6", {x = -12, y = -4}},
    {"dirt-6", {x = -12, y = -3}},
    {"dirt-7", {x = -12, y = -2}},
    {"dirt-7", {x = -12, y = -1}},
    {"dirt-6", {x = -12, y = 0}},
    {"dirt-6", {x = -12, y = 1}},
    {"dirt-6", {x = -12, y = 2}},
    {"dirt-6", {x = -12, y = 3}},
    {"dirt-6", {x = -12, y = 4}},
    {"dirt-6", {x = -12, y = 5}},
    {"dirt-6", {x = -12, y = 6}},
    {"dirt-6", {x = -12, y = 7}},
    {"dirt-6", {x = -12, y = 8}},
    {"dirt-6", {x = -12, y = 9}},
    {"dirt-6", {x = -12, y = 10}},
    {"dirt-6", {x = -12, y = 11}},
    {"dirt-6", {x = -12, y = 12}},
    {"dirt-6", {x = -12, y = 13}},
    {"dirt-6", {x = -12, y = 14}},
    {"dirt-6", {x = -12, y = 15}},
    {"dirt-6", {x = -11, y = -16}},
    {"dirt-6", {x = -11, y = -15}},
    {"dirt-7", {x = -11, y = -14}},
    {"dirt-7", {x = -11, y = -13}},
    {"dirt-7", {x = -11, y = -12}},
    {"dirt-7", {x = -11, y = -11}},
    {"dirt-7", {x = -11, y = -10}},
    {"dirt-6", {x = -11, y = -9}},
    {"dirt-6", {x = -11, y = -8}},
    {"dirt-6", {x = -11, y = -7}},
    {"dirt-6", {x = -11, y = -6}},
    {"dirt-6", {x = -11, y = -5}},
    {"dirt-6", {x = -11, y = -4}},
    {"dirt-7", {x = -11, y = -3}},
    {"dirt-7", {x = -11, y = -2}},
    {"dirt-7", {x = -11, y = -1}},
    {"dirt-7", {x = -11, y = 0}},
    {"dirt-6", {x = -11, y = 1}},
    {"dirt-6", {x = -11, y = 2}},
    {"dirt-6", {x = -11, y = 3}},
    {"dirt-6", {x = -11, y = 4}},
    {"dirt-6", {x = -11, y = 5}},
    {"dirt-6", {x = -11, y = 6}},
    {"dirt-6", {x = -11, y = 7}},
    {"dirt-6", {x = -11, y = 8}},
    {"dirt-6", {x = -11, y = 9}},
    {"dirt-6", {x = -11, y = 10}},
    {"dirt-6", {x = -11, y = 11}},
    {"dirt-6", {x = -11, y = 12}},
    {"dirt-6", {x = -11, y = 13}},
    {"dirt-6", {x = -11, y = 14}},
    {"dirt-6", {x = -11, y = 15}},
    {"dirt-6", {x = -10, y = -16}},
    {"dirt-6", {x = -10, y = -15}},
    {"dirt-7", {x = -10, y = -14}},
    {"dirt-7", {x = -10, y = -13}},
    {"dirt-7", {x = -10, y = -12}},
    {"dirt-7", {x = -10, y = -11}},
    {"dirt-7", {x = -10, y = -10}},
    {"dirt-6", {x = -10, y = -9}},
    {"dirt-6", {x = -10, y = -8}},
    {"dirt-6", {x = -10, y = -7}},
    {"dirt-6", {x = -10, y = -6}},
    {"dirt-6", {x = -10, y = -5}},
    {"dirt-6", {x = -10, y = -4}},
    {"dirt-7", {x = -10, y = -3}},
    {"dirt-7", {x = -10, y = -2}},
    {"dirt-7", {x = -10, y = -1}},
    {"dirt-6", {x = -10, y = 0}},
    {"dirt-6", {x = -10, y = 1}},
    {"dirt-6", {x = -10, y = 2}},
    {"dirt-6", {x = -10, y = 3}},
    {"dirt-6", {x = -10, y = 4}},
    {"dirt-6", {x = -10, y = 5}},
    {"dirt-6", {x = -10, y = 6}},
    {"dirt-6", {x = -10, y = 7}},
    {"dirt-6", {x = -10, y = 8}},
    {"dirt-6", {x = -10, y = 9}},
    {"dirt-6", {x = -10, y = 10}},
    {"dirt-6", {x = -10, y = 11}},
    {"dirt-6", {x = -10, y = 12}},
    {"dirt-6", {x = -10, y = 13}},
    {"dirt-6", {x = -10, y = 14}},
    {"dirt-6", {x = -10, y = 15}},
    {"dirt-6", {x = -9, y = -16}},
    {"dirt-6", {x = -9, y = -15}},
    {"dirt-7", {x = -9, y = -14}},
    {"dirt-7", {x = -9, y = -13}},
    {"dirt-7", {x = -9, y = -12}},
    {"dirt-7", {x = -9, y = -11}},
    {"dirt-7", {x = -9, y = -10}},
    {"dirt-7", {x = -9, y = -9}},
    {"dirt-6", {x = -9, y = -8}},
    {"dirt-6", {x = -9, y = -7}},
    {"dirt-6", {x = -9, y = -6}},
    {"dirt-6", {x = -9, y = -5}},
    {"dirt-6", {x = -9, y = -4}},
    {"dirt-7", {x = -9, y = -3}},
    {"dirt-7", {x = -9, y = -2}},
    {"dirt-7", {x = -9, y = -1}},
    {"dirt-6", {x = -9, y = 0}},
    {"dirt-6", {x = -9, y = 1}},
    {"dirt-6", {x = -9, y = 2}},
    {"dirt-6", {x = -9, y = 3}},
    {"dirt-6", {x = -9, y = 4}},
    {"dirt-6", {x = -9, y = 5}},
    {"dirt-6", {x = -9, y = 6}},
    {"dirt-6", {x = -9, y = 7}},
    {"dirt-6", {x = -9, y = 8}},
    {"dirt-6", {x = -9, y = 9}},
    {"dirt-6", {x = -9, y = 10}},
    {"dirt-6", {x = -9, y = 11}},
    {"dirt-6", {x = -9, y = 12}},
    {"dirt-6", {x = -9, y = 13}},
    {"dirt-6", {x = -9, y = 14}},
    {"dirt-6", {x = -9, y = 15}},
    {"dirt-6", {x = -8, y = -16}},
    {"dirt-6", {x = -8, y = -15}},
    {"dirt-6", {x = -8, y = -14}},
    {"dirt-7", {x = -8, y = -13}},
    {"dirt-7", {x = -8, y = -12}},
    {"dirt-7", {x = -8, y = -11}},
    {"dirt-7", {x = -8, y = -10}},
    {"dirt-7", {x = -8, y = -9}},
    {"dirt-6", {x = -8, y = -8}},
    {"dirt-6", {x = -8, y = -7}},
    {"dirt-6", {x = -8, y = -6}},
    {"dirt-6", {x = -8, y = -5}},
    {"dirt-6", {x = -8, y = -4}},
    {"dirt-7", {x = -8, y = -3}},
    {"dirt-7", {x = -8, y = -2}},
    {"dirt-7", {x = -8, y = -1}},
    {"dirt-6", {x = -8, y = 0}},
    {"dirt-6", {x = -8, y = 1}},
    {"dirt-6", {x = -8, y = 2}},
    {"dirt-6", {x = -8, y = 3}},
    {"dirt-6", {x = -8, y = 4}},
    {"dirt-6", {x = -8, y = 5}},
    {"dirt-6", {x = -8, y = 6}},
    {"dirt-6", {x = -8, y = 7}},
    {"dirt-6", {x = -8, y = 8}},
    {"dirt-6", {x = -8, y = 9}},
    {"dirt-6", {x = -8, y = 10}},
    {"dirt-6", {x = -8, y = 11}},
    {"dirt-6", {x = -8, y = 12}},
    {"dirt-6", {x = -8, y = 13}},
    {"dirt-6", {x = -8, y = 14}},
    {"dirt-6", {x = -8, y = 15}},
    {"dirt-6", {x = -7, y = -16}},
    {"dirt-6", {x = -7, y = -15}},
    {"dirt-6", {x = -7, y = -14}},
    {"dirt-6", {x = -7, y = -13}},
    {"dirt-7", {x = -7, y = -12}},
    {"dirt-7", {x = -7, y = -11}},
    {"dirt-7", {x = -7, y = -10}},
    {"dirt-7", {x = -7, y = -9}},
    {"dirt-7", {x = -7, y = -8}},
    {"dirt-7", {x = -7, y = -7}},
    {"dirt-7", {x = -7, y = -6}},
    {"dirt-7", {x = -7, y = -5}},
    {"dirt-7", {x = -7, y = -4}},
    {"dirt-7", {x = -7, y = -3}},
    {"dirt-7", {x = -7, y = -2}},
    {"dirt-6", {x = -7, y = -1}},
    {"dirt-6", {x = -7, y = 0}},
    {"dirt-6", {x = -7, y = 1}},
    {"dirt-6", {x = -7, y = 2}},
    {"dirt-6", {x = -7, y = 3}},
    {"dirt-6", {x = -7, y = 4}},
    {"dirt-6", {x = -7, y = 5}},
    {"dirt-6", {x = -7, y = 6}},
    {"dirt-6", {x = -7, y = 7}},
    {"dirt-6", {x = -7, y = 8}},
    {"dirt-6", {x = -7, y = 9}},
    {"dirt-6", {x = -7, y = 10}},
    {"dirt-6", {x = -7, y = 11}},
    {"dirt-6", {x = -7, y = 12}},
    {"dirt-6", {x = -7, y = 13}},
    {"dirt-6", {x = -7, y = 14}},
    {"dirt-6", {x = -7, y = 15}},
    {"dirt-6", {x = -6, y = -16}},
    {"dirt-6", {x = -6, y = -15}},
    {"dirt-6", {x = -6, y = -14}},
    {"dirt-6", {x = -6, y = -13}},
    {"dirt-7", {x = -6, y = -12}},
    {"dirt-7", {x = -6, y = -11}},
    {"dirt-7", {x = -6, y = -10}},
    {"dirt-7", {x = -6, y = -9}},
    {"dirt-7", {x = -6, y = -8}},
    {"dirt-7", {x = -6, y = -7}},
    {"dirt-7", {x = -6, y = -6}},
    {"dirt-7", {x = -6, y = -5}},
    {"dirt-7", {x = -6, y = -4}},
    {"dirt-7", {x = -6, y = -3}},
    {"dirt-7", {x = -6, y = -2}},
    {"dirt-6", {x = -6, y = -1}},
    {"dirt-6", {x = -6, y = 0}},
    {"dirt-6", {x = -6, y = 1}},
    {"dirt-6", {x = -6, y = 2}},
    {"dirt-6", {x = -6, y = 3}},
    {"dirt-6", {x = -6, y = 4}},
    {"dirt-6", {x = -6, y = 5}},
    {"dirt-6", {x = -6, y = 6}},
    {"dirt-6", {x = -6, y = 7}},
    {"dirt-6", {x = -6, y = 8}},
    {"dirt-6", {x = -6, y = 9}},
    {"dirt-6", {x = -6, y = 10}},
    {"dirt-6", {x = -6, y = 11}},
    {"dirt-6", {x = -6, y = 12}},
    {"dirt-6", {x = -6, y = 13}},
    {"dirt-6", {x = -6, y = 14}},
    {"dirt-6", {x = -6, y = 15}},
    {"dirt-6", {x = -5, y = -16}},
    {"dirt-6", {x = -5, y = -15}},
    {"dirt-6", {x = -5, y = -14}},
    {"dirt-6", {x = -5, y = -13}},
    {"dirt-6", {x = -5, y = -12}},
    {"dirt-7", {x = -5, y = -11}},
    {"dirt-7", {x = -5, y = -10}},
    {"dirt-7", {x = -5, y = -9}},
    {"dirt-7", {x = -5, y = -8}},
    {"dirt-7", {x = -5, y = -7}},
    {"dirt-7", {x = -5, y = -6}},
    {"dirt-7", {x = -5, y = -5}},
    {"dirt-7", {x = -5, y = -4}},
    {"dirt-7", {x = -5, y = -3}},
    {"dirt-7", {x = -5, y = -2}},
    {"dirt-6", {x = -5, y = -1}},
    {"dirt-6", {x = -5, y = 0}},
    {"dirt-6", {x = -5, y = 1}},
    {"dirt-6", {x = -5, y = 2}},
    {"dirt-6", {x = -5, y = 3}},
    {"dirt-6", {x = -5, y = 4}},
    {"dirt-6", {x = -5, y = 5}},
    {"dirt-6", {x = -5, y = 6}},
    {"dirt-6", {x = -5, y = 7}},
    {"dirt-6", {x = -5, y = 8}},
    {"dirt-6", {x = -5, y = 9}},
    {"dirt-6", {x = -5, y = 10}},
    {"dirt-6", {x = -5, y = 11}},
    {"dirt-6", {x = -5, y = 12}},
    {"dirt-6", {x = -5, y = 13}},
    {"dirt-6", {x = -5, y = 14}},
    {"dirt-6", {x = -5, y = 15}},
    {"dirt-6", {x = -4, y = -16}},
    {"dirt-6", {x = -4, y = -15}},
    {"dirt-6", {x = -4, y = -14}},
    {"dirt-6", {x = -4, y = -13}},
    {"dirt-6", {x = -4, y = -12}},
    {"dirt-7", {x = -4, y = -11}},
    {"dirt-7", {x = -4, y = -10}},
    {"dirt-7", {x = -4, y = -9}},
    {"dirt-7", {x = -4, y = -8}},
    {"dirt-7", {x = -4, y = -7}},
    {"dirt-7", {x = -4, y = -6}},
    {"dirt-7", {x = -4, y = -5}},
    {"dirt-7", {x = -4, y = -4}},
    {"dirt-7", {x = -4, y = -3}},
    {"dirt-7", {x = -4, y = -2}},
    {"dirt-7", {x = -4, y = -1}},
    {"dirt-6", {x = -4, y = 0}},
    {"dirt-6", {x = -4, y = 1}},
    {"dirt-6", {x = -4, y = 2}},
    {"dirt-6", {x = -4, y = 3}},
    {"dirt-6", {x = -4, y = 4}},
    {"dirt-6", {x = -4, y = 5}},
    {"dirt-6", {x = -4, y = 6}},
    {"dirt-6", {x = -4, y = 7}},
    {"dirt-6", {x = -4, y = 8}},
    {"dirt-6", {x = -4, y = 9}},
    {"dirt-6", {x = -4, y = 10}},
    {"dirt-6", {x = -4, y = 11}},
    {"dirt-6", {x = -4, y = 12}},
    {"dirt-6", {x = -4, y = 13}},
    {"dirt-6", {x = -4, y = 14}},
    {"dirt-6", {x = -4, y = 15}},
    {"dirt-6", {x = -3, y = -16}},
    {"dirt-6", {x = -3, y = -15}},
    {"dirt-6", {x = -3, y = -14}},
    {"dirt-6", {x = -3, y = -13}},
    {"dirt-7", {x = -3, y = -12}},
    {"dirt-7", {x = -3, y = -11}},
    {"dirt-7", {x = -3, y = -10}},
    {"dirt-7", {x = -3, y = -9}},
    {"dirt-7", {x = -3, y = -8}},
    {"dirt-7", {x = -3, y = -7}},
    {"dirt-7", {x = -3, y = -6}},
    {"dirt-7", {x = -3, y = -5}},
    {"dirt-7", {x = -3, y = -4}},
    {"dirt-7", {x = -3, y = -3}},
    {"dirt-7", {x = -3, y = -2}},
    {"dirt-7", {x = -3, y = -1}},
    {"dirt-6", {x = -3, y = 0}},
    {"dirt-6", {x = -3, y = 1}},
    {"dirt-6", {x = -3, y = 2}},
    {"dirt-6", {x = -3, y = 3}},
    {"dirt-6", {x = -3, y = 4}},
    {"dirt-6", {x = -3, y = 5}},
    {"dirt-6", {x = -3, y = 6}},
    {"dirt-6", {x = -3, y = 7}},
    {"dirt-6", {x = -3, y = 8}},
    {"dirt-6", {x = -3, y = 9}},
    {"dirt-6", {x = -3, y = 10}},
    {"dirt-6", {x = -3, y = 11}},
    {"dirt-6", {x = -3, y = 12}},
    {"dirt-6", {x = -3, y = 13}},
    {"dirt-6", {x = -3, y = 14}},
    {"dirt-6", {x = -3, y = 15}},
    {"dirt-6", {x = -2, y = -16}},
    {"dirt-6", {x = -2, y = -15}},
    {"dirt-6", {x = -2, y = -14}},
    {"dirt-6", {x = -2, y = -13}},
    {"dirt-7", {x = -2, y = -12}},
    {"dirt-7", {x = -2, y = -11}},
    {"dirt-7", {x = -2, y = -10}},
    {"dirt-7", {x = -2, y = -9}},
    {"dirt-7", {x = -2, y = -8}},
    {"dirt-7", {x = -2, y = -7}},
    {"dirt-7", {x = -2, y = -6}},
    {"dirt-7", {x = -2, y = -5}},
    {"dirt-7", {x = -2, y = -4}},
    {"dirt-7", {x = -2, y = -3}},
    {"dirt-7", {x = -2, y = -2}},
    {"dirt-7", {x = -2, y = -1}},
    {"dirt-7", {x = -2, y = 0}},
    {"dirt-6", {x = -2, y = 1}},
    {"dirt-6", {x = -2, y = 2}},
    {"dirt-6", {x = -2, y = 3}},
    {"dirt-6", {x = -2, y = 4}},
    {"dirt-6", {x = -2, y = 5}},
    {"dirt-6", {x = -2, y = 6}},
    {"dirt-6", {x = -2, y = 7}},
    {"dirt-6", {x = -2, y = 8}},
    {"dirt-6", {x = -2, y = 9}},
    {"dirt-6", {x = -2, y = 10}},
    {"dirt-6", {x = -2, y = 11}},
    {"dirt-6", {x = -2, y = 12}},
    {"dirt-6", {x = -2, y = 13}},
    {"dirt-6", {x = -2, y = 14}},
    {"dirt-6", {x = -2, y = 15}},
    {"dirt-6", {x = -1, y = -16}},
    {"dirt-6", {x = -1, y = -15}},
    {"dirt-6", {x = -1, y = -14}},
    {"dirt-6", {x = -1, y = -13}},
    {"dirt-7", {x = -1, y = -12}},
    {"dirt-7", {x = -1, y = -11}},
    {"dirt-7", {x = -1, y = -10}},
    {"dirt-7", {x = -1, y = -9}},
    {"dirt-7", {x = -1, y = -8}},
    {"dirt-7", {x = -1, y = -7}},
    {"dirt-7", {x = -1, y = -6}},
    {"dirt-7", {x = -1, y = -5}},
    {"dirt-7", {x = -1, y = -4}},
    {"dirt-7", {x = -1, y = -3}},
    {"dirt-7", {x = -1, y = -2}},
    {"dirt-7", {x = -1, y = -1}},
    {"dirt-7", {x = -1, y = 0}},
    {"dirt-7", {x = -1, y = 1}},
    {"dirt-6", {x = -1, y = 2}},
    {"dirt-6", {x = -1, y = 3}},
    {"dirt-6", {x = -1, y = 4}},
    {"dirt-6", {x = -1, y = 5}},
    {"dirt-6", {x = -1, y = 6}},
    {"dirt-6", {x = -1, y = 7}},
    {"dirt-6", {x = -1, y = 8}},
    {"dirt-6", {x = -1, y = 9}},
    {"dirt-6", {x = -1, y = 10}},
    {"dirt-6", {x = -1, y = 11}},
    {"dirt-6", {x = -1, y = 12}},
    {"dirt-6", {x = -1, y = 13}},
    {"dirt-6", {x = -1, y = 14}},
    {"dirt-6", {x = -1, y = 15}},
    {"dirt-6", {x = 0, y = -16}},
    {"dirt-6", {x = 0, y = -15}},
    {"dirt-6", {x = 0, y = -14}},
    {"dirt-6", {x = 0, y = -13}},
    {"dirt-7", {x = 0, y = -12}},
    {"dirt-7", {x = 0, y = -11}},
    {"dirt-7", {x = 0, y = -10}},
    {"dirt-7", {x = 0, y = -9}},
    {"dirt-7", {x = 0, y = -8}},
    {"dirt-7", {x = 0, y = -7}},
    {"dirt-7", {x = 0, y = -6}},
    {"dirt-7", {x = 0, y = -5}},
    {"dirt-7", {x = 0, y = -4}},
    {"dirt-7", {x = 0, y = -3}},
    {"dirt-7", {x = 0, y = -2}},
    {"dirt-7", {x = 0, y = -1}},
    {"dirt-7", {x = 0, y = 0}},
    {"dirt-7", {x = 0, y = 1}},
    {"dirt-6", {x = 0, y = 2}},
    {"dirt-6", {x = 0, y = 3}},
    {"dirt-6", {x = 0, y = 4}},
    {"dirt-6", {x = 0, y = 5}},
    {"dirt-6", {x = 0, y = 6}},
    {"dirt-6", {x = 0, y = 7}},
    {"dirt-6", {x = 0, y = 8}},
    {"dirt-6", {x = 0, y = 9}},
    {"dirt-6", {x = 0, y = 10}},
    {"dirt-6", {x = 0, y = 11}},
    {"dirt-6", {x = 0, y = 12}},
    {"dirt-6", {x = 0, y = 13}},
    {"dirt-6", {x = 0, y = 14}},
    {"dirt-6", {x = 0, y = 15}},
    {"dirt-6", {x = 1, y = -16}},
    {"dirt-6", {x = 1, y = -15}},
    {"dirt-6", {x = 1, y = -14}},
    {"dirt-6", {x = 1, y = -13}},
    {"dirt-6", {x = 1, y = -12}},
    {"dirt-7", {x = 1, y = -11}},
    {"dirt-7", {x = 1, y = -10}},
    {"dirt-7", {x = 1, y = -9}},
    {"dirt-7", {x = 1, y = -8}},
    {"dirt-7", {x = 1, y = -7}},
    {"dirt-7", {x = 1, y = -6}},
    {"dirt-7", {x = 1, y = -5}},
    {"dirt-7", {x = 1, y = -4}},
    {"dirt-7", {x = 1, y = -3}},
    {"dirt-7", {x = 1, y = -2}},
    {"dirt-7", {x = 1, y = -1}},
    {"dirt-7", {x = 1, y = 0}},
    {"dirt-7", {x = 1, y = 1}},
    {"dirt-6", {x = 1, y = 2}},
    {"dirt-6", {x = 1, y = 3}},
    {"dirt-6", {x = 1, y = 4}},
    {"dirt-6", {x = 1, y = 5}},
    {"dirt-6", {x = 1, y = 6}},
    {"dirt-6", {x = 1, y = 7}},
    {"dirt-6", {x = 1, y = 8}},
    {"dirt-6", {x = 1, y = 9}},
    {"dirt-6", {x = 1, y = 10}},
    {"dirt-6", {x = 1, y = 11}},
    {"dirt-6", {x = 1, y = 12}},
    {"dirt-6", {x = 1, y = 13}},
    {"dirt-6", {x = 1, y = 14}},
    {"dirt-6", {x = 1, y = 15}},
    {"dirt-6", {x = 2, y = -16}},
    {"dirt-6", {x = 2, y = -15}},
    {"dirt-6", {x = 2, y = -14}},
    {"dirt-6", {x = 2, y = -13}},
    {"dirt-6", {x = 2, y = -12}},
    {"dirt-6", {x = 2, y = -11}},
    {"dirt-7", {x = 2, y = -10}},
    {"dirt-7", {x = 2, y = -9}},
    {"dirt-7", {x = 2, y = -8}},
    {"dirt-7", {x = 2, y = -7}},
    {"dirt-7", {x = 2, y = -6}},
    {"dirt-7", {x = 2, y = -5}},
    {"dirt-7", {x = 2, y = -4}},
    {"dirt-7", {x = 2, y = -3}},
    {"dirt-7", {x = 2, y = -2}},
    {"dirt-7", {x = 2, y = -1}},
    {"dirt-7", {x = 2, y = 0}},
    {"dirt-7", {x = 2, y = 1}},
    {"dirt-6", {x = 2, y = 2}},
    {"dirt-6", {x = 2, y = 3}},
    {"dirt-6", {x = 2, y = 4}},
    {"dirt-6", {x = 2, y = 5}},
    {"dirt-6", {x = 2, y = 6}},
    {"dirt-6", {x = 2, y = 7}},
    {"dirt-6", {x = 2, y = 8}},
    {"dirt-6", {x = 2, y = 9}},
    {"dirt-6", {x = 2, y = 10}},
    {"dirt-6", {x = 2, y = 11}},
    {"dirt-6", {x = 2, y = 12}},
    {"dirt-6", {x = 2, y = 13}},
    {"dirt-6", {x = 2, y = 14}},
    {"dirt-6", {x = 2, y = 15}},
    {"dirt-6", {x = 3, y = -16}},
    {"dirt-6", {x = 3, y = -15}},
    {"dirt-6", {x = 3, y = -14}},
    {"dirt-6", {x = 3, y = -13}},
    {"dirt-6", {x = 3, y = -12}},
    {"dirt-6", {x = 3, y = -11}},
    {"dirt-6", {x = 3, y = -10}},
    {"dirt-6", {x = 3, y = -9}},
    {"dirt-6", {x = 3, y = -8}},
    {"dirt-7", {x = 3, y = -7}},
    {"dirt-7", {x = 3, y = -6}},
    {"dirt-7", {x = 3, y = -5}},
    {"dirt-7", {x = 3, y = -4}},
    {"dirt-7", {x = 3, y = -3}},
    {"dirt-7", {x = 3, y = -2}},
    {"dirt-7", {x = 3, y = -1}},
    {"dirt-7", {x = 3, y = 0}},
    {"dirt-6", {x = 3, y = 1}},
    {"dirt-6", {x = 3, y = 2}},
    {"dirt-6", {x = 3, y = 3}},
    {"dirt-6", {x = 3, y = 4}},
    {"dirt-6", {x = 3, y = 5}},
    {"dirt-6", {x = 3, y = 6}},
    {"dirt-6", {x = 3, y = 7}},
    {"dirt-6", {x = 3, y = 8}},
    {"dirt-6", {x = 3, y = 9}},
    {"dirt-6", {x = 3, y = 10}},
    {"dirt-6", {x = 3, y = 11}},
    {"dirt-6", {x = 3, y = 12}},
    {"dirt-6", {x = 3, y = 13}},
    {"dirt-6", {x = 3, y = 14}},
    {"dirt-6", {x = 3, y = 15}},
    {"dirt-6", {x = 4, y = -16}},
    {"dirt-6", {x = 4, y = -15}},
    {"dirt-6", {x = 4, y = -14}},
    {"dirt-6", {x = 4, y = -13}},
    {"dirt-6", {x = 4, y = -12}},
    {"dirt-6", {x = 4, y = -11}},
    {"dirt-6", {x = 4, y = -10}},
    {"dirt-6", {x = 4, y = -9}},
    {"dirt-6", {x = 4, y = -8}},
    {"dirt-6", {x = 4, y = -7}},
    {"dirt-7", {x = 4, y = -6}},
    {"dirt-7", {x = 4, y = -5}},
    {"dirt-7", {x = 4, y = -4}},
    {"dirt-7", {x = 4, y = -3}},
    {"dirt-7", {x = 4, y = -2}},
    {"dirt-7", {x = 4, y = -1}},
    {"dirt-7", {x = 4, y = 0}},
    {"dirt-6", {x = 4, y = 1}},
    {"dirt-6", {x = 4, y = 2}},
    {"dirt-6", {x = 4, y = 3}},
    {"dirt-6", {x = 4, y = 4}},
    {"dirt-6", {x = 4, y = 5}},
    {"dirt-6", {x = 4, y = 6}},
    {"dirt-6", {x = 4, y = 7}},
    {"dirt-6", {x = 4, y = 8}},
    {"dirt-6", {x = 4, y = 9}},
    {"dirt-6", {x = 4, y = 10}},
    {"dirt-6", {x = 4, y = 11}},
    {"dirt-6", {x = 4, y = 12}},
    {"dirt-6", {x = 4, y = 13}},
    {"dirt-6", {x = 4, y = 14}},
    {"dirt-6", {x = 4, y = 15}},
    {"dirt-6", {x = 5, y = -16}},
    {"dirt-6", {x = 5, y = -15}},
    {"dirt-6", {x = 5, y = -14}},
    {"dirt-6", {x = 5, y = -13}},
    {"dirt-6", {x = 5, y = -12}},
    {"dirt-6", {x = 5, y = -11}},
    {"dirt-6", {x = 5, y = -10}},
    {"dirt-6", {x = 5, y = -9}},
    {"dirt-6", {x = 5, y = -8}},
    {"dirt-6", {x = 5, y = -7}},
    {"dirt-7", {x = 5, y = -6}},
    {"dirt-7", {x = 5, y = -5}},
    {"dirt-7", {x = 5, y = -4}},
    {"dirt-7", {x = 5, y = -3}},
    {"dirt-7", {x = 5, y = -2}},
    {"dirt-7", {x = 5, y = -1}},
    {"dirt-7", {x = 5, y = 0}},
    {"dirt-6", {x = 5, y = 1}},
    {"dirt-6", {x = 5, y = 2}},
    {"dirt-6", {x = 5, y = 3}},
    {"dirt-6", {x = 5, y = 4}},
    {"dirt-6", {x = 5, y = 5}},
    {"dirt-6", {x = 5, y = 6}},
    {"dirt-6", {x = 5, y = 7}},
    {"dirt-6", {x = 5, y = 8}},
    {"dirt-6", {x = 5, y = 9}},
    {"dirt-6", {x = 5, y = 10}},
    {"dirt-6", {x = 5, y = 11}},
    {"dirt-6", {x = 5, y = 12}},
    {"dirt-6", {x = 5, y = 13}},
    {"dirt-6", {x = 5, y = 14}},
    {"dirt-6", {x = 5, y = 15}},
    {"dirt-6", {x = 6, y = -16}},
    {"dirt-6", {x = 6, y = -15}},
    {"dirt-6", {x = 6, y = -14}},
    {"dirt-6", {x = 6, y = -13}},
    {"dirt-7", {x = 6, y = -12}},
    {"dirt-6", {x = 6, y = -11}},
    {"dirt-6", {x = 6, y = -10}},
    {"dirt-6", {x = 6, y = -9}},
    {"dirt-6", {x = 6, y = -8}},
    {"dirt-6", {x = 6, y = -7}},
    {"dirt-7", {x = 6, y = -6}},
    {"dirt-7", {x = 6, y = -5}},
    {"dirt-7", {x = 6, y = -4}},
    {"dirt-7", {x = 6, y = -3}},
    {"dirt-7", {x = 6, y = -2}},
    {"dirt-7", {x = 6, y = -1}},
    {"dirt-7", {x = 6, y = 0}},
    {"dirt-7", {x = 6, y = 1}},
    {"dirt-6", {x = 6, y = 2}},
    {"dirt-6", {x = 6, y = 3}},
    {"dirt-6", {x = 6, y = 4}},
    {"dirt-6", {x = 6, y = 5}},
    {"dirt-6", {x = 6, y = 6}},
    {"dirt-6", {x = 6, y = 7}},
    {"dirt-6", {x = 6, y = 8}},
    {"dirt-6", {x = 6, y = 9}},
    {"dirt-6", {x = 6, y = 10}},
    {"dirt-6", {x = 6, y = 11}},
    {"dirt-6", {x = 6, y = 12}},
    {"dirt-6", {x = 6, y = 13}},
    {"dirt-6", {x = 6, y = 14}},
    {"dirt-6", {x = 6, y = 15}},
    {"grass-4", {x = 7, y = -16}},
    {"dirt-6", {x = 7, y = -15}},
    {"dirt-6", {x = 7, y = -14}},
    {"dirt-7", {x = 7, y = -13}},
    {"dirt-7", {x = 7, y = -12}},
    {"dirt-7", {x = 7, y = -11}},
    {"dirt-6", {x = 7, y = -10}},
    {"dirt-6", {x = 7, y = -9}},
    {"dirt-6", {x = 7, y = -8}},
    {"dirt-6", {x = 7, y = -7}},
    {"dirt-6", {x = 7, y = -6}},
    {"dirt-7", {x = 7, y = -5}},
    {"dirt-7", {x = 7, y = -4}},
    {"dirt-7", {x = 7, y = -3}},
    {"dirt-7", {x = 7, y = -2}},
    {"dirt-7", {x = 7, y = -1}},
    {"dirt-7", {x = 7, y = 0}},
    {"dirt-7", {x = 7, y = 1}},
    {"dirt-6", {x = 7, y = 2}},
    {"dirt-6", {x = 7, y = 3}},
    {"dirt-6", {x = 7, y = 4}},
    {"dirt-6", {x = 7, y = 5}},
    {"dirt-6", {x = 7, y = 6}},
    {"dirt-6", {x = 7, y = 7}},
    {"dirt-6", {x = 7, y = 8}},
    {"dirt-6", {x = 7, y = 9}},
    {"dirt-6", {x = 7, y = 10}},
    {"dirt-6", {x = 7, y = 11}},
    {"dirt-6", {x = 7, y = 12}},
    {"dirt-6", {x = 7, y = 13}},
    {"dirt-6", {x = 7, y = 14}},
    {"dirt-6", {x = 7, y = 15}},
    {"grass-4", {x = 8, y = -16}},
    {"dirt-6", {x = 8, y = -15}},
    {"dirt-6", {x = 8, y = -14}},
    {"dirt-7", {x = 8, y = -13}},
    {"dirt-7", {x = 8, y = -12}},
    {"dirt-7", {x = 8, y = -11}},
    {"dirt-7", {x = 8, y = -10}},
    {"dirt-6", {x = 8, y = -9}},
    {"dirt-6", {x = 8, y = -8}},
    {"dirt-6", {x = 8, y = -7}},
    {"dirt-6", {x = 8, y = -6}},
    {"dirt-6", {x = 8, y = -5}},
    {"dirt-7", {x = 8, y = -4}},
    {"dirt-7", {x = 8, y = -3}},
    {"dirt-7", {x = 8, y = -2}},
    {"dirt-7", {x = 8, y = -1}},
    {"dirt-7", {x = 8, y = 0}},
    {"dirt-6", {x = 8, y = 1}},
    {"dirt-6", {x = 8, y = 2}},
    {"dirt-6", {x = 8, y = 3}},
    {"dirt-6", {x = 8, y = 4}},
    {"dirt-6", {x = 8, y = 5}},
    {"dirt-6", {x = 8, y = 6}},
    {"dirt-6", {x = 8, y = 7}},
    {"dirt-6", {x = 8, y = 8}},
    {"dirt-6", {x = 8, y = 9}},
    {"dirt-6", {x = 8, y = 10}},
    {"dirt-6", {x = 8, y = 11}},
    {"dirt-6", {x = 8, y = 12}},
    {"dirt-6", {x = 8, y = 13}},
    {"dirt-6", {x = 8, y = 14}},
    {"dirt-6", {x = 8, y = 15}},
    {"grass-4", {x = 9, y = -16}},
    {"dirt-7", {x = 9, y = -15}},
    {"dirt-7", {x = 9, y = -14}},
    {"dirt-7", {x = 9, y = -13}},
    {"dirt-7", {x = 9, y = -12}},
    {"dirt-7", {x = 9, y = -11}},
    {"dirt-7", {x = 9, y = -10}},
    {"dirt-6", {x = 9, y = -9}},
    {"dirt-6", {x = 9, y = -8}},
    {"dirt-6", {x = 9, y = -7}},
    {"dirt-6", {x = 9, y = -6}},
    {"dirt-6", {x = 9, y = -5}},
    {"dirt-6", {x = 9, y = -4}},
    {"dirt-6", {x = 9, y = -3}},
    {"dirt-7", {x = 9, y = -2}},
    {"dirt-7", {x = 9, y = -1}},
    {"dirt-6", {x = 9, y = 0}},
    {"dirt-6", {x = 9, y = 1}},
    {"dirt-6", {x = 9, y = 2}},
    {"dirt-6", {x = 9, y = 3}},
    {"dirt-6", {x = 9, y = 4}},
    {"dirt-6", {x = 9, y = 5}},
    {"dirt-6", {x = 9, y = 6}},
    {"dirt-6", {x = 9, y = 7}},
    {"dirt-6", {x = 9, y = 8}},
    {"dirt-6", {x = 9, y = 9}},
    {"dirt-6", {x = 9, y = 10}},
    {"dirt-6", {x = 9, y = 11}},
    {"dirt-6", {x = 9, y = 12}},
    {"dirt-6", {x = 9, y = 13}},
    {"dirt-6", {x = 9, y = 14}},
    {"dirt-6", {x = 9, y = 15}},
    {"grass-4", {x = 10, y = -16}},
    {"dirt-7", {x = 10, y = -15}},
    {"dirt-7", {x = 10, y = -14}},
    {"dirt-7", {x = 10, y = -13}},
    {"dirt-7", {x = 10, y = -12}},
    {"dirt-7", {x = 10, y = -11}},
    {"dirt-7", {x = 10, y = -10}},
    {"dirt-6", {x = 10, y = -9}},
    {"dirt-6", {x = 10, y = -8}},
    {"dirt-6", {x = 10, y = -7}},
    {"dirt-6", {x = 10, y = -6}},
    {"dirt-6", {x = 10, y = -5}},
    {"dirt-6", {x = 10, y = -4}},
    {"dirt-6", {x = 10, y = -3}},
    {"dirt-6", {x = 10, y = -2}},
    {"dirt-6", {x = 10, y = -1}},
    {"dirt-6", {x = 10, y = 0}},
    {"dirt-6", {x = 10, y = 1}},
    {"dirt-6", {x = 10, y = 2}},
    {"dirt-6", {x = 10, y = 3}},
    {"dirt-6", {x = 10, y = 4}},
    {"dirt-6", {x = 10, y = 5}},
    {"dirt-6", {x = 10, y = 6}},
    {"dirt-6", {x = 10, y = 7}},
    {"dirt-6", {x = 10, y = 8}},
    {"dirt-6", {x = 10, y = 9}},
    {"dirt-6", {x = 10, y = 10}},
    {"dirt-6", {x = 10, y = 11}},
    {"dirt-6", {x = 10, y = 12}},
    {"dirt-6", {x = 10, y = 13}},
    {"dirt-6", {x = 10, y = 14}},
    {"dirt-6", {x = 10, y = 15}},
    {"grass-4", {x = 11, y = -16}},
    {"grass-4", {x = 11, y = -15}},
    {"dirt-7", {x = 11, y = -14}},
    {"dirt-7", {x = 11, y = -13}},
    {"dirt-7", {x = 11, y = -12}},
    {"dirt-7", {x = 11, y = -11}},
    {"dirt-7", {x = 11, y = -10}},
    {"grass-4", {x = 11, y = -9}},
    {"grass-4", {x = 11, y = -8}},
    {"dirt-6", {x = 11, y = -7}},
    {"dirt-6", {x = 11, y = -6}},
    {"dirt-6", {x = 11, y = -5}},
    {"dirt-5", {x = 11, y = -4}},
    {"dirt-5", {x = 11, y = -3}},
    {"dirt-5", {x = 11, y = -2}},
    {"dirt-5", {x = 11, y = -1}},
    {"dirt-6", {x = 11, y = 0}},
    {"dirt-6", {x = 11, y = 1}},
    {"dirt-6", {x = 11, y = 2}},
    {"dirt-6", {x = 11, y = 3}},
    {"dirt-6", {x = 11, y = 4}},
    {"dirt-6", {x = 11, y = 5}},
    {"dirt-6", {x = 11, y = 6}},
    {"dirt-6", {x = 11, y = 7}},
    {"dirt-6", {x = 11, y = 8}},
    {"dirt-6", {x = 11, y = 9}},
    {"dirt-6", {x = 11, y = 10}},
    {"dirt-6", {x = 11, y = 11}},
    {"dirt-6", {x = 11, y = 12}},
    {"dirt-6", {x = 11, y = 13}},
    {"dirt-6", {x = 11, y = 14}},
    {"dirt-6", {x = 11, y = 15}},
    {"grass-4", {x = 12, y = -16}},
    {"grass-4", {x = 12, y = -15}},
    {"grass-4", {x = 12, y = -14}},
    {"grass-4", {x = 12, y = -13}},
    {"dirt-7", {x = 12, y = -12}},
    {"dirt-7", {x = 12, y = -11}},
    {"grass-4", {x = 12, y = -10}},
    {"grass-4", {x = 12, y = -9}},
    {"grass-4", {x = 12, y = -8}},
    {"grass-4", {x = 12, y = -7}},
    {"dirt-5", {x = 12, y = -6}},
    {"dirt-5", {x = 12, y = -5}},
    {"dirt-5", {x = 12, y = -4}},
    {"dirt-5", {x = 12, y = -3}},
    {"dirt-5", {x = 12, y = -2}},
    {"dirt-5", {x = 12, y = -1}},
    {"dirt-6", {x = 12, y = 0}},
    {"dirt-6", {x = 12, y = 1}},
    {"dirt-6", {x = 12, y = 2}},
    {"dirt-6", {x = 12, y = 3}},
    {"dirt-6", {x = 12, y = 4}},
    {"dirt-6", {x = 12, y = 5}},
    {"dirt-6", {x = 12, y = 6}},
    {"dirt-6", {x = 12, y = 7}},
    {"dirt-6", {x = 12, y = 8}},
    {"dirt-6", {x = 12, y = 9}},
    {"dirt-6", {x = 12, y = 10}},
    {"dirt-6", {x = 12, y = 11}},
    {"dirt-6", {x = 12, y = 12}},
    {"dirt-6", {x = 12, y = 13}},
    {"dirt-6", {x = 12, y = 14}},
    {"dirt-6", {x = 12, y = 15}},
    {"dirt-7", {x = 13, y = -16}},
    {"grass-4", {x = 13, y = -15}},
    {"grass-4", {x = 13, y = -14}},
    {"grass-4", {x = 13, y = -13}},
    {"grass-4", {x = 13, y = -12}},
    {"grass-4", {x = 13, y = -11}},
    {"grass-4", {x = 13, y = -10}},
    {"grass-4", {x = 13, y = -9}},
    {"grass-4", {x = 13, y = -8}},
    {"grass-4", {x = 13, y = -7}},
    {"dirt-5", {x = 13, y = -6}},
    {"dirt-5", {x = 13, y = -5}},
    {"dirt-5", {x = 13, y = -4}},
    {"dirt-5", {x = 13, y = -3}},
    {"dirt-5", {x = 13, y = -2}},
    {"dirt-5", {x = 13, y = -1}},
    {"dirt-6", {x = 13, y = 0}},
    {"dirt-6", {x = 13, y = 1}},
    {"dirt-6", {x = 13, y = 2}},
    {"dirt-5", {x = 13, y = 3}},
    {"dirt-5", {x = 13, y = 4}},
    {"dirt-6", {x = 13, y = 5}},
    {"dirt-6", {x = 13, y = 6}},
    {"dirt-6", {x = 13, y = 7}},
    {"dirt-6", {x = 13, y = 8}},
    {"dirt-6", {x = 13, y = 9}},
    {"dirt-6", {x = 13, y = 10}},
    {"dirt-6", {x = 13, y = 11}},
    {"dirt-6", {x = 13, y = 12}},
    {"dirt-6", {x = 13, y = 13}},
    {"dirt-6", {x = 13, y = 14}},
    {"dirt-6", {x = 13, y = 15}},
    {"dirt-7", {x = 14, y = -16}},
    {"grass-4", {x = 14, y = -15}},
    {"grass-4", {x = 14, y = -14}},
    {"grass-4", {x = 14, y = -13}},
    {"grass-4", {x = 14, y = -12}},
    {"grass-4", {x = 14, y = -11}},
    {"grass-4", {x = 14, y = -10}},
    {"grass-4", {x = 14, y = -9}},
    {"grass-4", {x = 14, y = -8}},
    {"grass-4", {x = 14, y = -7}},
    {"grass-4", {x = 14, y = -6}},
    {"dirt-5", {x = 14, y = -5}},
    {"dirt-5", {x = 14, y = -4}},
    {"dirt-5", {x = 14, y = -3}},
    {"dirt-5", {x = 14, y = -2}},
    {"dirt-6", {x = 14, y = -1}},
    {"dirt-6", {x = 14, y = 0}},
    {"dirt-6", {x = 14, y = 1}},
    {"dirt-6", {x = 14, y = 2}},
    {"dirt-5", {x = 14, y = 3}},
    {"dirt-5", {x = 14, y = 4}},
    {"dirt-6", {x = 14, y = 5}},
    {"dirt-6", {x = 14, y = 6}},
    {"dirt-6", {x = 14, y = 7}},
    {"dirt-6", {x = 14, y = 8}},
    {"dirt-6", {x = 14, y = 9}},
    {"dirt-6", {x = 14, y = 10}},
    {"dirt-6", {x = 14, y = 11}},
    {"dirt-6", {x = 14, y = 12}},
    {"dirt-6", {x = 14, y = 13}},
    {"dirt-6", {x = 14, y = 14}},
    {"dirt-6", {x = 14, y = 15}},
    {"grass-4", {x = 15, y = -16}},
    {"grass-4", {x = 15, y = -15}},
    {"grass-4", {x = 15, y = -14}},
    {"grass-4", {x = 15, y = -13}},
    {"dirt-5", {x = 15, y = -12}},
    {"dirt-5", {x = 15, y = -11}},
    {"dirt-5", {x = 15, y = -10}},
    {"dirt-5", {x = 15, y = -9}},
    {"dirt-5", {x = 15, y = -8}},
    {"grass-4", {x = 15, y = -7}},
    {"grass-4", {x = 15, y = -6}},
    {"grass-4", {x = 15, y = -5}},
    {"dirt-6", {x = 15, y = -4}},
    {"dirt-6", {x = 15, y = -3}},
    {"dirt-6", {x = 15, y = -2}},
    {"dirt-6", {x = 15, y = -1}},
    {"dirt-6", {x = 15, y = 0}},
    {"dirt-6", {x = 15, y = 1}},
    {"dirt-6", {x = 15, y = 2}},
    {"dirt-6", {x = 15, y = 3}},
    {"dirt-6", {x = 15, y = 4}},
    {"dirt-6", {x = 15, y = 5}},
    {"dirt-6", {x = 15, y = 6}},
    {"dirt-6", {x = 15, y = 7}},
    {"dirt-6", {x = 15, y = 8}},
    {"dirt-6", {x = 15, y = 9}},
    {"dirt-6", {x = 15, y = 10}},
    {"dirt-6", {x = 15, y = 11}},
    {"dirt-6", {x = 15, y = 12}},
    {"dirt-6", {x = 15, y = 13}},
    {"dirt-6", {x = 15, y = 14}},
    {"dirt-6", {x = 15, y = 15}},
  }
}
