return
{
  entities =
  {
    {"laser-turret", {x = -14, y = -14}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -12, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -10, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -8, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -6, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -4, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -2, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = 0, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = 2, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 0.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = 4, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = 6, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -14, y = -12}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"fast-inserter", {x = -10.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = -8.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = -6.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = -1.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 0.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 2.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 5.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 4.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"fast-inserter", {x = -12.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -11.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -10.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -9.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -8.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -7.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -6.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -5.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -1.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -10.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 0.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 0.5, y = -10.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 1.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 5.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 4.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"laser-turret", {x = 6, y = -10}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -9.5}, {force = "enemy", }},
    {"steel-chest", {x = -6.5, y = -8.5}, {items = {["assembling-machine-3"] = 50}, }},
    {"stone-wall", {x = -7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -9.5}, {force = "enemy", }},
    {"steel-chest", {x = -5.5, y = -8.5}, {items = {["processing-unit"] = 100}, }},
    {"stone-wall", {x = -4.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -9.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = -9.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -2.5, y = -9.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -9.5}, {force = "enemy", }},
    {"express-splitter", {x = 0, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -8.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 0.5, y = -9.5}, {force = "enemy", }},
    {"purple-crystal-gen", {x = 3.5, y = -9}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -7.5}, {force = "enemy", }},
    {"substation", {x = -6, y = -7}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -7.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -6.5}, {force = "enemy", }},
    {"substation", {x = 7, y = -7}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -4.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -5.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -4.5}, {force = "enemy", }},
    {"steel-chest", {x = 3.5, y = -4.5}, {items = {["effectivity-module-3"] = 1, ["productivity-module-3"] = 1, ["speed-module-3"] = 1}, }},
    {"steel-chest", {x = 5.5, y = -4.5}, {items = {["rocket-control-unit"] = 10}, }},
    {"aliencon-robot", {x = 7.7, y = -4.24}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.7, y = -4.38}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.7, y = -4.47}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.7, y = -4.53}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.86, y = -4.1}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.88, y = -4.21}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.91, y = -4.3}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.91, y = -4.36}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.91, y = -4.44}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.91, y = -4.47}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.88, y = -4.53}, {force = "enemy", }},
    {"roboport", {x = 9, y = -4}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"stone-wall", {x = 11.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = -2.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -2.5, y = -2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -3.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -2.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.28, y = -2.32}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.28, y = -2.29}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.31, y = -2.35}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.31, y = -2.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.36, y = -2.69}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.48, y = -3.02}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.62, y = -3.51}, {force = "enemy", }},
    {"aliencon-robot", {x = 7.7, y = -3.99}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.77, y = -2.4}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.77, y = -2.37}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.77, y = -2.4}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.74, y = -2.43}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.74, y = -2.54}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.74, y = -2.63}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.74, y = -2.69}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.74, y = -2.71}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.77, y = -2.77}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.77, y = -2.83}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.77, y = -2.97}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.8, y = -3.14}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.83, y = -3.31}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.83, y = -3.54}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.83, y = -3.73}, {force = "enemy", }},
    {"aliencon-robot", {x = 6.83, y = -3.93}, {force = "enemy", }},
    {"logistic-chest-storage", {x = 6.5, y = -2.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"stone-wall", {x = 11.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -3.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = -4.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = -4.5, y = -1.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -1.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -1.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 5.5, y = -0.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"logistic-chest-passive-provider", {x = 4.5, y = -0.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = 5.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -1.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 6.5, y = -0.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = 7.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -1.5}, {force = "enemy", }},
    {"laser-turret", {x = 9, y = 0}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = -4.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = -4.5, y = 0.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 1.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 1.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 1.5, y = 1.5}, {dir = "west", force = "enemy", }},
    {"express-splitter", {x = 0.5, y = 1}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = 5.5, y = 0.5}, {force = "enemy", }},
    {"fast-inserter", {x = 4.5, y = 0.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 5.5, y = 1.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"logistic-chest-passive-provider", {x = 4.5, y = 1.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"fast-inserter", {x = 6.5, y = 0.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 6.5, y = 1.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = 7.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 0.5}, {force = "enemy", }},
    {"laser-turret", {x = 9, y = 2}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 2.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -2.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 3.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 2.5}, {force = "enemy", }},
    {"assembling-machine-2", {x = 1.5, y = 4.5}, {force = "enemy", recipe = "cryexplosive-rounds-magazine", }},
    {"fast-inserter", {x = 1.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 5.5, y = 2.5}, {force = "enemy", }},
    {"fast-inserter", {x = 4.5, y = 2.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 5.5, y = 3.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"logistic-chest-passive-provider", {x = 4.5, y = 3.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"fast-inserter", {x = 6.5, y = 2.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 6.5, y = 3.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = 7.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 2.5}, {force = "enemy", }},
    {"laser-turret", {x = 9, y = 4}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 4.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 5.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 4.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 4.5}, {force = "enemy", }},
    {"fast-inserter", {x = 3.5, y = 5.5}, {dir = "east", force = "enemy", }},
    {"fast-inserter", {x = 5.5, y = 4.5}, {force = "enemy", }},
    {"fast-inserter", {x = 4.5, y = 4.5}, {force = "enemy", }},
    {"electric-furnace", {x = 5.5, y = 6.5}, {force = "enemy", }},
    {"fast-inserter", {x = 6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 4.5}, {force = "enemy", }},
    {"laser-turret", {x = 9, y = 6}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 6.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 7.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 6.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 6.5}, {force = "enemy", }},
    {"green-crystal-gen", {x = 2.5, y = 7}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = 9, y = 8}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 8.5}, {force = "enemy", }},
    {"substation", {x = -6, y = 10}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 8.5}, {force = "enemy", }},
    {"gate", {x = -2.5, y = 9.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -3.5, y = 9.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 9.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 8.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 8.5}, {force = "enemy", }},
    {"substation", {x = 7, y = 10}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 10.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = 11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = 11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -1.5, y = 11.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-splitter", {x = -1, y = 10.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 1.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 0.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 10.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 10.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 5.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 4.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 10.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 7.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 6.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 9.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 8.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 10.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 11.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 10.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 10.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 13.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 12.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 10.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = 13}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 13.5}, {force = "enemy", }},
    {"laser-turret", {x = -12, y = 14}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = -10, y = 14}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = -8, y = 14}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = -6, y = 14}, {dir = "south", force = "enemy", }},
    {"gun-turret", {x = -4, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -3.5, y = 12.5}, {force = "enemy", }},
    {"fast-inserter", {x = -2.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = -2, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"laser-turret", {x = 0, y = 14}, {dir = "south", force = "enemy", }},
    {"gun-turret", {x = 2, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = 2.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = 4, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = 4.5, y = 12.5}, {force = "enemy", }},
    {"fast-inserter", {x = 5.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = 6, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"gun-turret", {x = 8, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = 8.5, y = 12.5}, {force = "enemy", }},
    {"fast-inserter", {x = 9.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = 10, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = 11.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = 12, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = 13.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = 14, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 14.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -16, y = -16}},
    {"grass-1", {x = -16, y = -15}},
    {"grass-1", {x = -16, y = -14}},
    {"grass-1", {x = -16, y = -13}},
    {"grass-1", {x = -16, y = -12}},
    {"grass-1", {x = -16, y = -11}},
    {"grass-1", {x = -16, y = -10}},
    {"grass-1", {x = -16, y = -9}},
    {"grass-1", {x = -16, y = -8}},
    {"grass-1", {x = -16, y = -7}},
    {"grass-3", {x = -16, y = -6}},
    {"grass-3", {x = -16, y = -5}},
    {"grass-3", {x = -16, y = -4}},
    {"grass-3", {x = -16, y = -3}},
    {"grass-1", {x = -16, y = -2}},
    {"refined-concrete", {x = -16, y = -1}},
    {"refined-concrete", {x = -16, y = 0}},
    {"grass-1", {x = -16, y = 1}},
    {"grass-1", {x = -16, y = 2}},
    {"grass-1", {x = -16, y = 3}},
    {"grass-1", {x = -16, y = 4}},
    {"grass-1", {x = -16, y = 5}},
    {"grass-1", {x = -16, y = 6}},
    {"grass-1", {x = -16, y = 7}},
    {"grass-1", {x = -16, y = 8}},
    {"grass-1", {x = -16, y = 9}},
    {"grass-1", {x = -16, y = 10}},
    {"grass-1", {x = -16, y = 11}},
    {"grass-1", {x = -16, y = 12}},
    {"grass-1", {x = -16, y = 13}},
    {"grass-3", {x = -16, y = 14}},
    {"grass-3", {x = -16, y = 15}},
    {"grass-1", {x = -15, y = -16}},
    {"grass-1", {x = -15, y = -15}},
    {"grass-1", {x = -15, y = -14}},
    {"grass-1", {x = -15, y = -13}},
    {"grass-1", {x = -15, y = -12}},
    {"grass-1", {x = -15, y = -11}},
    {"grass-1", {x = -15, y = -10}},
    {"grass-1", {x = -15, y = -9}},
    {"grass-1", {x = -15, y = -8}},
    {"grass-1", {x = -15, y = -7}},
    {"grass-3", {x = -15, y = -6}},
    {"grass-3", {x = -15, y = -5}},
    {"grass-3", {x = -15, y = -4}},
    {"grass-3", {x = -15, y = -3}},
    {"grass-1", {x = -15, y = -2}},
    {"refined-concrete", {x = -15, y = -1}},
    {"refined-concrete", {x = -15, y = 0}},
    {"grass-1", {x = -15, y = 1}},
    {"grass-1", {x = -15, y = 2}},
    {"grass-1", {x = -15, y = 3}},
    {"grass-1", {x = -15, y = 4}},
    {"grass-1", {x = -15, y = 5}},
    {"grass-1", {x = -15, y = 6}},
    {"grass-1", {x = -15, y = 7}},
    {"grass-1", {x = -15, y = 8}},
    {"grass-1", {x = -15, y = 9}},
    {"grass-1", {x = -15, y = 10}},
    {"grass-1", {x = -15, y = 11}},
    {"grass-1", {x = -15, y = 12}},
    {"grass-1", {x = -15, y = 13}},
    {"grass-1", {x = -15, y = 14}},
    {"grass-1", {x = -15, y = 15}},
    {"grass-1", {x = -14, y = -16}},
    {"grass-1", {x = -14, y = -15}},
    {"grass-1", {x = -14, y = -14}},
    {"grass-1", {x = -14, y = -13}},
    {"grass-1", {x = -14, y = -12}},
    {"grass-1", {x = -14, y = -11}},
    {"grass-1", {x = -14, y = -10}},
    {"grass-1", {x = -14, y = -9}},
    {"grass-1", {x = -14, y = -8}},
    {"grass-1", {x = -14, y = -7}},
    {"grass-1", {x = -14, y = -6}},
    {"grass-3", {x = -14, y = -5}},
    {"grass-3", {x = -14, y = -4}},
    {"grass-3", {x = -14, y = -3}},
    {"grass-1", {x = -14, y = -2}},
    {"refined-concrete", {x = -14, y = -1}},
    {"refined-concrete", {x = -14, y = 0}},
    {"grass-1", {x = -14, y = 1}},
    {"grass-1", {x = -14, y = 2}},
    {"grass-1", {x = -14, y = 3}},
    {"grass-1", {x = -14, y = 4}},
    {"grass-1", {x = -14, y = 5}},
    {"grass-1", {x = -14, y = 6}},
    {"grass-1", {x = -14, y = 7}},
    {"grass-1", {x = -14, y = 8}},
    {"grass-1", {x = -14, y = 9}},
    {"grass-1", {x = -14, y = 10}},
    {"grass-1", {x = -14, y = 11}},
    {"grass-1", {x = -14, y = 12}},
    {"grass-1", {x = -14, y = 13}},
    {"grass-1", {x = -14, y = 14}},
    {"grass-1", {x = -14, y = 15}},
    {"grass-1", {x = -13, y = -16}},
    {"grass-1", {x = -13, y = -15}},
    {"grass-1", {x = -13, y = -14}},
    {"grass-1", {x = -13, y = -13}},
    {"grass-1", {x = -13, y = -12}},
    {"grass-1", {x = -13, y = -11}},
    {"grass-1", {x = -13, y = -10}},
    {"grass-1", {x = -13, y = -9}},
    {"grass-1", {x = -13, y = -8}},
    {"grass-1", {x = -13, y = -7}},
    {"grass-1", {x = -13, y = -6}},
    {"grass-3", {x = -13, y = -5}},
    {"grass-3", {x = -13, y = -4}},
    {"grass-3", {x = -13, y = -3}},
    {"grass-1", {x = -13, y = -2}},
    {"refined-concrete", {x = -13, y = -1}},
    {"refined-concrete", {x = -13, y = 0}},
    {"grass-1", {x = -13, y = 1}},
    {"grass-1", {x = -13, y = 2}},
    {"grass-1", {x = -13, y = 3}},
    {"grass-1", {x = -13, y = 4}},
    {"grass-1", {x = -13, y = 5}},
    {"grass-1", {x = -13, y = 6}},
    {"grass-1", {x = -13, y = 7}},
    {"grass-1", {x = -13, y = 8}},
    {"grass-1", {x = -13, y = 9}},
    {"grass-1", {x = -13, y = 10}},
    {"grass-1", {x = -13, y = 11}},
    {"grass-1", {x = -13, y = 12}},
    {"grass-1", {x = -13, y = 13}},
    {"grass-1", {x = -13, y = 14}},
    {"grass-1", {x = -13, y = 15}},
    {"grass-1", {x = -12, y = -16}},
    {"grass-1", {x = -12, y = -15}},
    {"grass-1", {x = -12, y = -14}},
    {"grass-1", {x = -12, y = -13}},
    {"grass-1", {x = -12, y = -12}},
    {"grass-1", {x = -12, y = -11}},
    {"grass-1", {x = -12, y = -10}},
    {"grass-1", {x = -12, y = -9}},
    {"grass-1", {x = -12, y = -8}},
    {"grass-1", {x = -12, y = -7}},
    {"grass-1", {x = -12, y = -6}},
    {"grass-1", {x = -12, y = -5}},
    {"grass-3", {x = -12, y = -4}},
    {"grass-3", {x = -12, y = -3}},
    {"grass-1", {x = -12, y = -2}},
    {"refined-concrete", {x = -12, y = -1}},
    {"refined-concrete", {x = -12, y = 0}},
    {"grass-1", {x = -12, y = 1}},
    {"grass-1", {x = -12, y = 2}},
    {"grass-1", {x = -12, y = 3}},
    {"grass-1", {x = -12, y = 4}},
    {"grass-1", {x = -12, y = 5}},
    {"grass-1", {x = -12, y = 6}},
    {"grass-1", {x = -12, y = 7}},
    {"grass-1", {x = -12, y = 8}},
    {"grass-1", {x = -12, y = 9}},
    {"grass-1", {x = -12, y = 10}},
    {"grass-1", {x = -12, y = 11}},
    {"grass-1", {x = -12, y = 12}},
    {"grass-1", {x = -12, y = 13}},
    {"grass-1", {x = -12, y = 14}},
    {"grass-1", {x = -12, y = 15}},
    {"grass-1", {x = -11, y = -16}},
    {"grass-1", {x = -11, y = -15}},
    {"grass-1", {x = -11, y = -14}},
    {"grass-1", {x = -11, y = -13}},
    {"grass-1", {x = -11, y = -12}},
    {"grass-1", {x = -11, y = -11}},
    {"grass-1", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-1", {x = -11, y = -5}},
    {"grass-1", {x = -11, y = -4}},
    {"grass-1", {x = -11, y = -3}},
    {"grass-1", {x = -11, y = -2}},
    {"refined-concrete", {x = -11, y = -1}},
    {"refined-concrete", {x = -11, y = 0}},
    {"grass-1", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-1", {x = -11, y = 4}},
    {"grass-1", {x = -11, y = 5}},
    {"grass-1", {x = -11, y = 6}},
    {"grass-1", {x = -11, y = 7}},
    {"grass-1", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"grass-1", {x = -11, y = 10}},
    {"grass-1", {x = -11, y = 11}},
    {"grass-1", {x = -11, y = 12}},
    {"grass-1", {x = -11, y = 13}},
    {"grass-1", {x = -11, y = 14}},
    {"grass-1", {x = -11, y = 15}},
    {"grass-1", {x = -10, y = -16}},
    {"grass-1", {x = -10, y = -15}},
    {"grass-1", {x = -10, y = -14}},
    {"grass-1", {x = -10, y = -13}},
    {"grass-1", {x = -10, y = -12}},
    {"grass-1", {x = -10, y = -11}},
    {"grass-1", {x = -10, y = -10}},
    {"grass-1", {x = -10, y = -9}},
    {"grass-1", {x = -10, y = -8}},
    {"grass-1", {x = -10, y = -7}},
    {"grass-1", {x = -10, y = -6}},
    {"grass-1", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-1", {x = -10, y = -3}},
    {"grass-1", {x = -10, y = -2}},
    {"refined-concrete", {x = -10, y = -1}},
    {"refined-concrete", {x = -10, y = 0}},
    {"grass-1", {x = -10, y = 1}},
    {"grass-1", {x = -10, y = 2}},
    {"grass-1", {x = -10, y = 3}},
    {"grass-1", {x = -10, y = 4}},
    {"grass-1", {x = -10, y = 5}},
    {"grass-1", {x = -10, y = 6}},
    {"grass-1", {x = -10, y = 7}},
    {"grass-1", {x = -10, y = 8}},
    {"grass-3", {x = -10, y = 9}},
    {"grass-3", {x = -10, y = 10}},
    {"grass-3", {x = -10, y = 11}},
    {"grass-3", {x = -10, y = 12}},
    {"grass-1", {x = -10, y = 13}},
    {"grass-1", {x = -10, y = 14}},
    {"grass-1", {x = -10, y = 15}},
    {"grass-1", {x = -9, y = -16}},
    {"grass-1", {x = -9, y = -15}},
    {"grass-1", {x = -9, y = -14}},
    {"grass-1", {x = -9, y = -13}},
    {"grass-1", {x = -9, y = -12}},
    {"grass-1", {x = -9, y = -11}},
    {"grass-1", {x = -9, y = -10}},
    {"grass-1", {x = -9, y = -9}},
    {"grass-1", {x = -9, y = -8}},
    {"grass-1", {x = -9, y = -7}},
    {"grass-1", {x = -9, y = -6}},
    {"grass-1", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"grass-1", {x = -9, y = -2}},
    {"refined-concrete", {x = -9, y = -1}},
    {"refined-concrete", {x = -9, y = 0}},
    {"grass-1", {x = -9, y = 1}},
    {"grass-1", {x = -9, y = 2}},
    {"grass-1", {x = -9, y = 3}},
    {"grass-1", {x = -9, y = 4}},
    {"grass-1", {x = -9, y = 5}},
    {"grass-1", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-3", {x = -9, y = 8}},
    {"grass-3", {x = -9, y = 9}},
    {"grass-3", {x = -9, y = 10}},
    {"grass-3", {x = -9, y = 11}},
    {"grass-3", {x = -9, y = 12}},
    {"grass-3", {x = -9, y = 13}},
    {"grass-1", {x = -9, y = 14}},
    {"grass-1", {x = -9, y = 15}},
    {"grass-1", {x = -8, y = -16}},
    {"grass-1", {x = -8, y = -15}},
    {"grass-1", {x = -8, y = -14}},
    {"grass-1", {x = -8, y = -13}},
    {"grass-1", {x = -8, y = -12}},
    {"grass-1", {x = -8, y = -11}},
    {"grass-1", {x = -8, y = -10}},
    {"grass-1", {x = -8, y = -9}},
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-1", {x = -8, y = -2}},
    {"refined-concrete", {x = -8, y = -1}},
    {"refined-concrete", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-3", {x = -8, y = 9}},
    {"grass-3", {x = -8, y = 10}},
    {"grass-3", {x = -8, y = 11}},
    {"grass-3", {x = -8, y = 12}},
    {"grass-1", {x = -8, y = 13}},
    {"grass-1", {x = -8, y = 14}},
    {"grass-1", {x = -8, y = 15}},
    {"grass-1", {x = -7, y = -16}},
    {"grass-1", {x = -7, y = -15}},
    {"grass-1", {x = -7, y = -14}},
    {"grass-1", {x = -7, y = -13}},
    {"grass-1", {x = -7, y = -12}},
    {"grass-1", {x = -7, y = -11}},
    {"grass-1", {x = -7, y = -10}},
    {"grass-1", {x = -7, y = -9}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-1", {x = -7, y = -2}},
    {"refined-concrete", {x = -7, y = -1}},
    {"refined-concrete", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -7, y = 8}},
    {"grass-1", {x = -7, y = 9}},
    {"grass-3", {x = -7, y = 10}},
    {"grass-3", {x = -7, y = 11}},
    {"grass-3", {x = -7, y = 12}},
    {"grass-1", {x = -7, y = 13}},
    {"grass-1", {x = -7, y = 14}},
    {"grass-1", {x = -7, y = 15}},
    {"grass-1", {x = -6, y = -16}},
    {"grass-1", {x = -6, y = -15}},
    {"grass-1", {x = -6, y = -14}},
    {"grass-1", {x = -6, y = -13}},
    {"grass-1", {x = -6, y = -12}},
    {"grass-1", {x = -6, y = -11}},
    {"grass-1", {x = -6, y = -10}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"refined-concrete", {x = -6, y = -1}},
    {"refined-concrete", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"grass-1", {x = -6, y = 9}},
    {"grass-1", {x = -6, y = 10}},
    {"grass-1", {x = -6, y = 11}},
    {"grass-1", {x = -6, y = 12}},
    {"grass-1", {x = -6, y = 13}},
    {"grass-1", {x = -6, y = 14}},
    {"grass-1", {x = -6, y = 15}},
    {"grass-1", {x = -5, y = -16}},
    {"grass-1", {x = -5, y = -15}},
    {"grass-1", {x = -5, y = -14}},
    {"grass-1", {x = -5, y = -13}},
    {"grass-1", {x = -5, y = -12}},
    {"grass-1", {x = -5, y = -11}},
    {"grass-1", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"refined-concrete", {x = -5, y = -1}},
    {"refined-concrete", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -5, y = 8}},
    {"grass-1", {x = -5, y = 9}},
    {"grass-1", {x = -5, y = 10}},
    {"grass-1", {x = -5, y = 11}},
    {"grass-1", {x = -5, y = 12}},
    {"grass-1", {x = -5, y = 13}},
    {"grass-1", {x = -5, y = 14}},
    {"grass-1", {x = -5, y = 15}},
    {"grass-1", {x = -4, y = -16}},
    {"grass-1", {x = -4, y = -15}},
    {"grass-1", {x = -4, y = -14}},
    {"grass-1", {x = -4, y = -13}},
    {"grass-1", {x = -4, y = -12}},
    {"grass-1", {x = -4, y = -11}},
    {"grass-1", {x = -4, y = -10}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"refined-concrete", {x = -4, y = -1}},
    {"refined-concrete", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -4, y = 8}},
    {"grass-1", {x = -4, y = 9}},
    {"grass-1", {x = -4, y = 10}},
    {"grass-1", {x = -4, y = 11}},
    {"grass-1", {x = -4, y = 12}},
    {"grass-1", {x = -4, y = 13}},
    {"grass-1", {x = -4, y = 14}},
    {"grass-1", {x = -4, y = 15}},
    {"grass-1", {x = -3, y = -16}},
    {"grass-1", {x = -3, y = -15}},
    {"grass-1", {x = -3, y = -14}},
    {"grass-1", {x = -3, y = -13}},
    {"grass-1", {x = -3, y = -12}},
    {"grass-1", {x = -3, y = -11}},
    {"grass-1", {x = -3, y = -10}},
    {"refined-concrete", {x = -3, y = -9}},
    {"refined-concrete", {x = -3, y = -8}},
    {"refined-concrete", {x = -3, y = -7}},
    {"refined-concrete", {x = -3, y = -6}},
    {"refined-concrete", {x = -3, y = -5}},
    {"refined-concrete", {x = -3, y = -4}},
    {"refined-concrete", {x = -3, y = -3}},
    {"refined-concrete", {x = -3, y = -2}},
    {"refined-concrete", {x = -3, y = -1}},
    {"refined-concrete", {x = -3, y = 0}},
    {"refined-concrete", {x = -3, y = 1}},
    {"refined-concrete", {x = -3, y = 2}},
    {"refined-concrete", {x = -3, y = 3}},
    {"refined-concrete", {x = -3, y = 4}},
    {"refined-concrete", {x = -3, y = 5}},
    {"refined-concrete", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -3, y = 8}},
    {"grass-1", {x = -3, y = 9}},
    {"grass-1", {x = -3, y = 10}},
    {"grass-1", {x = -3, y = 11}},
    {"grass-1", {x = -3, y = 12}},
    {"grass-1", {x = -3, y = 13}},
    {"grass-1", {x = -3, y = 14}},
    {"grass-1", {x = -3, y = 15}},
    {"grass-1", {x = -2, y = -16}},
    {"grass-1", {x = -2, y = -15}},
    {"grass-1", {x = -2, y = -14}},
    {"grass-1", {x = -2, y = -13}},
    {"grass-1", {x = -2, y = -12}},
    {"grass-1", {x = -2, y = -11}},
    {"grass-1", {x = -2, y = -10}},
    {"refined-concrete", {x = -2, y = -9}},
    {"refined-concrete", {x = -2, y = -8}},
    {"refined-concrete", {x = -2, y = -7}},
    {"refined-concrete", {x = -2, y = -6}},
    {"refined-concrete", {x = -2, y = -5}},
    {"refined-concrete", {x = -2, y = -4}},
    {"refined-concrete", {x = -2, y = -3}},
    {"refined-concrete", {x = -2, y = -2}},
    {"refined-concrete", {x = -2, y = -1}},
    {"refined-concrete", {x = -2, y = 0}},
    {"refined-concrete", {x = -2, y = 1}},
    {"refined-concrete", {x = -2, y = 2}},
    {"refined-concrete", {x = -2, y = 3}},
    {"refined-concrete", {x = -2, y = 4}},
    {"refined-concrete", {x = -2, y = 5}},
    {"refined-concrete", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -2, y = 8}},
    {"grass-1", {x = -2, y = 9}},
    {"grass-1", {x = -2, y = 10}},
    {"grass-1", {x = -2, y = 11}},
    {"grass-1", {x = -2, y = 12}},
    {"grass-1", {x = -2, y = 13}},
    {"grass-1", {x = -2, y = 14}},
    {"grass-1", {x = -2, y = 15}},
    {"grass-1", {x = -1, y = -16}},
    {"grass-1", {x = -1, y = -15}},
    {"grass-1", {x = -1, y = -14}},
    {"grass-1", {x = -1, y = -13}},
    {"grass-1", {x = -1, y = -12}},
    {"grass-1", {x = -1, y = -11}},
    {"grass-1", {x = -1, y = -10}},
    {"refined-concrete", {x = -1, y = -9}},
    {"refined-concrete", {x = -1, y = -8}},
    {"refined-concrete", {x = -1, y = -7}},
    {"refined-concrete", {x = -1, y = -6}},
    {"refined-concrete", {x = -1, y = -5}},
    {"refined-concrete", {x = -1, y = -4}},
    {"refined-concrete", {x = -1, y = -3}},
    {"refined-concrete", {x = -1, y = -2}},
    {"refined-concrete", {x = -1, y = -1}},
    {"refined-concrete", {x = -1, y = 0}},
    {"refined-concrete", {x = -1, y = 1}},
    {"refined-concrete", {x = -1, y = 2}},
    {"refined-concrete", {x = -1, y = 3}},
    {"refined-concrete", {x = -1, y = 4}},
    {"refined-concrete", {x = -1, y = 5}},
    {"refined-concrete", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = -1, y = 8}},
    {"grass-1", {x = -1, y = 9}},
    {"grass-1", {x = -1, y = 10}},
    {"grass-1", {x = -1, y = 11}},
    {"grass-1", {x = -1, y = 12}},
    {"grass-1", {x = -1, y = 13}},
    {"grass-1", {x = -1, y = 14}},
    {"grass-1", {x = -1, y = 15}},
    {"grass-1", {x = 0, y = -16}},
    {"grass-1", {x = 0, y = -15}},
    {"grass-1", {x = 0, y = -14}},
    {"grass-1", {x = 0, y = -13}},
    {"grass-1", {x = 0, y = -12}},
    {"grass-1", {x = 0, y = -11}},
    {"grass-1", {x = 0, y = -10}},
    {"grass-1", {x = 0, y = -9}},
    {"grass-1", {x = 0, y = -8}},
    {"grass-1", {x = 0, y = -7}},
    {"refined-concrete", {x = 0, y = -6}},
    {"refined-concrete", {x = 0, y = -5}},
    {"refined-concrete", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"refined-concrete", {x = 0, y = -1}},
    {"refined-concrete", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-1", {x = 0, y = 9}},
    {"grass-1", {x = 0, y = 10}},
    {"grass-1", {x = 0, y = 11}},
    {"grass-1", {x = 0, y = 12}},
    {"grass-1", {x = 0, y = 13}},
    {"grass-1", {x = 0, y = 14}},
    {"grass-1", {x = 0, y = 15}},
    {"grass-1", {x = 1, y = -16}},
    {"grass-1", {x = 1, y = -15}},
    {"grass-1", {x = 1, y = -14}},
    {"grass-1", {x = 1, y = -13}},
    {"grass-1", {x = 1, y = -12}},
    {"grass-1", {x = 1, y = -11}},
    {"grass-1", {x = 1, y = -10}},
    {"grass-1", {x = 1, y = -9}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"refined-concrete", {x = 1, y = -6}},
    {"refined-concrete", {x = 1, y = -5}},
    {"refined-concrete", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-1", {x = 1, y = 9}},
    {"grass-1", {x = 1, y = 10}},
    {"grass-1", {x = 1, y = 11}},
    {"grass-1", {x = 1, y = 12}},
    {"grass-1", {x = 1, y = 13}},
    {"grass-1", {x = 1, y = 14}},
    {"grass-1", {x = 1, y = 15}},
    {"grass-1", {x = 2, y = -16}},
    {"grass-1", {x = 2, y = -15}},
    {"grass-1", {x = 2, y = -14}},
    {"grass-1", {x = 2, y = -13}},
    {"grass-1", {x = 2, y = -12}},
    {"grass-1", {x = 2, y = -11}},
    {"grass-1", {x = 2, y = -10}},
    {"grass-1", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"refined-concrete", {x = 2, y = -6}},
    {"refined-concrete", {x = 2, y = -5}},
    {"refined-concrete", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 2, y = 9}},
    {"grass-1", {x = 2, y = 10}},
    {"grass-1", {x = 2, y = 11}},
    {"grass-1", {x = 2, y = 12}},
    {"grass-1", {x = 2, y = 13}},
    {"grass-1", {x = 2, y = 14}},
    {"grass-1", {x = 2, y = 15}},
    {"grass-1", {x = 3, y = -16}},
    {"grass-1", {x = 3, y = -15}},
    {"grass-1", {x = 3, y = -14}},
    {"grass-1", {x = 3, y = -13}},
    {"grass-1", {x = 3, y = -12}},
    {"grass-1", {x = 3, y = -11}},
    {"grass-1", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"refined-concrete", {x = 3, y = -6}},
    {"refined-concrete", {x = 3, y = -5}},
    {"refined-concrete", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 3, y = 9}},
    {"grass-1", {x = 3, y = 10}},
    {"grass-1", {x = 3, y = 11}},
    {"grass-1", {x = 3, y = 12}},
    {"grass-1", {x = 3, y = 13}},
    {"grass-1", {x = 3, y = 14}},
    {"grass-1", {x = 3, y = 15}},
    {"grass-1", {x = 4, y = -16}},
    {"grass-1", {x = 4, y = -15}},
    {"grass-1", {x = 4, y = -14}},
    {"grass-1", {x = 4, y = -13}},
    {"grass-1", {x = 4, y = -12}},
    {"grass-1", {x = 4, y = -11}},
    {"grass-1", {x = 4, y = -10}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"refined-concrete", {x = 4, y = -6}},
    {"refined-concrete", {x = 4, y = -5}},
    {"refined-concrete", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 4, y = 8}},
    {"grass-1", {x = 4, y = 9}},
    {"grass-1", {x = 4, y = 10}},
    {"grass-1", {x = 4, y = 11}},
    {"grass-1", {x = 4, y = 12}},
    {"grass-1", {x = 4, y = 13}},
    {"grass-1", {x = 4, y = 14}},
    {"grass-1", {x = 4, y = 15}},
    {"grass-1", {x = 5, y = -16}},
    {"grass-1", {x = 5, y = -15}},
    {"grass-1", {x = 5, y = -14}},
    {"grass-1", {x = 5, y = -13}},
    {"grass-1", {x = 5, y = -12}},
    {"grass-1", {x = 5, y = -11}},
    {"grass-1", {x = 5, y = -10}},
    {"grass-1", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"refined-concrete", {x = 5, y = -6}},
    {"refined-concrete", {x = 5, y = -5}},
    {"refined-concrete", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 5, y = 8}},
    {"grass-1", {x = 5, y = 9}},
    {"grass-1", {x = 5, y = 10}},
    {"grass-1", {x = 5, y = 11}},
    {"grass-1", {x = 5, y = 12}},
    {"grass-1", {x = 5, y = 13}},
    {"grass-1", {x = 5, y = 14}},
    {"grass-1", {x = 5, y = 15}},
    {"grass-1", {x = 6, y = -16}},
    {"grass-1", {x = 6, y = -15}},
    {"grass-1", {x = 6, y = -14}},
    {"grass-1", {x = 6, y = -13}},
    {"grass-1", {x = 6, y = -12}},
    {"grass-1", {x = 6, y = -11}},
    {"grass-1", {x = 6, y = -10}},
    {"grass-1", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"refined-concrete", {x = 6, y = -6}},
    {"refined-concrete", {x = 6, y = -5}},
    {"refined-concrete", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-1", {x = 6, y = 7}},
    {"grass-1", {x = 6, y = 8}},
    {"grass-1", {x = 6, y = 9}},
    {"grass-1", {x = 6, y = 10}},
    {"grass-1", {x = 6, y = 11}},
    {"grass-1", {x = 6, y = 12}},
    {"grass-1", {x = 6, y = 13}},
    {"grass-1", {x = 6, y = 14}},
    {"grass-1", {x = 6, y = 15}},
    {"grass-1", {x = 7, y = -16}},
    {"grass-1", {x = 7, y = -15}},
    {"grass-1", {x = 7, y = -14}},
    {"grass-1", {x = 7, y = -13}},
    {"grass-1", {x = 7, y = -12}},
    {"grass-1", {x = 7, y = -11}},
    {"grass-1", {x = 7, y = -10}},
    {"grass-1", {x = 7, y = -9}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"refined-concrete", {x = 7, y = -6}},
    {"refined-concrete", {x = 7, y = -5}},
    {"refined-concrete", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-1", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
    {"grass-1", {x = 7, y = 8}},
    {"grass-1", {x = 7, y = 9}},
    {"grass-1", {x = 7, y = 10}},
    {"grass-1", {x = 7, y = 11}},
    {"grass-1", {x = 7, y = 12}},
    {"grass-1", {x = 7, y = 13}},
    {"grass-1", {x = 7, y = 14}},
    {"grass-1", {x = 7, y = 15}},
    {"grass-1", {x = 8, y = -16}},
    {"grass-1", {x = 8, y = -15}},
    {"grass-1", {x = 8, y = -14}},
    {"grass-1", {x = 8, y = -13}},
    {"grass-1", {x = 8, y = -12}},
    {"grass-1", {x = 8, y = -11}},
    {"grass-1", {x = 8, y = -10}},
    {"grass-1", {x = 8, y = -9}},
    {"grass-1", {x = 8, y = -8}},
    {"grass-1", {x = 8, y = -7}},
    {"refined-concrete", {x = 8, y = -6}},
    {"refined-concrete", {x = 8, y = -5}},
    {"refined-concrete", {x = 8, y = -4}},
    {"grass-1", {x = 8, y = -3}},
    {"grass-1", {x = 8, y = -2}},
    {"grass-1", {x = 8, y = -1}},
    {"grass-1", {x = 8, y = 0}},
    {"grass-1", {x = 8, y = 1}},
    {"grass-1", {x = 8, y = 2}},
    {"grass-1", {x = 8, y = 3}},
    {"grass-1", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-1", {x = 8, y = 6}},
    {"grass-1", {x = 8, y = 7}},
    {"grass-1", {x = 8, y = 8}},
    {"grass-1", {x = 8, y = 9}},
    {"grass-1", {x = 8, y = 10}},
    {"grass-1", {x = 8, y = 11}},
    {"grass-1", {x = 8, y = 12}},
    {"grass-1", {x = 8, y = 13}},
    {"grass-1", {x = 8, y = 14}},
    {"grass-1", {x = 8, y = 15}},
    {"grass-1", {x = 9, y = -16}},
    {"grass-1", {x = 9, y = -15}},
    {"grass-1", {x = 9, y = -14}},
    {"grass-1", {x = 9, y = -13}},
    {"grass-1", {x = 9, y = -12}},
    {"grass-1", {x = 9, y = -11}},
    {"grass-1", {x = 9, y = -10}},
    {"grass-1", {x = 9, y = -9}},
    {"grass-1", {x = 9, y = -8}},
    {"grass-1", {x = 9, y = -7}},
    {"refined-concrete", {x = 9, y = -6}},
    {"refined-concrete", {x = 9, y = -5}},
    {"refined-concrete", {x = 9, y = -4}},
    {"grass-1", {x = 9, y = -3}},
    {"grass-1", {x = 9, y = -2}},
    {"grass-1", {x = 9, y = -1}},
    {"grass-1", {x = 9, y = 0}},
    {"grass-1", {x = 9, y = 1}},
    {"grass-1", {x = 9, y = 2}},
    {"grass-1", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"grass-1", {x = 9, y = 5}},
    {"grass-1", {x = 9, y = 6}},
    {"grass-1", {x = 9, y = 7}},
    {"grass-1", {x = 9, y = 8}},
    {"grass-1", {x = 9, y = 9}},
    {"grass-1", {x = 9, y = 10}},
    {"grass-1", {x = 9, y = 11}},
    {"grass-1", {x = 9, y = 12}},
    {"grass-1", {x = 9, y = 13}},
    {"grass-1", {x = 9, y = 14}},
    {"grass-1", {x = 9, y = 15}},
    {"grass-1", {x = 10, y = -16}},
    {"grass-1", {x = 10, y = -15}},
    {"grass-1", {x = 10, y = -14}},
    {"grass-1", {x = 10, y = -13}},
    {"grass-1", {x = 10, y = -12}},
    {"grass-1", {x = 10, y = -11}},
    {"grass-1", {x = 10, y = -10}},
    {"grass-1", {x = 10, y = -9}},
    {"grass-1", {x = 10, y = -8}},
    {"grass-1", {x = 10, y = -7}},
    {"grass-1", {x = 10, y = -6}},
    {"grass-1", {x = 10, y = -5}},
    {"grass-1", {x = 10, y = -4}},
    {"grass-1", {x = 10, y = -3}},
    {"grass-1", {x = 10, y = -2}},
    {"grass-1", {x = 10, y = -1}},
    {"grass-1", {x = 10, y = 0}},
    {"grass-1", {x = 10, y = 1}},
    {"grass-1", {x = 10, y = 2}},
    {"grass-1", {x = 10, y = 3}},
    {"grass-1", {x = 10, y = 4}},
    {"grass-1", {x = 10, y = 5}},
    {"grass-1", {x = 10, y = 6}},
    {"grass-1", {x = 10, y = 7}},
    {"grass-1", {x = 10, y = 8}},
    {"grass-1", {x = 10, y = 9}},
    {"grass-1", {x = 10, y = 10}},
    {"grass-1", {x = 10, y = 11}},
    {"grass-1", {x = 10, y = 12}},
    {"grass-1", {x = 10, y = 13}},
    {"grass-1", {x = 10, y = 14}},
    {"grass-1", {x = 10, y = 15}},
    {"grass-1", {x = 11, y = -16}},
    {"grass-1", {x = 11, y = -15}},
    {"grass-1", {x = 11, y = -14}},
    {"grass-1", {x = 11, y = -13}},
    {"grass-1", {x = 11, y = -12}},
    {"grass-1", {x = 11, y = -11}},
    {"grass-1", {x = 11, y = -10}},
    {"grass-1", {x = 11, y = -9}},
    {"grass-1", {x = 11, y = -8}},
    {"grass-1", {x = 11, y = -7}},
    {"grass-1", {x = 11, y = -6}},
    {"grass-1", {x = 11, y = -5}},
    {"grass-1", {x = 11, y = -4}},
    {"grass-1", {x = 11, y = -3}},
    {"grass-1", {x = 11, y = -2}},
    {"grass-1", {x = 11, y = -1}},
    {"grass-1", {x = 11, y = 0}},
    {"grass-1", {x = 11, y = 1}},
    {"grass-1", {x = 11, y = 2}},
    {"grass-1", {x = 11, y = 3}},
    {"grass-1", {x = 11, y = 4}},
    {"grass-1", {x = 11, y = 5}},
    {"grass-1", {x = 11, y = 6}},
    {"grass-1", {x = 11, y = 7}},
    {"grass-1", {x = 11, y = 8}},
    {"grass-1", {x = 11, y = 9}},
    {"grass-1", {x = 11, y = 10}},
    {"grass-1", {x = 11, y = 11}},
    {"grass-1", {x = 11, y = 12}},
    {"grass-1", {x = 11, y = 13}},
    {"grass-1", {x = 11, y = 14}},
    {"grass-1", {x = 11, y = 15}},
    {"grass-1", {x = 12, y = -16}},
    {"grass-1", {x = 12, y = -15}},
    {"grass-1", {x = 12, y = -14}},
    {"grass-1", {x = 12, y = -13}},
    {"grass-1", {x = 12, y = -12}},
    {"grass-1", {x = 12, y = -11}},
    {"grass-1", {x = 12, y = -10}},
    {"grass-1", {x = 12, y = -9}},
    {"grass-1", {x = 12, y = -8}},
    {"grass-1", {x = 12, y = -7}},
    {"grass-1", {x = 12, y = -6}},
    {"grass-1", {x = 12, y = -5}},
    {"grass-1", {x = 12, y = -4}},
    {"grass-1", {x = 12, y = -3}},
    {"grass-1", {x = 12, y = -2}},
    {"grass-1", {x = 12, y = -1}},
    {"grass-1", {x = 12, y = 0}},
    {"grass-1", {x = 12, y = 1}},
    {"grass-1", {x = 12, y = 2}},
    {"grass-1", {x = 12, y = 3}},
    {"grass-1", {x = 12, y = 4}},
    {"grass-1", {x = 12, y = 5}},
    {"grass-1", {x = 12, y = 6}},
    {"grass-1", {x = 12, y = 7}},
    {"grass-1", {x = 12, y = 8}},
    {"grass-1", {x = 12, y = 9}},
    {"grass-1", {x = 12, y = 10}},
    {"grass-1", {x = 12, y = 11}},
    {"grass-1", {x = 12, y = 12}},
    {"grass-1", {x = 12, y = 13}},
    {"grass-1", {x = 12, y = 14}},
    {"grass-1", {x = 12, y = 15}},
    {"grass-1", {x = 13, y = -16}},
    {"grass-1", {x = 13, y = -15}},
    {"grass-1", {x = 13, y = -14}},
    {"grass-1", {x = 13, y = -13}},
    {"grass-1", {x = 13, y = -12}},
    {"grass-1", {x = 13, y = -11}},
    {"grass-1", {x = 13, y = -10}},
    {"grass-1", {x = 13, y = -9}},
    {"grass-1", {x = 13, y = -8}},
    {"grass-1", {x = 13, y = -7}},
    {"grass-1", {x = 13, y = -6}},
    {"grass-1", {x = 13, y = -5}},
    {"grass-1", {x = 13, y = -4}},
    {"grass-1", {x = 13, y = -3}},
    {"grass-1", {x = 13, y = -2}},
    {"grass-1", {x = 13, y = -1}},
    {"grass-1", {x = 13, y = 0}},
    {"grass-1", {x = 13, y = 1}},
    {"grass-1", {x = 13, y = 2}},
    {"grass-1", {x = 13, y = 3}},
    {"grass-1", {x = 13, y = 4}},
    {"grass-1", {x = 13, y = 5}},
    {"grass-1", {x = 13, y = 6}},
    {"grass-1", {x = 13, y = 7}},
    {"grass-1", {x = 13, y = 8}},
    {"grass-1", {x = 13, y = 9}},
    {"grass-1", {x = 13, y = 10}},
    {"grass-1", {x = 13, y = 11}},
    {"grass-1", {x = 13, y = 12}},
    {"grass-1", {x = 13, y = 13}},
    {"grass-1", {x = 13, y = 14}},
    {"grass-1", {x = 13, y = 15}},
    {"grass-1", {x = 14, y = -16}},
    {"grass-1", {x = 14, y = -15}},
    {"grass-1", {x = 14, y = -14}},
    {"grass-1", {x = 14, y = -13}},
    {"grass-1", {x = 14, y = -12}},
    {"grass-1", {x = 14, y = -11}},
    {"grass-1", {x = 14, y = -10}},
    {"grass-1", {x = 14, y = -9}},
    {"grass-1", {x = 14, y = -8}},
    {"grass-1", {x = 14, y = -7}},
    {"grass-1", {x = 14, y = -6}},
    {"grass-1", {x = 14, y = -5}},
    {"grass-1", {x = 14, y = -4}},
    {"grass-1", {x = 14, y = -3}},
    {"grass-1", {x = 14, y = -2}},
    {"grass-1", {x = 14, y = -1}},
    {"grass-1", {x = 14, y = 0}},
    {"grass-1", {x = 14, y = 1}},
    {"grass-1", {x = 14, y = 2}},
    {"grass-1", {x = 14, y = 3}},
    {"grass-1", {x = 14, y = 4}},
    {"grass-1", {x = 14, y = 5}},
    {"grass-1", {x = 14, y = 6}},
    {"grass-1", {x = 14, y = 7}},
    {"grass-1", {x = 14, y = 8}},
    {"grass-1", {x = 14, y = 9}},
    {"grass-1", {x = 14, y = 10}},
    {"grass-1", {x = 14, y = 11}},
    {"grass-1", {x = 14, y = 12}},
    {"grass-1", {x = 14, y = 13}},
    {"grass-1", {x = 14, y = 14}},
    {"grass-1", {x = 14, y = 15}},
    {"grass-1", {x = 15, y = -16}},
    {"grass-1", {x = 15, y = -15}},
    {"grass-1", {x = 15, y = -14}},
    {"grass-1", {x = 15, y = -13}},
    {"grass-1", {x = 15, y = -12}},
    {"grass-1", {x = 15, y = -11}},
    {"grass-1", {x = 15, y = -10}},
    {"grass-1", {x = 15, y = -9}},
    {"grass-1", {x = 15, y = -8}},
    {"grass-1", {x = 15, y = -7}},
    {"grass-1", {x = 15, y = -6}},
    {"grass-1", {x = 15, y = -5}},
    {"grass-1", {x = 15, y = -4}},
    {"grass-1", {x = 15, y = -3}},
    {"grass-1", {x = 15, y = -2}},
    {"grass-1", {x = 15, y = -1}},
    {"grass-1", {x = 15, y = 0}},
    {"grass-1", {x = 15, y = 1}},
    {"grass-1", {x = 15, y = 2}},
    {"grass-1", {x = 15, y = 3}},
    {"grass-1", {x = 15, y = 4}},
    {"grass-1", {x = 15, y = 5}},
    {"grass-1", {x = 15, y = 6}},
    {"grass-1", {x = 15, y = 7}},
    {"grass-1", {x = 15, y = 8}},
    {"grass-1", {x = 15, y = 9}},
    {"grass-1", {x = 15, y = 10}},
    {"grass-1", {x = 15, y = 11}},
    {"grass-1", {x = 15, y = 12}},
    {"grass-1", {x = 15, y = 13}},
    {"grass-1", {x = 15, y = 14}},
    {"grass-1", {x = 15, y = 15}},
  }
}
