return
{
  entities =
  {
    {"stone-wall", {x = -14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -10, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -8, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -5, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 5, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = 8, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = 10, y = -14}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -13.5}, {force = "enemy", }},
    {"fast-inserter", {x = -9.5, y = -12.5}, {dir = "south", }},
    {"fast-inserter", {x = -7.5, y = -12.5}, {dir = "south", }},
    {"stone-wall", {x = -6.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -12.5}, {force = "enemy", }},
    {"fast-inserter", {x = 7.5, y = -12.5}, {dir = "south", }},
    {"stone-wall", {x = 6.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -13.5}, {force = "enemy", }},
    {"fast-inserter", {x = 9.5, y = -12.5}, {dir = "south", }},
    {"stone-wall", {x = 11.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = -10}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"express-transport-belt", {x = -10.5, y = -11.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = -10.5}, {}},
    {"express-transport-belt", {x = -8.5, y = -11.5}, {dir = "east", }},
    {"express-transport-belt", {x = -9.5, y = -11.5}, {dir = "east", }},
    {"stone-wall", {x = -6.5, y = -11.5}, {force = "enemy", }},
    {"steel-chest", {x = -6.5, y = -10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = -7.5, y = -10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"express-transport-belt", {x = -7.5, y = -11.5}, {dir = "east", }},
    {"stone-wall", {x = -5.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -10.5}, {force = "enemy", }},
    {"steel-chest", {x = -5.5, y = -10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -2.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -11.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -11.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -10.5}, {force = "enemy", }},
    {"steel-chest", {x = 5.5, y = -10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = 6.5, y = -11.5}, {force = "enemy", }},
    {"steel-chest", {x = 7.5, y = -10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = 6.5, y = -10.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"express-transport-belt", {x = 7.5, y = -11.5}, {dir = "west", }},
    {"express-transport-belt", {x = 8.5, y = -11.5}, {dir = "west", }},
    {"express-transport-belt", {x = 9.5, y = -11.5}, {dir = "west", }},
    {"fast-inserter", {x = 11.5, y = -10.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = -11.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = -10.5}, {}},
    {"gun-turret", {x = 13, y = -11}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = -8}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -11.5, y = -9.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = -9.5}, {}},
    {"express-transport-belt", {x = -10.5, y = -8.5}, {}},
    {"fast-inserter", {x = -6.5, y = -9.5}, {force = "enemy", }},
    {"fast-inserter", {x = -7.5, y = -9.5}, {force = "enemy", }},
    {"steel-chest", {x = -6.5, y = -8.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = -7.5, y = -8.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -4.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -8.5}, {force = "enemy", }},
    {"fast-inserter", {x = -5.5, y = -9.5}, {force = "enemy", }},
    {"steel-chest", {x = -5.5, y = -8.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -2.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -8.5}, {force = "enemy", }},
    {"fast-inserter", {x = 5.5, y = -9.5}, {force = "enemy", }},
    {"steel-chest", {x = 5.5, y = -8.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"fast-inserter", {x = 7.5, y = -9.5}, {force = "enemy", }},
    {"fast-inserter", {x = 6.5, y = -9.5}, {force = "enemy", }},
    {"steel-chest", {x = 7.5, y = -8.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = 6.5, y = -8.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"fast-inserter", {x = 11.5, y = -8.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = -9.5}, {}},
    {"express-transport-belt", {x = 10.5, y = -8.5}, {}},
    {"gun-turret", {x = 13, y = -9}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -7.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = -6}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -11.5, y = -7.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = -7.5}, {}},
    {"express-transport-belt", {x = -10.5, y = -6.5}, {}},
    {"substation", {x = -9, y = -7}, {force = "enemy", }},
    {"fast-inserter", {x = -6.5, y = -7.5}, {force = "enemy", }},
    {"fast-inserter", {x = -7.5, y = -7.5}, {force = "enemy", }},
    {"steel-chest", {x = -6.5, y = -6.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = -7.5, y = -6.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -4.5, y = -7.5}, {force = "enemy", }},
    {"fast-inserter", {x = -5.5, y = -7.5}, {force = "enemy", }},
    {"steel-chest", {x = -5.5, y = -6.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"stone-wall", {x = -2.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -7.5}, {force = "enemy", }},
    {"fast-inserter", {x = 5.5, y = -7.5}, {force = "enemy", }},
    {"steel-chest", {x = 5.5, y = -6.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"fast-inserter", {x = 7.5, y = -7.5}, {force = "enemy", }},
    {"fast-inserter", {x = 6.5, y = -7.5}, {force = "enemy", }},
    {"steel-chest", {x = 7.5, y = -6.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"steel-chest", {x = 6.5, y = -6.5}, {force = "enemy", items = {["iron-ore"] = 2400}, }},
    {"substation", {x = 9, y = -7}, {force = "enemy", }},
    {"fast-inserter", {x = 11.5, y = -6.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = -7.5}, {}},
    {"express-transport-belt", {x = 10.5, y = -6.5}, {}},
    {"gun-turret", {x = 13, y = -7}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -5.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = -4}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -11.5, y = -5.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = -5.5}, {}},
    {"express-transport-belt", {x = -10.5, y = -4.5}, {}},
    {"steel-chest", {x = -9.5, y = -4.5}, {items = {["express-transport-belt"] = 10}, }},
    {"fast-inserter", {x = -6.5, y = -5.5}, {force = "enemy", }},
    {"fast-inserter", {x = -7.5, y = -5.5}, {force = "enemy", }},
    {"electric-furnace", {x = -6.5, y = -3.5}, {force = "enemy", }},
    {"fast-inserter", {x = -5.5, y = -5.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = -4.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = 0, y = -4}, {force = "enemy", }},
    {"gate", {x = 3.5, y = -4.5}, {force = "enemy", }},
    {"gate", {x = 3.5, y = -5.5}, {force = "enemy", }},
    {"fast-inserter", {x = 5.5, y = -5.5}, {force = "enemy", }},
    {"electric-furnace", {x = 6.5, y = -3.5}, {force = "enemy", }},
    {"fast-inserter", {x = 7.5, y = -5.5}, {force = "enemy", }},
    {"fast-inserter", {x = 6.5, y = -5.5}, {force = "enemy", }},
    {"steel-chest", {x = 9.5, y = -4.5}, {items = {["combat-shotgun"] = 1}, }},
    {"fast-inserter", {x = 11.5, y = -4.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = -5.5}, {}},
    {"express-transport-belt", {x = 10.5, y = -4.5}, {}},
    {"gun-turret", {x = 13, y = -5}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -2.5}, {force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = -3.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = -3.5}, {}},
    {"express-transport-belt", {x = -10.5, y = -2.5}, {}},
    {"stone-wall", {x = -11.5, y = -2.5}, {force = "enemy", }},
    {"fast-inserter", {x = -8.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"logistic-chest-active-provider", {x = -9.5, y = -3.5}, {force = "enemy", }},
    {"steel-chest", {x = -9.5, y = -2.5}, {items = {["production-science-pack"] = 200}, }},
    {"gate", {x = -3.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -2.5}, {force = "enemy", }},
    {"gate", {x = 3.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -2.5}, {force = "enemy", }},
    {"fast-inserter", {x = 8.5, y = -3.5}, {dir = "west", force = "enemy", }},
    {"logistic-chest-active-provider", {x = 9.5, y = -3.5}, {force = "enemy", }},
    {"steel-chest", {x = 9.5, y = -2.5}, {items = {["belt-immunity-equipment"] = 1}, }},
    {"express-transport-belt", {x = 10.5, y = -3.5}, {}},
    {"express-transport-belt", {x = 10.5, y = -2.5}, {}},
    {"stone-wall", {x = 11.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -1.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = -1}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -10.5, y = -1.5}, {}},
    {"express-transport-belt", {x = -10.5, y = -0.5}, {}},
    {"stone-wall", {x = -11.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -1.5}, {force = "enemy", }},
    {"steel-chest", {x = -9.5, y = -0.5}, {items = {["atomic-bomb"] = 10}, }},
    {"logistic-robot", {x = -6.86, y = -0.04}, {force = "enemy", }},
    {"logistic-robot", {x = -6.82, y = -0.22}, {force = "enemy", }},
    {"logistic-robot", {x = -6.82, y = -0.37}, {force = "enemy", }},
    {"logistic-robot", {x = -6.82, y = -0.45}, {force = "enemy", }},
    {"logistic-robot", {x = -6.82, y = -0.48}, {force = "enemy", }},
    {"logistic-robot", {x = -6.82, y = -0.54}, {force = "enemy", }},
    {"logistic-robot", {x = -6.12, y = -0.01}, {force = "enemy", }},
    {"logistic-robot", {x = -6.11, y = -0.18}, {force = "enemy", }},
    {"logistic-robot", {x = -6.11, y = -0.35}, {force = "enemy", }},
    {"logistic-robot", {x = -6.11, y = -0.43}, {force = "enemy", }},
    {"logistic-robot", {x = -6.11, y = -0.5}, {force = "enemy", }},
    {"roboport", {x = -6, y = 0}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"aliencon-robot", {x = -3.59, y = -0.1}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.27}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.35}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.38}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.46}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.55}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.66}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.72}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.83}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -0.92}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -1.03}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = -1.14}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.62, y = -1.31}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.62, y = -1.43}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.62, y = -1.46}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -0.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -1.5, y = -0.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"stone-wall", {x = -0.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -1.5}, {force = "enemy", }},
    {"purple-crystal-gen", {x = 0.5, y = -1}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -1.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = -0.04}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -0.1}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -0.21}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -0.35}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -0.46}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -0.58}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -0.63}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -0.72}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -0.89}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -1.06}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -1.2}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.77, y = -1.34}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = -1.46}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = -1.48}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = -1.51}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -1.5}, {force = "enemy", }},
    {"roboport", {x = 6, y = 0}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"steel-chest", {x = 9.5, y = -0.5}, {items = {["utility-science-pack"] = 200}, }},
    {"express-transport-belt", {x = 10.5, y = -1.5}, {}},
    {"express-transport-belt", {x = 10.5, y = -0.5}, {}},
    {"stone-wall", {x = 11.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -1.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = -1}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 0.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = 2}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -13.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 0.5}, {force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = 1.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = 0.5}, {}},
    {"express-transport-belt", {x = -10.5, y = 1.5}, {}},
    {"stone-wall", {x = -11.5, y = 0.5}, {force = "enemy", }},
    {"steel-chest", {x = -9.5, y = 1.5}, {items = {["laser-turret"] = 25}, }},
    {"logistic-robot", {x = -6.95, y = 0.47}, {force = "enemy", }},
    {"logistic-robot", {x = -6.95, y = 0.45}, {force = "enemy", }},
    {"logistic-robot", {x = -6.95, y = 0.43}, {force = "enemy", }},
    {"logistic-robot", {x = -6.95, y = 0.39}, {force = "enemy", }},
    {"logistic-robot", {x = -6.95, y = 0.32}, {force = "enemy", }},
    {"logistic-robot", {x = -6.95, y = 0.26}, {force = "enemy", }},
    {"logistic-robot", {x = -6.95, y = 0.2}, {force = "enemy", }},
    {"logistic-robot", {x = -6.91, y = 0.07}, {force = "enemy", }},
    {"logistic-robot", {x = -6.12, y = 0.87}, {force = "enemy", }},
    {"logistic-robot", {x = -6.12, y = 0.85}, {force = "enemy", }},
    {"logistic-robot", {x = -6.12, y = 0.83}, {force = "enemy", }},
    {"logistic-robot", {x = -6.12, y = 0.81}, {force = "enemy", }},
    {"logistic-robot", {x = -6.12, y = 0.79}, {force = "enemy", }},
    {"logistic-robot", {x = -6.12, y = 0.77}, {force = "enemy", }},
    {"logistic-robot", {x = -6.12, y = 0.75}, {force = "enemy", }},
    {"logistic-robot", {x = -6.15, y = 0.64}, {force = "enemy", }},
    {"logistic-robot", {x = -6.15, y = 0.51}, {force = "enemy", }},
    {"logistic-robot", {x = -6.15, y = 0.37}, {force = "enemy", }},
    {"logistic-robot", {x = -6.15, y = 0.2}, {force = "enemy", }},
    {"logistic-robot", {x = -6.15, y = 0.11}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.73, y = 1.06}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.73, y = 1.04}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.73, y = 0.98}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.73, y = 0.95}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.73, y = 0.92}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.73, y = 0.89}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.73, y = 0.87}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.73, y = 0.81}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.7, y = 0.7}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.68, y = 0.55}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.65, y = 0.47}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.65, y = 0.38}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.62, y = 0.3}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = 0.21}, {force = "enemy", }},
    {"aliencon-robot", {x = -3.59, y = 0.1}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 1.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -1.5, y = 0.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"stone-wall", {x = -0.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 1.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = 0.84}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = 0.81}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = 0.75}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.71, y = 0.58}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.71, y = 0.5}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.71, y = 0.44}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.71, y = 0.38}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.71, y = 0.36}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.71, y = 0.27}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.71, y = 0.19}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = 0.13}, {force = "enemy", }},
    {"aliencon-robot", {x = 3.74, y = 0.04}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 0.5}, {force = "enemy", }},
    {"steel-chest", {x = 9.5, y = 1.5}, {items = {["flying-robot-frame"] = 25, ["low-density-structure"] = 10, ["processing-unit"] = 20}, }},
    {"fast-inserter", {x = 11.5, y = 1.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = 0.5}, {}},
    {"express-transport-belt", {x = 10.5, y = 1.5}, {}},
    {"stone-wall", {x = 11.5, y = 0.5}, {force = "enemy", }},
    {"gun-turret", {x = 13, y = 2}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 13.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 2.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = 4}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -11.5, y = 3.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = 2.5}, {}},
    {"express-transport-belt", {x = -10.5, y = 3.5}, {}},
    {"express-transport-belt", {x = -2.5, y = 3.5}, {dir = "south", }},
    {"stone-wall", {x = -2.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 2.5}, {force = "enemy", }},
    {"fast-inserter", {x = -1.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"logistic-chest-storage", {x = -0.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 2.5}, {force = "enemy", }},
    {"fast-inserter", {x = 11.5, y = 3.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = 2.5}, {}},
    {"express-transport-belt", {x = 10.5, y = 3.5}, {}},
    {"gun-turret", {x = 13, y = 4}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 4.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = 6}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"express-transport-belt", {x = -10.5, y = 5.5}, {dir = "south", }},
    {"express-transport-belt", {x = -10.5, y = 4.5}, {}},
    {"express-transport-belt", {x = -8.5, y = 4.5}, {dir = "west", }},
    {"express-splitter", {x = -9.5, y = 5}, {dir = "west", }},
    {"fast-inserter", {x = -7.5, y = 5.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -7.5, y = 4.5}, {dir = "west", }},
    {"fast-inserter", {x = -5.5, y = 5.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -5.5, y = 4.5}, {dir = "west", }},
    {"express-transport-belt", {x = -4.5, y = 4.5}, {dir = "west", }},
    {"express-transport-belt", {x = -4.5, y = 5.5}, {}},
    {"express-transport-belt", {x = -3.5, y = 5.5}, {dir = "west", }},
    {"express-transport-belt", {x = -2.5, y = 5.5}, {dir = "west", }},
    {"express-splitter", {x = -2, y = 4.5}, {dir = "south", }},
    {"express-transport-belt", {x = -0.5, y = 4.5}, {dir = "east", }},
    {"express-transport-belt", {x = -0.5, y = 5.5}, {}},
    {"express-transport-belt", {x = -1.5, y = 5.5}, {dir = "east", }},
    {"express-transport-belt", {x = 1.5, y = 4.5}, {dir = "east", }},
    {"express-transport-belt", {x = 0.5, y = 4.5}, {dir = "east", }},
    {"express-transport-belt", {x = 3.5, y = 4.5}, {dir = "east", }},
    {"express-transport-belt", {x = 2.5, y = 4.5}, {dir = "east", }},
    {"fast-inserter", {x = 5.5, y = 5.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 5.5, y = 4.5}, {dir = "east", }},
    {"express-transport-belt", {x = 4.5, y = 4.5}, {dir = "east", }},
    {"fast-inserter", {x = 7.5, y = 5.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 7.5, y = 4.5}, {dir = "east", }},
    {"express-transport-belt", {x = 8.5, y = 4.5}, {dir = "east", }},
    {"express-splitter", {x = 9.5, y = 5}, {dir = "east", }},
    {"express-transport-belt", {x = 10.5, y = 4.5}, {}},
    {"express-transport-belt", {x = 10.5, y = 5.5}, {dir = "south", }},
    {"gun-turret", {x = 13, y = 6}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 6.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = 8}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -11.5, y = 6.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = 7.5}, {dir = "south", }},
    {"express-transport-belt", {x = -10.5, y = 6.5}, {dir = "south", }},
    {"substation", {x = -9, y = 7}, {force = "enemy", }},
    {"assembling-machine-2", {x = -6.5, y = 7.5}, {recipe = "cryexplosive-rounds-magazine", }},
    {"stone-wall", {x = -2.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 6.5}, {force = "enemy", }},
    {"assembling-machine-2", {x = 6.5, y = 7.5}, {recipe = "cryexplosive-rounds-magazine", }},
    {"substation", {x = 9, y = 7}, {force = "enemy", }},
    {"fast-inserter", {x = 11.5, y = 6.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = 7.5}, {dir = "south", }},
    {"express-transport-belt", {x = 10.5, y = 6.5}, {dir = "south", }},
    {"gun-turret", {x = 13, y = 8}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 8.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = 10}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -11.5, y = 8.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = 9.5}, {dir = "south", }},
    {"express-transport-belt", {x = -10.5, y = 8.5}, {dir = "south", }},
    {"gate", {x = -3.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 8.5}, {force = "enemy", }},
    {"laser-turret", {x = 0, y = 9}, {dir = "south", force = "enemy", }},
    {"gate", {x = 3.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 8.5}, {force = "enemy", }},
    {"small-lamp", {x = 9.5, y = 8.5}, {force = "enemy", }},
    {"fast-inserter", {x = 11.5, y = 8.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = 9.5}, {dir = "south", }},
    {"express-transport-belt", {x = 10.5, y = 8.5}, {dir = "south", }},
    {"gun-turret", {x = 13, y = 10}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 10.5}, {force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = 10.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = 11.5}, {dir = "east", }},
    {"express-transport-belt", {x = -10.5, y = 10.5}, {dir = "south", }},
    {"express-transport-belt", {x = -8.5, y = 11.5}, {dir = "east", }},
    {"express-transport-belt", {x = -9.5, y = 11.5}, {dir = "east", }},
    {"express-transport-belt", {x = -7.5, y = 11.5}, {dir = "east", }},
    {"stone-wall", {x = -2.5, y = 11.5}, {force = "enemy", }},
    {"gate", {x = -3.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 11.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 11.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 11.5}, {force = "enemy", }},
    {"gate", {x = 3.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 11.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 7.5, y = 11.5}, {dir = "west", }},
    {"express-transport-belt", {x = 8.5, y = 11.5}, {dir = "west", }},
    {"express-transport-belt", {x = 9.5, y = 11.5}, {dir = "west", }},
    {"fast-inserter", {x = 11.5, y = 10.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = 11.5}, {dir = "west", }},
    {"express-transport-belt", {x = 10.5, y = 10.5}, {dir = "south", }},
    {"stone-wall", {x = 14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -13, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = -10, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -11.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 13.5}, {force = "enemy", }},
    {"fast-inserter", {x = -9.5, y = 12.5}, {}},
    {"gun-turret", {x = -8, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -7.5, y = 12.5}, {}},
    {"stone-wall", {x = -6.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 13.5}, {force = "enemy", }},
    {"laser-turret", {x = -5, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 5, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 12.5}, {force = "enemy", }},
    {"fast-inserter", {x = 7.5, y = 12.5}, {}},
    {"gun-turret", {x = 8, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 6.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 12.5}, {force = "enemy", }},
    {"fast-inserter", {x = 9.5, y = 12.5}, {}},
    {"gun-turret", {x = 10, y = 14}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 11.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 13, y = 14}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 15.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -16, y = -16}},
    {"grass-1", {x = -16, y = -15}},
    {"grass-1", {x = -16, y = -14}},
    {"grass-1", {x = -16, y = -13}},
    {"grass-1", {x = -16, y = -12}},
    {"grass-1", {x = -16, y = -11}},
    {"grass-1", {x = -16, y = -10}},
    {"grass-1", {x = -16, y = -9}},
    {"grass-1", {x = -16, y = -8}},
    {"grass-1", {x = -16, y = -7}},
    {"grass-1", {x = -16, y = -6}},
    {"grass-1", {x = -16, y = -5}},
    {"grass-1", {x = -16, y = -4}},
    {"grass-1", {x = -16, y = -3}},
    {"grass-1", {x = -16, y = -2}},
    {"grass-1", {x = -16, y = -1}},
    {"grass-1", {x = -16, y = 0}},
    {"grass-1", {x = -16, y = 1}},
    {"grass-1", {x = -16, y = 2}},
    {"grass-1", {x = -16, y = 3}},
    {"grass-1", {x = -16, y = 4}},
    {"grass-1", {x = -16, y = 5}},
    {"grass-1", {x = -16, y = 6}},
    {"grass-1", {x = -16, y = 7}},
    {"grass-1", {x = -16, y = 8}},
    {"grass-1", {x = -16, y = 9}},
    {"grass-1", {x = -16, y = 10}},
    {"grass-1", {x = -16, y = 11}},
    {"grass-1", {x = -16, y = 12}},
    {"grass-1", {x = -16, y = 13}},
    {"grass-1", {x = -16, y = 14}},
    {"grass-1", {x = -16, y = 15}},
    {"grass-1", {x = -15, y = -16}},
    {"grass-1", {x = -15, y = -15}},
    {"grass-1", {x = -15, y = -14}},
    {"grass-1", {x = -15, y = -13}},
    {"grass-1", {x = -15, y = -12}},
    {"grass-1", {x = -15, y = -11}},
    {"grass-1", {x = -15, y = -10}},
    {"grass-1", {x = -15, y = -9}},
    {"grass-1", {x = -15, y = -8}},
    {"grass-1", {x = -15, y = -7}},
    {"grass-1", {x = -15, y = -6}},
    {"grass-1", {x = -15, y = -5}},
    {"grass-1", {x = -15, y = -4}},
    {"grass-1", {x = -15, y = -3}},
    {"grass-1", {x = -15, y = -2}},
    {"grass-1", {x = -15, y = -1}},
    {"grass-1", {x = -15, y = 0}},
    {"grass-1", {x = -15, y = 1}},
    {"grass-1", {x = -15, y = 2}},
    {"grass-1", {x = -15, y = 3}},
    {"grass-1", {x = -15, y = 4}},
    {"grass-1", {x = -15, y = 5}},
    {"grass-1", {x = -15, y = 6}},
    {"grass-1", {x = -15, y = 7}},
    {"grass-1", {x = -15, y = 8}},
    {"grass-1", {x = -15, y = 9}},
    {"grass-1", {x = -15, y = 10}},
    {"grass-1", {x = -15, y = 11}},
    {"grass-1", {x = -15, y = 12}},
    {"grass-1", {x = -15, y = 13}},
    {"grass-1", {x = -15, y = 14}},
    {"grass-1", {x = -15, y = 15}},
    {"grass-1", {x = -14, y = -16}},
    {"grass-1", {x = -14, y = -15}},
    {"grass-1", {x = -14, y = -14}},
    {"grass-1", {x = -14, y = -13}},
    {"grass-1", {x = -14, y = -12}},
    {"grass-1", {x = -14, y = -11}},
    {"grass-1", {x = -14, y = -10}},
    {"grass-1", {x = -14, y = -9}},
    {"grass-1", {x = -14, y = -8}},
    {"grass-1", {x = -14, y = -7}},
    {"grass-1", {x = -14, y = -6}},
    {"grass-1", {x = -14, y = -5}},
    {"grass-1", {x = -14, y = -4}},
    {"grass-1", {x = -14, y = -3}},
    {"grass-1", {x = -14, y = -2}},
    {"grass-1", {x = -14, y = -1}},
    {"grass-1", {x = -14, y = 0}},
    {"grass-1", {x = -14, y = 1}},
    {"grass-1", {x = -14, y = 2}},
    {"grass-1", {x = -14, y = 3}},
    {"grass-1", {x = -14, y = 4}},
    {"grass-1", {x = -14, y = 5}},
    {"grass-1", {x = -14, y = 6}},
    {"grass-1", {x = -14, y = 7}},
    {"grass-1", {x = -14, y = 8}},
    {"grass-1", {x = -14, y = 9}},
    {"grass-1", {x = -14, y = 10}},
    {"grass-1", {x = -14, y = 11}},
    {"grass-1", {x = -14, y = 12}},
    {"grass-1", {x = -14, y = 13}},
    {"grass-1", {x = -14, y = 14}},
    {"grass-1", {x = -14, y = 15}},
    {"grass-1", {x = -13, y = -16}},
    {"grass-1", {x = -13, y = -15}},
    {"grass-1", {x = -13, y = -14}},
    {"grass-1", {x = -13, y = -13}},
    {"grass-1", {x = -13, y = -12}},
    {"grass-1", {x = -13, y = -11}},
    {"grass-1", {x = -13, y = -10}},
    {"grass-1", {x = -13, y = -9}},
    {"grass-1", {x = -13, y = -8}},
    {"grass-1", {x = -13, y = -7}},
    {"grass-1", {x = -13, y = -6}},
    {"grass-1", {x = -13, y = -5}},
    {"grass-1", {x = -13, y = -4}},
    {"grass-1", {x = -13, y = -3}},
    {"grass-1", {x = -13, y = -2}},
    {"grass-1", {x = -13, y = -1}},
    {"grass-1", {x = -13, y = 0}},
    {"grass-1", {x = -13, y = 1}},
    {"grass-1", {x = -13, y = 2}},
    {"grass-1", {x = -13, y = 3}},
    {"grass-1", {x = -13, y = 4}},
    {"grass-1", {x = -13, y = 5}},
    {"grass-1", {x = -13, y = 6}},
    {"grass-1", {x = -13, y = 7}},
    {"grass-1", {x = -13, y = 8}},
    {"grass-1", {x = -13, y = 9}},
    {"grass-1", {x = -13, y = 10}},
    {"grass-1", {x = -13, y = 11}},
    {"grass-1", {x = -13, y = 12}},
    {"grass-1", {x = -13, y = 13}},
    {"grass-1", {x = -13, y = 14}},
    {"grass-1", {x = -13, y = 15}},
    {"grass-1", {x = -12, y = -16}},
    {"grass-1", {x = -12, y = -15}},
    {"grass-1", {x = -12, y = -14}},
    {"grass-1", {x = -12, y = -13}},
    {"grass-1", {x = -12, y = -12}},
    {"grass-1", {x = -12, y = -11}},
    {"grass-1", {x = -12, y = -10}},
    {"grass-1", {x = -12, y = -9}},
    {"grass-1", {x = -12, y = -8}},
    {"grass-1", {x = -12, y = -7}},
    {"grass-1", {x = -12, y = -6}},
    {"grass-1", {x = -12, y = -5}},
    {"grass-1", {x = -12, y = -4}},
    {"grass-1", {x = -12, y = -3}},
    {"grass-1", {x = -12, y = -2}},
    {"grass-1", {x = -12, y = -1}},
    {"grass-1", {x = -12, y = 0}},
    {"grass-1", {x = -12, y = 1}},
    {"grass-1", {x = -12, y = 2}},
    {"grass-1", {x = -12, y = 3}},
    {"grass-1", {x = -12, y = 4}},
    {"grass-1", {x = -12, y = 5}},
    {"grass-1", {x = -12, y = 6}},
    {"grass-1", {x = -12, y = 7}},
    {"grass-1", {x = -12, y = 8}},
    {"grass-1", {x = -12, y = 9}},
    {"grass-1", {x = -12, y = 10}},
    {"grass-1", {x = -12, y = 11}},
    {"grass-1", {x = -12, y = 12}},
    {"grass-1", {x = -12, y = 13}},
    {"grass-1", {x = -12, y = 14}},
    {"grass-1", {x = -12, y = 15}},
    {"grass-1", {x = -11, y = -16}},
    {"grass-1", {x = -11, y = -15}},
    {"grass-1", {x = -11, y = -14}},
    {"grass-1", {x = -11, y = -13}},
    {"grass-1", {x = -11, y = -12}},
    {"grass-1", {x = -11, y = -11}},
    {"grass-1", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-1", {x = -11, y = -5}},
    {"grass-1", {x = -11, y = -4}},
    {"grass-1", {x = -11, y = -3}},
    {"grass-1", {x = -11, y = -2}},
    {"grass-1", {x = -11, y = -1}},
    {"grass-1", {x = -11, y = 0}},
    {"grass-1", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-1", {x = -11, y = 4}},
    {"grass-1", {x = -11, y = 5}},
    {"grass-1", {x = -11, y = 6}},
    {"grass-1", {x = -11, y = 7}},
    {"grass-1", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"grass-1", {x = -11, y = 10}},
    {"grass-1", {x = -11, y = 11}},
    {"grass-1", {x = -11, y = 12}},
    {"grass-1", {x = -11, y = 13}},
    {"grass-1", {x = -11, y = 14}},
    {"grass-1", {x = -11, y = 15}},
    {"grass-1", {x = -10, y = -16}},
    {"grass-1", {x = -10, y = -15}},
    {"grass-1", {x = -10, y = -14}},
    {"grass-1", {x = -10, y = -13}},
    {"grass-1", {x = -10, y = -12}},
    {"grass-1", {x = -10, y = -11}},
    {"grass-1", {x = -10, y = -10}},
    {"grass-1", {x = -10, y = -9}},
    {"grass-1", {x = -10, y = -8}},
    {"grass-1", {x = -10, y = -7}},
    {"grass-1", {x = -10, y = -6}},
    {"grass-1", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-1", {x = -10, y = -3}},
    {"grass-1", {x = -10, y = -2}},
    {"grass-1", {x = -10, y = -1}},
    {"grass-1", {x = -10, y = 0}},
    {"grass-1", {x = -10, y = 1}},
    {"grass-1", {x = -10, y = 2}},
    {"grass-1", {x = -10, y = 3}},
    {"grass-1", {x = -10, y = 4}},
    {"grass-1", {x = -10, y = 5}},
    {"grass-1", {x = -10, y = 6}},
    {"grass-1", {x = -10, y = 7}},
    {"grass-1", {x = -10, y = 8}},
    {"grass-1", {x = -10, y = 9}},
    {"grass-1", {x = -10, y = 10}},
    {"grass-1", {x = -10, y = 11}},
    {"grass-1", {x = -10, y = 12}},
    {"grass-1", {x = -10, y = 13}},
    {"grass-1", {x = -10, y = 14}},
    {"grass-1", {x = -10, y = 15}},
    {"grass-1", {x = -9, y = -16}},
    {"grass-1", {x = -9, y = -15}},
    {"grass-1", {x = -9, y = -14}},
    {"grass-1", {x = -9, y = -13}},
    {"grass-1", {x = -9, y = -12}},
    {"grass-1", {x = -9, y = -11}},
    {"grass-1", {x = -9, y = -10}},
    {"grass-1", {x = -9, y = -9}},
    {"grass-1", {x = -9, y = -8}},
    {"grass-1", {x = -9, y = -7}},
    {"grass-1", {x = -9, y = -6}},
    {"grass-1", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"grass-1", {x = -9, y = -2}},
    {"grass-1", {x = -9, y = -1}},
    {"grass-1", {x = -9, y = 0}},
    {"grass-1", {x = -9, y = 1}},
    {"grass-1", {x = -9, y = 2}},
    {"grass-1", {x = -9, y = 3}},
    {"grass-1", {x = -9, y = 4}},
    {"grass-1", {x = -9, y = 5}},
    {"grass-1", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-1", {x = -9, y = 9}},
    {"grass-1", {x = -9, y = 10}},
    {"grass-1", {x = -9, y = 11}},
    {"grass-1", {x = -9, y = 12}},
    {"grass-1", {x = -9, y = 13}},
    {"grass-1", {x = -9, y = 14}},
    {"grass-1", {x = -9, y = 15}},
    {"grass-1", {x = -8, y = -16}},
    {"grass-1", {x = -8, y = -15}},
    {"grass-1", {x = -8, y = -14}},
    {"grass-1", {x = -8, y = -13}},
    {"grass-1", {x = -8, y = -12}},
    {"grass-1", {x = -8, y = -11}},
    {"grass-1", {x = -8, y = -10}},
    {"grass-1", {x = -8, y = -9}},
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-1", {x = -8, y = -2}},
    {"grass-1", {x = -8, y = -1}},
    {"grass-1", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-1", {x = -8, y = 9}},
    {"grass-1", {x = -8, y = 10}},
    {"grass-1", {x = -8, y = 11}},
    {"grass-1", {x = -8, y = 12}},
    {"grass-1", {x = -8, y = 13}},
    {"grass-1", {x = -8, y = 14}},
    {"grass-1", {x = -8, y = 15}},
    {"grass-1", {x = -7, y = -16}},
    {"grass-1", {x = -7, y = -15}},
    {"grass-1", {x = -7, y = -14}},
    {"grass-1", {x = -7, y = -13}},
    {"grass-1", {x = -7, y = -12}},
    {"grass-1", {x = -7, y = -11}},
    {"grass-1", {x = -7, y = -10}},
    {"grass-1", {x = -7, y = -9}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-1", {x = -7, y = -2}},
    {"grass-1", {x = -7, y = -1}},
    {"grass-1", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -7, y = 8}},
    {"grass-1", {x = -7, y = 9}},
    {"grass-1", {x = -7, y = 10}},
    {"grass-1", {x = -7, y = 11}},
    {"grass-1", {x = -7, y = 12}},
    {"grass-1", {x = -7, y = 13}},
    {"grass-1", {x = -7, y = 14}},
    {"grass-1", {x = -7, y = 15}},
    {"grass-1", {x = -6, y = -16}},
    {"grass-1", {x = -6, y = -15}},
    {"grass-1", {x = -6, y = -14}},
    {"grass-1", {x = -6, y = -13}},
    {"grass-1", {x = -6, y = -12}},
    {"grass-1", {x = -6, y = -11}},
    {"grass-1", {x = -6, y = -10}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-1", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"grass-1", {x = -6, y = 9}},
    {"grass-1", {x = -6, y = 10}},
    {"grass-1", {x = -6, y = 11}},
    {"grass-1", {x = -6, y = 12}},
    {"grass-1", {x = -6, y = 13}},
    {"grass-1", {x = -6, y = 14}},
    {"grass-1", {x = -6, y = 15}},
    {"grass-1", {x = -5, y = -16}},
    {"grass-1", {x = -5, y = -15}},
    {"grass-1", {x = -5, y = -14}},
    {"grass-1", {x = -5, y = -13}},
    {"grass-1", {x = -5, y = -12}},
    {"grass-1", {x = -5, y = -11}},
    {"grass-1", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -5, y = 8}},
    {"grass-1", {x = -5, y = 9}},
    {"grass-1", {x = -5, y = 10}},
    {"grass-1", {x = -5, y = 11}},
    {"grass-1", {x = -5, y = 12}},
    {"grass-1", {x = -5, y = 13}},
    {"grass-1", {x = -5, y = 14}},
    {"grass-1", {x = -5, y = 15}},
    {"grass-1", {x = -4, y = -16}},
    {"grass-1", {x = -4, y = -15}},
    {"grass-1", {x = -4, y = -14}},
    {"grass-1", {x = -4, y = -13}},
    {"grass-1", {x = -4, y = -12}},
    {"grass-1", {x = -4, y = -11}},
    {"grass-1", {x = -4, y = -10}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"grass-1", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -4, y = 8}},
    {"grass-1", {x = -4, y = 9}},
    {"grass-1", {x = -4, y = 10}},
    {"grass-1", {x = -4, y = 11}},
    {"grass-1", {x = -4, y = 12}},
    {"grass-1", {x = -4, y = 13}},
    {"grass-1", {x = -4, y = 14}},
    {"grass-1", {x = -4, y = 15}},
    {"grass-1", {x = -3, y = -16}},
    {"grass-1", {x = -3, y = -15}},
    {"grass-1", {x = -3, y = -14}},
    {"grass-1", {x = -3, y = -13}},
    {"grass-1", {x = -3, y = -12}},
    {"grass-1", {x = -3, y = -11}},
    {"grass-1", {x = -3, y = -10}},
    {"grass-1", {x = -3, y = -9}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -3, y = 8}},
    {"grass-1", {x = -3, y = 9}},
    {"grass-1", {x = -3, y = 10}},
    {"grass-1", {x = -3, y = 11}},
    {"grass-1", {x = -3, y = 12}},
    {"grass-1", {x = -3, y = 13}},
    {"grass-1", {x = -3, y = 14}},
    {"grass-1", {x = -3, y = 15}},
    {"grass-1", {x = -2, y = -16}},
    {"grass-1", {x = -2, y = -15}},
    {"grass-1", {x = -2, y = -14}},
    {"grass-1", {x = -2, y = -13}},
    {"grass-1", {x = -2, y = -12}},
    {"grass-1", {x = -2, y = -11}},
    {"grass-1", {x = -2, y = -10}},
    {"grass-1", {x = -2, y = -9}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-1", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -2, y = 8}},
    {"grass-1", {x = -2, y = 9}},
    {"grass-1", {x = -2, y = 10}},
    {"grass-1", {x = -2, y = 11}},
    {"grass-1", {x = -2, y = 12}},
    {"grass-1", {x = -2, y = 13}},
    {"grass-1", {x = -2, y = 14}},
    {"grass-1", {x = -2, y = 15}},
    {"grass-1", {x = -1, y = -16}},
    {"grass-1", {x = -1, y = -15}},
    {"grass-1", {x = -1, y = -14}},
    {"grass-1", {x = -1, y = -13}},
    {"grass-1", {x = -1, y = -12}},
    {"grass-1", {x = -1, y = -11}},
    {"grass-1", {x = -1, y = -10}},
    {"grass-1", {x = -1, y = -9}},
    {"grass-1", {x = -1, y = -8}},
    {"grass-1", {x = -1, y = -7}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = -1, y = 8}},
    {"grass-1", {x = -1, y = 9}},
    {"grass-1", {x = -1, y = 10}},
    {"grass-1", {x = -1, y = 11}},
    {"grass-1", {x = -1, y = 12}},
    {"grass-1", {x = -1, y = 13}},
    {"grass-1", {x = -1, y = 14}},
    {"grass-1", {x = -1, y = 15}},
    {"grass-1", {x = 0, y = -16}},
    {"grass-1", {x = 0, y = -15}},
    {"grass-1", {x = 0, y = -14}},
    {"grass-1", {x = 0, y = -13}},
    {"grass-1", {x = 0, y = -12}},
    {"grass-1", {x = 0, y = -11}},
    {"grass-1", {x = 0, y = -10}},
    {"grass-1", {x = 0, y = -9}},
    {"grass-1", {x = 0, y = -8}},
    {"grass-1", {x = 0, y = -7}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-1", {x = 0, y = 9}},
    {"grass-1", {x = 0, y = 10}},
    {"grass-1", {x = 0, y = 11}},
    {"grass-1", {x = 0, y = 12}},
    {"grass-1", {x = 0, y = 13}},
    {"grass-1", {x = 0, y = 14}},
    {"grass-1", {x = 0, y = 15}},
    {"grass-1", {x = 1, y = -16}},
    {"grass-1", {x = 1, y = -15}},
    {"grass-1", {x = 1, y = -14}},
    {"grass-1", {x = 1, y = -13}},
    {"grass-1", {x = 1, y = -12}},
    {"grass-1", {x = 1, y = -11}},
    {"grass-1", {x = 1, y = -10}},
    {"grass-1", {x = 1, y = -9}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-1", {x = 1, y = 9}},
    {"grass-1", {x = 1, y = 10}},
    {"grass-1", {x = 1, y = 11}},
    {"grass-1", {x = 1, y = 12}},
    {"grass-1", {x = 1, y = 13}},
    {"grass-1", {x = 1, y = 14}},
    {"grass-1", {x = 1, y = 15}},
    {"grass-1", {x = 2, y = -16}},
    {"grass-1", {x = 2, y = -15}},
    {"grass-1", {x = 2, y = -14}},
    {"grass-1", {x = 2, y = -13}},
    {"grass-1", {x = 2, y = -12}},
    {"grass-1", {x = 2, y = -11}},
    {"grass-1", {x = 2, y = -10}},
    {"grass-1", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 2, y = 9}},
    {"grass-1", {x = 2, y = 10}},
    {"grass-1", {x = 2, y = 11}},
    {"grass-1", {x = 2, y = 12}},
    {"grass-1", {x = 2, y = 13}},
    {"grass-1", {x = 2, y = 14}},
    {"grass-1", {x = 2, y = 15}},
    {"grass-1", {x = 3, y = -16}},
    {"grass-1", {x = 3, y = -15}},
    {"grass-1", {x = 3, y = -14}},
    {"grass-1", {x = 3, y = -13}},
    {"grass-1", {x = 3, y = -12}},
    {"grass-1", {x = 3, y = -11}},
    {"grass-1", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 3, y = 9}},
    {"grass-1", {x = 3, y = 10}},
    {"grass-1", {x = 3, y = 11}},
    {"grass-1", {x = 3, y = 12}},
    {"grass-1", {x = 3, y = 13}},
    {"grass-1", {x = 3, y = 14}},
    {"grass-1", {x = 3, y = 15}},
    {"grass-1", {x = 4, y = -16}},
    {"grass-1", {x = 4, y = -15}},
    {"grass-1", {x = 4, y = -14}},
    {"grass-1", {x = 4, y = -13}},
    {"grass-1", {x = 4, y = -12}},
    {"grass-1", {x = 4, y = -11}},
    {"grass-1", {x = 4, y = -10}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 4, y = 8}},
    {"grass-1", {x = 4, y = 9}},
    {"grass-1", {x = 4, y = 10}},
    {"grass-1", {x = 4, y = 11}},
    {"grass-1", {x = 4, y = 12}},
    {"grass-1", {x = 4, y = 13}},
    {"grass-1", {x = 4, y = 14}},
    {"grass-1", {x = 4, y = 15}},
    {"grass-1", {x = 5, y = -16}},
    {"grass-1", {x = 5, y = -15}},
    {"grass-1", {x = 5, y = -14}},
    {"grass-1", {x = 5, y = -13}},
    {"grass-1", {x = 5, y = -12}},
    {"grass-1", {x = 5, y = -11}},
    {"grass-1", {x = 5, y = -10}},
    {"grass-1", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 5, y = 8}},
    {"grass-1", {x = 5, y = 9}},
    {"grass-1", {x = 5, y = 10}},
    {"grass-1", {x = 5, y = 11}},
    {"grass-1", {x = 5, y = 12}},
    {"grass-1", {x = 5, y = 13}},
    {"grass-1", {x = 5, y = 14}},
    {"grass-1", {x = 5, y = 15}},
    {"grass-1", {x = 6, y = -16}},
    {"grass-1", {x = 6, y = -15}},
    {"grass-1", {x = 6, y = -14}},
    {"grass-1", {x = 6, y = -13}},
    {"grass-1", {x = 6, y = -12}},
    {"grass-1", {x = 6, y = -11}},
    {"grass-1", {x = 6, y = -10}},
    {"grass-1", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-1", {x = 6, y = 7}},
    {"grass-1", {x = 6, y = 8}},
    {"grass-1", {x = 6, y = 9}},
    {"grass-1", {x = 6, y = 10}},
    {"grass-1", {x = 6, y = 11}},
    {"grass-1", {x = 6, y = 12}},
    {"grass-1", {x = 6, y = 13}},
    {"grass-1", {x = 6, y = 14}},
    {"grass-1", {x = 6, y = 15}},
    {"grass-1", {x = 7, y = -16}},
    {"grass-1", {x = 7, y = -15}},
    {"grass-1", {x = 7, y = -14}},
    {"grass-1", {x = 7, y = -13}},
    {"grass-1", {x = 7, y = -12}},
    {"grass-1", {x = 7, y = -11}},
    {"grass-1", {x = 7, y = -10}},
    {"grass-1", {x = 7, y = -9}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-1", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
    {"grass-1", {x = 7, y = 8}},
    {"grass-1", {x = 7, y = 9}},
    {"grass-1", {x = 7, y = 10}},
    {"grass-1", {x = 7, y = 11}},
    {"grass-1", {x = 7, y = 12}},
    {"grass-1", {x = 7, y = 13}},
    {"grass-1", {x = 7, y = 14}},
    {"grass-1", {x = 7, y = 15}},
    {"grass-1", {x = 8, y = -16}},
    {"grass-1", {x = 8, y = -15}},
    {"grass-1", {x = 8, y = -14}},
    {"grass-1", {x = 8, y = -13}},
    {"grass-1", {x = 8, y = -12}},
    {"grass-1", {x = 8, y = -11}},
    {"grass-1", {x = 8, y = -10}},
    {"grass-1", {x = 8, y = -9}},
    {"grass-1", {x = 8, y = -8}},
    {"grass-1", {x = 8, y = -7}},
    {"grass-1", {x = 8, y = -6}},
    {"grass-1", {x = 8, y = -5}},
    {"grass-1", {x = 8, y = -4}},
    {"grass-1", {x = 8, y = -3}},
    {"grass-1", {x = 8, y = -2}},
    {"grass-1", {x = 8, y = -1}},
    {"grass-1", {x = 8, y = 0}},
    {"grass-1", {x = 8, y = 1}},
    {"grass-1", {x = 8, y = 2}},
    {"grass-1", {x = 8, y = 3}},
    {"grass-1", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-1", {x = 8, y = 6}},
    {"grass-1", {x = 8, y = 7}},
    {"grass-1", {x = 8, y = 8}},
    {"grass-1", {x = 8, y = 9}},
    {"grass-1", {x = 8, y = 10}},
    {"grass-1", {x = 8, y = 11}},
    {"grass-1", {x = 8, y = 12}},
    {"grass-1", {x = 8, y = 13}},
    {"grass-1", {x = 8, y = 14}},
    {"grass-1", {x = 8, y = 15}},
    {"grass-1", {x = 9, y = -16}},
    {"grass-1", {x = 9, y = -15}},
    {"grass-1", {x = 9, y = -14}},
    {"grass-1", {x = 9, y = -13}},
    {"grass-1", {x = 9, y = -12}},
    {"grass-1", {x = 9, y = -11}},
    {"grass-1", {x = 9, y = -10}},
    {"grass-1", {x = 9, y = -9}},
    {"grass-1", {x = 9, y = -8}},
    {"grass-1", {x = 9, y = -7}},
    {"grass-1", {x = 9, y = -6}},
    {"grass-1", {x = 9, y = -5}},
    {"grass-1", {x = 9, y = -4}},
    {"grass-1", {x = 9, y = -3}},
    {"grass-1", {x = 9, y = -2}},
    {"grass-1", {x = 9, y = -1}},
    {"grass-1", {x = 9, y = 0}},
    {"grass-1", {x = 9, y = 1}},
    {"grass-1", {x = 9, y = 2}},
    {"grass-1", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"grass-1", {x = 9, y = 5}},
    {"grass-1", {x = 9, y = 6}},
    {"grass-1", {x = 9, y = 7}},
    {"grass-1", {x = 9, y = 8}},
    {"grass-1", {x = 9, y = 9}},
    {"grass-1", {x = 9, y = 10}},
    {"grass-1", {x = 9, y = 11}},
    {"grass-1", {x = 9, y = 12}},
    {"grass-1", {x = 9, y = 13}},
    {"grass-1", {x = 9, y = 14}},
    {"grass-1", {x = 9, y = 15}},
    {"grass-1", {x = 10, y = -16}},
    {"grass-1", {x = 10, y = -15}},
    {"grass-1", {x = 10, y = -14}},
    {"grass-1", {x = 10, y = -13}},
    {"grass-1", {x = 10, y = -12}},
    {"grass-1", {x = 10, y = -11}},
    {"grass-1", {x = 10, y = -10}},
    {"grass-1", {x = 10, y = -9}},
    {"grass-1", {x = 10, y = -8}},
    {"grass-1", {x = 10, y = -7}},
    {"grass-1", {x = 10, y = -6}},
    {"grass-1", {x = 10, y = -5}},
    {"grass-1", {x = 10, y = -4}},
    {"grass-1", {x = 10, y = -3}},
    {"grass-1", {x = 10, y = -2}},
    {"grass-1", {x = 10, y = -1}},
    {"grass-1", {x = 10, y = 0}},
    {"grass-1", {x = 10, y = 1}},
    {"grass-1", {x = 10, y = 2}},
    {"grass-1", {x = 10, y = 3}},
    {"grass-1", {x = 10, y = 4}},
    {"grass-1", {x = 10, y = 5}},
    {"grass-1", {x = 10, y = 6}},
    {"grass-1", {x = 10, y = 7}},
    {"grass-1", {x = 10, y = 8}},
    {"grass-1", {x = 10, y = 9}},
    {"grass-1", {x = 10, y = 10}},
    {"grass-1", {x = 10, y = 11}},
    {"grass-1", {x = 10, y = 12}},
    {"grass-1", {x = 10, y = 13}},
    {"grass-1", {x = 10, y = 14}},
    {"grass-1", {x = 10, y = 15}},
    {"grass-1", {x = 11, y = -16}},
    {"grass-1", {x = 11, y = -15}},
    {"grass-1", {x = 11, y = -14}},
    {"grass-1", {x = 11, y = -13}},
    {"grass-1", {x = 11, y = -12}},
    {"grass-1", {x = 11, y = -11}},
    {"grass-1", {x = 11, y = -10}},
    {"grass-1", {x = 11, y = -9}},
    {"grass-1", {x = 11, y = -8}},
    {"grass-1", {x = 11, y = -7}},
    {"grass-1", {x = 11, y = -6}},
    {"grass-1", {x = 11, y = -5}},
    {"grass-1", {x = 11, y = -4}},
    {"grass-1", {x = 11, y = -3}},
    {"grass-1", {x = 11, y = -2}},
    {"grass-1", {x = 11, y = -1}},
    {"grass-1", {x = 11, y = 0}},
    {"grass-1", {x = 11, y = 1}},
    {"grass-1", {x = 11, y = 2}},
    {"grass-1", {x = 11, y = 3}},
    {"grass-1", {x = 11, y = 4}},
    {"grass-1", {x = 11, y = 5}},
    {"grass-1", {x = 11, y = 6}},
    {"grass-1", {x = 11, y = 7}},
    {"grass-1", {x = 11, y = 8}},
    {"grass-1", {x = 11, y = 9}},
    {"grass-1", {x = 11, y = 10}},
    {"grass-1", {x = 11, y = 11}},
    {"grass-1", {x = 11, y = 12}},
    {"grass-1", {x = 11, y = 13}},
    {"grass-1", {x = 11, y = 14}},
    {"grass-1", {x = 11, y = 15}},
    {"grass-1", {x = 12, y = -16}},
    {"grass-1", {x = 12, y = -15}},
    {"grass-1", {x = 12, y = -14}},
    {"grass-1", {x = 12, y = -13}},
    {"grass-1", {x = 12, y = -12}},
    {"grass-1", {x = 12, y = -11}},
    {"grass-1", {x = 12, y = -10}},
    {"grass-1", {x = 12, y = -9}},
    {"grass-1", {x = 12, y = -8}},
    {"grass-1", {x = 12, y = -7}},
    {"grass-1", {x = 12, y = -6}},
    {"grass-1", {x = 12, y = -5}},
    {"grass-1", {x = 12, y = -4}},
    {"grass-1", {x = 12, y = -3}},
    {"grass-1", {x = 12, y = -2}},
    {"grass-1", {x = 12, y = -1}},
    {"grass-1", {x = 12, y = 0}},
    {"grass-1", {x = 12, y = 1}},
    {"grass-1", {x = 12, y = 2}},
    {"grass-1", {x = 12, y = 3}},
    {"grass-1", {x = 12, y = 4}},
    {"grass-1", {x = 12, y = 5}},
    {"grass-1", {x = 12, y = 6}},
    {"grass-1", {x = 12, y = 7}},
    {"grass-1", {x = 12, y = 8}},
    {"grass-1", {x = 12, y = 9}},
    {"grass-1", {x = 12, y = 10}},
    {"grass-1", {x = 12, y = 11}},
    {"grass-1", {x = 12, y = 12}},
    {"grass-1", {x = 12, y = 13}},
    {"grass-1", {x = 12, y = 14}},
    {"grass-1", {x = 12, y = 15}},
    {"grass-1", {x = 13, y = -16}},
    {"grass-1", {x = 13, y = -15}},
    {"grass-1", {x = 13, y = -14}},
    {"grass-1", {x = 13, y = -13}},
    {"grass-1", {x = 13, y = -12}},
    {"grass-1", {x = 13, y = -11}},
    {"grass-1", {x = 13, y = -10}},
    {"grass-1", {x = 13, y = -9}},
    {"grass-1", {x = 13, y = -8}},
    {"grass-1", {x = 13, y = -7}},
    {"grass-1", {x = 13, y = -6}},
    {"grass-1", {x = 13, y = -5}},
    {"grass-1", {x = 13, y = -4}},
    {"grass-1", {x = 13, y = -3}},
    {"grass-1", {x = 13, y = -2}},
    {"grass-1", {x = 13, y = -1}},
    {"grass-1", {x = 13, y = 0}},
    {"grass-1", {x = 13, y = 1}},
    {"grass-1", {x = 13, y = 2}},
    {"grass-1", {x = 13, y = 3}},
    {"grass-1", {x = 13, y = 4}},
    {"grass-1", {x = 13, y = 5}},
    {"grass-1", {x = 13, y = 6}},
    {"grass-1", {x = 13, y = 7}},
    {"grass-1", {x = 13, y = 8}},
    {"grass-1", {x = 13, y = 9}},
    {"grass-1", {x = 13, y = 10}},
    {"grass-1", {x = 13, y = 11}},
    {"grass-1", {x = 13, y = 12}},
    {"grass-1", {x = 13, y = 13}},
    {"grass-1", {x = 13, y = 14}},
    {"grass-1", {x = 13, y = 15}},
    {"grass-1", {x = 14, y = -16}},
    {"grass-1", {x = 14, y = -15}},
    {"grass-1", {x = 14, y = -14}},
    {"grass-1", {x = 14, y = -13}},
    {"grass-1", {x = 14, y = -12}},
    {"grass-1", {x = 14, y = -11}},
    {"grass-1", {x = 14, y = -10}},
    {"grass-1", {x = 14, y = -9}},
    {"grass-1", {x = 14, y = -8}},
    {"grass-1", {x = 14, y = -7}},
    {"grass-1", {x = 14, y = -6}},
    {"grass-1", {x = 14, y = -5}},
    {"grass-1", {x = 14, y = -4}},
    {"grass-1", {x = 14, y = -3}},
    {"grass-1", {x = 14, y = -2}},
    {"grass-1", {x = 14, y = -1}},
    {"grass-1", {x = 14, y = 0}},
    {"grass-1", {x = 14, y = 1}},
    {"grass-1", {x = 14, y = 2}},
    {"grass-1", {x = 14, y = 3}},
    {"grass-1", {x = 14, y = 4}},
    {"grass-1", {x = 14, y = 5}},
    {"grass-1", {x = 14, y = 6}},
    {"grass-1", {x = 14, y = 7}},
    {"grass-1", {x = 14, y = 8}},
    {"grass-1", {x = 14, y = 9}},
    {"grass-1", {x = 14, y = 10}},
    {"grass-1", {x = 14, y = 11}},
    {"grass-1", {x = 14, y = 12}},
    {"grass-1", {x = 14, y = 13}},
    {"grass-1", {x = 14, y = 14}},
    {"grass-1", {x = 14, y = 15}},
    {"grass-1", {x = 15, y = -16}},
    {"grass-1", {x = 15, y = -15}},
    {"grass-1", {x = 15, y = -14}},
    {"grass-1", {x = 15, y = -13}},
    {"grass-1", {x = 15, y = -12}},
    {"grass-1", {x = 15, y = -11}},
    {"grass-1", {x = 15, y = -10}},
    {"grass-1", {x = 15, y = -9}},
    {"grass-1", {x = 15, y = -8}},
    {"grass-1", {x = 15, y = -7}},
    {"grass-1", {x = 15, y = -6}},
    {"grass-1", {x = 15, y = -5}},
    {"grass-1", {x = 15, y = -4}},
    {"grass-1", {x = 15, y = -3}},
    {"grass-1", {x = 15, y = -2}},
    {"grass-1", {x = 15, y = -1}},
    {"grass-1", {x = 15, y = 0}},
    {"grass-1", {x = 15, y = 1}},
    {"grass-1", {x = 15, y = 2}},
    {"grass-1", {x = 15, y = 3}},
    {"grass-1", {x = 15, y = 4}},
    {"grass-1", {x = 15, y = 5}},
    {"grass-1", {x = 15, y = 6}},
    {"grass-1", {x = 15, y = 7}},
    {"grass-1", {x = 15, y = 8}},
    {"grass-1", {x = 15, y = 9}},
    {"grass-1", {x = 15, y = 10}},
    {"grass-1", {x = 15, y = 11}},
    {"grass-1", {x = 15, y = 12}},
    {"grass-1", {x = 15, y = 13}},
    {"grass-1", {x = 15, y = 14}},
    {"grass-1", {x = 15, y = 15}},
  }
}
