return
{
  entities =
  {
    {"stone-wall", {x = -15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -12.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = -13}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"logistic-chest-passive-provider", {x = -10.5, y = -13.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"logistic-chest-passive-provider", {x = -10.5, y = -12.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9400}, }},
    {"fast-inserter", {x = -11.5, y = -13.5}, {dir = "east", force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = -12.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -12.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 10.5, y = -13.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"logistic-chest-passive-provider", {x = 10.5, y = -12.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = 11.5, y = -13.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = 11.5, y = -12.5}, {dir = "west", force = "enemy", }},
    {"gun-turret", {x = 13, y = -13}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -10.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -13.5, y = -10.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"logistic-chest-passive-provider", {x = -12.5, y = -10.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = -12.5, y = -11.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = -13.5, y = -11.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -10.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 12.5, y = -10.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 4400}, }},
    {"logistic-chest-passive-provider", {x = 13.5, y = -10.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = 13.5, y = -11.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 12.5, y = -11.5}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -7.5}, {force = "enemy", }},
    {"substation", {x = -6, y = -7}, {}},
    {"stone-wall", {x = -7.5, y = -7.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = -6.5}, {force = "enemy", }},
    {"steel-chest", {x = -4.5, y = -7.5}, {items = {["processing-unit"] = 100, ["repair-pack"] = 100}, }},
    {"steel-chest", {x = 3.5, y = -7.5}, {items = {["flying-robot-frame"] = 50}, }},
    {"substation", {x = 6, y = -7}, {}},
    {"stone-wall", {x = 7.5, y = -7.5}, {force = "enemy", }},
    {"gate", {x = 7.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -4.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -4.5}, {force = "enemy", }},
    {"steel-chest", {x = -4.5, y = -5.5}, {items = {["production-science-pack"] = 200}, }},
    {"stone-wall", {x = -2.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -4.5}, {force = "enemy", }},
    {"gate", {x = -1.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -0.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -4.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -4.5}, {force = "enemy", }},
    {"steel-chest", {x = 3.5, y = -5.5}, {items = {["power-armor"] = 1}, }},
    {"stone-wall", {x = 5.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -4.5}, {force = "enemy", }},
    {"gate", {x = 7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -3.5}, {force = "enemy", }},
    {"aliengenerator", {x = -0.5, y = -1}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = -1.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -0.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -3.5}, {force = "enemy", }},
    {"roboport", {x = 7, y = -1}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"stone-wall", {x = 7.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -3.5}, {force = "enemy", }},
    {"laser-turret", {x = 11, y = -2}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -1.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -5.5, y = -0.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"aliencon-robot", {x = -0.02, y = -1.21}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.16, y = -1.21}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.21, y = -1.12}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.21, y = -1.07}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.26, y = -0.98}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.26, y = -0.89}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.26, y = -0.79}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.3, y = -0.7}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.3, y = -0.61}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.3, y = -0.47}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.26, y = -0.33}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.26, y = -0.23}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.26, y = -0.1}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.88, y = -1.39}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.7, y = -1.44}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.55, y = -1.44}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.46, y = -1.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.37, y = -1.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.28, y = -1.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.14, y = -1.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.04, y = -1.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.86, y = -1.49}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.67, y = -1.44}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.58, y = -1.44}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.39, y = -1.39}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.16, y = -1.3}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.25, y = -0.89}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.25, y = -0.98}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.25, y = -1.07}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.2, y = -1.16}, {force = "enemy", }},
    {"aliencon-robot", {x = 2.07, y = -1.26}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 0.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -5.5, y = 1.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"aliencon-robot", {x = -0.16, y = 0.09}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.12, y = 0.18}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.02, y = 0.28}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.21, y = 0}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.07, y = 0.37}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.3, y = 0.37}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 1.5}, {force = "enemy", }},
    {"substation", {x = 6, y = 2}, {force = "enemy", }},
    {"laser-turret", {x = 11, y = 1}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 3.5}, {force = "enemy", }},
    {"gate", {x = -1.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -0.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 0.5, y = 3.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 4.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 4.5}, {force = "enemy", }},
    {"steel-chest", {x = -4.5, y = 5.5}, {items = {["utility-science-pack"] = 200}, }},
    {"stone-wall", {x = -3.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 4.5}, {force = "enemy", }},
    {"gate", {x = -1.5, y = 4.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -0.5, y = 4.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 4.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 4.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 4.5}, {force = "enemy", }},
    {"steel-chest", {x = 3.5, y = 5.5}, {items = {["low-density-structure"] = 20}, }},
    {"stone-wall", {x = 4.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 4.5}, {force = "enemy", }},
    {"gate", {x = 7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 6.5}, {force = "enemy", }},
    {"substation", {x = -6, y = 7}, {}},
    {"stone-wall", {x = -7.5, y = 7.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = 6.5}, {force = "enemy", }},
    {"steel-chest", {x = -4.5, y = 7.5}, {items = {["fusion-reactor-equipment"] = 1}, }},
    {"steel-chest", {x = 3.5, y = 7.5}, {items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"substation", {x = 6, y = 7}, {}},
    {"stone-wall", {x = 7.5, y = 7.5}, {force = "enemy", }},
    {"gate", {x = 7.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 10.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -13.5, y = 10.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"logistic-chest-passive-provider", {x = -12.5, y = 10.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = -13.5, y = 11.5}, {force = "enemy", }},
    {"fast-inserter", {x = -12.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 11.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 12.5, y = 10.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"logistic-chest-passive-provider", {x = 13.5, y = 10.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = 12.5, y = 11.5}, {force = "enemy", }},
    {"fast-inserter", {x = 13.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = -13, y = 13}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"logistic-chest-passive-provider", {x = -10.5, y = 12.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"logistic-chest-passive-provider", {x = -10.5, y = 13.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = -11.5, y = 12.5}, {dir = "east", force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = 13.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 13.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 10.5, y = 13.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 3600}, }},
    {"logistic-chest-passive-provider", {x = 10.5, y = 12.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = 11.5, y = 12.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = 11.5, y = 13.5}, {dir = "west", force = "enemy", }},
    {"gun-turret", {x = 13, y = 13}, {dir = "south", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 14.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 15.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-4", {x = -16, y = -16}},
    {"grass-4", {x = -16, y = -15}},
    {"dirt-7", {x = -16, y = -14}},
    {"dirt-7", {x = -16, y = -13}},
    {"dirt-7", {x = -16, y = -12}},
    {"dirt-7", {x = -16, y = -11}},
    {"dirt-7", {x = -16, y = -10}},
    {"dirt-7", {x = -16, y = -9}},
    {"dirt-7", {x = -16, y = -8}},
    {"dirt-7", {x = -16, y = -7}},
    {"dirt-7", {x = -16, y = -6}},
    {"dirt-7", {x = -16, y = -5}},
    {"dirt-7", {x = -16, y = -4}},
    {"grass-4", {x = -16, y = -3}},
    {"grass-4", {x = -16, y = -2}},
    {"dirt-7", {x = -16, y = -1}},
    {"dirt-7", {x = -16, y = 0}},
    {"dirt-7", {x = -16, y = 1}},
    {"dirt-7", {x = -16, y = 2}},
    {"dirt-7", {x = -16, y = 3}},
    {"dirt-7", {x = -16, y = 4}},
    {"dirt-7", {x = -16, y = 5}},
    {"dirt-7", {x = -16, y = 6}},
    {"dirt-7", {x = -16, y = 7}},
    {"dirt-7", {x = -16, y = 8}},
    {"dirt-7", {x = -16, y = 9}},
    {"dirt-7", {x = -16, y = 10}},
    {"grass-4", {x = -16, y = 11}},
    {"grass-4", {x = -16, y = 12}},
    {"grass-4", {x = -16, y = 13}},
    {"grass-4", {x = -16, y = 14}},
    {"grass-4", {x = -16, y = 15}},
    {"grass-4", {x = -15, y = -16}},
    {"grass-4", {x = -15, y = -15}},
    {"dirt-7", {x = -15, y = -14}},
    {"dirt-7", {x = -15, y = -13}},
    {"dirt-7", {x = -15, y = -12}},
    {"dirt-7", {x = -15, y = -11}},
    {"dirt-7", {x = -15, y = -10}},
    {"dirt-7", {x = -15, y = -9}},
    {"dirt-7", {x = -15, y = -8}},
    {"dirt-7", {x = -15, y = -7}},
    {"dirt-7", {x = -15, y = -6}},
    {"dirt-7", {x = -15, y = -5}},
    {"grass-4", {x = -15, y = -4}},
    {"grass-4", {x = -15, y = -3}},
    {"grass-4", {x = -15, y = -2}},
    {"dirt-7", {x = -15, y = -1}},
    {"dirt-7", {x = -15, y = 0}},
    {"dirt-7", {x = -15, y = 1}},
    {"dirt-7", {x = -15, y = 2}},
    {"dirt-7", {x = -15, y = 3}},
    {"dirt-7", {x = -15, y = 4}},
    {"dirt-7", {x = -15, y = 5}},
    {"dirt-7", {x = -15, y = 6}},
    {"dirt-7", {x = -15, y = 7}},
    {"dirt-7", {x = -15, y = 8}},
    {"dirt-7", {x = -15, y = 9}},
    {"dirt-7", {x = -15, y = 10}},
    {"dirt-7", {x = -15, y = 11}},
    {"grass-4", {x = -15, y = 12}},
    {"grass-4", {x = -15, y = 13}},
    {"grass-4", {x = -15, y = 14}},
    {"grass-4", {x = -15, y = 15}},
    {"grass-4", {x = -14, y = -16}},
    {"grass-4", {x = -14, y = -15}},
    {"dirt-7", {x = -14, y = -14}},
    {"dirt-7", {x = -14, y = -13}},
    {"dirt-7", {x = -14, y = -12}},
    {"dirt-7", {x = -14, y = -11}},
    {"dirt-7", {x = -14, y = -10}},
    {"dirt-7", {x = -14, y = -9}},
    {"dirt-7", {x = -14, y = -8}},
    {"dirt-7", {x = -14, y = -7}},
    {"dirt-7", {x = -14, y = -6}},
    {"dirt-7", {x = -14, y = -5}},
    {"grass-4", {x = -14, y = -4}},
    {"grass-4", {x = -14, y = -3}},
    {"dirt-7", {x = -14, y = -2}},
    {"dirt-7", {x = -14, y = -1}},
    {"dirt-7", {x = -14, y = 0}},
    {"dirt-7", {x = -14, y = 1}},
    {"dirt-7", {x = -14, y = 2}},
    {"dirt-7", {x = -14, y = 3}},
    {"dirt-6", {x = -14, y = 4}},
    {"dirt-6", {x = -14, y = 5}},
    {"dirt-7", {x = -14, y = 6}},
    {"dirt-7", {x = -14, y = 7}},
    {"dirt-7", {x = -14, y = 8}},
    {"dirt-7", {x = -14, y = 9}},
    {"dirt-7", {x = -14, y = 10}},
    {"dirt-7", {x = -14, y = 11}},
    {"dirt-7", {x = -14, y = 12}},
    {"grass-4", {x = -14, y = 13}},
    {"grass-4", {x = -14, y = 14}},
    {"grass-4", {x = -14, y = 15}},
    {"grass-4", {x = -13, y = -16}},
    {"dirt-7", {x = -13, y = -15}},
    {"dirt-7", {x = -13, y = -14}},
    {"dirt-7", {x = -13, y = -13}},
    {"dirt-7", {x = -13, y = -12}},
    {"dirt-7", {x = -13, y = -11}},
    {"dirt-7", {x = -13, y = -10}},
    {"dirt-7", {x = -13, y = -9}},
    {"dirt-7", {x = -13, y = -8}},
    {"dirt-7", {x = -13, y = -7}},
    {"dirt-7", {x = -13, y = -6}},
    {"dirt-7", {x = -13, y = -5}},
    {"dirt-7", {x = -13, y = -4}},
    {"dirt-7", {x = -13, y = -3}},
    {"dirt-7", {x = -13, y = -2}},
    {"dirt-7", {x = -13, y = -1}},
    {"dirt-7", {x = -13, y = 0}},
    {"dirt-7", {x = -13, y = 1}},
    {"dirt-7", {x = -13, y = 2}},
    {"dirt-6", {x = -13, y = 3}},
    {"dirt-6", {x = -13, y = 4}},
    {"dirt-6", {x = -13, y = 5}},
    {"dirt-6", {x = -13, y = 6}},
    {"dirt-7", {x = -13, y = 7}},
    {"dirt-7", {x = -13, y = 8}},
    {"dirt-7", {x = -13, y = 9}},
    {"dirt-7", {x = -13, y = 10}},
    {"dirt-7", {x = -13, y = 11}},
    {"dirt-7", {x = -13, y = 12}},
    {"dirt-7", {x = -13, y = 13}},
    {"dirt-7", {x = -13, y = 14}},
    {"dirt-7", {x = -13, y = 15}},
    {"grass-4", {x = -12, y = -16}},
    {"dirt-7", {x = -12, y = -15}},
    {"dirt-7", {x = -12, y = -14}},
    {"dirt-7", {x = -12, y = -13}},
    {"dirt-7", {x = -12, y = -12}},
    {"dirt-7", {x = -12, y = -11}},
    {"dirt-7", {x = -12, y = -10}},
    {"dirt-7", {x = -12, y = -9}},
    {"dirt-7", {x = -12, y = -8}},
    {"dirt-7", {x = -12, y = -7}},
    {"dirt-7", {x = -12, y = -6}},
    {"dirt-7", {x = -12, y = -5}},
    {"dirt-7", {x = -12, y = -4}},
    {"dirt-7", {x = -12, y = -3}},
    {"dirt-7", {x = -12, y = -2}},
    {"dirt-7", {x = -12, y = -1}},
    {"dirt-7", {x = -12, y = 0}},
    {"dirt-7", {x = -12, y = 1}},
    {"dirt-6", {x = -12, y = 2}},
    {"dirt-6", {x = -12, y = 3}},
    {"dirt-6", {x = -12, y = 4}},
    {"dirt-6", {x = -12, y = 5}},
    {"dirt-6", {x = -12, y = 6}},
    {"dirt-6", {x = -12, y = 7}},
    {"dirt-7", {x = -12, y = 8}},
    {"dirt-7", {x = -12, y = 9}},
    {"dirt-7", {x = -12, y = 10}},
    {"dirt-7", {x = -12, y = 11}},
    {"dirt-7", {x = -12, y = 12}},
    {"dirt-7", {x = -12, y = 13}},
    {"dirt-7", {x = -12, y = 14}},
    {"dirt-7", {x = -12, y = 15}},
    {"dirt-7", {x = -11, y = -16}},
    {"dirt-7", {x = -11, y = -15}},
    {"dirt-7", {x = -11, y = -14}},
    {"dirt-7", {x = -11, y = -13}},
    {"dirt-7", {x = -11, y = -12}},
    {"dirt-7", {x = -11, y = -11}},
    {"dirt-7", {x = -11, y = -10}},
    {"dirt-7", {x = -11, y = -9}},
    {"dirt-7", {x = -11, y = -8}},
    {"dirt-7", {x = -11, y = -7}},
    {"dirt-7", {x = -11, y = -6}},
    {"dirt-7", {x = -11, y = -5}},
    {"dirt-7", {x = -11, y = -4}},
    {"dirt-7", {x = -11, y = -3}},
    {"dirt-7", {x = -11, y = -2}},
    {"dirt-7", {x = -11, y = -1}},
    {"dirt-7", {x = -11, y = 0}},
    {"dirt-7", {x = -11, y = 1}},
    {"dirt-6", {x = -11, y = 2}},
    {"dirt-6", {x = -11, y = 3}},
    {"dirt-6", {x = -11, y = 4}},
    {"dirt-6", {x = -11, y = 5}},
    {"dirt-6", {x = -11, y = 6}},
    {"dirt-6", {x = -11, y = 7}},
    {"dirt-6", {x = -11, y = 8}},
    {"dirt-7", {x = -11, y = 9}},
    {"dirt-7", {x = -11, y = 10}},
    {"dirt-7", {x = -11, y = 11}},
    {"dirt-7", {x = -11, y = 12}},
    {"dirt-7", {x = -11, y = 13}},
    {"dirt-7", {x = -11, y = 14}},
    {"dirt-7", {x = -11, y = 15}},
    {"dirt-7", {x = -10, y = -16}},
    {"dirt-7", {x = -10, y = -15}},
    {"dirt-7", {x = -10, y = -14}},
    {"dirt-7", {x = -10, y = -13}},
    {"dirt-7", {x = -10, y = -12}},
    {"dirt-7", {x = -10, y = -11}},
    {"dirt-7", {x = -10, y = -10}},
    {"dirt-7", {x = -10, y = -9}},
    {"dirt-7", {x = -10, y = -8}},
    {"dirt-6", {x = -10, y = -7}},
    {"dirt-6", {x = -10, y = -6}},
    {"dirt-6", {x = -10, y = -5}},
    {"dirt-6", {x = -10, y = -4}},
    {"dirt-6", {x = -10, y = -3}},
    {"dirt-6", {x = -10, y = -2}},
    {"dirt-7", {x = -10, y = -1}},
    {"dirt-6", {x = -10, y = 0}},
    {"dirt-6", {x = -10, y = 1}},
    {"dirt-6", {x = -10, y = 2}},
    {"dirt-6", {x = -10, y = 3}},
    {"dirt-6", {x = -10, y = 4}},
    {"dirt-6", {x = -10, y = 5}},
    {"dirt-6", {x = -10, y = 6}},
    {"dirt-6", {x = -10, y = 7}},
    {"dirt-6", {x = -10, y = 8}},
    {"dirt-6", {x = -10, y = 9}},
    {"dirt-7", {x = -10, y = 10}},
    {"dirt-7", {x = -10, y = 11}},
    {"dirt-6", {x = -10, y = 12}},
    {"dirt-6", {x = -10, y = 13}},
    {"dirt-7", {x = -10, y = 14}},
    {"dirt-7", {x = -10, y = 15}},
    {"dirt-7", {x = -9, y = -16}},
    {"dirt-7", {x = -9, y = -15}},
    {"dirt-7", {x = -9, y = -14}},
    {"dirt-7", {x = -9, y = -13}},
    {"dirt-7", {x = -9, y = -12}},
    {"dirt-7", {x = -9, y = -11}},
    {"dirt-7", {x = -9, y = -10}},
    {"dirt-7", {x = -9, y = -9}},
    {"dirt-6", {x = -9, y = -8}},
    {"dirt-6", {x = -9, y = -7}},
    {"dirt-6", {x = -9, y = -6}},
    {"dirt-6", {x = -9, y = -5}},
    {"dirt-6", {x = -9, y = -4}},
    {"dirt-6", {x = -9, y = -3}},
    {"dirt-6", {x = -9, y = -2}},
    {"dirt-6", {x = -9, y = -1}},
    {"dirt-6", {x = -9, y = 0}},
    {"dirt-6", {x = -9, y = 1}},
    {"dirt-6", {x = -9, y = 2}},
    {"dirt-6", {x = -9, y = 3}},
    {"dirt-6", {x = -9, y = 4}},
    {"dirt-6", {x = -9, y = 5}},
    {"dirt-6", {x = -9, y = 6}},
    {"dirt-6", {x = -9, y = 7}},
    {"dirt-6", {x = -9, y = 8}},
    {"dirt-6", {x = -9, y = 9}},
    {"dirt-6", {x = -9, y = 10}},
    {"dirt-6", {x = -9, y = 11}},
    {"dirt-6", {x = -9, y = 12}},
    {"dirt-6", {x = -9, y = 13}},
    {"dirt-7", {x = -9, y = 14}},
    {"dirt-7", {x = -9, y = 15}},
    {"dirt-7", {x = -8, y = -16}},
    {"dirt-7", {x = -8, y = -15}},
    {"dirt-7", {x = -8, y = -14}},
    {"dirt-7", {x = -8, y = -13}},
    {"dirt-7", {x = -8, y = -12}},
    {"dirt-7", {x = -8, y = -11}},
    {"grass-4", {x = -8, y = -10}},
    {"dirt-6", {x = -8, y = -9}},
    {"dirt-6", {x = -8, y = -8}},
    {"dirt-6", {x = -8, y = -7}},
    {"dirt-6", {x = -8, y = -6}},
    {"dirt-6", {x = -8, y = -5}},
    {"dirt-6", {x = -8, y = -4}},
    {"dirt-6", {x = -8, y = -3}},
    {"dirt-6", {x = -8, y = -2}},
    {"dirt-6", {x = -8, y = -1}},
    {"dirt-6", {x = -8, y = 0}},
    {"dirt-6", {x = -8, y = 1}},
    {"dirt-6", {x = -8, y = 2}},
    {"dirt-6", {x = -8, y = 3}},
    {"dirt-6", {x = -8, y = 4}},
    {"dirt-6", {x = -8, y = 5}},
    {"dirt-6", {x = -8, y = 6}},
    {"dirt-6", {x = -8, y = 7}},
    {"dirt-6", {x = -8, y = 8}},
    {"dirt-6", {x = -8, y = 9}},
    {"dirt-6", {x = -8, y = 10}},
    {"dirt-6", {x = -8, y = 11}},
    {"dirt-6", {x = -8, y = 12}},
    {"dirt-6", {x = -8, y = 13}},
    {"grass-4", {x = -8, y = 14}},
    {"dirt-7", {x = -8, y = 15}},
    {"grass-4", {x = -7, y = -16}},
    {"dirt-7", {x = -7, y = -15}},
    {"dirt-7", {x = -7, y = -14}},
    {"grass-4", {x = -7, y = -13}},
    {"grass-4", {x = -7, y = -12}},
    {"grass-4", {x = -7, y = -11}},
    {"grass-4", {x = -7, y = -10}},
    {"dirt-6", {x = -7, y = -9}},
    {"dirt-6", {x = -7, y = -8}},
    {"dirt-6", {x = -7, y = -7}},
    {"dirt-6", {x = -7, y = -6}},
    {"dirt-6", {x = -7, y = -5}},
    {"dirt-6", {x = -7, y = -4}},
    {"dirt-6", {x = -7, y = -3}},
    {"dirt-6", {x = -7, y = -2}},
    {"dirt-6", {x = -7, y = -1}},
    {"dirt-6", {x = -7, y = 0}},
    {"dirt-6", {x = -7, y = 1}},
    {"dirt-6", {x = -7, y = 2}},
    {"dirt-6", {x = -7, y = 3}},
    {"dirt-6", {x = -7, y = 4}},
    {"dirt-6", {x = -7, y = 5}},
    {"dirt-6", {x = -7, y = 6}},
    {"dirt-6", {x = -7, y = 7}},
    {"dirt-6", {x = -7, y = 8}},
    {"dirt-6", {x = -7, y = 9}},
    {"dirt-6", {x = -7, y = 10}},
    {"grass-4", {x = -7, y = 11}},
    {"grass-4", {x = -7, y = 12}},
    {"grass-4", {x = -7, y = 13}},
    {"grass-4", {x = -7, y = 14}},
    {"grass-4", {x = -7, y = 15}},
    {"grass-4", {x = -6, y = -16}},
    {"grass-4", {x = -6, y = -15}},
    {"grass-4", {x = -6, y = -14}},
    {"grass-4", {x = -6, y = -13}},
    {"grass-4", {x = -6, y = -12}},
    {"grass-4", {x = -6, y = -11}},
    {"grass-4", {x = -6, y = -10}},
    {"dirt-6", {x = -6, y = -9}},
    {"dirt-6", {x = -6, y = -8}},
    {"dirt-6", {x = -6, y = -7}},
    {"dirt-6", {x = -6, y = -6}},
    {"dirt-6", {x = -6, y = -5}},
    {"dirt-6", {x = -6, y = -4}},
    {"dirt-6", {x = -6, y = -3}},
    {"dirt-6", {x = -6, y = -2}},
    {"dirt-6", {x = -6, y = -1}},
    {"dirt-6", {x = -6, y = 0}},
    {"dirt-6", {x = -6, y = 1}},
    {"dirt-6", {x = -6, y = 2}},
    {"dirt-6", {x = -6, y = 3}},
    {"dirt-6", {x = -6, y = 4}},
    {"dirt-6", {x = -6, y = 5}},
    {"dirt-6", {x = -6, y = 6}},
    {"dirt-6", {x = -6, y = 7}},
    {"dirt-6", {x = -6, y = 8}},
    {"dirt-6", {x = -6, y = 9}},
    {"dirt-6", {x = -6, y = 10}},
    {"grass-4", {x = -6, y = 11}},
    {"grass-4", {x = -6, y = 12}},
    {"grass-4", {x = -6, y = 13}},
    {"grass-4", {x = -6, y = 14}},
    {"grass-4", {x = -6, y = 15}},
    {"grass-4", {x = -5, y = -16}},
    {"grass-4", {x = -5, y = -15}},
    {"grass-4", {x = -5, y = -14}},
    {"grass-4", {x = -5, y = -13}},
    {"grass-4", {x = -5, y = -12}},
    {"grass-4", {x = -5, y = -11}},
    {"grass-4", {x = -5, y = -10}},
    {"grass-4", {x = -5, y = -9}},
    {"dirt-6", {x = -5, y = -8}},
    {"dirt-6", {x = -5, y = -7}},
    {"dirt-6", {x = -5, y = -6}},
    {"dirt-6", {x = -5, y = -5}},
    {"dirt-6", {x = -5, y = -4}},
    {"dirt-6", {x = -5, y = -3}},
    {"dirt-6", {x = -5, y = -2}},
    {"dirt-6", {x = -5, y = -1}},
    {"dirt-6", {x = -5, y = 0}},
    {"dirt-6", {x = -5, y = 1}},
    {"dirt-6", {x = -5, y = 2}},
    {"dirt-6", {x = -5, y = 3}},
    {"dirt-6", {x = -5, y = 4}},
    {"dirt-6", {x = -5, y = 5}},
    {"dirt-6", {x = -5, y = 6}},
    {"dirt-6", {x = -5, y = 7}},
    {"dirt-6", {x = -5, y = 8}},
    {"dirt-6", {x = -5, y = 9}},
    {"dirt-6", {x = -5, y = 10}},
    {"grass-4", {x = -5, y = 11}},
    {"grass-4", {x = -5, y = 12}},
    {"grass-4", {x = -5, y = 13}},
    {"grass-4", {x = -5, y = 14}},
    {"grass-4", {x = -5, y = 15}},
    {"grass-4", {x = -4, y = -16}},
    {"grass-4", {x = -4, y = -15}},
    {"grass-4", {x = -4, y = -14}},
    {"grass-4", {x = -4, y = -13}},
    {"grass-4", {x = -4, y = -12}},
    {"grass-4", {x = -4, y = -11}},
    {"grass-4", {x = -4, y = -10}},
    {"grass-4", {x = -4, y = -9}},
    {"dirt-6", {x = -4, y = -8}},
    {"dirt-6", {x = -4, y = -7}},
    {"dirt-6", {x = -4, y = -6}},
    {"dirt-6", {x = -4, y = -5}},
    {"dirt-6", {x = -4, y = -4}},
    {"dirt-6", {x = -4, y = -3}},
    {"dirt-6", {x = -4, y = -2}},
    {"dirt-6", {x = -4, y = -1}},
    {"dirt-6", {x = -4, y = 0}},
    {"dirt-6", {x = -4, y = 1}},
    {"dirt-6", {x = -4, y = 2}},
    {"dirt-6", {x = -4, y = 3}},
    {"dirt-6", {x = -4, y = 4}},
    {"dirt-6", {x = -4, y = 5}},
    {"dirt-6", {x = -4, y = 6}},
    {"dirt-6", {x = -4, y = 7}},
    {"dirt-6", {x = -4, y = 8}},
    {"dirt-6", {x = -4, y = 9}},
    {"dirt-6", {x = -4, y = 10}},
    {"dirt-6", {x = -4, y = 11}},
    {"grass-4", {x = -4, y = 12}},
    {"grass-4", {x = -4, y = 13}},
    {"grass-4", {x = -4, y = 14}},
    {"grass-4", {x = -4, y = 15}},
    {"grass-4", {x = -3, y = -16}},
    {"grass-4", {x = -3, y = -15}},
    {"grass-4", {x = -3, y = -14}},
    {"grass-4", {x = -3, y = -13}},
    {"grass-4", {x = -3, y = -12}},
    {"grass-4", {x = -3, y = -11}},
    {"grass-4", {x = -3, y = -10}},
    {"grass-4", {x = -3, y = -9}},
    {"dirt-6", {x = -3, y = -8}},
    {"dirt-6", {x = -3, y = -7}},
    {"dirt-6", {x = -3, y = -6}},
    {"dirt-6", {x = -3, y = -5}},
    {"dirt-6", {x = -3, y = -4}},
    {"dirt-6", {x = -3, y = -3}},
    {"dirt-6", {x = -3, y = -2}},
    {"dirt-6", {x = -3, y = -1}},
    {"dirt-6", {x = -3, y = 0}},
    {"dirt-6", {x = -3, y = 1}},
    {"dirt-6", {x = -3, y = 2}},
    {"dirt-6", {x = -3, y = 3}},
    {"dirt-6", {x = -3, y = 4}},
    {"dirt-6", {x = -3, y = 5}},
    {"dirt-6", {x = -3, y = 6}},
    {"dirt-6", {x = -3, y = 7}},
    {"dirt-6", {x = -3, y = 8}},
    {"dirt-6", {x = -3, y = 9}},
    {"dirt-6", {x = -3, y = 10}},
    {"dirt-6", {x = -3, y = 11}},
    {"grass-4", {x = -3, y = 12}},
    {"grass-4", {x = -3, y = 13}},
    {"grass-4", {x = -3, y = 14}},
    {"grass-4", {x = -3, y = 15}},
    {"grass-4", {x = -2, y = -16}},
    {"grass-4", {x = -2, y = -15}},
    {"grass-4", {x = -2, y = -14}},
    {"grass-4", {x = -2, y = -13}},
    {"grass-4", {x = -2, y = -12}},
    {"grass-4", {x = -2, y = -11}},
    {"grass-4", {x = -2, y = -10}},
    {"dirt-6", {x = -2, y = -9}},
    {"dirt-6", {x = -2, y = -8}},
    {"dirt-6", {x = -2, y = -7}},
    {"dirt-6", {x = -2, y = -6}},
    {"dirt-6", {x = -2, y = -5}},
    {"dirt-6", {x = -2, y = -4}},
    {"dirt-6", {x = -2, y = -3}},
    {"dirt-6", {x = -2, y = -2}},
    {"dirt-6", {x = -2, y = -1}},
    {"dirt-6", {x = -2, y = 0}},
    {"dirt-6", {x = -2, y = 1}},
    {"dirt-6", {x = -2, y = 2}},
    {"dirt-6", {x = -2, y = 3}},
    {"dirt-6", {x = -2, y = 4}},
    {"dirt-6", {x = -2, y = 5}},
    {"dirt-6", {x = -2, y = 6}},
    {"dirt-6", {x = -2, y = 7}},
    {"dirt-6", {x = -2, y = 8}},
    {"dirt-6", {x = -2, y = 9}},
    {"dirt-6", {x = -2, y = 10}},
    {"dirt-6", {x = -2, y = 11}},
    {"dirt-6", {x = -2, y = 12}},
    {"grass-4", {x = -2, y = 13}},
    {"grass-4", {x = -2, y = 14}},
    {"grass-4", {x = -2, y = 15}},
    {"grass-4", {x = -1, y = -16}},
    {"grass-4", {x = -1, y = -15}},
    {"grass-4", {x = -1, y = -14}},
    {"grass-4", {x = -1, y = -13}},
    {"grass-4", {x = -1, y = -12}},
    {"grass-4", {x = -1, y = -11}},
    {"grass-4", {x = -1, y = -10}},
    {"dirt-6", {x = -1, y = -9}},
    {"dirt-6", {x = -1, y = -8}},
    {"dirt-6", {x = -1, y = -7}},
    {"dirt-6", {x = -1, y = -6}},
    {"dirt-6", {x = -1, y = -5}},
    {"dirt-6", {x = -1, y = -4}},
    {"dirt-6", {x = -1, y = -3}},
    {"dirt-7", {x = -1, y = -2}},
    {"dirt-7", {x = -1, y = -1}},
    {"dirt-6", {x = -1, y = 0}},
    {"dirt-6", {x = -1, y = 1}},
    {"dirt-6", {x = -1, y = 2}},
    {"dirt-6", {x = -1, y = 3}},
    {"dirt-6", {x = -1, y = 4}},
    {"dirt-6", {x = -1, y = 5}},
    {"dirt-6", {x = -1, y = 6}},
    {"dirt-6", {x = -1, y = 7}},
    {"dirt-6", {x = -1, y = 8}},
    {"dirt-6", {x = -1, y = 9}},
    {"dirt-6", {x = -1, y = 10}},
    {"dirt-6", {x = -1, y = 11}},
    {"dirt-6", {x = -1, y = 12}},
    {"dirt-6", {x = -1, y = 13}},
    {"dirt-6", {x = -1, y = 14}},
    {"grass-4", {x = -1, y = 15}},
    {"grass-4", {x = 0, y = -16}},
    {"grass-4", {x = 0, y = -15}},
    {"grass-4", {x = 0, y = -14}},
    {"grass-4", {x = 0, y = -13}},
    {"grass-4", {x = 0, y = -12}},
    {"grass-4", {x = 0, y = -11}},
    {"grass-4", {x = 0, y = -10}},
    {"dirt-6", {x = 0, y = -9}},
    {"dirt-6", {x = 0, y = -8}},
    {"dirt-6", {x = 0, y = -7}},
    {"dirt-6", {x = 0, y = -6}},
    {"dirt-6", {x = 0, y = -5}},
    {"dirt-6", {x = 0, y = -4}},
    {"dirt-7", {x = 0, y = -3}},
    {"dirt-7", {x = 0, y = -2}},
    {"dirt-7", {x = 0, y = -1}},
    {"dirt-7", {x = 0, y = 0}},
    {"dirt-6", {x = 0, y = 1}},
    {"dirt-6", {x = 0, y = 2}},
    {"dirt-6", {x = 0, y = 3}},
    {"dirt-6", {x = 0, y = 4}},
    {"dirt-6", {x = 0, y = 5}},
    {"dirt-6", {x = 0, y = 6}},
    {"dirt-6", {x = 0, y = 7}},
    {"dirt-6", {x = 0, y = 8}},
    {"dirt-6", {x = 0, y = 9}},
    {"dirt-6", {x = 0, y = 10}},
    {"dirt-6", {x = 0, y = 11}},
    {"dirt-6", {x = 0, y = 12}},
    {"dirt-6", {x = 0, y = 13}},
    {"dirt-6", {x = 0, y = 14}},
    {"dirt-6", {x = 0, y = 15}},
    {"grass-4", {x = 1, y = -16}},
    {"grass-4", {x = 1, y = -15}},
    {"grass-4", {x = 1, y = -14}},
    {"grass-4", {x = 1, y = -13}},
    {"grass-4", {x = 1, y = -12}},
    {"grass-4", {x = 1, y = -11}},
    {"grass-4", {x = 1, y = -10}},
    {"dirt-6", {x = 1, y = -9}},
    {"dirt-6", {x = 1, y = -8}},
    {"dirt-6", {x = 1, y = -7}},
    {"dirt-6", {x = 1, y = -6}},
    {"dirt-6", {x = 1, y = -5}},
    {"dirt-6", {x = 1, y = -4}},
    {"dirt-7", {x = 1, y = -3}},
    {"dirt-7", {x = 1, y = -2}},
    {"dirt-7", {x = 1, y = -1}},
    {"dirt-7", {x = 1, y = 0}},
    {"dirt-6", {x = 1, y = 1}},
    {"dirt-6", {x = 1, y = 2}},
    {"dirt-6", {x = 1, y = 3}},
    {"dirt-6", {x = 1, y = 4}},
    {"dirt-6", {x = 1, y = 5}},
    {"dirt-7", {x = 1, y = 6}},
    {"dirt-7", {x = 1, y = 7}},
    {"dirt-7", {x = 1, y = 8}},
    {"dirt-7", {x = 1, y = 9}},
    {"dirt-7", {x = 1, y = 10}},
    {"dirt-6", {x = 1, y = 11}},
    {"dirt-6", {x = 1, y = 12}},
    {"dirt-6", {x = 1, y = 13}},
    {"dirt-6", {x = 1, y = 14}},
    {"dirt-6", {x = 1, y = 15}},
    {"grass-4", {x = 2, y = -16}},
    {"grass-4", {x = 2, y = -15}},
    {"grass-4", {x = 2, y = -14}},
    {"grass-4", {x = 2, y = -13}},
    {"grass-4", {x = 2, y = -12}},
    {"grass-4", {x = 2, y = -11}},
    {"grass-4", {x = 2, y = -10}},
    {"dirt-6", {x = 2, y = -9}},
    {"dirt-6", {x = 2, y = -8}},
    {"dirt-6", {x = 2, y = -7}},
    {"dirt-6", {x = 2, y = -6}},
    {"dirt-6", {x = 2, y = -5}},
    {"dirt-7", {x = 2, y = -4}},
    {"dirt-7", {x = 2, y = -3}},
    {"dirt-7", {x = 2, y = -2}},
    {"dirt-7", {x = 2, y = -1}},
    {"dirt-7", {x = 2, y = 0}},
    {"dirt-6", {x = 2, y = 1}},
    {"dirt-6", {x = 2, y = 2}},
    {"dirt-6", {x = 2, y = 3}},
    {"dirt-6", {x = 2, y = 4}},
    {"dirt-7", {x = 2, y = 5}},
    {"dirt-7", {x = 2, y = 6}},
    {"dirt-7", {x = 2, y = 7}},
    {"dirt-7", {x = 2, y = 8}},
    {"dirt-7", {x = 2, y = 9}},
    {"dirt-7", {x = 2, y = 10}},
    {"dirt-7", {x = 2, y = 11}},
    {"dirt-6", {x = 2, y = 12}},
    {"dirt-6", {x = 2, y = 13}},
    {"dirt-6", {x = 2, y = 14}},
    {"dirt-6", {x = 2, y = 15}},
    {"grass-4", {x = 3, y = -16}},
    {"grass-4", {x = 3, y = -15}},
    {"grass-4", {x = 3, y = -14}},
    {"grass-4", {x = 3, y = -13}},
    {"grass-4", {x = 3, y = -12}},
    {"grass-4", {x = 3, y = -11}},
    {"grass-4", {x = 3, y = -10}},
    {"dirt-7", {x = 3, y = -9}},
    {"dirt-7", {x = 3, y = -8}},
    {"dirt-7", {x = 3, y = -7}},
    {"dirt-7", {x = 3, y = -6}},
    {"dirt-7", {x = 3, y = -5}},
    {"dirt-7", {x = 3, y = -4}},
    {"dirt-7", {x = 3, y = -3}},
    {"dirt-7", {x = 3, y = -2}},
    {"dirt-7", {x = 3, y = -1}},
    {"dirt-7", {x = 3, y = 0}},
    {"dirt-7", {x = 3, y = 1}},
    {"dirt-6", {x = 3, y = 2}},
    {"dirt-6", {x = 3, y = 3}},
    {"dirt-6", {x = 3, y = 4}},
    {"dirt-7", {x = 3, y = 5}},
    {"dirt-7", {x = 3, y = 6}},
    {"dirt-7", {x = 3, y = 7}},
    {"dirt-7", {x = 3, y = 8}},
    {"dirt-7", {x = 3, y = 9}},
    {"dirt-7", {x = 3, y = 10}},
    {"dirt-7", {x = 3, y = 11}},
    {"dirt-6", {x = 3, y = 12}},
    {"dirt-6", {x = 3, y = 13}},
    {"dirt-6", {x = 3, y = 14}},
    {"dirt-6", {x = 3, y = 15}},
    {"grass-4", {x = 4, y = -16}},
    {"grass-4", {x = 4, y = -15}},
    {"grass-4", {x = 4, y = -14}},
    {"grass-4", {x = 4, y = -13}},
    {"grass-4", {x = 4, y = -12}},
    {"dirt-6", {x = 4, y = -11}},
    {"dirt-6", {x = 4, y = -10}},
    {"dirt-7", {x = 4, y = -9}},
    {"dirt-7", {x = 4, y = -8}},
    {"dirt-7", {x = 4, y = -7}},
    {"dirt-7", {x = 4, y = -6}},
    {"dirt-7", {x = 4, y = -5}},
    {"dirt-7", {x = 4, y = -4}},
    {"dirt-7", {x = 4, y = -3}},
    {"dirt-7", {x = 4, y = -2}},
    {"dirt-7", {x = 4, y = -1}},
    {"dirt-7", {x = 4, y = 0}},
    {"dirt-7", {x = 4, y = 1}},
    {"dirt-7", {x = 4, y = 2}},
    {"dirt-6", {x = 4, y = 3}},
    {"dirt-6", {x = 4, y = 4}},
    {"dirt-7", {x = 4, y = 5}},
    {"dirt-7", {x = 4, y = 6}},
    {"dirt-7", {x = 4, y = 7}},
    {"dirt-7", {x = 4, y = 8}},
    {"dirt-7", {x = 4, y = 9}},
    {"dirt-7", {x = 4, y = 10}},
    {"dirt-7", {x = 4, y = 11}},
    {"dirt-6", {x = 4, y = 12}},
    {"dirt-6", {x = 4, y = 13}},
    {"dirt-6", {x = 4, y = 14}},
    {"dirt-6", {x = 4, y = 15}},
    {"grass-4", {x = 5, y = -16}},
    {"grass-4", {x = 5, y = -15}},
    {"grass-4", {x = 5, y = -14}},
    {"dirt-6", {x = 5, y = -13}},
    {"dirt-6", {x = 5, y = -12}},
    {"dirt-6", {x = 5, y = -11}},
    {"dirt-6", {x = 5, y = -10}},
    {"dirt-7", {x = 5, y = -9}},
    {"dirt-7", {x = 5, y = -8}},
    {"dirt-7", {x = 5, y = -7}},
    {"dirt-7", {x = 5, y = -6}},
    {"dirt-7", {x = 5, y = -5}},
    {"dirt-7", {x = 5, y = -4}},
    {"dirt-7", {x = 5, y = -3}},
    {"dirt-7", {x = 5, y = -2}},
    {"dirt-7", {x = 5, y = -1}},
    {"dirt-7", {x = 5, y = 0}},
    {"dirt-7", {x = 5, y = 1}},
    {"dirt-6", {x = 5, y = 2}},
    {"dirt-6", {x = 5, y = 3}},
    {"dirt-6", {x = 5, y = 4}},
    {"dirt-7", {x = 5, y = 5}},
    {"dirt-7", {x = 5, y = 6}},
    {"dirt-7", {x = 5, y = 7}},
    {"dirt-7", {x = 5, y = 8}},
    {"dirt-7", {x = 5, y = 9}},
    {"dirt-7", {x = 5, y = 10}},
    {"dirt-6", {x = 5, y = 11}},
    {"dirt-6", {x = 5, y = 12}},
    {"dirt-6", {x = 5, y = 13}},
    {"dirt-6", {x = 5, y = 14}},
    {"dirt-6", {x = 5, y = 15}},
    {"grass-4", {x = 6, y = -16}},
    {"grass-4", {x = 6, y = -15}},
    {"dirt-6", {x = 6, y = -14}},
    {"dirt-6", {x = 6, y = -13}},
    {"dirt-6", {x = 6, y = -12}},
    {"dirt-6", {x = 6, y = -11}},
    {"dirt-6", {x = 6, y = -10}},
    {"dirt-6", {x = 6, y = -9}},
    {"dirt-7", {x = 6, y = -8}},
    {"dirt-7", {x = 6, y = -7}},
    {"dirt-7", {x = 6, y = -6}},
    {"dirt-7", {x = 6, y = -5}},
    {"dirt-7", {x = 6, y = -4}},
    {"dirt-7", {x = 6, y = -3}},
    {"dirt-7", {x = 6, y = -2}},
    {"dirt-7", {x = 6, y = -1}},
    {"dirt-7", {x = 6, y = 0}},
    {"dirt-7", {x = 6, y = 1}},
    {"dirt-6", {x = 6, y = 2}},
    {"dirt-6", {x = 6, y = 3}},
    {"dirt-6", {x = 6, y = 4}},
    {"dirt-6", {x = 6, y = 5}},
    {"dirt-7", {x = 6, y = 6}},
    {"dirt-7", {x = 6, y = 7}},
    {"dirt-7", {x = 6, y = 8}},
    {"dirt-7", {x = 6, y = 9}},
    {"dirt-6", {x = 6, y = 10}},
    {"dirt-6", {x = 6, y = 11}},
    {"dirt-6", {x = 6, y = 12}},
    {"dirt-6", {x = 6, y = 13}},
    {"dirt-6", {x = 6, y = 14}},
    {"dirt-6", {x = 6, y = 15}},
    {"grass-4", {x = 7, y = -16}},
    {"grass-4", {x = 7, y = -15}},
    {"dirt-6", {x = 7, y = -14}},
    {"dirt-6", {x = 7, y = -13}},
    {"dirt-6", {x = 7, y = -12}},
    {"dirt-6", {x = 7, y = -11}},
    {"dirt-6", {x = 7, y = -10}},
    {"dirt-6", {x = 7, y = -9}},
    {"dirt-6", {x = 7, y = -8}},
    {"dirt-6", {x = 7, y = -7}},
    {"dirt-6", {x = 7, y = -6}},
    {"dirt-6", {x = 7, y = -5}},
    {"dirt-6", {x = 7, y = -4}},
    {"dirt-6", {x = 7, y = -3}},
    {"dirt-7", {x = 7, y = -2}},
    {"dirt-7", {x = 7, y = -1}},
    {"dirt-6", {x = 7, y = 0}},
    {"dirt-6", {x = 7, y = 1}},
    {"dirt-6", {x = 7, y = 2}},
    {"dirt-6", {x = 7, y = 3}},
    {"dirt-6", {x = 7, y = 4}},
    {"dirt-6", {x = 7, y = 5}},
    {"dirt-6", {x = 7, y = 6}},
    {"dirt-6", {x = 7, y = 7}},
    {"dirt-6", {x = 7, y = 8}},
    {"dirt-6", {x = 7, y = 9}},
    {"dirt-6", {x = 7, y = 10}},
    {"dirt-6", {x = 7, y = 11}},
    {"dirt-6", {x = 7, y = 12}},
    {"dirt-6", {x = 7, y = 13}},
    {"dirt-6", {x = 7, y = 14}},
    {"dirt-6", {x = 7, y = 15}},
    {"grass-4", {x = 8, y = -16}},
    {"grass-4", {x = 8, y = -15}},
    {"dirt-6", {x = 8, y = -14}},
    {"dirt-6", {x = 8, y = -13}},
    {"dirt-6", {x = 8, y = -12}},
    {"dirt-6", {x = 8, y = -11}},
    {"dirt-6", {x = 8, y = -10}},
    {"dirt-6", {x = 8, y = -9}},
    {"dirt-6", {x = 8, y = -8}},
    {"dirt-6", {x = 8, y = -7}},
    {"dirt-6", {x = 8, y = -6}},
    {"dirt-6", {x = 8, y = -5}},
    {"dirt-6", {x = 8, y = -4}},
    {"dirt-6", {x = 8, y = -3}},
    {"dirt-6", {x = 8, y = -2}},
    {"dirt-6", {x = 8, y = -1}},
    {"dirt-6", {x = 8, y = 0}},
    {"dirt-6", {x = 8, y = 1}},
    {"dirt-6", {x = 8, y = 2}},
    {"dirt-6", {x = 8, y = 3}},
    {"dirt-6", {x = 8, y = 4}},
    {"dirt-6", {x = 8, y = 5}},
    {"dirt-6", {x = 8, y = 6}},
    {"dirt-6", {x = 8, y = 7}},
    {"dirt-6", {x = 8, y = 8}},
    {"dirt-6", {x = 8, y = 9}},
    {"dirt-6", {x = 8, y = 10}},
    {"dirt-6", {x = 8, y = 11}},
    {"dirt-6", {x = 8, y = 12}},
    {"dirt-6", {x = 8, y = 13}},
    {"dirt-6", {x = 8, y = 14}},
    {"dirt-6", {x = 8, y = 15}},
    {"grass-4", {x = 9, y = -16}},
    {"grass-4", {x = 9, y = -15}},
    {"dirt-6", {x = 9, y = -14}},
    {"dirt-6", {x = 9, y = -13}},
    {"dirt-6", {x = 9, y = -12}},
    {"dirt-6", {x = 9, y = -11}},
    {"dirt-6", {x = 9, y = -10}},
    {"dirt-6", {x = 9, y = -9}},
    {"dirt-6", {x = 9, y = -8}},
    {"dirt-6", {x = 9, y = -7}},
    {"dirt-6", {x = 9, y = -6}},
    {"dirt-6", {x = 9, y = -5}},
    {"dirt-6", {x = 9, y = -4}},
    {"dirt-6", {x = 9, y = -3}},
    {"dirt-6", {x = 9, y = -2}},
    {"dirt-6", {x = 9, y = -1}},
    {"dirt-6", {x = 9, y = 0}},
    {"dirt-6", {x = 9, y = 1}},
    {"dirt-6", {x = 9, y = 2}},
    {"dirt-6", {x = 9, y = 3}},
    {"dirt-6", {x = 9, y = 4}},
    {"dirt-6", {x = 9, y = 5}},
    {"dirt-6", {x = 9, y = 6}},
    {"dirt-6", {x = 9, y = 7}},
    {"dirt-6", {x = 9, y = 8}},
    {"dirt-6", {x = 9, y = 9}},
    {"dirt-6", {x = 9, y = 10}},
    {"dirt-6", {x = 9, y = 11}},
    {"dirt-6", {x = 9, y = 12}},
    {"dirt-6", {x = 9, y = 13}},
    {"dirt-6", {x = 9, y = 14}},
    {"dirt-6", {x = 9, y = 15}},
    {"grass-4", {x = 10, y = -16}},
    {"grass-4", {x = 10, y = -15}},
    {"dirt-6", {x = 10, y = -14}},
    {"dirt-6", {x = 10, y = -13}},
    {"dirt-6", {x = 10, y = -12}},
    {"dirt-6", {x = 10, y = -11}},
    {"dirt-6", {x = 10, y = -10}},
    {"dirt-6", {x = 10, y = -9}},
    {"dirt-6", {x = 10, y = -8}},
    {"dirt-6", {x = 10, y = -7}},
    {"dirt-6", {x = 10, y = -6}},
    {"dirt-6", {x = 10, y = -5}},
    {"dirt-6", {x = 10, y = -4}},
    {"dirt-6", {x = 10, y = -3}},
    {"dirt-6", {x = 10, y = -2}},
    {"dirt-6", {x = 10, y = -1}},
    {"dirt-6", {x = 10, y = 0}},
    {"dirt-6", {x = 10, y = 1}},
    {"dirt-6", {x = 10, y = 2}},
    {"dirt-6", {x = 10, y = 3}},
    {"dirt-6", {x = 10, y = 4}},
    {"dirt-6", {x = 10, y = 5}},
    {"dirt-6", {x = 10, y = 6}},
    {"dirt-6", {x = 10, y = 7}},
    {"dirt-6", {x = 10, y = 8}},
    {"dirt-6", {x = 10, y = 9}},
    {"dirt-6", {x = 10, y = 10}},
    {"dirt-6", {x = 10, y = 11}},
    {"dirt-6", {x = 10, y = 12}},
    {"dirt-6", {x = 10, y = 13}},
    {"dirt-6", {x = 10, y = 14}},
    {"dirt-6", {x = 10, y = 15}},
    {"grass-4", {x = 11, y = -16}},
    {"grass-4", {x = 11, y = -15}},
    {"dirt-6", {x = 11, y = -14}},
    {"dirt-6", {x = 11, y = -13}},
    {"dirt-6", {x = 11, y = -12}},
    {"dirt-6", {x = 11, y = -11}},
    {"dirt-6", {x = 11, y = -10}},
    {"dirt-6", {x = 11, y = -9}},
    {"dirt-6", {x = 11, y = -8}},
    {"dirt-6", {x = 11, y = -7}},
    {"dirt-6", {x = 11, y = -6}},
    {"dirt-6", {x = 11, y = -5}},
    {"dirt-6", {x = 11, y = -4}},
    {"dirt-6", {x = 11, y = -3}},
    {"dirt-6", {x = 11, y = -2}},
    {"dirt-6", {x = 11, y = -1}},
    {"dirt-6", {x = 11, y = 0}},
    {"dirt-6", {x = 11, y = 1}},
    {"dirt-6", {x = 11, y = 2}},
    {"dirt-6", {x = 11, y = 3}},
    {"dirt-6", {x = 11, y = 4}},
    {"dirt-6", {x = 11, y = 5}},
    {"dirt-6", {x = 11, y = 6}},
    {"dirt-6", {x = 11, y = 7}},
    {"dirt-6", {x = 11, y = 8}},
    {"dirt-6", {x = 11, y = 9}},
    {"dirt-6", {x = 11, y = 10}},
    {"dirt-6", {x = 11, y = 11}},
    {"dirt-6", {x = 11, y = 12}},
    {"dirt-6", {x = 11, y = 13}},
    {"dirt-6", {x = 11, y = 14}},
    {"dirt-6", {x = 11, y = 15}},
    {"grass-4", {x = 12, y = -16}},
    {"grass-4", {x = 12, y = -15}},
    {"dirt-6", {x = 12, y = -14}},
    {"dirt-6", {x = 12, y = -13}},
    {"dirt-6", {x = 12, y = -12}},
    {"dirt-6", {x = 12, y = -11}},
    {"dirt-6", {x = 12, y = -10}},
    {"dirt-6", {x = 12, y = -9}},
    {"dirt-6", {x = 12, y = -8}},
    {"dirt-6", {x = 12, y = -7}},
    {"dirt-6", {x = 12, y = -6}},
    {"dirt-6", {x = 12, y = -5}},
    {"dirt-6", {x = 12, y = -4}},
    {"dirt-6", {x = 12, y = -3}},
    {"dirt-6", {x = 12, y = -2}},
    {"dirt-6", {x = 12, y = -1}},
    {"dirt-6", {x = 12, y = 0}},
    {"dirt-6", {x = 12, y = 1}},
    {"dirt-6", {x = 12, y = 2}},
    {"dirt-6", {x = 12, y = 3}},
    {"dirt-6", {x = 12, y = 4}},
    {"dirt-6", {x = 12, y = 5}},
    {"dirt-6", {x = 12, y = 6}},
    {"dirt-6", {x = 12, y = 7}},
    {"dirt-6", {x = 12, y = 8}},
    {"dirt-6", {x = 12, y = 9}},
    {"dirt-6", {x = 12, y = 10}},
    {"dirt-6", {x = 12, y = 11}},
    {"dirt-6", {x = 12, y = 12}},
    {"dirt-6", {x = 12, y = 13}},
    {"dirt-6", {x = 12, y = 14}},
    {"dirt-6", {x = 12, y = 15}},
    {"grass-4", {x = 13, y = -16}},
    {"dirt-6", {x = 13, y = -15}},
    {"dirt-6", {x = 13, y = -14}},
    {"dirt-6", {x = 13, y = -13}},
    {"dirt-6", {x = 13, y = -12}},
    {"dirt-6", {x = 13, y = -11}},
    {"dirt-6", {x = 13, y = -10}},
    {"dirt-6", {x = 13, y = -9}},
    {"dirt-6", {x = 13, y = -8}},
    {"dirt-6", {x = 13, y = -7}},
    {"dirt-6", {x = 13, y = -6}},
    {"dirt-6", {x = 13, y = -5}},
    {"dirt-6", {x = 13, y = -4}},
    {"dirt-6", {x = 13, y = -3}},
    {"dirt-6", {x = 13, y = -2}},
    {"dirt-6", {x = 13, y = -1}},
    {"dirt-6", {x = 13, y = 0}},
    {"dirt-6", {x = 13, y = 1}},
    {"dirt-6", {x = 13, y = 2}},
    {"dirt-6", {x = 13, y = 3}},
    {"dirt-6", {x = 13, y = 4}},
    {"dirt-6", {x = 13, y = 5}},
    {"dirt-6", {x = 13, y = 6}},
    {"dirt-6", {x = 13, y = 7}},
    {"dirt-6", {x = 13, y = 8}},
    {"dirt-6", {x = 13, y = 9}},
    {"dirt-6", {x = 13, y = 10}},
    {"dirt-6", {x = 13, y = 11}},
    {"dirt-6", {x = 13, y = 12}},
    {"dirt-6", {x = 13, y = 13}},
    {"dirt-6", {x = 13, y = 14}},
    {"dirt-6", {x = 13, y = 15}},
    {"grass-4", {x = 14, y = -16}},
    {"dirt-6", {x = 14, y = -15}},
    {"dirt-6", {x = 14, y = -14}},
    {"dirt-6", {x = 14, y = -13}},
    {"dirt-6", {x = 14, y = -12}},
    {"dirt-6", {x = 14, y = -11}},
    {"dirt-6", {x = 14, y = -10}},
    {"dirt-6", {x = 14, y = -9}},
    {"dirt-6", {x = 14, y = -8}},
    {"dirt-6", {x = 14, y = -7}},
    {"dirt-6", {x = 14, y = -6}},
    {"dirt-6", {x = 14, y = -5}},
    {"dirt-6", {x = 14, y = -4}},
    {"dirt-6", {x = 14, y = -3}},
    {"dirt-6", {x = 14, y = -2}},
    {"dirt-6", {x = 14, y = -1}},
    {"dirt-6", {x = 14, y = 0}},
    {"dirt-6", {x = 14, y = 1}},
    {"dirt-6", {x = 14, y = 2}},
    {"dirt-6", {x = 14, y = 3}},
    {"dirt-6", {x = 14, y = 4}},
    {"dirt-6", {x = 14, y = 5}},
    {"dirt-6", {x = 14, y = 6}},
    {"dirt-6", {x = 14, y = 7}},
    {"dirt-6", {x = 14, y = 8}},
    {"dirt-6", {x = 14, y = 9}},
    {"dirt-6", {x = 14, y = 10}},
    {"dirt-6", {x = 14, y = 11}},
    {"dirt-6", {x = 14, y = 12}},
    {"dirt-6", {x = 14, y = 13}},
    {"dirt-6", {x = 14, y = 14}},
    {"dirt-6", {x = 14, y = 15}},
    {"dirt-7", {x = 15, y = -16}},
    {"dirt-6", {x = 15, y = -15}},
    {"dirt-6", {x = 15, y = -14}},
    {"dirt-6", {x = 15, y = -13}},
    {"dirt-6", {x = 15, y = -12}},
    {"dirt-6", {x = 15, y = -11}},
    {"dirt-6", {x = 15, y = -10}},
    {"dirt-6", {x = 15, y = -9}},
    {"dirt-6", {x = 15, y = -8}},
    {"dirt-6", {x = 15, y = -7}},
    {"dirt-6", {x = 15, y = -6}},
    {"dirt-6", {x = 15, y = -5}},
    {"dirt-6", {x = 15, y = -4}},
    {"dirt-6", {x = 15, y = -3}},
    {"dirt-6", {x = 15, y = -2}},
    {"dirt-6", {x = 15, y = -1}},
    {"dirt-6", {x = 15, y = 0}},
    {"dirt-6", {x = 15, y = 1}},
    {"dirt-6", {x = 15, y = 2}},
    {"dirt-6", {x = 15, y = 3}},
    {"dirt-6", {x = 15, y = 4}},
    {"dirt-6", {x = 15, y = 5}},
    {"dirt-6", {x = 15, y = 6}},
    {"dirt-6", {x = 15, y = 7}},
    {"dirt-6", {x = 15, y = 8}},
    {"dirt-6", {x = 15, y = 9}},
    {"dirt-6", {x = 15, y = 10}},
    {"dirt-6", {x = 15, y = 11}},
    {"dirt-6", {x = 15, y = 12}},
    {"dirt-6", {x = 15, y = 13}},
    {"dirt-6", {x = 15, y = 14}},
    {"dirt-6", {x = 15, y = 15}},
  }
}
