return
{
  entities =
  {
    {"laser-turret", {x = -14, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -12, y = -14}, {force = "enemy", items = {["piercing-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = -10, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 10, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = 12, y = -14}, {force = "enemy", items = {["piercing-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 10.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = -15.5}, {force = "enemy", }},
    {"laser-turret", {x = 14, y = -14}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -14.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -15.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -15.5}, {force = "enemy", }},
    {"gun-turret", {x = -14, y = -12}, {dir = "west", force = "enemy", items = {["piercing-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -13.5}, {force = "enemy", }},
    {"fast-inserter", {x = -11.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"gate", {x = -8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -13.5}, {force = "enemy", }},
    {"gate", {x = 8.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -13.5}, {force = "enemy", }},
    {"fast-inserter", {x = 11.5, y = -12.5}, {dir = "south", force = "enemy", }},
    {"gun-turret", {x = 14, y = -12}, {dir = "east", force = "enemy", items = {["piercing-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 15.5, y = -12.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -13.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = -10}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -11.5}, {force = "enemy", }},
    {"fast-inserter", {x = -12.5, y = -11.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = -11.5, y = -11.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 9600}, }},
    {"substation", {x = -10, y = -10}, {force = "enemy", }},
    {"gate", {x = -8.5, y = -11.5}, {force = "enemy", }},
    {"steel-chest", {x = -9.5, y = -11.5}, {items = {["chemical-science-pack"] = 200, ["electronic-circuit"] = 200}, }},
    {"stone-wall", {x = -8.5, y = -10.5}, {force = "enemy", }},
    {"gate", {x = 8.5, y = -11.5}, {force = "enemy", }},
    {"steel-chest", {x = 9.5, y = -11.5}, {items = {["artillery-targeting-remote"] = 1, ["cluster-grenade"] = 100}, }},
    {"substation", {x = 10, y = -10}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -10.5}, {force = "enemy", }},
    {"steel-chest", {x = 11.5, y = -11.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = 12.5, y = -11.5}, {dir = "west", force = "enemy", }},
    {"laser-turret", {x = 14, y = -10}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -11.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -9.5}, {force = "enemy", }},
    {"gate", {x = -12.5, y = -8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = -8.5}, {force = "enemy", }},
    {"gate", {x = -11.5, y = -8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -8.5}, {force = "enemy", }},
    {"gate", {x = 11.5, y = -8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -8.5}, {force = "enemy", }},
    {"gate", {x = 12.5, y = -8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 13.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = -4, y = -4}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -5.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = -5.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -1.5, y = -5.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 1.5, y = -5.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 0.5, y = -5.5}, {dir = "east", force = "enemy", }},
    {"laser-turret", {x = 4, y = -4}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = -5.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = -5.5, y = -1.5}, {force = "enemy", }},
    {"substation", {x = -2, y = 0}, {force = "enemy", }},
    {"purple-crystal-gen", {x = 0.5, y = -1}, {force = "enemy", }},
    {"gate", {x = 5.5, y = -0.5}, {force = "enemy", }},
    {"gate", {x = 5.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = -5.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = -5.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = 5.5, y = 1.5}, {force = "enemy", }},
    {"gate", {x = 5.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 3.5}, {force = "enemy", }},
    {"laser-turret", {x = -4, y = 4}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 2.5}, {force = "enemy", }},
    {"laser-turret", {x = 4, y = 4}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 5.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = 5.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = -1.5, y = 5.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 1.5, y = 5.5}, {dir = "east", force = "enemy", }},
    {"gate", {x = 0.5, y = 5.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = 10}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {force = "enemy", }},
    {"gate", {x = -12.5, y = 8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 8.5}, {force = "enemy", }},
    {"gate", {x = -11.5, y = 8.5}, {dir = "east", force = "enemy", }},
    {"substation", {x = -10, y = 10}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 8.5}, {force = "enemy", }},
    {"substation", {x = 10, y = 10}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 9.5}, {force = "enemy", }},
    {"gate", {x = 11.5, y = 8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 8.5}, {force = "enemy", }},
    {"gate", {x = 12.5, y = 8.5}, {dir = "east", force = "enemy", }},
    {"laser-turret", {x = 14, y = 10}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 8.5}, {force = "enemy", }},
    {"gun-turret", {x = -14, y = 12}, {dir = "west", force = "enemy", items = {["piercing-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = -15.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 11.5}, {force = "enemy", }},
    {"fast-inserter", {x = -12.5, y = 11.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = -11.5, y = 11.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 9600}, }},
    {"gate", {x = -8.5, y = 11.5}, {force = "enemy", }},
    {"steel-chest", {x = -9.5, y = 11.5}, {items = {["advanced-circuit"] = 40, ["electronic-circuit"] = 6, ["stone-wall"] = 34}, }},
    {"stone-wall", {x = -8.5, y = 10.5}, {force = "enemy", }},
    {"gate", {x = 8.5, y = 11.5}, {force = "enemy", }},
    {"steel-chest", {x = 9.5, y = 11.5}, {items = {["chemical-science-pack"] = 200, ["modular-armor"] = 1}, }},
    {"stone-wall", {x = 8.5, y = 10.5}, {force = "enemy", }},
    {"steel-chest", {x = 11.5, y = 11.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 9600}, }},
    {"fast-inserter", {x = 12.5, y = 11.5}, {dir = "west", force = "enemy", }},
    {"gun-turret", {x = 14, y = 12}, {dir = "east", force = "enemy", items = {["piercing-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 15.5, y = 11.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 10.5}, {force = "enemy", }},
    {"laser-turret", {x = -14, y = 14}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 13.5}, {force = "enemy", }},
    {"gun-turret", {x = -12, y = 14}, {dir = "south", force = "enemy", items = {["piercing-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -11.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = -10, y = 14}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 13.5}, {force = "enemy", }},
    {"gate", {x = -8.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 13.5}, {force = "enemy", }},
    {"gate", {x = 8.5, y = 12.5}, {force = "enemy", }},
    {"laser-turret", {x = 10, y = 14}, {force = "enemy", }},
    {"fast-inserter", {x = 11.5, y = 12.5}, {force = "enemy", }},
    {"gun-turret", {x = 12, y = 14}, {dir = "south", force = "enemy", items = {["piercing-rounds-magazine"] = 200}, }},
    {"laser-turret", {x = 14, y = 14}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 13.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {force = "enemy", }},
    {"stone-wall", {x = -14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -15.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = -0.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 11.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 12.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 13.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 14.5}, {force = "enemy", }},
    {"stone-wall", {x = 14.5, y = 15.5}, {force = "enemy", }},
    {"stone-wall", {x = 15.5, y = 15.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -16, y = -16}},
    {"grass-1", {x = -16, y = -15}},
    {"grass-1", {x = -16, y = -14}},
    {"grass-1", {x = -16, y = -13}},
    {"grass-1", {x = -16, y = -12}},
    {"grass-1", {x = -16, y = -11}},
    {"grass-1", {x = -16, y = -10}},
    {"grass-1", {x = -16, y = -9}},
    {"grass-1", {x = -16, y = -8}},
    {"grass-1", {x = -16, y = -7}},
    {"grass-1", {x = -16, y = -6}},
    {"grass-1", {x = -16, y = -5}},
    {"grass-1", {x = -16, y = -4}},
    {"grass-1", {x = -16, y = -3}},
    {"grass-1", {x = -16, y = -2}},
    {"grass-1", {x = -16, y = -1}},
    {"grass-1", {x = -16, y = 0}},
    {"grass-1", {x = -16, y = 1}},
    {"grass-1", {x = -16, y = 2}},
    {"grass-1", {x = -16, y = 3}},
    {"grass-1", {x = -16, y = 4}},
    {"grass-1", {x = -16, y = 5}},
    {"grass-1", {x = -16, y = 6}},
    {"grass-1", {x = -16, y = 7}},
    {"grass-1", {x = -16, y = 8}},
    {"grass-1", {x = -16, y = 9}},
    {"grass-1", {x = -16, y = 10}},
    {"grass-1", {x = -16, y = 11}},
    {"grass-1", {x = -16, y = 12}},
    {"grass-1", {x = -16, y = 13}},
    {"grass-1", {x = -16, y = 14}},
    {"grass-1", {x = -16, y = 15}},
    {"grass-1", {x = -15, y = -16}},
    {"grass-1", {x = -15, y = -15}},
    {"grass-1", {x = -15, y = -14}},
    {"grass-1", {x = -15, y = -13}},
    {"grass-1", {x = -15, y = -12}},
    {"grass-1", {x = -15, y = -11}},
    {"grass-1", {x = -15, y = -10}},
    {"grass-1", {x = -15, y = -9}},
    {"grass-1", {x = -15, y = -8}},
    {"grass-1", {x = -15, y = -7}},
    {"grass-1", {x = -15, y = -6}},
    {"grass-1", {x = -15, y = -5}},
    {"grass-1", {x = -15, y = -4}},
    {"grass-1", {x = -15, y = -3}},
    {"grass-1", {x = -15, y = -2}},
    {"grass-1", {x = -15, y = -1}},
    {"grass-1", {x = -15, y = 0}},
    {"grass-1", {x = -15, y = 1}},
    {"grass-1", {x = -15, y = 2}},
    {"grass-1", {x = -15, y = 3}},
    {"grass-1", {x = -15, y = 4}},
    {"grass-1", {x = -15, y = 5}},
    {"grass-1", {x = -15, y = 6}},
    {"grass-1", {x = -15, y = 7}},
    {"grass-1", {x = -15, y = 8}},
    {"grass-1", {x = -15, y = 9}},
    {"grass-1", {x = -15, y = 10}},
    {"grass-1", {x = -15, y = 11}},
    {"grass-1", {x = -15, y = 12}},
    {"grass-1", {x = -15, y = 13}},
    {"grass-1", {x = -15, y = 14}},
    {"grass-1", {x = -15, y = 15}},
    {"grass-1", {x = -14, y = -16}},
    {"grass-1", {x = -14, y = -15}},
    {"grass-1", {x = -14, y = -14}},
    {"grass-1", {x = -14, y = -13}},
    {"grass-1", {x = -14, y = -12}},
    {"grass-1", {x = -14, y = -11}},
    {"grass-1", {x = -14, y = -10}},
    {"grass-1", {x = -14, y = -9}},
    {"grass-1", {x = -14, y = -8}},
    {"grass-1", {x = -14, y = -7}},
    {"grass-1", {x = -14, y = -6}},
    {"grass-1", {x = -14, y = -5}},
    {"grass-1", {x = -14, y = -4}},
    {"grass-1", {x = -14, y = -3}},
    {"grass-1", {x = -14, y = -2}},
    {"grass-1", {x = -14, y = -1}},
    {"grass-1", {x = -14, y = 0}},
    {"grass-1", {x = -14, y = 1}},
    {"grass-1", {x = -14, y = 2}},
    {"grass-1", {x = -14, y = 3}},
    {"grass-1", {x = -14, y = 4}},
    {"grass-1", {x = -14, y = 5}},
    {"grass-1", {x = -14, y = 6}},
    {"grass-1", {x = -14, y = 7}},
    {"grass-1", {x = -14, y = 8}},
    {"grass-1", {x = -14, y = 9}},
    {"grass-1", {x = -14, y = 10}},
    {"grass-1", {x = -14, y = 11}},
    {"grass-1", {x = -14, y = 12}},
    {"grass-1", {x = -14, y = 13}},
    {"grass-1", {x = -14, y = 14}},
    {"grass-1", {x = -14, y = 15}},
    {"grass-1", {x = -13, y = -16}},
    {"grass-1", {x = -13, y = -15}},
    {"grass-1", {x = -13, y = -14}},
    {"grass-1", {x = -13, y = -13}},
    {"grass-1", {x = -13, y = -12}},
    {"grass-1", {x = -13, y = -11}},
    {"grass-1", {x = -13, y = -10}},
    {"grass-1", {x = -13, y = -9}},
    {"concrete", {x = -13, y = -8}},
    {"concrete", {x = -13, y = -7}},
    {"concrete", {x = -13, y = -6}},
    {"concrete", {x = -13, y = -5}},
    {"concrete", {x = -13, y = -4}},
    {"concrete", {x = -13, y = -3}},
    {"concrete", {x = -13, y = -2}},
    {"concrete", {x = -13, y = -1}},
    {"concrete", {x = -13, y = 0}},
    {"concrete", {x = -13, y = 1}},
    {"concrete", {x = -13, y = 2}},
    {"concrete", {x = -13, y = 3}},
    {"concrete", {x = -13, y = 4}},
    {"concrete", {x = -13, y = 5}},
    {"concrete", {x = -13, y = 6}},
    {"concrete", {x = -13, y = 7}},
    {"grass-1", {x = -13, y = 8}},
    {"grass-1", {x = -13, y = 9}},
    {"grass-1", {x = -13, y = 10}},
    {"grass-1", {x = -13, y = 11}},
    {"grass-1", {x = -13, y = 12}},
    {"grass-1", {x = -13, y = 13}},
    {"grass-1", {x = -13, y = 14}},
    {"grass-1", {x = -13, y = 15}},
    {"grass-1", {x = -12, y = -16}},
    {"grass-1", {x = -12, y = -15}},
    {"grass-1", {x = -12, y = -14}},
    {"grass-1", {x = -12, y = -13}},
    {"grass-1", {x = -12, y = -12}},
    {"grass-1", {x = -12, y = -11}},
    {"grass-1", {x = -12, y = -10}},
    {"grass-1", {x = -12, y = -9}},
    {"concrete", {x = -12, y = -8}},
    {"concrete", {x = -12, y = -7}},
    {"concrete", {x = -12, y = -6}},
    {"concrete", {x = -12, y = -5}},
    {"concrete", {x = -12, y = -4}},
    {"concrete", {x = -12, y = -3}},
    {"concrete", {x = -12, y = -2}},
    {"concrete", {x = -12, y = -1}},
    {"concrete", {x = -12, y = 0}},
    {"concrete", {x = -12, y = 1}},
    {"concrete", {x = -12, y = 2}},
    {"concrete", {x = -12, y = 3}},
    {"concrete", {x = -12, y = 4}},
    {"concrete", {x = -12, y = 5}},
    {"concrete", {x = -12, y = 6}},
    {"concrete", {x = -12, y = 7}},
    {"grass-1", {x = -12, y = 8}},
    {"grass-1", {x = -12, y = 9}},
    {"grass-1", {x = -12, y = 10}},
    {"grass-1", {x = -12, y = 11}},
    {"grass-1", {x = -12, y = 12}},
    {"grass-1", {x = -12, y = 13}},
    {"grass-1", {x = -12, y = 14}},
    {"grass-1", {x = -12, y = 15}},
    {"grass-1", {x = -11, y = -16}},
    {"grass-1", {x = -11, y = -15}},
    {"grass-1", {x = -11, y = -14}},
    {"grass-1", {x = -11, y = -13}},
    {"grass-1", {x = -11, y = -12}},
    {"grass-1", {x = -11, y = -11}},
    {"grass-1", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-1", {x = -11, y = -5}},
    {"grass-1", {x = -11, y = -4}},
    {"grass-1", {x = -11, y = -3}},
    {"concrete", {x = -11, y = -2}},
    {"concrete", {x = -11, y = -1}},
    {"concrete", {x = -11, y = 0}},
    {"concrete", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-1", {x = -11, y = 4}},
    {"grass-1", {x = -11, y = 5}},
    {"grass-1", {x = -11, y = 6}},
    {"grass-1", {x = -11, y = 7}},
    {"grass-1", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"grass-1", {x = -11, y = 10}},
    {"grass-1", {x = -11, y = 11}},
    {"grass-1", {x = -11, y = 12}},
    {"grass-1", {x = -11, y = 13}},
    {"grass-1", {x = -11, y = 14}},
    {"grass-1", {x = -11, y = 15}},
    {"grass-1", {x = -10, y = -16}},
    {"grass-1", {x = -10, y = -15}},
    {"grass-1", {x = -10, y = -14}},
    {"grass-1", {x = -10, y = -13}},
    {"grass-1", {x = -10, y = -12}},
    {"grass-1", {x = -10, y = -11}},
    {"grass-1", {x = -10, y = -10}},
    {"grass-1", {x = -10, y = -9}},
    {"grass-1", {x = -10, y = -8}},
    {"grass-1", {x = -10, y = -7}},
    {"grass-1", {x = -10, y = -6}},
    {"grass-1", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-1", {x = -10, y = -3}},
    {"concrete", {x = -10, y = -2}},
    {"concrete", {x = -10, y = -1}},
    {"concrete", {x = -10, y = 0}},
    {"concrete", {x = -10, y = 1}},
    {"grass-1", {x = -10, y = 2}},
    {"grass-1", {x = -10, y = 3}},
    {"grass-1", {x = -10, y = 4}},
    {"grass-1", {x = -10, y = 5}},
    {"grass-1", {x = -10, y = 6}},
    {"grass-1", {x = -10, y = 7}},
    {"grass-1", {x = -10, y = 8}},
    {"grass-1", {x = -10, y = 9}},
    {"grass-1", {x = -10, y = 10}},
    {"grass-1", {x = -10, y = 11}},
    {"grass-1", {x = -10, y = 12}},
    {"grass-1", {x = -10, y = 13}},
    {"grass-1", {x = -10, y = 14}},
    {"grass-1", {x = -10, y = 15}},
    {"grass-1", {x = -9, y = -16}},
    {"grass-1", {x = -9, y = -15}},
    {"grass-1", {x = -9, y = -14}},
    {"grass-1", {x = -9, y = -13}},
    {"grass-1", {x = -9, y = -12}},
    {"grass-1", {x = -9, y = -11}},
    {"grass-1", {x = -9, y = -10}},
    {"grass-1", {x = -9, y = -9}},
    {"grass-1", {x = -9, y = -8}},
    {"grass-1", {x = -9, y = -7}},
    {"grass-1", {x = -9, y = -6}},
    {"grass-1", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"concrete", {x = -9, y = -2}},
    {"concrete", {x = -9, y = -1}},
    {"concrete", {x = -9, y = 0}},
    {"concrete", {x = -9, y = 1}},
    {"grass-1", {x = -9, y = 2}},
    {"grass-1", {x = -9, y = 3}},
    {"grass-1", {x = -9, y = 4}},
    {"grass-1", {x = -9, y = 5}},
    {"grass-1", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-1", {x = -9, y = 9}},
    {"grass-1", {x = -9, y = 10}},
    {"grass-1", {x = -9, y = 11}},
    {"grass-1", {x = -9, y = 12}},
    {"grass-1", {x = -9, y = 13}},
    {"grass-1", {x = -9, y = 14}},
    {"grass-1", {x = -9, y = 15}},
    {"grass-1", {x = -8, y = -16}},
    {"grass-1", {x = -8, y = -15}},
    {"grass-1", {x = -8, y = -14}},
    {"concrete", {x = -8, y = -13}},
    {"concrete", {x = -8, y = -12}},
    {"grass-1", {x = -8, y = -11}},
    {"grass-1", {x = -8, y = -10}},
    {"grass-1", {x = -8, y = -9}},
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"concrete", {x = -8, y = -2}},
    {"concrete", {x = -8, y = -1}},
    {"concrete", {x = -8, y = 0}},
    {"concrete", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-1", {x = -8, y = 9}},
    {"grass-1", {x = -8, y = 10}},
    {"concrete", {x = -8, y = 11}},
    {"concrete", {x = -8, y = 12}},
    {"grass-1", {x = -8, y = 13}},
    {"grass-1", {x = -8, y = 14}},
    {"grass-1", {x = -8, y = 15}},
    {"grass-1", {x = -7, y = -16}},
    {"grass-1", {x = -7, y = -15}},
    {"grass-1", {x = -7, y = -14}},
    {"concrete", {x = -7, y = -13}},
    {"concrete", {x = -7, y = -12}},
    {"grass-1", {x = -7, y = -11}},
    {"grass-1", {x = -7, y = -10}},
    {"grass-1", {x = -7, y = -9}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"concrete", {x = -7, y = -2}},
    {"concrete", {x = -7, y = -1}},
    {"concrete", {x = -7, y = 0}},
    {"concrete", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -7, y = 8}},
    {"grass-1", {x = -7, y = 9}},
    {"grass-1", {x = -7, y = 10}},
    {"concrete", {x = -7, y = 11}},
    {"concrete", {x = -7, y = 12}},
    {"grass-1", {x = -7, y = 13}},
    {"grass-1", {x = -7, y = 14}},
    {"grass-1", {x = -7, y = 15}},
    {"grass-1", {x = -6, y = -16}},
    {"grass-1", {x = -6, y = -15}},
    {"grass-1", {x = -6, y = -14}},
    {"concrete", {x = -6, y = -13}},
    {"concrete", {x = -6, y = -12}},
    {"grass-1", {x = -6, y = -11}},
    {"grass-1", {x = -6, y = -10}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-1", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"grass-1", {x = -6, y = 9}},
    {"grass-1", {x = -6, y = 10}},
    {"concrete", {x = -6, y = 11}},
    {"concrete", {x = -6, y = 12}},
    {"grass-1", {x = -6, y = 13}},
    {"grass-1", {x = -6, y = 14}},
    {"grass-1", {x = -6, y = 15}},
    {"grass-1", {x = -5, y = -16}},
    {"grass-1", {x = -5, y = -15}},
    {"grass-1", {x = -5, y = -14}},
    {"concrete", {x = -5, y = -13}},
    {"concrete", {x = -5, y = -12}},
    {"grass-1", {x = -5, y = -11}},
    {"grass-1", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -5, y = 8}},
    {"grass-1", {x = -5, y = 9}},
    {"grass-1", {x = -5, y = 10}},
    {"concrete", {x = -5, y = 11}},
    {"concrete", {x = -5, y = 12}},
    {"grass-1", {x = -5, y = 13}},
    {"grass-1", {x = -5, y = 14}},
    {"grass-1", {x = -5, y = 15}},
    {"grass-1", {x = -4, y = -16}},
    {"grass-1", {x = -4, y = -15}},
    {"grass-1", {x = -4, y = -14}},
    {"concrete", {x = -4, y = -13}},
    {"concrete", {x = -4, y = -12}},
    {"grass-1", {x = -4, y = -11}},
    {"grass-1", {x = -4, y = -10}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"grass-1", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -4, y = 8}},
    {"grass-1", {x = -4, y = 9}},
    {"grass-1", {x = -4, y = 10}},
    {"concrete", {x = -4, y = 11}},
    {"concrete", {x = -4, y = 12}},
    {"grass-1", {x = -4, y = 13}},
    {"grass-1", {x = -4, y = 14}},
    {"grass-1", {x = -4, y = 15}},
    {"grass-1", {x = -3, y = -16}},
    {"grass-1", {x = -3, y = -15}},
    {"grass-1", {x = -3, y = -14}},
    {"concrete", {x = -3, y = -13}},
    {"concrete", {x = -3, y = -12}},
    {"grass-1", {x = -3, y = -11}},
    {"grass-1", {x = -3, y = -10}},
    {"grass-1", {x = -3, y = -9}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -3, y = 8}},
    {"grass-1", {x = -3, y = 9}},
    {"grass-1", {x = -3, y = 10}},
    {"concrete", {x = -3, y = 11}},
    {"concrete", {x = -3, y = 12}},
    {"grass-1", {x = -3, y = 13}},
    {"grass-1", {x = -3, y = 14}},
    {"grass-1", {x = -3, y = 15}},
    {"grass-1", {x = -2, y = -16}},
    {"grass-1", {x = -2, y = -15}},
    {"grass-1", {x = -2, y = -14}},
    {"concrete", {x = -2, y = -13}},
    {"concrete", {x = -2, y = -12}},
    {"concrete", {x = -2, y = -11}},
    {"concrete", {x = -2, y = -10}},
    {"concrete", {x = -2, y = -9}},
    {"concrete", {x = -2, y = -8}},
    {"concrete", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"concrete", {x = -2, y = 6}},
    {"concrete", {x = -2, y = 7}},
    {"concrete", {x = -2, y = 8}},
    {"concrete", {x = -2, y = 9}},
    {"concrete", {x = -2, y = 10}},
    {"concrete", {x = -2, y = 11}},
    {"concrete", {x = -2, y = 12}},
    {"grass-1", {x = -2, y = 13}},
    {"grass-1", {x = -2, y = 14}},
    {"grass-1", {x = -2, y = 15}},
    {"grass-1", {x = -1, y = -16}},
    {"grass-1", {x = -1, y = -15}},
    {"grass-1", {x = -1, y = -14}},
    {"concrete", {x = -1, y = -13}},
    {"concrete", {x = -1, y = -12}},
    {"concrete", {x = -1, y = -11}},
    {"concrete", {x = -1, y = -10}},
    {"concrete", {x = -1, y = -9}},
    {"concrete", {x = -1, y = -8}},
    {"concrete", {x = -1, y = -7}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"concrete", {x = -1, y = 6}},
    {"concrete", {x = -1, y = 7}},
    {"concrete", {x = -1, y = 8}},
    {"concrete", {x = -1, y = 9}},
    {"concrete", {x = -1, y = 10}},
    {"concrete", {x = -1, y = 11}},
    {"concrete", {x = -1, y = 12}},
    {"grass-1", {x = -1, y = 13}},
    {"grass-1", {x = -1, y = 14}},
    {"grass-1", {x = -1, y = 15}},
    {"grass-1", {x = 0, y = -16}},
    {"grass-1", {x = 0, y = -15}},
    {"grass-1", {x = 0, y = -14}},
    {"concrete", {x = 0, y = -13}},
    {"concrete", {x = 0, y = -12}},
    {"concrete", {x = 0, y = -11}},
    {"concrete", {x = 0, y = -10}},
    {"concrete", {x = 0, y = -9}},
    {"concrete", {x = 0, y = -8}},
    {"concrete", {x = 0, y = -7}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"concrete", {x = 0, y = 6}},
    {"concrete", {x = 0, y = 7}},
    {"concrete", {x = 0, y = 8}},
    {"concrete", {x = 0, y = 9}},
    {"concrete", {x = 0, y = 10}},
    {"concrete", {x = 0, y = 11}},
    {"concrete", {x = 0, y = 12}},
    {"grass-1", {x = 0, y = 13}},
    {"grass-1", {x = 0, y = 14}},
    {"grass-1", {x = 0, y = 15}},
    {"grass-1", {x = 1, y = -16}},
    {"grass-1", {x = 1, y = -15}},
    {"grass-1", {x = 1, y = -14}},
    {"concrete", {x = 1, y = -13}},
    {"concrete", {x = 1, y = -12}},
    {"concrete", {x = 1, y = -11}},
    {"concrete", {x = 1, y = -10}},
    {"concrete", {x = 1, y = -9}},
    {"concrete", {x = 1, y = -8}},
    {"concrete", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"concrete", {x = 1, y = 6}},
    {"concrete", {x = 1, y = 7}},
    {"concrete", {x = 1, y = 8}},
    {"concrete", {x = 1, y = 9}},
    {"concrete", {x = 1, y = 10}},
    {"concrete", {x = 1, y = 11}},
    {"concrete", {x = 1, y = 12}},
    {"grass-1", {x = 1, y = 13}},
    {"grass-1", {x = 1, y = 14}},
    {"grass-1", {x = 1, y = 15}},
    {"grass-1", {x = 2, y = -16}},
    {"grass-1", {x = 2, y = -15}},
    {"grass-1", {x = 2, y = -14}},
    {"concrete", {x = 2, y = -13}},
    {"concrete", {x = 2, y = -12}},
    {"grass-1", {x = 2, y = -11}},
    {"grass-1", {x = 2, y = -10}},
    {"grass-1", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 2, y = 9}},
    {"grass-1", {x = 2, y = 10}},
    {"concrete", {x = 2, y = 11}},
    {"concrete", {x = 2, y = 12}},
    {"grass-1", {x = 2, y = 13}},
    {"grass-1", {x = 2, y = 14}},
    {"grass-1", {x = 2, y = 15}},
    {"grass-1", {x = 3, y = -16}},
    {"grass-1", {x = 3, y = -15}},
    {"grass-1", {x = 3, y = -14}},
    {"concrete", {x = 3, y = -13}},
    {"concrete", {x = 3, y = -12}},
    {"grass-1", {x = 3, y = -11}},
    {"grass-1", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 3, y = 9}},
    {"grass-1", {x = 3, y = 10}},
    {"concrete", {x = 3, y = 11}},
    {"concrete", {x = 3, y = 12}},
    {"grass-1", {x = 3, y = 13}},
    {"grass-1", {x = 3, y = 14}},
    {"grass-1", {x = 3, y = 15}},
    {"grass-1", {x = 4, y = -16}},
    {"grass-1", {x = 4, y = -15}},
    {"grass-1", {x = 4, y = -14}},
    {"concrete", {x = 4, y = -13}},
    {"concrete", {x = 4, y = -12}},
    {"grass-1", {x = 4, y = -11}},
    {"grass-1", {x = 4, y = -10}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 4, y = 8}},
    {"grass-1", {x = 4, y = 9}},
    {"grass-1", {x = 4, y = 10}},
    {"concrete", {x = 4, y = 11}},
    {"concrete", {x = 4, y = 12}},
    {"grass-1", {x = 4, y = 13}},
    {"grass-1", {x = 4, y = 14}},
    {"grass-1", {x = 4, y = 15}},
    {"grass-1", {x = 5, y = -16}},
    {"grass-1", {x = 5, y = -15}},
    {"grass-1", {x = 5, y = -14}},
    {"concrete", {x = 5, y = -13}},
    {"concrete", {x = 5, y = -12}},
    {"grass-1", {x = 5, y = -11}},
    {"grass-1", {x = 5, y = -10}},
    {"grass-1", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 5, y = 8}},
    {"grass-1", {x = 5, y = 9}},
    {"grass-1", {x = 5, y = 10}},
    {"concrete", {x = 5, y = 11}},
    {"concrete", {x = 5, y = 12}},
    {"grass-1", {x = 5, y = 13}},
    {"grass-1", {x = 5, y = 14}},
    {"grass-1", {x = 5, y = 15}},
    {"grass-1", {x = 6, y = -16}},
    {"grass-1", {x = 6, y = -15}},
    {"grass-1", {x = 6, y = -14}},
    {"concrete", {x = 6, y = -13}},
    {"concrete", {x = 6, y = -12}},
    {"grass-1", {x = 6, y = -11}},
    {"grass-1", {x = 6, y = -10}},
    {"grass-1", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"concrete", {x = 6, y = -2}},
    {"concrete", {x = 6, y = -1}},
    {"concrete", {x = 6, y = 0}},
    {"concrete", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-1", {x = 6, y = 7}},
    {"grass-1", {x = 6, y = 8}},
    {"grass-1", {x = 6, y = 9}},
    {"grass-1", {x = 6, y = 10}},
    {"concrete", {x = 6, y = 11}},
    {"concrete", {x = 6, y = 12}},
    {"grass-1", {x = 6, y = 13}},
    {"grass-1", {x = 6, y = 14}},
    {"grass-1", {x = 6, y = 15}},
    {"grass-1", {x = 7, y = -16}},
    {"grass-1", {x = 7, y = -15}},
    {"grass-1", {x = 7, y = -14}},
    {"concrete", {x = 7, y = -13}},
    {"concrete", {x = 7, y = -12}},
    {"grass-1", {x = 7, y = -11}},
    {"grass-1", {x = 7, y = -10}},
    {"grass-1", {x = 7, y = -9}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"concrete", {x = 7, y = -2}},
    {"concrete", {x = 7, y = -1}},
    {"concrete", {x = 7, y = 0}},
    {"concrete", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
    {"grass-1", {x = 7, y = 8}},
    {"grass-1", {x = 7, y = 9}},
    {"grass-1", {x = 7, y = 10}},
    {"concrete", {x = 7, y = 11}},
    {"concrete", {x = 7, y = 12}},
    {"grass-1", {x = 7, y = 13}},
    {"grass-1", {x = 7, y = 14}},
    {"grass-1", {x = 7, y = 15}},
    {"grass-1", {x = 8, y = -16}},
    {"grass-1", {x = 8, y = -15}},
    {"grass-1", {x = 8, y = -14}},
    {"grass-1", {x = 8, y = -13}},
    {"grass-1", {x = 8, y = -12}},
    {"grass-1", {x = 8, y = -11}},
    {"grass-1", {x = 8, y = -10}},
    {"grass-1", {x = 8, y = -9}},
    {"grass-1", {x = 8, y = -8}},
    {"grass-1", {x = 8, y = -7}},
    {"grass-1", {x = 8, y = -6}},
    {"grass-1", {x = 8, y = -5}},
    {"grass-1", {x = 8, y = -4}},
    {"grass-1", {x = 8, y = -3}},
    {"concrete", {x = 8, y = -2}},
    {"concrete", {x = 8, y = -1}},
    {"concrete", {x = 8, y = 0}},
    {"concrete", {x = 8, y = 1}},
    {"grass-1", {x = 8, y = 2}},
    {"grass-1", {x = 8, y = 3}},
    {"grass-1", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-1", {x = 8, y = 6}},
    {"grass-1", {x = 8, y = 7}},
    {"grass-1", {x = 8, y = 8}},
    {"grass-1", {x = 8, y = 9}},
    {"grass-1", {x = 8, y = 10}},
    {"grass-1", {x = 8, y = 11}},
    {"grass-1", {x = 8, y = 12}},
    {"grass-1", {x = 8, y = 13}},
    {"grass-1", {x = 8, y = 14}},
    {"grass-1", {x = 8, y = 15}},
    {"grass-1", {x = 9, y = -16}},
    {"grass-1", {x = 9, y = -15}},
    {"grass-1", {x = 9, y = -14}},
    {"grass-1", {x = 9, y = -13}},
    {"grass-1", {x = 9, y = -12}},
    {"grass-1", {x = 9, y = -11}},
    {"grass-1", {x = 9, y = -10}},
    {"grass-1", {x = 9, y = -9}},
    {"grass-1", {x = 9, y = -8}},
    {"grass-1", {x = 9, y = -7}},
    {"grass-1", {x = 9, y = -6}},
    {"grass-1", {x = 9, y = -5}},
    {"grass-1", {x = 9, y = -4}},
    {"grass-1", {x = 9, y = -3}},
    {"concrete", {x = 9, y = -2}},
    {"concrete", {x = 9, y = -1}},
    {"concrete", {x = 9, y = 0}},
    {"concrete", {x = 9, y = 1}},
    {"grass-1", {x = 9, y = 2}},
    {"grass-1", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"grass-1", {x = 9, y = 5}},
    {"grass-1", {x = 9, y = 6}},
    {"grass-1", {x = 9, y = 7}},
    {"grass-1", {x = 9, y = 8}},
    {"grass-1", {x = 9, y = 9}},
    {"grass-1", {x = 9, y = 10}},
    {"grass-1", {x = 9, y = 11}},
    {"grass-1", {x = 9, y = 12}},
    {"grass-1", {x = 9, y = 13}},
    {"grass-1", {x = 9, y = 14}},
    {"grass-1", {x = 9, y = 15}},
    {"grass-1", {x = 10, y = -16}},
    {"grass-1", {x = 10, y = -15}},
    {"grass-1", {x = 10, y = -14}},
    {"grass-1", {x = 10, y = -13}},
    {"grass-1", {x = 10, y = -12}},
    {"grass-1", {x = 10, y = -11}},
    {"grass-1", {x = 10, y = -10}},
    {"grass-1", {x = 10, y = -9}},
    {"grass-1", {x = 10, y = -8}},
    {"grass-1", {x = 10, y = -7}},
    {"grass-1", {x = 10, y = -6}},
    {"grass-1", {x = 10, y = -5}},
    {"grass-1", {x = 10, y = -4}},
    {"grass-1", {x = 10, y = -3}},
    {"concrete", {x = 10, y = -2}},
    {"concrete", {x = 10, y = -1}},
    {"concrete", {x = 10, y = 0}},
    {"concrete", {x = 10, y = 1}},
    {"grass-1", {x = 10, y = 2}},
    {"grass-1", {x = 10, y = 3}},
    {"grass-1", {x = 10, y = 4}},
    {"grass-1", {x = 10, y = 5}},
    {"grass-1", {x = 10, y = 6}},
    {"grass-1", {x = 10, y = 7}},
    {"grass-1", {x = 10, y = 8}},
    {"grass-1", {x = 10, y = 9}},
    {"grass-1", {x = 10, y = 10}},
    {"grass-1", {x = 10, y = 11}},
    {"grass-1", {x = 10, y = 12}},
    {"grass-1", {x = 10, y = 13}},
    {"grass-1", {x = 10, y = 14}},
    {"grass-1", {x = 10, y = 15}},
    {"grass-1", {x = 11, y = -16}},
    {"grass-1", {x = 11, y = -15}},
    {"grass-1", {x = 11, y = -14}},
    {"grass-1", {x = 11, y = -13}},
    {"grass-1", {x = 11, y = -12}},
    {"grass-1", {x = 11, y = -11}},
    {"grass-1", {x = 11, y = -10}},
    {"grass-1", {x = 11, y = -9}},
    {"concrete", {x = 11, y = -8}},
    {"concrete", {x = 11, y = -7}},
    {"concrete", {x = 11, y = -6}},
    {"concrete", {x = 11, y = -5}},
    {"concrete", {x = 11, y = -4}},
    {"concrete", {x = 11, y = -3}},
    {"concrete", {x = 11, y = -2}},
    {"concrete", {x = 11, y = -1}},
    {"concrete", {x = 11, y = 0}},
    {"concrete", {x = 11, y = 1}},
    {"concrete", {x = 11, y = 2}},
    {"concrete", {x = 11, y = 3}},
    {"concrete", {x = 11, y = 4}},
    {"concrete", {x = 11, y = 5}},
    {"concrete", {x = 11, y = 6}},
    {"concrete", {x = 11, y = 7}},
    {"grass-1", {x = 11, y = 8}},
    {"grass-1", {x = 11, y = 9}},
    {"grass-1", {x = 11, y = 10}},
    {"grass-1", {x = 11, y = 11}},
    {"grass-1", {x = 11, y = 12}},
    {"grass-1", {x = 11, y = 13}},
    {"grass-1", {x = 11, y = 14}},
    {"grass-1", {x = 11, y = 15}},
    {"grass-1", {x = 12, y = -16}},
    {"grass-1", {x = 12, y = -15}},
    {"grass-1", {x = 12, y = -14}},
    {"grass-1", {x = 12, y = -13}},
    {"grass-1", {x = 12, y = -12}},
    {"grass-1", {x = 12, y = -11}},
    {"grass-1", {x = 12, y = -10}},
    {"grass-1", {x = 12, y = -9}},
    {"concrete", {x = 12, y = -8}},
    {"concrete", {x = 12, y = -7}},
    {"concrete", {x = 12, y = -6}},
    {"concrete", {x = 12, y = -5}},
    {"concrete", {x = 12, y = -4}},
    {"concrete", {x = 12, y = -3}},
    {"concrete", {x = 12, y = -2}},
    {"concrete", {x = 12, y = -1}},
    {"concrete", {x = 12, y = 0}},
    {"concrete", {x = 12, y = 1}},
    {"concrete", {x = 12, y = 2}},
    {"concrete", {x = 12, y = 3}},
    {"concrete", {x = 12, y = 4}},
    {"concrete", {x = 12, y = 5}},
    {"concrete", {x = 12, y = 6}},
    {"concrete", {x = 12, y = 7}},
    {"grass-1", {x = 12, y = 8}},
    {"grass-1", {x = 12, y = 9}},
    {"grass-1", {x = 12, y = 10}},
    {"grass-1", {x = 12, y = 11}},
    {"grass-1", {x = 12, y = 12}},
    {"grass-1", {x = 12, y = 13}},
    {"grass-1", {x = 12, y = 14}},
    {"grass-1", {x = 12, y = 15}},
    {"grass-1", {x = 13, y = -16}},
    {"grass-1", {x = 13, y = -15}},
    {"grass-1", {x = 13, y = -14}},
    {"grass-1", {x = 13, y = -13}},
    {"grass-1", {x = 13, y = -12}},
    {"grass-1", {x = 13, y = -11}},
    {"grass-1", {x = 13, y = -10}},
    {"grass-1", {x = 13, y = -9}},
    {"grass-1", {x = 13, y = -8}},
    {"grass-1", {x = 13, y = -7}},
    {"grass-1", {x = 13, y = -6}},
    {"grass-1", {x = 13, y = -5}},
    {"grass-1", {x = 13, y = -4}},
    {"grass-1", {x = 13, y = -3}},
    {"grass-1", {x = 13, y = -2}},
    {"grass-1", {x = 13, y = -1}},
    {"grass-1", {x = 13, y = 0}},
    {"grass-1", {x = 13, y = 1}},
    {"grass-1", {x = 13, y = 2}},
    {"grass-1", {x = 13, y = 3}},
    {"grass-1", {x = 13, y = 4}},
    {"grass-1", {x = 13, y = 5}},
    {"grass-1", {x = 13, y = 6}},
    {"grass-1", {x = 13, y = 7}},
    {"grass-1", {x = 13, y = 8}},
    {"grass-1", {x = 13, y = 9}},
    {"grass-1", {x = 13, y = 10}},
    {"grass-1", {x = 13, y = 11}},
    {"grass-1", {x = 13, y = 12}},
    {"grass-1", {x = 13, y = 13}},
    {"grass-1", {x = 13, y = 14}},
    {"grass-1", {x = 13, y = 15}},
    {"grass-1", {x = 14, y = -16}},
    {"grass-1", {x = 14, y = -15}},
    {"grass-1", {x = 14, y = -14}},
    {"grass-1", {x = 14, y = -13}},
    {"grass-1", {x = 14, y = -12}},
    {"grass-1", {x = 14, y = -11}},
    {"grass-1", {x = 14, y = -10}},
    {"grass-1", {x = 14, y = -9}},
    {"grass-1", {x = 14, y = -8}},
    {"grass-1", {x = 14, y = -7}},
    {"grass-1", {x = 14, y = -6}},
    {"grass-1", {x = 14, y = -5}},
    {"grass-1", {x = 14, y = -4}},
    {"grass-1", {x = 14, y = -3}},
    {"grass-1", {x = 14, y = -2}},
    {"grass-1", {x = 14, y = -1}},
    {"grass-1", {x = 14, y = 0}},
    {"grass-1", {x = 14, y = 1}},
    {"grass-1", {x = 14, y = 2}},
    {"grass-1", {x = 14, y = 3}},
    {"grass-1", {x = 14, y = 4}},
    {"grass-1", {x = 14, y = 5}},
    {"grass-1", {x = 14, y = 6}},
    {"grass-1", {x = 14, y = 7}},
    {"grass-1", {x = 14, y = 8}},
    {"grass-1", {x = 14, y = 9}},
    {"grass-1", {x = 14, y = 10}},
    {"grass-1", {x = 14, y = 11}},
    {"grass-1", {x = 14, y = 12}},
    {"grass-1", {x = 14, y = 13}},
    {"grass-1", {x = 14, y = 14}},
    {"grass-1", {x = 14, y = 15}},
    {"grass-1", {x = 15, y = -16}},
    {"grass-1", {x = 15, y = -15}},
    {"grass-1", {x = 15, y = -14}},
    {"grass-1", {x = 15, y = -13}},
    {"grass-1", {x = 15, y = -12}},
    {"grass-1", {x = 15, y = -11}},
    {"grass-1", {x = 15, y = -10}},
    {"grass-1", {x = 15, y = -9}},
    {"grass-1", {x = 15, y = -8}},
    {"grass-1", {x = 15, y = -7}},
    {"grass-1", {x = 15, y = -6}},
    {"grass-1", {x = 15, y = -5}},
    {"grass-1", {x = 15, y = -4}},
    {"grass-1", {x = 15, y = -3}},
    {"grass-1", {x = 15, y = -2}},
    {"grass-1", {x = 15, y = -1}},
    {"grass-1", {x = 15, y = 0}},
    {"grass-1", {x = 15, y = 1}},
    {"grass-1", {x = 15, y = 2}},
    {"grass-1", {x = 15, y = 3}},
    {"grass-1", {x = 15, y = 4}},
    {"grass-1", {x = 15, y = 5}},
    {"grass-1", {x = 15, y = 6}},
    {"grass-1", {x = 15, y = 7}},
    {"grass-1", {x = 15, y = 8}},
    {"grass-1", {x = 15, y = 9}},
    {"grass-1", {x = 15, y = 10}},
    {"grass-1", {x = 15, y = 11}},
    {"grass-1", {x = 15, y = 12}},
    {"grass-1", {x = 15, y = 13}},
    {"grass-1", {x = 15, y = 14}},
    {"grass-1", {x = 15, y = 15}},
  }
}
