return
{
  entities =
  {
    {"stone-wall", {x = -6.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -7.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = -7.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -7.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -7.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -7.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = -6}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -5.5}, {force = "enemy", }},
    {"laser-turret", {x = -3, y = -6}, {force = "enemy", }},
    {"roboport", {x = 0, y = -4}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"laser-turret", {x = 3, y = -6}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -6.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = -6}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -4.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = -3}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -4.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = -3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -2.5}, {force = "enemy", }},
    {"steel-chest", {x = -2.5, y = -1.5}, {items = {["chemical-science-pack"] = 100}, }},
    {"steel-chest", {x = -0.5, y = -1.5}, {items = {["flying-robot-frame"] = 10, ["low-density-structure"] = 10}, }},
    {"steel-chest", {x = 0.5, y = -1.5}, {items = {["rocket-fuel"] = 10}, }},
    {"steel-chest", {x = 2.5, y = -1.5}, {items = {["production-science-pack"] = 100}, }},
    {"logistic-chest-passive-provider", {x = 2.5, y = -2.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"stone-wall", {x = 7.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -2.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = -0.5}, {force = "enemy", }},
    {"substation", {x = -2, y = 0}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.23, y = -0.57}, {force = "enemy", }},
    {"aliencon-robot", {x = -0.73, y = -0.57}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.22, y = -0.57}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.61, y = -0.57}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.85, y = -0.57}, {force = "enemy", }},
    {"aliencon-robot", {x = -1.91, y = -0.57}, {force = "enemy", }},
    {"green-crystal-gen", {x = 0.5, y = -1}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.73, y = -0.62}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.69, y = -0.64}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.59, y = -0.66}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.42, y = -0.68}, {force = "enemy", }},
    {"aliencon-robot", {x = 1.18, y = -0.68}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.89, y = -0.68}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.62, y = -0.64}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.34, y = -0.61}, {force = "enemy", }},
    {"aliencon-robot", {x = 0.11, y = -0.59}, {force = "enemy", }},
    {"substation", {x = 3, y = 0}, {force = "enemy", }},
    {"gate", {x = 7.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = 7.5, y = -0.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = 3}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 1.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -2.5, y = 1.5}, {force = "enemy", items = {["repair-pack"] = 4800}, }},
    {"roboport", {x = 0, y = 3}, {force = "enemy", }, {items = {["aliencon-robot"] = 10}, }},
    {"laser-turret", {x = 6, y = 3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 3.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = 6}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = -3, y = 6}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = 3, y = 6}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = 6}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 7.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = 7.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 7.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 7.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 7.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-1", {x = -8, y = -2}},
    {"grass-1", {x = -8, y = -1}},
    {"grass-1", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-1", {x = -7, y = -2}},
    {"grass-1", {x = -7, y = -1}},
    {"grass-1", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-1", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"grass-1", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-1", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -1, y = -8}},
    {"grass-1", {x = -1, y = -7}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = 0, y = -8}},
    {"grass-1", {x = 0, y = -7}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-1", {x = 6, y = 7}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-1", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
  }
}
