return
{
  entities =
  {
    {"stone-wall", {x = -9.5, y = -9.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = -9}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -10.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = -9}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -10.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -9.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -8.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = -7.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -8.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -7.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -6.5}, {force = "enemy", }},
    {"laser-turret", {x = -9, y = -6}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -5.5}, {force = "enemy", }},
    {"gun-turret", {x = -3, y = -6}, {force = "enemy", }},
    {"gun-turret", {x = 3, y = -6}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -6.5}, {force = "enemy", }},
    {"laser-turret", {x = 9, y = -6}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -4.5}, {force = "enemy", }},
    {"gun-turret", {x = -6, y = -3}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -3.5}, {force = "enemy", }},
    {"fast-inserter", {x = -2.5, y = -4.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -1.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 1.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 0.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"fast-inserter", {x = 2.5, y = -4.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = -3.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = -3.5}, {dir = "east", force = "enemy", }},
    {"gun-turret", {x = 6, y = -3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -1.5}, {force = "enemy", }},
    {"fast-inserter", {x = -4.5, y = -2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = -1.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = -1.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = -2.5}, {force = "enemy", }},
    {"purple-crystal-gen", {x = -0.5, y = -3}, {force = "enemy", }},
    {"steel-chest", {x = 1.5, y = -1.5}, {items = {["low-density-structure"] = 10, ["utility-science-pack"] = 100}, }},
    {"steel-chest", {x = 2.5, y = -1.5}, {items = {["flying-robot-frame"] = 10, ["production-science-pack"] = 100}, }},
    {"express-transport-belt", {x = 3.5, y = -1.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = -2.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 4.5, y = -2.5}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = -7.5, y = -0.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = -0.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = 0.5}, {force = "enemy", }},
    {"substation", {x = -3, y = 0}, {force = "enemy", }},
    {"assembling-machine-2", {x = -0.5, y = 0.5}, {force = "enemy", recipe = "cryexplosive-rounds-magazine", }},
    {"substation", {x = 2, y = 0}, {force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = 0.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = -0.5}, {dir = "south", force = "enemy", }},
    {"gate", {x = 7.5, y = 0.5}, {force = "enemy", }},
    {"gate", {x = 7.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 1.5}, {force = "enemy", }},
    {"gun-turret", {x = -6, y = 3}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 2.5}, {force = "enemy", }},
    {"fast-inserter", {x = -4.5, y = 2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = 1.5}, {force = "enemy", }},
    {"fast-inserter", {x = -2.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = 1.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = 2.5}, {force = "enemy", }},
    {"long-handed-inserter", {x = -0.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"long-handed-inserter", {x = -1.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"long-handed-inserter", {x = 0.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 1.5, y = 1.5}, {dir = "east", force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 2.5, y = 1.5}, {force = "enemy", items = {["iron-plate"] = 2000, ["copper-plate"] = 2000,["green-crystal-fragment"] = 1600, }}},
    {"express-transport-belt", {x = 3.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = 1.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 4.5, y = 2.5}, {dir = "west", force = "enemy", }},
    {"gun-turret", {x = 6, y = 3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 4.5}, {force = "enemy", }},
    {"fast-inserter", {x = -2.5, y = 4.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = 3.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = 3.5}, {dir = "west", force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -0.5, y = 4.5}, {force = "enemy", items = {["iron-plate"] = 2000, ["copper-plate"] = 2000,["green-crystal-fragment"] = 1600, }}},
    {"logistic-chest-passive-provider", {x = -1.5, y = 4.5}, {force = "enemy", items = {["iron-plate"] = 2000, ["copper-plate"] = 2000,["green-crystal-fragment"] = 1600, }}},
    {"express-transport-belt", {x = -1.5, y = 3.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 3.5}, {dir = "west", force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 0.5, y = 4.5}, {force = "enemy", items = {["iron-plate"] = 2000, ["copper-plate"] = 2000,["green-crystal-fragment"] = 1600, }}},
    {"express-transport-belt", {x = 0.5, y = 3.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = 1.5, y = 3.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = 2.5, y = 4.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 3.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = 3.5}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 5.5}, {force = "enemy", }},
    {"laser-turret", {x = -9, y = 6}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 6.5}, {force = "enemy", }},
    {"gun-turret", {x = -3, y = 6}, {dir = "south", force = "enemy", }},
    {"gun-turret", {x = 3, y = 6}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 6.5}, {force = "enemy", }},
    {"laser-turret", {x = 9, y = 6}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -10.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 7.5}, {force = "enemy", }},
    {"laser-turret", {x = -6, y = 9}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 8.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = 7.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 8.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 7.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 7.5}, {force = "enemy", }},
    {"laser-turret", {x = 6, y = 9}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 10.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -9.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 10.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 9.5}, {force = "enemy", }},
    {"stone-wall", {x = 9.5, y = 9.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -11, y = -11}},
    {"grass-1", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-1", {x = -11, y = -5}},
    {"grass-1", {x = -11, y = -4}},
    {"grass-1", {x = -11, y = -3}},
    {"grass-1", {x = -11, y = -2}},
    {"grass-1", {x = -11, y = -1}},
    {"grass-1", {x = -11, y = 0}},
    {"grass-1", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-1", {x = -11, y = 4}},
    {"grass-1", {x = -11, y = 5}},
    {"grass-1", {x = -11, y = 6}},
    {"grass-1", {x = -11, y = 7}},
    {"grass-1", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"grass-1", {x = -11, y = 10}},
    {"grass-1", {x = -10, y = -11}},
    {"grass-1", {x = -10, y = -10}},
    {"grass-1", {x = -10, y = -9}},
    {"grass-1", {x = -10, y = -8}},
    {"grass-1", {x = -10, y = -7}},
    {"grass-1", {x = -10, y = -6}},
    {"grass-1", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-1", {x = -10, y = -3}},
    {"grass-1", {x = -10, y = -2}},
    {"grass-1", {x = -10, y = -1}},
    {"grass-1", {x = -10, y = 0}},
    {"grass-1", {x = -10, y = 1}},
    {"grass-1", {x = -10, y = 2}},
    {"grass-1", {x = -10, y = 3}},
    {"grass-1", {x = -10, y = 4}},
    {"grass-1", {x = -10, y = 5}},
    {"grass-1", {x = -10, y = 6}},
    {"grass-1", {x = -10, y = 7}},
    {"grass-1", {x = -10, y = 8}},
    {"grass-1", {x = -10, y = 9}},
    {"grass-1", {x = -10, y = 10}},
    {"grass-1", {x = -9, y = -11}},
    {"grass-1", {x = -9, y = -10}},
    {"grass-1", {x = -9, y = -9}},
    {"grass-1", {x = -9, y = -8}},
    {"grass-1", {x = -9, y = -7}},
    {"grass-1", {x = -9, y = -6}},
    {"grass-1", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"grass-1", {x = -9, y = -2}},
    {"grass-1", {x = -9, y = -1}},
    {"grass-1", {x = -9, y = 0}},
    {"grass-1", {x = -9, y = 1}},
    {"grass-1", {x = -9, y = 2}},
    {"grass-1", {x = -9, y = 3}},
    {"grass-1", {x = -9, y = 4}},
    {"grass-1", {x = -9, y = 5}},
    {"grass-1", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-1", {x = -9, y = 9}},
    {"grass-1", {x = -9, y = 10}},
    {"grass-1", {x = -8, y = -11}},
    {"grass-1", {x = -8, y = -10}},
    {"grass-1", {x = -8, y = -9}},
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-1", {x = -8, y = -2}},
    {"grass-1", {x = -8, y = -1}},
    {"grass-1", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-1", {x = -8, y = 9}},
    {"grass-1", {x = -8, y = 10}},
    {"grass-1", {x = -7, y = -11}},
    {"grass-1", {x = -7, y = -10}},
    {"grass-1", {x = -7, y = -9}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-1", {x = -7, y = -2}},
    {"grass-1", {x = -7, y = -1}},
    {"grass-1", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -7, y = 8}},
    {"grass-1", {x = -7, y = 9}},
    {"grass-1", {x = -7, y = 10}},
    {"grass-1", {x = -6, y = -11}},
    {"grass-1", {x = -6, y = -10}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-1", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"grass-1", {x = -6, y = 9}},
    {"grass-1", {x = -6, y = 10}},
    {"grass-1", {x = -5, y = -11}},
    {"grass-1", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -5, y = 8}},
    {"grass-1", {x = -5, y = 9}},
    {"grass-1", {x = -5, y = 10}},
    {"grass-1", {x = -4, y = -11}},
    {"grass-1", {x = -4, y = -10}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"grass-1", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -4, y = 8}},
    {"grass-1", {x = -4, y = 9}},
    {"grass-1", {x = -4, y = 10}},
    {"grass-1", {x = -3, y = -11}},
    {"grass-1", {x = -3, y = -10}},
    {"grass-1", {x = -3, y = -9}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -3, y = 8}},
    {"grass-1", {x = -3, y = 9}},
    {"grass-1", {x = -3, y = 10}},
    {"grass-1", {x = -2, y = -11}},
    {"grass-1", {x = -2, y = -10}},
    {"grass-1", {x = -2, y = -9}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-1", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -2, y = 8}},
    {"grass-1", {x = -2, y = 9}},
    {"grass-1", {x = -2, y = 10}},
    {"grass-1", {x = -1, y = -11}},
    {"grass-1", {x = -1, y = -10}},
    {"grass-1", {x = -1, y = -9}},
    {"grass-1", {x = -1, y = -8}},
    {"grass-1", {x = -1, y = -7}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = -1, y = 8}},
    {"grass-1", {x = -1, y = 9}},
    {"grass-1", {x = -1, y = 10}},
    {"grass-1", {x = 0, y = -11}},
    {"grass-1", {x = 0, y = -10}},
    {"grass-1", {x = 0, y = -9}},
    {"grass-1", {x = 0, y = -8}},
    {"grass-1", {x = 0, y = -7}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-1", {x = 0, y = 9}},
    {"grass-1", {x = 0, y = 10}},
    {"grass-1", {x = 1, y = -11}},
    {"grass-1", {x = 1, y = -10}},
    {"grass-1", {x = 1, y = -9}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-1", {x = 1, y = 9}},
    {"grass-1", {x = 1, y = 10}},
    {"grass-1", {x = 2, y = -11}},
    {"grass-1", {x = 2, y = -10}},
    {"grass-1", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 2, y = 9}},
    {"grass-1", {x = 2, y = 10}},
    {"grass-1", {x = 3, y = -11}},
    {"grass-1", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 3, y = 9}},
    {"grass-1", {x = 3, y = 10}},
    {"grass-1", {x = 4, y = -11}},
    {"grass-1", {x = 4, y = -10}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 4, y = 8}},
    {"grass-1", {x = 4, y = 9}},
    {"grass-1", {x = 4, y = 10}},
    {"grass-1", {x = 5, y = -11}},
    {"grass-1", {x = 5, y = -10}},
    {"grass-1", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 5, y = 8}},
    {"grass-1", {x = 5, y = 9}},
    {"grass-1", {x = 5, y = 10}},
    {"grass-1", {x = 6, y = -11}},
    {"grass-1", {x = 6, y = -10}},
    {"grass-1", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-1", {x = 6, y = 7}},
    {"grass-1", {x = 6, y = 8}},
    {"grass-1", {x = 6, y = 9}},
    {"grass-1", {x = 6, y = 10}},
    {"grass-1", {x = 7, y = -11}},
    {"grass-1", {x = 7, y = -10}},
    {"grass-1", {x = 7, y = -9}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-1", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
    {"grass-1", {x = 7, y = 8}},
    {"grass-1", {x = 7, y = 9}},
    {"grass-1", {x = 7, y = 10}},
    {"grass-1", {x = 8, y = -11}},
    {"grass-1", {x = 8, y = -10}},
    {"grass-1", {x = 8, y = -9}},
    {"grass-1", {x = 8, y = -8}},
    {"grass-1", {x = 8, y = -7}},
    {"grass-1", {x = 8, y = -6}},
    {"grass-1", {x = 8, y = -5}},
    {"grass-1", {x = 8, y = -4}},
    {"grass-1", {x = 8, y = -3}},
    {"grass-1", {x = 8, y = -2}},
    {"grass-1", {x = 8, y = -1}},
    {"grass-1", {x = 8, y = 0}},
    {"grass-1", {x = 8, y = 1}},
    {"grass-1", {x = 8, y = 2}},
    {"grass-1", {x = 8, y = 3}},
    {"grass-1", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-1", {x = 8, y = 6}},
    {"grass-1", {x = 8, y = 7}},
    {"grass-1", {x = 8, y = 8}},
    {"grass-1", {x = 8, y = 9}},
    {"grass-1", {x = 8, y = 10}},
    {"grass-1", {x = 9, y = -11}},
    {"grass-1", {x = 9, y = -10}},
    {"grass-1", {x = 9, y = -9}},
    {"grass-1", {x = 9, y = -8}},
    {"grass-1", {x = 9, y = -7}},
    {"grass-1", {x = 9, y = -6}},
    {"grass-1", {x = 9, y = -5}},
    {"grass-1", {x = 9, y = -4}},
    {"grass-1", {x = 9, y = -3}},
    {"grass-1", {x = 9, y = -2}},
    {"grass-1", {x = 9, y = -1}},
    {"grass-1", {x = 9, y = 0}},
    {"grass-1", {x = 9, y = 1}},
    {"grass-1", {x = 9, y = 2}},
    {"grass-1", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"grass-1", {x = 9, y = 5}},
    {"grass-1", {x = 9, y = 6}},
    {"grass-1", {x = 9, y = 7}},
    {"grass-1", {x = 9, y = 8}},
    {"grass-1", {x = 9, y = 9}},
    {"grass-1", {x = 9, y = 10}},
    {"grass-1", {x = 10, y = -11}},
    {"grass-1", {x = 10, y = -10}},
    {"grass-1", {x = 10, y = -9}},
    {"grass-1", {x = 10, y = -8}},
    {"grass-1", {x = 10, y = -7}},
    {"grass-1", {x = 10, y = -6}},
    {"grass-1", {x = 10, y = -5}},
    {"grass-1", {x = 10, y = -4}},
    {"grass-1", {x = 10, y = -3}},
    {"grass-1", {x = 10, y = -2}},
    {"grass-1", {x = 10, y = -1}},
    {"grass-1", {x = 10, y = 0}},
    {"grass-1", {x = 10, y = 1}},
    {"grass-1", {x = 10, y = 2}},
    {"grass-1", {x = 10, y = 3}},
    {"grass-1", {x = 10, y = 4}},
    {"grass-1", {x = 10, y = 5}},
    {"grass-1", {x = 10, y = 6}},
    {"grass-1", {x = 10, y = 7}},
    {"grass-1", {x = 10, y = 8}},
    {"grass-1", {x = 10, y = 9}},
    {"grass-1", {x = 10, y = 10}},
  }
}
