return
{
  entities =
  {
    {"stone-wall", {x = -7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = -8.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = -8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -8.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = -8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 3.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -8.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = -6.5}, {force = "enemy", }},
    {"laser-turret", {x = -3, y = -7}, {force = "enemy", }},
    {"laser-turret", {x = 3, y = -7}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = -6.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -7.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = -4.5}, {force = "enemy", }},
    {"gun-turret", {x = -5, y = -5}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -3.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = -0.5, y = -5.5}, {items = {["fast-splitter"] = 50, radar = 6}, }},
    {"express-transport-belt", {x = -0.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -1.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"steel-chest", {x = 0.5, y = -5.5}, {items = {["cryexplosive-rounds-magazine"] = 5, ["laser-turret"] = 10}, }},
    {"express-transport-belt", {x = 1.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 0.5, y = -4.5}, {dir = "east", force = "enemy", }},
    {"fast-inserter", {x = 3.5, y = -4.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = -4.5}, {dir = "south", force = "enemy", }},
    {"gun-turret", {x = 5, y = -5}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 7.5, y = -4.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -5.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -3.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -2.5}, {force = "enemy", }},
    {"laser-turret", {x = -7, y = -3}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = -4.5, y = -3.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = -2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = -2.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = -2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = -3.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -1.5, y = -2.5}, {force = "enemy", items = {["iron-plate"] = 2000, ["copper-plate"] = 2000,["green-crystal-fragment"] = 1600, }}},
    {"substation", {x = 0, y = -2}, {force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = -2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = -2.5}, {dir = "east", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = -3.5}, {dir = "south", force = "enemy", }},
    {"fast-inserter", {x = 4.5, y = -3.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 4.5, y = -2.5}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = 7, y = -3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -3.5}, {force = "enemy", }},
    {"gate", {x = -8.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = -1.5}, {force = "enemy", }},
    {"steel-chest", {x = -5.5, y = -0.5}, {items = {["fast-underground-belt"] = 50}, }},
    {"express-transport-belt", {x = -4.5, y = -1.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = -0.5}, {force = "enemy", }},
    {"fast-inserter", {x = -3.5, y = -1.5}, {dir = "south", force = "enemy", }},
    {"assembling-machine-2", {x = -2.5, y = 0.5}, {force = "enemy", recipe = "cryexplosive-rounds-magazine", }},
    {"fast-inserter", {x = -1.5, y = -1.5}, {force = "enemy", }},
    {"green-crystal-gen", {x = 0.5, y = -1}, {force = "enemy", }},
    {"fast-inserter", {x = 3.5, y = -0.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = 3.5, y = -1.5}, {dir = "west", force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 2.5, y = -0.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"logistic-chest-passive-provider", {x = 2.5, y = -1.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"steel-chest", {x = 5.5, y = -0.5}, {}},
    {"express-transport-belt", {x = 4.5, y = -0.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 4.5, y = -1.5}, {dir = "south", force = "enemy", }},
    {"gate", {x = 8.5, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = -1.5}, {force = "enemy", }},
    {"gate", {x = -8.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 1.5}, {force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -7.5, y = 1.5}, {force = "enemy", items = {["iron-plate"] = 2000, ["copper-plate"] = 2000,["green-crystal-fragment"] = 1600, }}},
    {"steel-chest", {x = -5.5, y = 0.5}, {items = {["fast-transport-belt"] = 100}, }},
    {"long-handed-inserter", {x = -5.5, y = 1.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = 0.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = 1.5}, {force = "enemy", }},
    {"substation", {x = 0, y = 2}, {force = "enemy", }},
    {"fast-inserter", {x = 3.5, y = 1.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = 3.5, y = 0.5}, {dir = "west", force = "enemy", }},
    {"logistic-chest-passive-provider", {x = 2.5, y = 1.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"logistic-chest-passive-provider", {x = 2.5, y = 0.5}, {force = "enemy", items = {["cryexplosive-rounds-magazine"] = 9600}, }},
    {"steel-chest", {x = 5.5, y = 0.5}, {items = {["effectivity-module-2"] = 1, ["express-transport-belt"] = 10, ["steel-chest"] = 1}, }},
    {"express-transport-belt", {x = 4.5, y = 1.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 4.5, y = 0.5}, {dir = "south", force = "enemy", }},
    {"gate", {x = 8.5, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 3.5}, {force = "enemy", }},
    {"laser-turret", {x = -7, y = 3}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = -4.5, y = 3.5}, {force = "enemy", }},
    {"express-transport-belt", {x = -4.5, y = 2.5}, {force = "enemy", }},
    {"long-handed-inserter", {x = -3.5, y = 3.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = 2.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -3.5, y = 2.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -2.5, y = 3.5}, {force = "enemy", }},
    {"fast-inserter", {x = -1.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -1.5, y = 3.5}, {force = "enemy", items = {["iron-plate"] = 2000, ["copper-plate"] = 2000,["green-crystal-fragment"] = 1600, }}},
    {"express-transport-belt", {x = 2.5, y = 3.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 2.5}, {dir = "south", force = "enemy", }},
    {"express-transport-belt", {x = 3.5, y = 2.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = 4.5, y = 3.5}, {force = "enemy", }},
    {"express-transport-belt", {x = 4.5, y = 2.5}, {dir = "west", force = "enemy", }},
    {"laser-turret", {x = 7, y = 3}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 3.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 5.5}, {force = "enemy", }},
    {"gun-turret", {x = -5, y = 5}, {dir = "west", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"fast-inserter", {x = -3.5, y = 4.5}, {dir = "east", force = "enemy", }},
    {"logistic-chest-passive-provider", {x = -3.5, y = 5.5}, {force = "enemy", items = {["iron-plate"] = 2000, ["copper-plate"] = 2000,["green-crystal-fragment"] = 1600, }}},
    {"express-transport-belt", {x = -2.5, y = 4.5}, {force = "enemy", }},
    {"steel-chest", {x = -0.5, y = 5.5}, {items = {["speed-module-2"] = 1}, }},
    {"express-transport-belt", {x = -1.5, y = 4.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = -0.5, y = 4.5}, {dir = "west", force = "enemy", }},
    {"steel-chest", {x = 0.5, y = 5.5}, {items = {["power-armor"] = 1, ["productivity-module-2"] = 1}, }},
    {"express-transport-belt", {x = 0.5, y = 4.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = 1.5, y = 4.5}, {dir = "west", force = "enemy", }},
    {"fast-inserter", {x = 3.5, y = 4.5}, {dir = "west", force = "enemy", }},
    {"express-transport-belt", {x = 2.5, y = 4.5}, {dir = "west", force = "enemy", }},
    {"gun-turret", {x = 5, y = 5}, {dir = "east", force = "enemy", items = {["cryexplosive-rounds-magazine"] = 200}, }},
    {"stone-wall", {x = 7.5, y = 4.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 5.5}, {force = "enemy", }},
    {"stone-wall", {x = -8.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -6.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = -4.5, y = 7.5}, {force = "enemy", }},
    {"laser-turret", {x = -3, y = 7}, {dir = "south", force = "enemy", }},
    {"laser-turret", {x = 3, y = 7}, {dir = "south", force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 4.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 6.5}, {force = "enemy", }},
    {"stone-wall", {x = 6.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = 8.5, y = 7.5}, {force = "enemy", }},
    {"stone-wall", {x = -7.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 8.5}, {force = "enemy", }},
    {"gate", {x = -0.5, y = 8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = 8.5}, {force = "enemy", }},
    {"gate", {x = 0.5, y = 8.5}, {dir = "east", force = "enemy", }},
    {"stone-wall", {x = 1.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 3.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 5.5, y = 8.5}, {force = "enemy", }},
    {"stone-wall", {x = 7.5, y = 8.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -9, y = -9}},
    {"grass-1", {x = -9, y = -8}},
    {"grass-1", {x = -9, y = -7}},
    {"grass-1", {x = -9, y = -6}},
    {"grass-1", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"grass-1", {x = -9, y = -2}},
    {"refined-concrete", {x = -9, y = -1}},
    {"refined-concrete", {x = -9, y = 0}},
    {"grass-1", {x = -9, y = 1}},
    {"grass-1", {x = -9, y = 2}},
    {"grass-1", {x = -9, y = 3}},
    {"grass-1", {x = -9, y = 4}},
    {"grass-1", {x = -9, y = 5}},
    {"grass-1", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-1", {x = -8, y = -9}},
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-1", {x = -8, y = -2}},
    {"refined-concrete", {x = -8, y = -1}},
    {"refined-concrete", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-1", {x = -7, y = -9}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-1", {x = -7, y = -2}},
    {"refined-concrete", {x = -7, y = -1}},
    {"refined-concrete", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -7, y = 8}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"refined-concrete", {x = -6, y = -1}},
    {"refined-concrete", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"refined-concrete", {x = -5, y = -1}},
    {"refined-concrete", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -5, y = 8}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"refined-concrete", {x = -4, y = -1}},
    {"refined-concrete", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -4, y = 8}},
    {"grass-1", {x = -3, y = -9}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"refined-concrete", {x = -3, y = -1}},
    {"refined-concrete", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -3, y = 8}},
    {"grass-1", {x = -2, y = -9}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-1", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"refined-concrete", {x = -2, y = -1}},
    {"refined-concrete", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -2, y = 8}},
    {"refined-concrete", {x = -1, y = -9}},
    {"refined-concrete", {x = -1, y = -8}},
    {"refined-concrete", {x = -1, y = -7}},
    {"refined-concrete", {x = -1, y = -6}},
    {"refined-concrete", {x = -1, y = -5}},
    {"refined-concrete", {x = -1, y = -4}},
    {"refined-concrete", {x = -1, y = -3}},
    {"refined-concrete", {x = -1, y = -2}},
    {"refined-concrete", {x = -1, y = -1}},
    {"refined-concrete", {x = -1, y = 0}},
    {"refined-concrete", {x = -1, y = 1}},
    {"refined-concrete", {x = -1, y = 2}},
    {"refined-concrete", {x = -1, y = 3}},
    {"refined-concrete", {x = -1, y = 4}},
    {"refined-concrete", {x = -1, y = 5}},
    {"refined-concrete", {x = -1, y = 6}},
    {"refined-concrete", {x = -1, y = 7}},
    {"refined-concrete", {x = -1, y = 8}},
    {"refined-concrete", {x = 0, y = -9}},
    {"refined-concrete", {x = 0, y = -8}},
    {"refined-concrete", {x = 0, y = -7}},
    {"refined-concrete", {x = 0, y = -6}},
    {"refined-concrete", {x = 0, y = -5}},
    {"refined-concrete", {x = 0, y = -4}},
    {"refined-concrete", {x = 0, y = -3}},
    {"refined-concrete", {x = 0, y = -2}},
    {"refined-concrete", {x = 0, y = -1}},
    {"refined-concrete", {x = 0, y = 0}},
    {"refined-concrete", {x = 0, y = 1}},
    {"refined-concrete", {x = 0, y = 2}},
    {"refined-concrete", {x = 0, y = 3}},
    {"refined-concrete", {x = 0, y = 4}},
    {"refined-concrete", {x = 0, y = 5}},
    {"refined-concrete", {x = 0, y = 6}},
    {"refined-concrete", {x = 0, y = 7}},
    {"refined-concrete", {x = 0, y = 8}},
    {"grass-1", {x = 1, y = -9}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"refined-concrete", {x = 1, y = -1}},
    {"refined-concrete", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-1", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"refined-concrete", {x = 2, y = -1}},
    {"refined-concrete", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"refined-concrete", {x = 3, y = -1}},
    {"refined-concrete", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"refined-concrete", {x = 4, y = -1}},
    {"refined-concrete", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 4, y = 8}},
    {"grass-1", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"refined-concrete", {x = 5, y = -1}},
    {"refined-concrete", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 5, y = 8}},
    {"grass-1", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"refined-concrete", {x = 6, y = -1}},
    {"refined-concrete", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-1", {x = 6, y = 7}},
    {"grass-1", {x = 6, y = 8}},
    {"grass-1", {x = 7, y = -9}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"refined-concrete", {x = 7, y = -1}},
    {"refined-concrete", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
    {"grass-1", {x = 7, y = 8}},
    {"grass-1", {x = 8, y = -9}},
    {"grass-1", {x = 8, y = -8}},
    {"grass-1", {x = 8, y = -7}},
    {"grass-1", {x = 8, y = -6}},
    {"grass-1", {x = 8, y = -5}},
    {"grass-1", {x = 8, y = -4}},
    {"grass-1", {x = 8, y = -3}},
    {"grass-1", {x = 8, y = -2}},
    {"refined-concrete", {x = 8, y = -1}},
    {"refined-concrete", {x = 8, y = 0}},
    {"grass-1", {x = 8, y = 1}},
    {"grass-1", {x = 8, y = 2}},
    {"grass-1", {x = 8, y = 3}},
    {"grass-1", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-1", {x = 8, y = 6}},
    {"grass-1", {x = 8, y = 7}},
    {"grass-1", {x = 8, y = 8}},
  }
}
