return
{
  entities =
  {
    {"stone-wall", {x = -4, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -3, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -2, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -1, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 0, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 1, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 2, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 3, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = 4, y = -2.5}, {force = "enemy", }},
    {"stone-wall", {x = -4, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -4, y = -1.5}, {force = "enemy", }},
    {"laser-turret", {x = -2.5, y = 0}, {force = "enemy", }},
    {"medium-electric-pole", {x = 0, y = -1.5}, {force = "enemy", }},
    {"purple-crystal-gen", {x = 0, y = -1}, {force = "enemy", }},
    {"tree-05", {x = 2.57, y = -1.3}, {}},
    {"laser-turret", {x = 2.5, y = 0}, {force = "enemy", }},
    {"stone-wall", {x = 4, y = -1.5}, {force = "enemy", }},
    {"stone-wall", {x = 4, y = -0.5}, {force = "enemy", }},
    {"stone-wall", {x = -4, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -4, y = 0.5}, {force = "enemy", }},
    {"tree-05", {x = -2.22, y = 1.54}, {}},
    {"medium-electric-pole", {x = 0, y = 1.5}, {force = "enemy", }},
    {"tree-05", {x = 2.21, y = 1.69}, {}},
    {"stone-wall", {x = 4, y = 0.5}, {force = "enemy", }},
    {"stone-wall", {x = 4, y = 1.5}, {force = "enemy", }},
    {"stone-wall", {x = -4, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -2, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -3, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 0, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -1, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 2, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 1, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 4, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = 3, y = 2.5}, {force = "enemy", }},
  },
  tiles =
  {
    {"grass-1", {x = -4.5, y = -3}},
    {"grass-1", {x = -4.5, y = -2}},
    {"grass-1", {x = -4.5, y = -1}},
    {"grass-1", {x = -4.5, y = 0}},
    {"grass-1", {x = -4.5, y = 1}},
    {"grass-1", {x = -4.5, y = 2}},
    {"grass-1", {x = -3.5, y = -3}},
    {"grass-1", {x = -3.5, y = -2}},
    {"grass-1", {x = -3.5, y = -1}},
    {"grass-1", {x = -3.5, y = 0}},
    {"grass-1", {x = -3.5, y = 1}},
    {"grass-1", {x = -3.5, y = 2}},
    {"grass-1", {x = -2.5, y = -3}},
    {"grass-1", {x = -2.5, y = -2}},
    {"grass-1", {x = -2.5, y = -1}},
    {"grass-1", {x = -2.5, y = 0}},
    {"grass-1", {x = -2.5, y = 1}},
    {"grass-1", {x = -2.5, y = 2}},
    {"grass-1", {x = -1.5, y = -3}},
    {"grass-1", {x = -1.5, y = -2}},
    {"grass-1", {x = -1.5, y = -1}},
    {"grass-1", {x = -1.5, y = 0}},
    {"grass-1", {x = -1.5, y = 1}},
    {"grass-1", {x = -1.5, y = 2}},
    {"grass-1", {x = -0.5, y = -3}},
    {"grass-1", {x = -0.5, y = -2}},
    {"grass-1", {x = -0.5, y = -1}},
    {"grass-1", {x = -0.5, y = 0}},
    {"grass-1", {x = -0.5, y = 1}},
    {"grass-1", {x = -0.5, y = 2}},
    {"grass-1", {x = 0.5, y = -3}},
    {"grass-1", {x = 0.5, y = -2}},
    {"grass-1", {x = 0.5, y = -1}},
    {"grass-1", {x = 0.5, y = 0}},
    {"grass-1", {x = 0.5, y = 1}},
    {"grass-1", {x = 0.5, y = 2}},
    {"grass-1", {x = 1.5, y = -3}},
    {"grass-1", {x = 1.5, y = -2}},
    {"grass-1", {x = 1.5, y = -1}},
    {"grass-1", {x = 1.5, y = 0}},
    {"grass-1", {x = 1.5, y = 1}},
    {"grass-1", {x = 1.5, y = 2}},
    {"grass-1", {x = 2.5, y = -3}},
    {"grass-1", {x = 2.5, y = -2}},
    {"grass-1", {x = 2.5, y = -1}},
    {"grass-1", {x = 2.5, y = 0}},
    {"grass-1", {x = 2.5, y = 1}},
    {"grass-1", {x = 2.5, y = 2}},
    {"grass-1", {x = 3.5, y = -3}},
    {"grass-1", {x = 3.5, y = -2}},
    {"grass-1", {x = 3.5, y = -1}},
    {"grass-1", {x = 3.5, y = 0}},
    {"grass-1", {x = 3.5, y = 1}},
    {"grass-1", {x = 3.5, y = 2}},
  }
}
